force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Round_Type__c.field-meta.xml
<CustomField>
    <fullName>Round_Type__c</fullName>
    <label>Round Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM Academy</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
                <label>MIDNIGHT</label>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PM + Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Collection - Support</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery (Bike)</fullName>
            </value>
            <value>
                <fullName>In-Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DispatchSequence.cls
public without sharing class DispatchSequence {

	@InvocableMethod(Label='Sequence Dispatches')
	public static void sequence(List<Id> dispatchIds) {
		Database.executebatch(new ClusterSequenceBatch(dispatchIds), 1);
	}

	public static void sequenceMorningDispatches() {
		Database.executebatch(new ClusterSequenceBatch(getDispatchIds('AM')), 1);
	}

	public static void sequenceEveningDispatches() {
		Database.executebatch(new ClusterSequenceBatch(getDispatchIds('PM')), 1);
	}

	private static Set<Id> getDispatchIds(String roundType) {
		List<DailyDispatch__c> dispataches = [SELECT Id FROM DailyDispatch__c WHERE CreatedDate = TODAY AND Status__c = 'Created'
			AND RoundId__r.Type__c = 'Collection' AND RoundId__r.Round_Type__c = :roundType];

		return IdUtil.extractId(dispataches);
	}
}