force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Round_Type__c.field-meta.xml
<CustomField>
    <fullName>Round_Type__c</fullName>
    <label>Round Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM Academy</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
                <label>MIDNIGHT</label>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PM + Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/RoundNo__c.field-meta.xml
<CustomField>
    <fullName>RoundNo__c</fullName>
    <externalId>true</externalId>
    <label>RoundNo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tonnage__c/Tonnage__c.object-meta.xml
<CustomObject>
    <label>Tonnage</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Tonnage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tonnages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tonnage__c/fields/DailyDispatch__c.field-meta.xml
<CustomField>
    <fullName>DailyDispatch__c</fullName>
    <label>Daily Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Tonnages</relationshipLabel>
    <relationshipName>Tonnages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tonnage__c/fields/Date_of_Round__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Round__c</fullName>
    <label>Date of Round</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tonnage__c/fields/Site_of_Tip__c.field-meta.xml
<CustomField>
    <fullName>Site_of_Tip__c</fullName>
    <label>Site of Tip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tips</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tonnage__c/fields/Time_of_Tip__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Tip__c</fullName>
    <label>Time of Tip</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Tonnage__c/fields/Type_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Waste__c</fullName>
    <label>Type of Waste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aluminium</fullName>
            </value>
            <value>
                <fullName>Aluminum Tubes</fullName>
            </value>
            <value>
                <fullName>Batteries</fullName>
            </value>
            <value>
                <fullName>Biodegradable</fullName>
            </value>
            <value>
                <fullName>Cardboard</fullName>
            </value>
            <value>
                <fullName>Coat Hangers</fullName>
            </value>
            <value>
                <fullName>Coffee</fullName>
            </value>
            <value>
                <fullName>Coffee Cups</fullName>
            </value>
            <value>
                <fullName>Cooking Oil</fullName>
            </value>
            <value>
                <fullName>Flexible Plastics</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Fridges</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Helium Canisters</fullName>
            </value>
            <value>
                <fullName>Light Bulbs</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Non Clinical Medical</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Plastics</fullName>
            </value>
            <value>
                <fullName>Recycling</fullName>
            </value>
            <value>
                <fullName>Rubber (wellies/tyres)</fullName>
            </value>
            <value>
                <fullName>Textiles</fullName>
            </value>
            <value>
                <fullName>Toners &amp; Cartridges</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>WEEE</fullName>
            </value>
            <value>
                <fullName>Confidential</fullName>
                <isActive>false</isActive>
                <label>Confidential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tonnage__c/fields/Weight_kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_kg__c</fullName>
    <label>Weight_kg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TonnageSettings__c/TonnageSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Tonnage Settings</label>
</CustomObject>

force-app/main/default/objects/TonnageSettings__c/fields/DefaultDispatch__c.field-meta.xml
<CustomField>
    <fullName>DefaultDispatch__c</fullName>
    <label>Default Dispatch</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/WeightronEvent__c.object-meta.xml
<CustomObject>
    <label>Weightron Event</label>
    <nameField>
        <label>Ticket No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weightron Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WeightronEvent__c/fields/DateOfTip__c.field-meta.xml
<CustomField>
    <fullName>DateOfTip__c</fullName>
    <label>Date of Tip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/Net__c.field-meta.xml
<CustomField>
    <fullName>Net__c</fullName>
    <label>Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/RoundNumber__c.field-meta.xml
<CustomField>
    <fullName>RoundNumber__c</fullName>
    <label>Round Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Not Matched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/TimeOfTip__c.field-meta.xml
<CustomField>
    <fullName>TimeOfTip__c</fullName>
    <label>Time of Tip</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/TypeOfWaste__c.field-meta.xml
<CustomField>
    <fullName>TypeOfWaste__c</fullName>
    <label>Type of Waste</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Tips.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avon Metals</fullName>
    </customValue>
    <customValue>
        <fullName>Balcan Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Berry BPI</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Barking</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Edmonton</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Oldbury</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Wembley</fullName>
    </customValue>
    <customValue>
        <fullName>BioBean</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Collectors</fullName>
    </customValue>
    <customValue>
        <fullName>BioGen</fullName>
    </customValue>
    <customValue>
        <fullName>Biomass UK</fullName>
    </customValue>
    <customValue>
        <fullName>Bywaters</fullName>
    </customValue>
    <customValue>
        <fullName>Cater Oils</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Barking</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Belvedere</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Cringle Dock</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Northumberland Warf</fullName>
        <label>Cory Northumberland Wharf</label>
    </customValue>
    <customValue>
        <fullName>Cory Pensbury Place</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Smugglers Way</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Wallbrook Wharf</fullName>
    </customValue>
    <customValue>
        <fullName>CTR Group</fullName>
    </customValue>
    <customValue>
        <fullName>D.S Smith</fullName>
    </customValue>
    <customValue>
        <fullName>Edwards</fullName>
    </customValue>
    <customValue>
        <fullName>Endurmeta</fullName>
    </customValue>
    <customValue>
        <fullName>Enval</fullName>
    </customValue>
    <customValue>
        <fullName>ENVAR</fullName>
    </customValue>
    <customValue>
        <fullName>European Metal Recycling</fullName>
    </customValue>
    <customValue>
        <fullName>G &amp; P Batteries</fullName>
    </customValue>
    <customValue>
        <fullName>Go 4 Greener</fullName>
    </customValue>
    <customValue>
        <fullName>Green recycling</fullName>
    </customValue>
    <customValue>
        <fullName>Weighbridge</fullName>
    </customValue>
    <masterLabel>Tips</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TonnageCreateBatch.cls
public without sharing class TonnageCreateBatch implements Database.Batchable<SObject> {

	private final String DEFAULT_DISPATCH = TonnageSettings__c.getOrgDefaults().DefaultDispatch__c;

	public Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator([SELECT TypeOfWaste__c, Net__c, TimeOfTip__c, DateOfTip__c, RoundNumber__c FROM WeightronEvent__c WHERE Status__c = 'New']);
	}

	public void execute(Database.BatchableContext context, List<WeightronEvent__c> scope) {
		createTonnage(scope);
	}

	private void createTonnage(List<WeightronEvent__c> events) {
		Map<String, DailyDispatch__c> dispatchMap = getDispatches(events);

		List<WeightronEvent__c> eventsToUpdate = new List<WeightronEvent__c>();
		WeightronEvent__c eventToUpdate;
		List<Tonnage__c> tonnages = new List<Tonnage__c>();
		Tonnage__c tonnage;
		DailyDispatch__c dispatch;
		Date previousDate;

		for (WeightronEvent__c event : events) {
			eventToUpdate = new WeightronEvent__c(Id = event.Id);
			tonnage = new Tonnage__c(Site_of_Tip__c = 'Weighbridge', Type_of_Waste__c = event.TypeOfWaste__c, Weight_kg__c = event.Net__c, Time_of_Tip__c = event.TimeOfTip__c);
			dispatch = dispatchMap.get(key(event));
			previousDate = event.DateOfTip__c.addDays(-1);
			if (dispatch == null) {	// Current day's dispatched not yet created. E.g. Event of PM round @ 02:05 AM
				// Try previous date
				dispatch = dispatchMap.get(key(event.RoundNumber__c, previousDate));
				if (dispatch == null || dispatch.RoundId__r.Round_Type__c != 'PM') {
					setDispatch(tonnage, eventToUpdate, DEFAULT_DISPATCH, event.DateOfTip__c, 'Not Matched');
				} else {
					setDispatch(tonnage, eventToUpdate, dispatch.Id, previousDate, 'Matched');				// PM previous day when current day record not created yet
				}
			} else {
				if (dispatch.RoundId__r.Round_Type__c == 'PM') {
					if (event.TimeOfTip__c.hour() >= 0 && event.TimeOfTip__c.hour() <= 16) {				// PM round but time is before PM start, so find previous day dispatch
						// Get previous date
						dispatch = dispatchMap.get(key(event.RoundNumber__c, previousDate));
						if (dispatch == null) {
							setDispatch(tonnage, eventToUpdate, DEFAULT_DISPATCH, event.DateOfTip__c, 'Not Matched');
						} else {
							setDispatch(tonnage, eventToUpdate, dispatch.Id, previousDate, 'Matched');		// PM previous day
						}
					} else {
						setDispatch(tonnage, eventToUpdate, dispatch.Id, event.DateOfTip__c, 'Matched');	// PM same day
					}
				} else {
					setDispatch(tonnage, eventToUpdate, dispatch.Id, event.DateOfTip__c, 'Matched');		// AM
				}
			}

			tonnages.add(tonnage);
			eventsToUpdate.add(eventToUpdate);
		}

		Database.SaveResult[] results = Database.insert(tonnages, false);
		LogRegister.createLogsUpsert(results, tonnages, 'Create Tonnages from Weightron Events', 'Insert', 'Tonnage__c', 'DailyDispatch__c');

		results = Database.update(eventsToUpdate, false);
		LogRegister.createLogsUpsert(results, eventsToUpdate, 'Status update on Weightron Events', 'Update', 'WeightronEvent__c', null);
	}

	private Map<String, DailyDispatch__c> getDispatches(List<WeightronEvent__c> events) {
		Set<Decimal> roundNumbers = new Set<Decimal>();
		Set<Date> dispatchDates = new Set<Date>();
		for (WeightronEvent__c event : events) {
			roundNumbers.add(event.RoundNumber__c);
			dispatchDates.add(event.DateOfTip__c);
			dispatchDates.add(event.DateOfTip__c.addDays(-1));
		}

		Map<String, DailyDispatch__c> dispatchMap = new Map<String, DailyDispatch__c>();

		List<DailyDispatch__c> dispatches = [SELECT RoundId__r.RoundNo__c, RoundId__r.Round_Type__c, Dispatch_Date__c FROM DailyDispatch__c
			WHERE RoundId__r.RoundNo__c IN :roundNumbers AND Dispatch_Date__c IN :dispatchDates];
		for (DailyDispatch__c dispatch : dispatches) {
			dispatchMap.put(key(dispatch), dispatch);
		}

		return dispatchMap;
	}

	private void setDispatch(Tonnage__c tonnage, WeightronEvent__c event, Id dispatchId, Date dispatchDate, String status) {
		tonnage.DailyDispatch__c = dispatchId;
		tonnage.Date_of_Round__c = dispatchDate;
		event.Status__c = status;
	}

	private static String key(DailyDispatch__c dispatch) {
		return key(dispatch.RoundId__r.RoundNo__c, dispatch.Dispatch_Date__c);
	}

	private static String key(WeightronEvent__c event) {
		return key(event.RoundNumber__c, event.DateOfTip__c);
	}

	private static String key(Decimal roundNumber, Date dispatchDate) {
		return String.format('{0}-{1}', new Object[]{roundNumber, dispatchDate});
	}

	public void finish(Database.BatchableContext context) {}
}