force-app/main/default/objects/Case/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Monday&quot;), &quot;Monday&quot;+BR(), NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Tuesday&quot;), &quot;Tuesday&quot;+BR(), NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Wednesday&quot;), &quot;Wednesday&quot;+BR(), NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Thursday&quot;), &quot;Thursday&quot;+BR(), NULL)  + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Friday&quot;), &quot;Friday&quot;+BR(), NULL)  + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Saturday&quot;), &quot;Saturday&quot;+BR(), NULL)  + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Sunday&quot;), &quot;Sunday&quot;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <filterItems>
            <field>Account.Enqix_Dead_Live__c</field>
            <operation>equals</operation>
            <value>LIVE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Off Issue</fullName>
                <label>Accident/Injury</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Bin Replacement Request</fullName>
            </value>
            <value>
                <fullName>Change of name, address, or contact details</fullName>
            </value>
            <value>
                <fullName>Chasing delivery or collection ETA</fullName>
            </value>
            <value>
                <fullName>Check or Change Schedule or Recurring Orders</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Collection Complete</fullName>
            </value>
            <value>
                <fullName>Collection Point Review Request</fullName>
            </value>
            <value>
                <fullName>Collection Round Service Missed</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Container too heavy to collect</fullName>
            </value>
            <value>
                <fullName>Couldn&apos;t find bins/bags</fullName>
            </value>
            <value>
                <fullName>Council Fine</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Dangerous Material In Waste</fullName>
            </value>
            <value>
                <fullName>Delivery Issue</fullName>
            </value>
            <value>
                <fullName>Delivery Round Service Missed</fullName>
            </value>
            <value>
                <fullName>Document Request</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Formal Complaint</fullName>
            </value>
            <value>
                <fullName>Frequent Issues at Site</fullName>
            </value>
            <value>
                <fullName>Goodwill</fullName>
            </value>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>Invoice Error</fullName>
            </value>
            <value>
                <fullName>Invoice Query</fullName>
            </value>
            <value>
                <fullName>Key or Access Card not working</fullName>
            </value>
            <value>
                <fullName>Key Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/Missed_Collection__c.object-meta.xml
<CustomObject>
    <label>Missed Collection</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Missed_Collection__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Monday&quot;), &quot;Monday&quot;+ &quot;;&quot;, NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Tuesday&quot;), &quot;Tuesday&quot;+ &quot;;&quot;, NULL)  + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Wednesday&quot;), &quot;Wednesday&quot;+ &quot;;&quot;, NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Thursday&quot;), &quot;Thursday&quot;+ &quot;;&quot;, NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Friday&quot;), &quot;Friday&quot;+ &quot;;&quot;, NULL) + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Saturday&quot;), &quot;Saturday&quot;+ &quot;;&quot;, NULL)  + 
IF(INCLUDES( Collection_Schedule__r.Days__c , &quot;Sunday&quot;), &quot;Sunday&quot;+ &quot;;&quot;, NULL)</formula>
    <label>Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <formula>Collection_Schedule__r.Round_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Round Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MissedCollectionHandlerTest.cls
@isTest
public with sharing class MissedCollectionHandlerTest {

	@testSetup
	static void makeData() {
		Product2 product = TestDataHelper.insertProduct('Product 1', 'P0001', 'Collection');
		Suppliers__c supplier = TestDataHelper.insertSupplier('First Mile Ltd');
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		Round__c round = TestDataHelper.insertRound();
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		List<Schedule__c> schedules = new List<Schedule__c>();
		schedules.add(TestDataHelper.createSchedule(location, round, supplier, supplierProduct, '08:00'));
		schedules.add(TestDataHelper.createSchedule(location, round, supplier, supplierProduct, '09:00'));
		INSERT schedules;

		INSERT new DailyDispatch__c(RoundId__c = round.Id, Name = 'Test dispatch');
	}

	@isTest
	static void checkWithoutMissedCollection() {
		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(0, [SELECT Id FROM DispatchLocation__c].size());
		updateCase(false);
		Assert.areEqual(1, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c].size());
	}

	@isTest
	static void checkWaypointAndDispatchLocation() {
		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(0, [SELECT Id FROM DispatchLocation__c].size());
		updateCase(true);
		Assert.areEqual(2, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c].size());
	}

	@isTest
	static void checkWaypoint() {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		DailyDispatch__c dispatch = [SELECT Id FROM DailyDispatch__c LIMIT 1];
		INSERT new DispatchLocation__c(Dispatch__c = dispatch.Id, Location__c = location.Id);

		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c].size());
		updateCase(true);
		Assert.areEqual(2, [SELECT Id FROM Collection_Waypoints__c].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c].size());
	}

	static void updateCase(Boolean withMissedCollections) {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		Case missedCase = new Case(
			RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Missed Collection').getRecordTypeId(),
			Type = 'Missed Collection',
			AccountId = location.Id,
			Location__c = location.Id,
			Sub_Type__c = 'Collection Round Service Missed'
		);
		INSERT missedCase;

		if (withMissedCollections) {
			List<Missed_Collection__c> missedCollections = new List<Missed_Collection__c>();
			for (Schedule__c schedule : [SELECT Id FROM Schedule__c WHERE Location__c = :location.Id AND Days__c = :System.now().format('EEEE')]) {
				missedCollections.add(new Missed_Collection__c(Case__c = missedCase.Id, Collection_Schedule__c = schedule.Id));
			}
			INSERT missedCollections;
		}

		missedCase.Round_Dispatched__c = [SELECT Id FROM DailyDispatch__c LIMIT 1].Id;
		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c].size());

		Test.startTest();
		UPDATE missedCase;
		Test.stopTest();
	}
}