force-app/main/default/objects/Case/fields/ParentCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>ParentCaseNumber__c</fullName>
    <description>This field is made as external field just to make indexed.</description>
    <externalId>true</externalId>
    <label>Parent Case Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <businessProcess>Email</businessProcess>
    <label>Master Case Record Type</label>
</RecordType>

force-app/main/default/objects/CaseSetting__c/CaseSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Case Setting</label>
</CustomObject>

force-app/main/default/objects/CaseSetting__c/fields/ReopenDuration__c.field-meta.xml
<CustomField>
    <fullName>ReopenDuration__c</fullName>
    <description>Number of days within which a closed case is allowed to be reopened.</description>
    <label>Reopen Duration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmailMessageTrigger_Test.cls
@isTest
public class EmailMessageTrigger_Test {

	@testSetup static void setup() {
		CaseSetting__c cs = new CaseSetting__c();
		cs.ReopenDuration__c = 7;
		INSERT cs;

		Case c1 = new Case();
		c1.Subject = 'Test Case';
		c1.Status ='New';
		c1.Priority = 'Medium';
		c1.Origin = 'Email';
		c1.Type = 'Council Fine';
		c1.CreatedDate = system.today().addDays(-8);
		INSERT c1;
	}

	private static testmethod void testEmailOnExistingOpenCase() {
		Integer caseSize = [SELECT Id FROM Case].size();
		Case currentOpenedCase = [SELECT Id FROM Case WHERE ClosedDate = null LIMIT 1];
		EmailMessage email = new EmailMessage();
		email.FromAddress = 'test@abc.org';
		email.Incoming = True;
		email.ToAddress= 'test@xyz.org';
		email.Subject = 'Test email';
		email.HtmlBody = 'Test email body';
		email.ParentId = currentOpenedCase.Id;
		INSERT email;
		System.assertEquals(caseSize, [SELECT Id FROM Case].size());
	}

	private static testmethod void emailToReopenExistingClosedCase() {
		Case c1 = new Case();
		c1.Subject = 'Test Case 2';
		c1.Status ='Closed';
		c1.Priority = 'Medium';
		c1.Origin = 'Email';
		c1.Type = 'Council Fine';
		c1.CreatedDate = system.today().addDays(-8);
		c1.ClosedDate = system.today().addDays(-6);
		INSERT c1;

		EmailMessage email = new EmailMessage();
		email.FromAddress = 'test@abc.org';
		email.Incoming = True;
		email.ToAddress= 'test@xyz.org';
		email.Subject = 'Test email';
		email.HtmlBody = 'Test email body';
		email.ParentId = c1.Id;
		INSERT email;

		CaseResponseTime.getFirstResponseDuration(new List<Id>{c1.Id});

		System.assertEquals('Active', [SELECT Status FROM Case WHERE Id = :c1.Id].Status);
	}

	private static testmethod void emailOnHistoricalClosedCase() {
		Case c1 = new Case();
		c1.Subject = 'Test Case 2';
		c1.Status ='Closed';
		c1.Priority = 'Medium';
		c1.Origin = 'Email';
		c1.Type = 'Council Fine';
		c1.CreatedDate = system.today().addDays(-8);
		c1.ClosedDate = system.today().addDays(-6);
		INSERT c1;

		String caseNumber = [SELECT CaseNumber FROM Case WHERE Id = :c1.Id].CaseNumber;
		c1.ParentCaseNumber__c = caseNumber;
		UPDATE c1;

		Case c2 = new Case();
		c2.Subject = 'Test Case 2';
		c2.Status ='Closed';
		c2.Priority = 'Medium';
		c2.Origin = 'Email';
		c2.Type = 'Council Fine';
		c2.CreatedDate = system.today().addDays(-8);
		c2.ClosedDate = system.today().addDays(-3);
		c2.ParentCaseNumber__c = caseNumber;
		INSERT c2;

		Case c3 = new Case();
		c3.Subject = 'Test Case 2';
		c3.Status ='Closed';
		c3.Priority = 'Medium';
		c3.Origin = 'Email';
		c3.Type = 'Council Fine';
		c3.CreatedDate = system.today().addDays(-8);
		c3.ClosedDate = system.today().addDays(-2);
		c3.ParentCaseNumber__c = caseNumber;
		INSERT c3;

		CaseSetting__c cs = [SELECT Id From CaseSetting__c LIMIT 1];
		cs.ReopenDuration__c = 1;
		UPDATE cs;

		Integer caseSize = [SELECT Id FROM Case].size();

		EmailMessage email = new EmailMessage();
		email.FromAddress = 'test@abc.org';
		email.Incoming = True;
		email.ToAddress= 'test@xyz.org';
		email.Subject = 'Test email';
		email.HtmlBody = 'Test email body';
		email.ParentId = c1.Id;
		INSERT email;
		System.assertEquals(caseSize+1, [SELECT Id FROM Case].size());
	}
}