force-app/main/default/objects/DeliveryPackageTrackingFile__c/DeliveryPackageTrackingFile__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking File</label>
    <nameField>
        <displayFormat>DelPkgTrkngFile-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryCarrier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryCarrier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Parcelforce</fullName>
        <default>true</default>
        <label>Parcelforce</label>
    </customValue>
    <customValue>
        <fullName>Royal Mail</fullName>
    </customValue>
    <customValue>
        <fullName>First Mile</fullName>
    </customValue>
    <masterLabel>Delivery Carrier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryPackageTrackingFileHandler.cls
public without sharing class DeliveryPackageTrackingFileHandler {

	public void handleTrigger(List<DeliveryPackageTrackingFile__c> newList, Map<Id, DeliveryPackageTrackingFile__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_INSERT {
				createEvents(newList);
			}
		}
	}

	private void createEvents(List<DeliveryPackageTrackingFile__c> newList) {
		List<DeliveryPackageTrackingFile__c> parcelforceList = filter(newList, DeliveryPackage.CARRIER_PARCELFORCE);
		if (!parcelforceList.isEmpty()) {
			ParcelforceTrackingFile.process(IdUtil.extractId(parcelforceList));
		}

		List<DeliveryPackageTrackingFile__c> royalMailList = filter(newList, DeliveryPackage.CARRIER_ROYAL_MAIL);
		if (!royalMailList.isEmpty()) {
			RoyalMailTrackingFile.process(IdUtil.extractId(royalMailList));
		}
	}

	private List<DeliveryPackageTrackingFile__c> filter(List<DeliveryPackageTrackingFile__c> trackingFiles, String carrier) {
		List<DeliveryPackageTrackingFile__c> filtered = new List<DeliveryPackageTrackingFile__c>();
		for (DeliveryPackageTrackingFile__c trackingFile : trackingFiles) {
			if (trackingFile.Carrier__c == carrier) {
				filtered.add(trackingFile);
			}
		}

		return filtered;
	}
}