force-app/main/default/objects/DeliveryPackageTrackingFile__c/DeliveryPackageTrackingFile__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking File</label>
    <nameField>
        <displayFormat>DelPkgTrkngFile-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryCarrier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>File Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/RoyalMailSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Royal Mail Setting</label>
</CustomObject>

force-app/main/default/objects/RoyalMailSetting__c/fields/WireNumber__c.field-meta.xml
<CustomField>
    <fullName>WireNumber__c</fullName>
    <label>Wire Number</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/DeliveryCarrier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Parcelforce</fullName>
        <default>true</default>
        <label>Parcelforce</label>
    </customValue>
    <customValue>
        <fullName>Royal Mail</fullName>
    </customValue>
    <customValue>
        <fullName>First Mile</fullName>
    </customValue>
    <masterLabel>Delivery Carrier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoyalMailSftpEmailServiceBulk.cls
global without sharing class RoyalMailSftpEmailServiceBulk implements Messaging.InboundEmailHandler {

	private static final String WIRE_NUMBER = RoyalMailSetting__c.getOrgDefaults().WireNumber__c;

	global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {

		List<Messaging.InboundEmail.BinaryAttachment> fileAttachments = getFileAttachment(email);

		if (fileAttachments == null || fileAttachments.isEmpty()) {
			return new Messaging.InboundEmailResult();
		}

		List<Attachment> attachments = new List<Attachment>();
		for (Messaging.InboundEmail.BinaryAttachment fileAttachment : fileAttachments) {
			String fileName = fileAttachment.fileName;

			DeliveryPackageTrackingFile__c trackingFile = new DeliveryPackageTrackingFile__c(FileName__c = fileName, Carrier__c = DeliveryPackage.CARRIER_ROYAL_MAIL);
			INSERT trackingFile;

			attachments.add(new Attachment(ParentId = trackingFile.Id, Name = fileName, Body = fileAttachment.body));
		}

		INSERT attachments;

		return new Messaging.InboundEmailResult();
	}

	private List<Messaging.InboundEmail.BinaryAttachment> getFileAttachment(Messaging.InboundEmail email) {
		if (email.binaryAttachments == null || email.binaryAttachments.isEmpty()) {
			return null;
		}

		List<Messaging.InboundEmail.BinaryAttachment> binaryAttachments = new List<Messaging.InboundEmail.BinaryAttachment>();
		for (Messaging.InboundEmail.BinaryAttachment binaryAttachment : email.binaryAttachments) {
			if (binaryAttachment.fileName.startsWithIgnoreCase(WIRE_NUMBER)) {
				binaryAttachments.add(binaryAttachment);
			}
		}

		return binaryAttachments;
	}
}