force-app/main/default/objects/RoutingSetting__c/RoutingSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Routing Setting</label>
</CustomObject>

force-app/main/default/objects/RoutingSetting__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <description>RaaS licence key.</description>
    <label>Licence</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoutingPostJob.cls
public without sharing abstract class RoutingPostJob {

	protected abstract RoutingRequest createRequest();
	protected abstract void updateJobError(String status, String message);
	protected abstract void processResult(RoutingResponse routingResponse);

	public void postJob() {
		try {
			post();
		} catch (Exception e) {
			updateJobError('Error', e.getMessage());
		}
	}

	private void post() {
		RoutingSetting__c setting = RoutingSetting__c.getOrgDefaults();

		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:RaaS/?licenseId=' + setting.Licence__c);
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json');
		request.setBody(JSON.serialize(createRequest()));

		HttpResponse response = new Http().send(request);
		if (response.getStatusCode() != 202) {
			throw new RoutingException(response.getStatusCode() + ' : ' + response.getStatus() + ' : ' + response.getBody());
		}

		processResult((RoutingResponse) JSON.deserialize(response.getBody(), RoutingResponse.class));
	}

	private class RoutingException extends Exception {}
}