force-app/main/default/objects/EnqixImportCSVParameters__c/EnqixImportCSVParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds all configuration parameters for defining CSV import settings</description>
    <label>Enqix Import CSV Parameters</label>
</CustomObject>

force-app/main/default/objects/EnqixImportCSVParameters__c/fields/Delimiter__c.field-meta.xml
<CustomField>
    <fullName>Delimiter__c</fullName>
    <defaultValue>&apos;,&apos;</defaultValue>
    <description>The delimiter on the import file.</description>
    <inlineHelpText>The delimiter on the import file.</inlineHelpText>
    <label>Delimiter</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnqixImportCSVParametersManager.cls
/**
* @author Zoran Zunko
* @date 11/17/15
*
* @group 
* @group-content ../../ApexDocContent/
*
* @description 
*/

public with sharing class EnqixImportCSVParametersManager {

    private static EnqixImportCSVParameters__c csvParameters;

    public static EnqixImportCSVParameters__c getCsvParameters() {

        if(csvParameters == null) {

            csvParameters = EnqixImportCSVParameters__c.getInstance();

            if(String.isBlank(csvParameters.Delimiter__c)) {

                upsert csvParameters;
            }

            csvParameters = EnqixImportCSVParameters__c.getInstance();
        }

        return csvParameters;
    }

}