force-app/main/default/objects/Order/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <defaultValue>&quot;Awaiting Allocation&quot;</defaultValue>
    <label>Delivery Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Detrack_Status__c.field-meta.xml
<CustomField>
    <fullName>Detrack_Status__c</fullName>
    <label>Detrack_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Not Delivered</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Maps_Route__c.field-meta.xml
<CustomField>
    <fullName>Maps_Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maps Route</label>
    <referenceTo>maps__Route__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/RouteName__c.field-meta.xml
<CustomField>
    <fullName>RouteName__c</fullName>
    <label>RouteName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tracking_Link__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Link__c</fullName>
    <label>Tracking Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/ReceivedWaypoint__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint</label>
    <nameField>
        <label>Route</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Received Waypoints</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>ReceivedWaypointGroup__c</referenceTo>
    <relationshipLabel>Received Waypoints</relationshipLabel>
    <relationshipName>ReceivedWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/MapsRouteId__c.field-meta.xml
<CustomField>
    <fullName>MapsRouteId__c</fullName>
    <label>Maps RouteId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/MapsWaypointId__c.field-meta.xml
<CustomField>
    <fullName>MapsWaypointId__c</fullName>
    <label>Maps WaypointId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Received Waypoints</relationshipLabel>
    <relationshipName>ReceivedWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecivedWaypointStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/ReceivedWaypointGroup__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint Group</label>
    <nameField>
        <displayFormat>GRP-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Received Waypoint Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecivedWaypointSource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroupEvent__e/ReceivedWaypointGroupEvent__e.object-meta.xml
<CustomObject>
    <label>Received Waypoint Group Event</label>
    <pluralLabel>Received Waypoint GroupEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypointGroupEvent__e/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroupEvent__e/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <label>Group Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroupEvent__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroupEvent__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/RecivedWaypointSource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RaaS</fullName>
    </customValue>
    <masterLabel>Recived Waypoint Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RecivedWaypointStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Recived Waypoint Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReceivedWaypointGroupEventHandler.cls
@SuppressWarnings('PMD.ApexSharingViolations, PMD.ApexCRUDViolation')
public class ReceivedWaypointGroupEventHandler {

	/*
	Variations:
	1.	Group insertion for first time for a specific date & source combination
	2.	Add route
	3.	Delete route
	4.	New waypoint added to existing route
	5.	Delete waypoint from existing route
	6.	Route changed: i.e., Waypoint moved to another route
	7.	Sequence number of waypoint changed
	*/

	private ReceivedWaypointGroupEvent__e event;
	private Map<String, Id> mapsRoutes = new Map<String, Id>();

	public ReceivedWaypointGroupEventHandler(ReceivedWaypointGroupEvent__e event) {
		this.event = event;
	}

	public void process() {
		// Fetch all waypoints of current group to be processed
		List<ReceivedWaypoint__c> newWaypoints = [SELECT Name, Order__c, Date__c, SequenceNumber__c FROM ReceivedWaypoint__c
			WHERE Date__c = :event.Date__c AND Timestamp__c = :event.Timestamp__c AND Source__c = :event.Source__c AND Status__c = 'New'];

		Map<Id, ReceivedWaypoint__c> newOrderMap = new Map<Id, ReceivedWaypoint__c>();
		Set<String> newRouteNames = new Set<String>();
		for (ReceivedWaypoint__c receivedWaypoint : newWaypoints) {
			newOrderMap.put(receivedWaypoint.Order__c, receivedWaypoint);
			newRouteNames.add(receivedWaypoint.Name);
		}

		// Check if waypoints was received for date & source previously. Get latest group processed previously.
		List<ReceivedWaypointGroup__c> oldGroup = [SELECT Id FROM ReceivedWaypointGroup__c
			WHERE Id != :event.GroupId__c AND Date__c = :event.Date__c AND Source__c = :event.Source__c AND Status__c = 'Complete'
			ORDER BY CreatedDate DESC LIMIT 1];

		// Variation 1
		if (oldGroup.isEmpty()) {
			createMapsRoutes(newRouteNames);
			Map<Id, maps__Waypoint__c> mapsWaypointsInserted = createMapsWaypoints(newWaypoints);
			setWaypointsAsProcessed(newWaypoints, mapsWaypointsInserted, null);
			setGroupAsProcessed();
			return;
		}

		// Variation 2 to 7
		// Fetch all waypoints of latest group processed previously
		List<ReceivedWaypoint__c> oldWaypoints = [SELECT Name, Order__c, Date__c, SequenceNumber__c, MapsWaypointId__c, MapsRouteId__c FROM ReceivedWaypoint__c
				WHERE Group__c = :oldGroup[0].Id];

		Map<Id, ReceivedWaypoint__c> oldOrderMap = new Map<Id, ReceivedWaypoint__c>();
		Map<String, Id> oldRouteMap = new Map<String, Id>();
		if (!oldWaypoints.isEmpty()) {
			for (ReceivedWaypoint__c receivedWaypoint : oldWaypoints) {
				oldOrderMap.put(receivedWaypoint.Order__c, receivedWaypoint);
				oldRouteMap.put(receivedWaypoint.Name, receivedWaypoint.MapsRouteId__c);
			}
		}

		processRoutes(oldRouteMap, newRouteNames);
		processWaypoints(oldOrderMap, newOrderMap, oldRouteMap);
	}

	private void createMapsRoutes(Set<String> routesToCreate) {
		List<maps__Route__c> mapsRoutesToBeInserted = new List<maps__Route__c>();
		for (String routeName : routesToCreate) {
			mapsRoutesToBeInserted.add(new maps__Route__c(Name = routeName, maps__Date__c = event.Date__c));
		}

		INSERT mapsRoutesToBeInserted;

		for (maps__Route__c mapsRoute : mapsRoutesToBeInserted) {
			mapsRoutes.put(mapsRoute.Name, mapsRoute.Id);
		}
	}

	private Map<Id, maps__Waypoint__c> createMapsWaypoints(List<ReceivedWaypoint__c> waypointsToCreate) {
		Map<Id, maps__Waypoint__c> mapsWaypointsToBeInserted = new Map<Id, maps__Waypoint__c>();
		for (ReceivedWaypoint__c receivedWaypoint : waypointsToCreate) {
			mapsWaypointsToBeInserted.put(receivedWaypoint.Order__c, createMapsWaypoint(receivedWaypoint));
		}

		INSERT mapsWaypointsToBeInserted.values();
		return mapsWaypointsToBeInserted;
	}

	private maps__Waypoint__c createMapsWaypoint(ReceivedWaypoint__c receivedWaypoint) {
		maps__Waypoint__c mapsWaypoint = new maps__Waypoint__c();
		mapsWaypoint.maps__LinkId__c = mapsWaypoint.Order__c = receivedWaypoint.Order__c;
		mapsWaypoint.maps__SortOrder__c = receivedWaypoint.SequenceNumber__c;
		mapsWaypoint.maps__Route__c = mapsRoutes.get(receivedWaypoint.Name);
		return mapsWaypoint;
	}

	private void processRoutes(Map<String, Id> oldRouteMap, Set<String> newRouteNames) {
		// Reset isCompleted field for oldRoutes
		setRoutesAsComplete(false, oldRouteMap.values());

		// Delete
		Set<String> routesToBeDeleted = new Set<String>(oldRouteMap.keySet());
		routesToBeDeleted.removeAll(newRouteNames);
		if (!routesToBeDeleted.isEmpty()) {
			Set<Id> mapRouteIds = new Set<Id>();
			for (String routeName : routesToBeDeleted) {
				mapRouteIds.add(oldRouteMap.get(routeName));
			}
			DELETE [SELECT Id FROM maps__Route__c WHERE Id IN :mapRouteIds];
		}

		// Insert
		Set<String> routesToBeInserted = new Set<String>(newRouteNames);
		routesToBeInserted.removeAll(oldRouteMap.keySet());
		if (!routesToBeInserted.isEmpty()) {
			createMapsRoutes(routesToBeInserted);
		}

		// Retain
		Set<String> routesToBeRetained = new Set<String>(oldRouteMap.keySet());
		routesToBeRetained.removeAll(routesToBeDeleted);
		if (!routesToBeRetained.isEmpty()) {
			for (String routeName : routesToBeRetained) {
				mapsRoutes.put(routeName, oldRouteMap.get(routeName));
			}
		}
	}

	private void processWaypoints(Map<Id, ReceivedWaypoint__c> oldOrderMap, Map<Id, ReceivedWaypoint__c> newOrderMap, Map<String, Id> oldRouteMap) {
		// Delete
		Set<Id> ordersToBeDeleted  = new Set<Id>(oldOrderMap.keySet());
		ordersToBeDeleted.removeAll(newOrderMap.keySet());
		Set<Id> mapsWaypointsToBeDeleted = new Set<Id>();
		for (Id orderId : ordersToBeDeleted) {
			mapsWaypointsToBeDeleted.add(oldOrderMap.get(orderId).MapsWaypointId__c);
		}
		
		Set<Id> ordersToBeReset = new Set<Id>(ordersToBeDeleted);

		// Insert
		Map<Id, maps__Waypoint__c> mapsWaypointsToBeInserted = new Map<Id, maps__Waypoint__c>();
		Set<Id> ordersTobeInserted = new Set<Id>(newOrderMap.keySet());
		ordersTobeInserted.removeAll(oldOrderMap.keySet());
		for (String orderId : ordersTobeInserted) {
			mapsWaypointsToBeInserted.put(orderId, createMapsWaypoint(newOrderMap.get(orderId)));
		}

		// Retain
		Set<Id> ordersToBeRetained = new Set<Id>(oldOrderMap.keySet());
		ordersToBeRetained.removeAll(ordersToBeDeleted);
		for (String orderId : ordersToBeRetained) {
			ReceivedWaypoint__c oldReceivedWaypoint = oldOrderMap.get(orderId);
			ReceivedWaypoint__c newReceivedWaypoint = newOrderMap.get(orderId);
			if (newReceivedWaypoint.Name != oldReceivedWaypoint.Name || newReceivedWaypoint.SequenceNumber__c != oldReceivedWaypoint.SequenceNumber__c) {
				ordersToBeReset.add(orderId);
				mapsWaypointsToBeDeleted.add(oldReceivedWaypoint.MapsWaypointId__c);
				mapsWaypointsToBeInserted.put(newReceivedWaypoint.Order__c, createMapsWaypoint(newReceivedWaypoint));
			}
		}
		resetOrders(ordersToBeReset);

		if (!mapsWaypointsToBeDeleted.isEmpty()) {
			DELETE [SELECT Id FROM maps__Waypoint__c WHERE Id IN :mapsWaypointsToBeDeleted];
		}

		if (!mapsWaypointsToBeInserted.isEmpty()) {
			INSERT mapsWaypointsToBeInserted.values();
		}

		setWaypointsAsProcessed(newOrderMap.values(), mapsWaypointsToBeInserted, oldOrderMap);
		setGroupAsProcessed();
	}

	private void setWaypointsAsProcessed(List<ReceivedWaypoint__c> receivedWaypoints, Map<Id, maps__Waypoint__c> mapsWaypointsInserted, Map<Id, ReceivedWaypoint__c> oldOrderMap) {
		for (ReceivedWaypoint__c receivedWaypoint : receivedWaypoints) {
			receivedWaypoint.Status__c = 'Complete';
			receivedWaypoint.Group__c = event.GroupId__c;
			receivedWaypoint.MapsWaypointId__c = mapsWaypointsInserted.containsKey(receivedWaypoint.Order__c) ? mapsWaypointsInserted.get(receivedWaypoint.Order__c).Id : oldOrderMap.get(receivedWaypoint.Order__c).MapsWaypointId__c;
			receivedWaypoint.MapsRouteId__c = mapsRoutes.get(receivedWaypoint.Name);
		}
		UPDATE receivedWaypoints;
	}

	private void resetOrders(Set<Id> orderIds) {
		List<Order> orders = new List<Order>();
		for (Id orderId : orderIds) {
			Order order = new order(Id = orderId, Detrack_Status__c = 'In progress', Delivery_Status__c = 'Awaiting Allocation');
			order.Maps_Route__c = order.RouteName__c = order.Tracking_Link__c = null;
			orders.add(order);
		}
		UPDATE orders;
	}

	private void setGroupAsProcessed() {
		UPDATE new ReceivedWaypointGroup__c(Id = event.GroupId__c, Status__c = 'Complete');
		setRoutesAsComplete(true, mapsRoutes.values());
	}

	private void setRoutesAsComplete(Boolean isComplete, List<Id> mapsRouteIds) {
		List<maps__Route__c> routes = new List<maps__Route__c>();
		for (Id routeId : mapsRouteIds) {
			routes.add(new maps__Route__c(Id = routeId, IsComplete__c = isComplete));
		}
		UPDATE routes;
	}
}