force-app/main/default/objects/DeliveryPackageQrCode__c/DeliveryPackageQrCode__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code</label>
    <nameField>
        <displayFormat>DelPkgQrCde - {0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package QR Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>QR Codes</relationshipLabel>
    <relationshipName>QrCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/detrack_Qrcode__c.field-meta.xml
<CustomField>
    <fullName>detrack_Qrcode__c</fullName>
    <label>DEtrack QR Code</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DeliveryPackageAttachQrCode.cls
public without sharing class DeliveryPackageAttachQrCode {

	@InvocableMethod(label='Update QR Codes into Order Items')
	public static void attach(List<Id> orderIds) {
		List<OrderItem> orderItems = [SELECT detrack_Qrcode__c, (SELECT Code__c FROM QrCodes__r) FROM OrderItem WHERE OrderId IN :orderIds];
		for (OrderItem orderItem : orderItems) {
			List<String> detractQrCodes = new List<String>();
			for (DeliveryPackageQrCode__c qrCode : orderItem.QrCodes__r) {
				detractQrCodes.add(qrCode.Code__c.replace('-', ','));
			}
			detractQrCodes.sort();
			orderItem.detrack_Qrcode__c = String.join(detractQrCodes, ',');
		}
		UPDATE orderItems;
	}
}