force-app/main/default/objects/DeliveryPackageQrCode__c/DeliveryPackageQrCode__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code</label>
    <nameField>
        <displayFormat>DelPkgQrCde - {0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package QR Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageQrCodeItem__c/DeliveryPackageQrCodeItem__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code Item</label>
    <nameField>
        <label>QR Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Package QR Code Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCodeItem__c/fields/DeliveryPackageQrCode__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPackageQrCode__c</fullName>
    <label>Delivery Package QR Code</label>
    <referenceTo>DeliveryPackageQrCode__c</referenceTo>
    <relationshipLabel>Delivery Package QR Code Items</relationshipLabel>
    <relationshipName>DeliveryPackageQrCodeItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeliveryPackageQrCodeHandler.cls
public without sharing class DeliveryPackageQrCodeHandler {

	public void handleTrigger(List<DeliveryPackageQrCode__c> newList, Map<Id, DeliveryPackageQrCode__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when BEFORE_INSERT{
				verifyDuplicates(newList);
			}
			when AFTER_INSERT {
				createQrCodeItems(newList);
			}
		}
	}

	private void verifyDuplicates(List<DeliveryPackageQrCode__c> newList) {
		for (DeliveryPackageQrCode__c packageQrCode : newList) {
			if (!DeliveryPackageQrCode.verifyDuplicates(new List<String>{packageQrCode.Code__c}).isEmpty()) {
				packageQrCode.Code__c.addError('Duplicate QR Code.');
			}
		}
	}

	private void createQrCodeItems(List<DeliveryPackageQrCode__c> newList) {
		List<DeliveryPackageQrCodeItem__c> packageQrCodeItems = new List<DeliveryPackageQrCodeItem__c>();

		for (DeliveryPackageQrCode__c packageQrCode : newList) {
			Set<String> individualQrCodes = DeliveryPackageQrCode.toIndividual(new List<String>{packageQrCode.Code__c});
			for (String individualQrCode : individualQrCodes) {
				packageQrCodeItems.add(new DeliveryPackageQrCodeItem__c(DeliveryPackageQrCode__c = packageQrCode.Id, Name = individualQrCode));
			}
		}

		if (!packageQrCodeItems.isEmpty()) {
			INSERT packageQrCodeItems;
		}
	}
}