force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/MaximumRouteTime__c.field-meta.xml
<CustomField>
    <fullName>MaximumRouteTime__c</fullName>
    <label>Maximum Route Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/RtePref__c.field-meta.xml
<CustomField>
    <fullName>RtePref__c</fullName>
    <label>Rte Pref</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartLocation__c.field-meta.xml
<CustomField>
    <fullName>StartLocation__c</fullName>
    <label>Start Location</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/VehicleCapacity__c.field-meta.xml
<CustomField>
    <fullName>VehicleCapacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRouteGroup__c/DeliveryRouteGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Route Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeliveryRouteFileUpload.cls
public with sharing class DeliveryRouteFileUpload extends FileUpload{
    public static final String FILE_REFERENCE = 'DeliveryRoute';
	private static final String LABEL = 'Delivery Route';
	private static final String DELIMITER = ';';
    private static final Map<String, String> FIELDS_TO_PROCESS = new Map<String, String>{'routeId'=>'Name',
																						'startTime' => 'StartTime__c',
																						'maxRouteTime' => 'MaximumRouteTime__c',
																						'vehicleCapacity' => 'VehicleCapacity__c',
                                                                                        'startLocation' => 'StartLocation__c',
																						'rtePref' => 'RtePref__c',
                                                                                        'skillSetProperties' => 'SkillSet__c'};

	private static final Schema.SObjectType SOBJECT_TYPE = SObjectType.DeliveryRoute__c.getSobjectType();
	private static final Map<String, Schema.SObjectField> FIELD_MAP = SObjectType.DeliveryRoute__c.fields.getMap();

    protected override String getOptionLabel() {
		return LABEL;
	}

	protected override String getFileReference() {
		return FILE_REFERENCE;
	}

	protected override Schema.SObjectType getObjectType() {
		return SOBJECT_TYPE;
	}

	protected override Map<String, Schema.SObjectField> getFieldMap() {
		return FIELD_MAP;
	}

	public override String getDelimiter() {
		return DELIMITER;
	}

	public override void process(List<Object> rows) {
        DeliveryRouteGroup__c deliveryRouteGroup = new DeliveryRouteGroup__c();
        INSERT deliveryRouteGroup;
		List<SObject> sObjects = createSObject(rows);
        for (SObject sObj : sObjects) {
            sObj.put('DeliveryRouteGroup__c', deliveryRouteGroup.Id);
        }
		List<Database.SaveResult> results = Database.insert(sObjects, false);
		LogRegister.createLogsUpsert(results, sObjects, 'Delivery Route - File Upload', 'Insert', 'DeliveryRoute__c', 'DeliveryRouteGroup__c');
	}

	protected override String getFieldName(String columnHeader) {
		return FIELDS_TO_PROCESS.get(columnHeader);
	}

	protected override void addField(SObject sObj, String fieldName, Object value) {
		if (!FIELDS_TO_PROCESS.values().contains(fieldName)) {
			return;
		}
        if (fieldName == 'Date__c') {
			value = Date.parse(String.valueOf(value).left(10));
		}

		super.addField(sObj, fieldName, value);
 	}
}