force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/RtePref__c.field-meta.xml
<CustomField>
    <fullName>RtePref__c</fullName>
    <label>Rte Pref</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartLocation__c.field-meta.xml
<CustomField>
    <fullName>StartLocation__c</fullName>
    <label>Start Location</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/VehicleCapacity__c.field-meta.xml
<CustomField>
    <fullName>VehicleCapacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRouteGroup__c/DeliveryRouteGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Route Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeliveryRouteFileUploadTest.cls
@isTest
public with sharing class DeliveryRouteFileUploadTest {
    
    @isTest
    static void testProcess() {
        
        List<Map<Object, Object>> rows = new List<Map<Object, Object>>();
        Map<Object, Object> row1 = new Map<Object, Object>{
            'routeId'=>'B1 180324',
			'startTime' => '08:00:00',
			'maxRouteTime' => '18:00:00',
			'vehicleCapacity' => 1000,
            'startLocation' => 2,
			'rtePref' => 1,
            'skillSetProperties' => 'B'
        };
        Map<Object, Object> row2 = new Map<Object, Object>{
            'routeId'=>'B2 180324',
			'startTime' => '09:00:00',
			'maxRouteTime' => '18:00:00',
			'vehicleCapacity' => 2000,
            'startLocation' => 3,
			'rtePref' => 4,
            'skillSetProperties' => 'Ag'
        };
        rows.add(row1);
        rows.add(row2);
        String delimiter = FileUploadController.getDelimiter('DeliveryRoute');
        String previewText = FileUploadController.preview('DeliveryRoute', rows);
        Test.startTest();
        FileUploadController.process('DeliveryRoute', rows);
        Test.stopTest();
        List<DeliveryRoute__c> deliveryRoutes = [SELECT Name, RtePref__c, SkillSet__c, StartLocation__c, StartTime__c, VehicleCapacity__c FROM DeliveryRoute__c];
        Assert.areEqual(2, deliveryRoutes.size());
        List<DeliveryRouteGroup__c> deliveryRouteGroup = [SELECT Id FROM DeliveryRouteGroup__c];
        Assert.areEqual(1, deliveryRouteGroup.size());
    }
}