force-app/main/default/objects/MileySetting__c/MileySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used by Miley mobile app</description>
    <label>Miley Setting</label>
</CustomObject>

force-app/main/default/objects/MileySetting__c/fields/AutoOpenLocationSubmissionRadius__c.field-meta.xml
<CustomField>
    <fullName>AutoOpenLocationSubmissionRadius__c</fullName>
    <defaultValue>50</defaultValue>
    <label>Auto Open Location Submission Radius</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/GeofenceLocationSubmissionRadius__c.field-meta.xml
<CustomField>
    <fullName>GeofenceLocationSubmissionRadius__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Geofence Location Submission Radius</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/IsLocationSubmissionAutoOpenEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsLocationSubmissionAutoOpenEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Open Location Submission?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/IsLocationSubmissionGeofenceEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsLocationSubmissionGeofenceEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Geofence Location Submission?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/LocationAccuracyPriority__c.field-meta.xml
<CustomField>
    <fullName>LocationAccuracyPriority__c</fullName>
    <description>105: PRIORITY_PASSIVE - No extra power will be used to derive locations.
104: PRIORITY_LOW_POWER - Low power usage at the possible expense of location accuracy.
102: PRIORITY_BALANCED_POWER_ACCURACY - Balanced between location accuracy and power usage.
100: PRIORITY_HIGH_ACCURACY - Highly accurate locations at the possible expense of additional power usage.</description>
    <label>Location Accuracy Priority</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/MaxLocationUpdateDelayMillis__c.field-meta.xml
<CustomField>
    <fullName>MaxLocationUpdateDelayMillis__c</fullName>
    <description>The longest a location update may be delayed.</description>
    <label>Maximum Location Update Delay (Millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MileySetting__c/fields/MinLocationUpdateDistanceMeters__c.field-meta.xml
<CustomField>
    <fullName>MinLocationUpdateDistanceMeters__c</fullName>
    <description>Minimum distance required between consecutive location updates.</description>
    <label>Minimum Location Update Distance (Mtrs)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RoutingConfigurationRestTest.cls
@isTest
private class RoutingConfigurationRestTest {

	@isTest
	static void getConfigurations() {

		INSERT new MileySetting__c(IsLocationSubmissionAutoOpenEnabled__c = false, AutoOpenLocationSubmissionRadius__c = 50.0,
			IsLocationSubmissionGeofenceEnabled__c = true, GeofenceLocationSubmissionRadius__c = 100.0,
			LocationAccuracyPriority__c = 102.0, MaxLocationUpdateDelayMillis__c = 10000, MinLocationUpdateDistanceMeters__c = 200);

		RestRequest request = new RestRequest();
		RestContext.request = request;
		request.requestURI = '/services/apexrest/MileyConfiguration/';
		request.httpMethod = 'GET';

		RestResponse response = new RestResponse();
		RestContext.response = response;
		Test.startTest();
		RoutingConfigurationRest.get();
		Test.stopTest();

		Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response.responseBody.toString());
		Assert.isFalse((Boolean)responseMap.get('isLocationSubmissionAutoOpenEnabled'));
		Assert.isTrue((Boolean)responseMap.get('isLocationSubmissionGeofenceEnabled'));
		Assert.areEqual(50.0, (Decimal)responseMap.get('autoOpenLocationSubmissionRadius'));
		Assert.areEqual(100.0, (Decimal)responseMap.get('geofenceLocationSubmissionRadius'));
		Assert.areEqual(102, (Integer)responseMap.get('locationAccuracyPriority'));
		Assert.areEqual(10000, (Integer)responseMap.get('maxLocationUpdateDelayMillis'));
		Assert.areEqual(200, (Integer)responseMap.get('minLocationUpdateDistanceMeters'));
	}
}