force-app/main/default/objects/QR_Codes_from_Detrack__c/QR_Codes_from_Detrack__c.object-meta.xml
<CustomObject>
    <description>Where QR codes from Detrack are stored. On insertion a trigger will be fired to parse the codes field by &quot;\n&quot; or &quot; &quot; and insert a new Qr_code__c for each parsed value. The Driver app will then pick up these Qr_code__c records.</description>
    <label>QR Codes from Detrack</label>
    <nameField>
        <displayFormat>QRS-{00000000}</displayFormat>
        <label>QR Codes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QR Codes from Detrack</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QR_Codes_from_Detrack__c/fields/Number_of_codes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_codes__c</fullName>
    <description>Populated by trigger with total number of parsed values from QR_Codes_from_OrderItem__c</description>
    <label>Number of codes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QR_Codes_from_Detrack__c/fields/QR_Codes_from_OrderItem__c.field-meta.xml
<CustomField>
    <fullName>QR_Codes_from_OrderItem__c</fullName>
    <description>Populated by process on orderItem that creates record whenever the detrack QR code field is populated</description>
    <label>QR Codes from OrderItem</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestSplitQRCodesIntoNewRecords.cls
@istest

private class TestSplitQRCodesIntoNewRecords {
    @istest static void TestAddDetrackQRCodesRecord() {
        //test date setup
        //create new detrackQRcodesRecord
      QR_Codes_from_Detrack__c qrcodesOb = new QR_Codes_from_Detrack__c (QR_Codes_from_OrderItem__c = '12322');
      insert qrcodesOb;
        //perform test
        Test.startTest();
        qrcodesOb.Number_of_codes__c = 1;
        Test.stopTest();
    }
}