force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/IsSuspended__c.field-meta.xml
<CustomField>
    <fullName>IsSuspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suspended?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/ScheduleSuspension__c.object-meta.xml
<CustomObject>
    <label>Schedule Suspension</label>
    <nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Suspensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleSuspension__c/fields/Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Aggregator__c</fullName>
    <label>Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Suspensions</relationshipLabel>
    <relationshipName>Suspensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsEveryYear__c.field-meta.xml
<CustomField>
    <fullName>IsEveryYear__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Every Year?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/ReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationDate__c</fullName>
    <label>Reactivation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/SuspensionDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionDate__c</fullName>
    <label>Suspension Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateScheduleSuspensions.cls
public without sharing class CreateScheduleSuspensions {
	private static final Date TODAY = Date.today();
	private static final Date TOMORROW = Date.today().addDays(1);

	@InvocableMethod(Label='Create Schedule Suspensions')
	public static void create(List<Input> inputs) {
		if (inputs.isEmpty()){
			return;
		}

		List<ScheduleSuspension__c> scheduleSuspensions;
		List<String> newAggregatorSuspensionKeys;
		CollectionAggregator__c newAggregator;
		for (Input input : inputs) {
			if (input.amendedAggregatorId == null || input.newSchedules.isEmpty()) {
				return;
			}

			newAggregatorSuspensionKeys = new List<String>();
			newAggregator = [SELECT CollectionAggregator__c, CollectionAggregator__r.IsSuspended__c FROM Schedule__c WHERE Id IN :input.newSchedules ORDER BY CreatedDate DESC LIMIT 1].CollectionAggregator__r;
			for (ScheduleSuspension__c scheduleSuspension : [SELECT Aggregator__c, SuspensionDate__c, ReactivationDate__c, IsEveryYear__c FROM ScheduleSuspension__c WHERE Aggregator__c = :newAggregator.Id AND ReactivationDate__c > TODAY]) {
				newAggregatorSuspensionKeys.add(scheduleSuspension.Aggregator__c + '-' + scheduleSuspension.SuspensionDate__c + '-' + scheduleSuspension.ReactivationDate__c);
			}

			scheduleSuspensions = new List<ScheduleSuspension__c>();
			String key;
			for (ScheduleSuspension__c scheduleSuspension : [SELECT Aggregator__c, SuspensionDate__c, ReactivationDate__c, IsEveryYear__c FROM ScheduleSuspension__c WHERE Aggregator__c = :input.amendedAggregatorId AND ReactivationDate__c > TODAY AND IsActive__c = TRUE]) {
				key = scheduleSuspension.Aggregator__c + '-' + scheduleSuspension.SuspensionDate__c + '-' + scheduleSuspension.ReactivationDate__c;
				if (!newAggregatorSuspensionKeys.contains(key) && scheduleSuspension.SuspensionDate__c > TODAY) {
					scheduleSuspensions.add(new ScheduleSuspension__c(Aggregator__c = newAggregator.Id, SuspensionDate__c = scheduleSuspension.SuspensionDate__c, ReactivationDate__c = scheduleSuspension.ReactivationDate__c, IsEveryYear__c = scheduleSuspension.IsEveryYear__c));
				} else if (!newAggregatorSuspensionKeys.contains(key) && scheduleSuspension.SuspensionDate__c < TODAY && scheduleSuspension.ReactivationDate__c > TOMORROW && !newAggregator.IsSuspended__c) {
					scheduleSuspensions.add(new ScheduleSuspension__c(Aggregator__c = newAggregator.Id, SuspensionDate__c = TOMORROW, ReactivationDate__c = scheduleSuspension.ReactivationDate__c, IsEveryYear__c = scheduleSuspension.IsEveryYear__c));
				}
			}

			if (!scheduleSuspensions.isEmpty()) {
				Database.SaveResult[] results = Database.insert(scheduleSuspensions, false);
				LogRegister.createLogsUpsert(results, scheduleSuspensions, 'Create Schedule Suspensions', 'Insert', 'ScheduleSuspension__c', 'Aggregator__c');
			}

		}
	}

	public class Input {
		@InvocableVariable(required=true label='New Schedules')
		public List<Schedule__c> newSchedules;
		@InvocableVariable(required=true label='Amended Aggregator Id')
		public Id amendedAggregatorId;
	}
}