force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>LEFT(
  IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;),
  LEN(
    IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;)
  ) - 2
)</formula>
    <label>Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <label>Friday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <label>Monday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <label>Saturday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <label>Sunday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <label>Thursday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <label>Tuesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <label>Wednesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectionScheduleController.cls
global without sharing class CollectionScheduleController {

	@AuraEnabled
	public static List<CollectionAggregator__c> getCollections(Id recordId) {
		return [SELECT Supplier_Product__c, Supplier_Product__r.Product_Name__c, Quantity__c,
					Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c,
					(SELECT Id, Days__c FROM Collections__r)
				FROM CollectionAggregator__c WHERE Location__c = :recordId
				ORDER BY Supplier_Product__r.Product_Name__c];
	}

	@AuraEnabled
	public static void deleteAllCollections(Id recordId) {
		DELETE [SELECT Id FROM Schedule__c WHERE Location__c = :recordId];
	}
}