force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Waste_Category__c.field-meta.xml
<CustomField>
    <fullName>Waste_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Waste Category</label>
    <referenceTo>Waste_Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/WTN_Product__c.field-meta.xml
<CustomField>
    <fullName>WTN_Product__c</fullName>
    <label>WTN Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTNProduct</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Waste_Category__c/Waste_Category__c.object-meta.xml
<CustomObject>
    <label>Waste Category</label>
    <nameField>
        <label>Waste Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTN_Waste_Category__c/WTN_Waste_Category__c.object-meta.xml
<CustomObject>
    <label>WTN Waste Category</label>
    <nameField>
        <displayFormat>WTN{YYYY}{MM}-{0}</displayFormat>
        <label>WTN Waste Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WTN Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTN_Waste_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/fields/Waste_Category__c.field-meta.xml
<CustomField>
    <fullName>Waste_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Waste Category</label>
    <referenceTo>Waste_Category__c</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/WTNProduct.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Season Ticket</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No WTN</fullName>
    </customValue>
    <customValue>
        <fullName>Hazardous Consignment Note</fullName>
    </customValue>
    <masterLabel>WTN Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateWasteCategoryProductTest.cls
@isTest
public class CreateWasteCategoryProductTest {

	@testSetup
	static void setup() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Contact contact = TestDataHelper.insertContact(parent.Id, 'FirstMile');
		TestDataHelper.insertAccountContactRelation(location.Id, contact.Id, 'Service Contact');

		Product_Category__c productCategory = TestDataHelper.insertProductCategory('Test Product Category');
		Waste_Category__c  wasteCategory = TestDataHelper.insertWasteCategory('Cardboard Waste', '123456');
		Container_Type__c containerType = TestDataHelper.insertContainerType('Bin');

		Product2 product = TestDataHelper.createProduct('Test Product', '12355321', 'Collection', productCategory.Id, wasteCategory.Id, containerType.Id, '264');
		product.WTN_Product__c = 'Season Ticket';
		INSERT product;

		Suppliers__c supplier = TestDataHelper.insertSupplier('First Mile Ltd');
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);

		List<CreateSeasonTicketWasteTransferNote.Input> inputs = new List<CreateSeasonTicketWasteTransferNote.Input>();
		CreateSeasonTicketWasteTransferNote.Input input = new CreateSeasonTicketWasteTransferNote.Input();
		input.locationId = location.Id;
		input.supplierId = supplier.Id;
		input.startDate = System.today();
		inputs.add(input);

		CreateSeasonTicketWasteTransferNote.create(inputs);
		Assert.areEqual(1, [SELECT Id FROM Compliance_Doc__c].size());
	}

	@isTest
	static void create() {
		Supplier_Product__c supplierProduct = [SELECT Id, Product__c FROM Supplier_Product__c LIMIT 1];
		List<CreateWasteCategoryProduct.Input> inputs = new List<CreateWasteCategoryProduct.Input>();
		CreateWasteCategoryProduct.Input input = new CreateWasteCategoryProduct.Input();
		input.complianceDocumentId = [SELECT Id FROM Compliance_Doc__c LIMIT 1].Id;
		input.productId = supplierProduct.Product__c;
		inputs.add(input);

		CreateWasteCategoryProduct.create(inputs);
		Assert.areEqual(1, [SELECT Id FROM WTN_Waste_Category__c].size());
	}

	@isTest
	static void duplicateCheck() {
		Supplier_Product__c supplierProduct = [SELECT Id, Product__c FROM Supplier_Product__c LIMIT 1];
		String complianceDocumentId = [SELECT Id FROM Compliance_Doc__c LIMIT 1].Id;
		List<CreateWasteCategoryProduct.Input> inputs = new List<CreateWasteCategoryProduct.Input>();
		for (Integer i=0; i<5; i++) {
			CreateWasteCategoryProduct.Input input = new CreateWasteCategoryProduct.Input();
			input.complianceDocumentId = complianceDocumentId;
			input.productId = supplierProduct.Product__c;
			inputs.add(input);
		}

		CreateWasteCategoryProduct.create(inputs);
		Assert.areEqual(1, [SELECT Id FROM WTN_Waste_Category__c].size());
	}
}