force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DispatchFormRestTest.cls
@isTest
private class DispatchFormRestTest {

	private static final Integer JOB_ID = 1234;

	@testSetup
	static void setup() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		Round__c round = TestDataHelper.insertRound(true);
		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		TestDataHelper.insertVehicle('ABC XYZ');
	}

	@isTest
	static void get() {
		DailyDispatch__c dispatch = [SELECT Id FROM DailyDispatch__c];
		RestRequest request = new RestRequest();
		RestContext.request = request;
		request.requestURI = '/services/apexrest/DispatchForm/' + dispatch.Id;
		request.httpMethod = 'GET';

		RestResponse response = new RestResponse();
		RestContext.response = response;
		Test.startTest();
		DispatchFormRest.get();
		Test.stopTest();

		Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response.responseBody.toString());
		Assert.areEqual(1, ((List<Object>)responseMap.get('vehicles')).size());
		Assert.areEqual(false, (Boolean)responseMap.get('isStarted'));
	}

	@isTest
	static void getWithPreviousDispatch() {
		Round__c round = [SELECT Id FROM Round__c];
		DailyDispatch__c dispatchYesterday = new DailyDispatch__c(RoundId__c = round.Id, Name = 'Yesterday');
		dispatchYesterday.CreatedDate = System.today().addDays(-1);
		INSERT dispatchYesterday;

		DailyDispatch__c dispatch = [SELECT Id FROM DailyDispatch__c WHERE Id != :dispatchYesterday.Id];
		RestRequest request = new RestRequest();
		RestContext.request = request;
		request.requestURI = '/services/apexrest/DispatchForm/' + dispatch.Id;
		request.httpMethod = 'GET';

		RestResponse response = new RestResponse();
		RestContext.response = response;
		Test.startTest();
		DispatchFormRest.get();
		Test.stopTest();

		Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response.responseBody.toString());
		Assert.areEqual(1, ((List<Object>)responseMap.get('vehicles')).size());
		Assert.areEqual(false, (Boolean)responseMap.get('isStarted'));
	}
}