force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DeliveryOrder__c/DeliveryOrder__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DlvyOrder-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryOrderGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryOrderGroup__c</fullName>
    <label>Delivery Order Group</label>
    <referenceTo>DeliveryOrderGroup__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <label>Demand</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTime__c</fullName>
    <label>Service Time</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/DeliveryOrderGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Order Group</label>
    <nameField>
        <displayFormat>DlvyOrderGrp-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Order Group</relationshipLabel>
    <relationshipName>DeliveryRouteGroup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RoutingPollCount__c.field-meta.xml
<CustomField>
    <fullName>RoutingPollCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Routing Poll Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RoutingSummary__c.field-meta.xml
<CustomField>
    <fullName>RoutingSummary__c</fullName>
    <label>Routing Summary</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/EndDepot__c.field-meta.xml
<CustomField>
    <fullName>EndDepot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Delivery Routes End</relationshipLabel>
    <relationshipName>DeliveryRoutesEnd</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/MaxRouteTime__c.field-meta.xml
<CustomField>
    <fullName>MaxRouteTime__c</fullName>
    <label>Max Route Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <label>Preference</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartDepot__c.field-meta.xml
<CustomField>
    <fullName>StartDepot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Start Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Delivery Routes Start</relationshipLabel>
    <relationshipName>DeliveryRoutesStart</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/VehicleCapacity__c.field-meta.xml
<CustomField>
    <fullName>VehicleCapacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRouteGroup__c/DeliveryRouteGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Route Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Index</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingStreetLineSingle__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreetLineSingle__c</fullName>
    <description>Street as a single line.</description>
    <formula>SUBSTITUTE(ShippingStreet, MID($Setup.LineBreak__c.Value__c, 2, 2), &apos;, &apos;)</formula>
    <label>Shipping Street Line Single</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/RoutingParameterOverride__mdt.object-meta.xml
<CustomObject>
    <label>Routing Parameter Override</label>
    <pluralLabel>Routing Parameter Overrides</pluralLabel>
</CustomObject>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/MaxRouteTime__c.field-meta.xml
<CustomField>
    <fullName>MaxRouteTime__c</fullName>
    <description>Max duration of route.</description>
    <label>Max Route Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/NumberOfRoutes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfRoutes__c</fullName>
    <description>Desired number of routes to create.</description>
    <label>Number of Routes to create</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time of routes.</description>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoutingPostDeliveryJob.cls
public without sharing class RoutingPostDeliveryJob extends RoutingPostJob {

	private Id orderGroupId;

	public RoutingPostDeliveryJob(Id orderGroupId) {
		this.orderGroupId = orderGroupId;
	}

	protected override RoutingRequest createRequest() {
		RoutingParameterOverride__mdt overrides = RoutingParameterOverride.get('Delivery');

		List<DeliveryOrder__c> orders = [SELECT Order__r.OrderNumber, Order__r.Account.Name, Order__r.ShippingStreetLineSingle__c, Order__r.ShippingPostalCode,
			Order__r.ShippingLatitude, Order__r.ShippingLongitude, ServiceTime__c, Demand__c, ServiceType__c, SkillSet__c
			FROM DeliveryOrder__c WHERE DeliveryOrderGroup__c = :orderGroupId];

		Id deliveryRouteGroupId = [SELECT DeliveryRouteGroup__c FROM DeliveryOrderGroup__c WHERE Id = :orderGroupId].DeliveryRouteGroup__c;
		List<DeliveryRoute__c> routes = [SELECT Name, StartTime__c, MaxRouteTime__c, VehicleCapacity__c, StartDepot__r.Index__c, EndDepot__r.Index__c, Preference__c, SkillSet__c
			FROM DeliveryRoute__c WHERE DeliveryRouteGroup__c = :deliveryRouteGroupId];

		overrides.NumberOfRoutes__c = routes.size();

		Set<Id> depotIds = IdUtil.extractId(routes, 'StartDepot__c');
		List<Depot__c> depots = [SELECT Index__c, Name, Address__Street__s, Address__City__s, Address__PostalCode__s, Coordinates__Latitude__s, Coordinates__Longitude__s
			FROM Depot__c WHERE Id IN :depotIds];

		return new RoutingRequestDelivery(overrides, depots, orders, routes);
	}

	protected override void updateJobError(String status, String message) {
		updateJob(new DeliveryOrderGroup__c(RoutingStatus__c = status, RoutingResponse__c = message));
	}

	protected override void processResult(RoutingResponse routingResponse) {
		updateJob(new DeliveryOrderGroup__c(RoutingJobId__c = routingResponse.jobId, RoutingStatus__c = 'In Progress',
			RoutingPollCount__c = 0, RoutingResponse__c = null, RoutingSummary__c = null));

		System.enqueueJob(new RoutingGetDeliveryResultQueueable(routingResponse.jobId), 1);
	}

	private void updateJob(DeliveryOrderGroup__c deliveryOrderGroup) {
		deliveryOrderGroup.Id = orderGroupId;
		UPDATE deliveryOrderGroup;
	}
}