force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/OrderProducts__c.field-meta.xml
<CustomField>
    <fullName>OrderProducts__c</fullName>
    <label>Order Products</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BinKey__c.field-meta.xml
<CustomField>
    <fullName>BinKey__c</fullName>
    <label>Bin Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CollectionDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionDate__c</fullName>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BinSummaryOfOrderProductBatch.cls
public without sharing class BinSummaryOfOrderProductBatch implements Database.Batchable<sObject>, Database.Stateful {

	private String MONTH;
	private String YEAR;
	private String CREATED_DATE_CRITERIA;

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		Date today = System.today();

		if (today.day() == 1) {
			Date yesterday = today - 1;
			CREATED_DATE_CRITERIA = 'CollectionDate__c = LAST_MONTH';
			MONTH = String.valueOf('0' + yesterday.month()).right(2);
			YEAR = String.valueOf(yesterday.year());
		} else {
			CREATED_DATE_CRITERIA = 'CollectionDate__c = THIS_MONTH AND CollectionDate__c != TODAY';
			MONTH = String.valueOf('0' + today.month()).right(2);
			YEAR = String.valueOf(today.year());
		}

		String query = 'SELECT Id FROM Account WHERE Id IN (SELECT Location__c FROM OrderItem WHERE BinKey__c != null AND ' + CREATED_DATE_CRITERIA + ')';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Account> locations) {
		List<BinSummary__c> binSummaries = new List<BinSummary__c>();
		String key;
		List<String> splitKey;

		String aggregateQuery = 'SELECT BinKey__c, SUM(Quantity) OrderProducts FROM OrderItem WHERE Location__c IN :locations AND BinKey__c != null AND ' + CREATED_DATE_CRITERIA + ' GROUP BY BinKey__c';
		for (AggregateResult aggregateResult : Database.query(aggregateQuery)) {
			key = (String)aggregateResult.get('BinKey__c');
			splitKey = StringUtil.splitTrim(key, '-');
			binSummaries.add(new BinSummary__c(Key__c = key, Location__c = splitKey[0], CategoryCode__c = splitKey[1], Year__c = YEAR, Month__c = MONTH, OrderProducts__c = (Decimal)aggregateResult.get('OrderProducts')));
		}

		if (!binSummaries.isEmpty()) {
			UPSERT binSummaries Key__c;
		}
	}

	public void finish(Database.BatchableContext BC) {
        Database.executeBatch(new BinSummaryOfBinLiftBatch());
    }
}