force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/AD_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AD_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.AD_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AD KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Coffee_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_from_Weights__c</fullName>
    <label>Coffee KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Coffee_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Coffee_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coffee KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/KWH_Produced_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>KWH_Produced_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.KWH_Produced__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KWH Produced Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Recycle_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recycled KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.CO2_Saved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tonnes CO2 Saved Per Unit</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_from_Weights__c</fullName>
    <label>Total KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Trees_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Trees_Saved_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Trees_Saved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trees Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.WTE_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WTE KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weight__c/Weight__c.object-meta.xml
<CustomObject>
    <label>Weight</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weight__c/fields/AD_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AD_KG_Per_Unit__c</fullName>
    <label>AD KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Coffee_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_Per_Unit__c</fullName>
    <label>Coffee KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/KWH_Produced_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>KWH_Produced_Per_Unit__c</fullName>
    <label>KWH Produced Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Weights</relationshipLabel>
    <relationshipName>Weights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Recycled_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG_Per_Unit__c</fullName>
    <label>Recycled KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Tonnes_CO2_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved_Per_Unit__c</fullName>
    <label>Tonnes CO2 Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Total_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_Per_Unit__c</fullName>
    <label>Total KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Trees_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Trees_Saved_Per_Unit__c</fullName>
    <label>Trees Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/WTE_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG_Per_Unit__c</fullName>
    <label>WTE KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeightToOrderProductRollupTest.cls
@isTest
public class WeightToOrderProductRollupTest {

	public static Id pricebookId = Test.getStandardPricebookId();

	@TestSetup
	static void testSetup(){
		Account parentAcc = TestDataHelper.insertAccount();
        Account location = TestDataHelper.insertLocation(parentAcc.Id, null);

		Product2 product = TestDataHelper.insertProduct('General Collection', '123', 'Collection');
		product.BinCategoryCode__c = 'COFFEE140';
        UPDATE product;

		PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = product.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        Insert pbe;

		TestDataHelper.insertSupplier('First Mile Ltd');
		Order order = new Order(AccountId = location.Id,
									EffectiveDate = System.today(),
									Status = 'Confirmed',
									Pricebook2Id = Test.getStandardPricebookId(),
									Type = 'Regular');
		INSERT order;

		OrderItem orderItem = new OrderItem(OrderId = order.Id,
												Quantity =4,
												Product2Id = product.Id,
												PriceBookEntryId = pbe.Id,
												UnitPrice = 1500);
		INSERT orderItem;
	}

	@isTest
	static void testWeightToOrderProductRollup() {
		Account account = [SELECT Id FROM Account WHERE RecordType.Name ='Location' LIMIT 1];
		OrderItem orderItems = [SELECT Id FROM OrderItem LIMIT 1];

		Weight__c weight = new Weight__c();
        weight.Order_Product__c = orderItems.Id;
        weight.AD_KG_Per_Unit__c = 1;
        weight.Coffee_KG_Per_Unit__c = 2;
        weight.KWH_Produced_Per_Unit__c = 3;
        weight.Recycled_KG_Per_Unit__c = 4;
        weight.Tonnes_CO2_Saved_Per_Unit__c = 5;
        weight.Total_KG_Per_Unit__c = 6;
        weight.Trees_Saved_Per_Unit__c = 7;
        weight.WTE_KG_Per_Unit__c = 8;
        INSERT weight;

		List<OrderItem> orderItemList = [SELECT Coffee_KG_from_Weights__c, Total_KG_from_Weights__c FROM OrderItem];
		Assert.areEqual(2, orderItemList[0].Coffee_KG_from_Weights__c);
		Assert.areEqual(6, orderItemList[0].Total_KG_from_Weights__c);

        DELETE weight;
		List<OrderItem> orderItemsAfterDelete = [SELECT Coffee_KG_from_Weights__c, Total_KG_from_Weights__c FROM OrderItem];
		Assert.areEqual(null, orderItemsAfterDelete[0].Coffee_KG_from_Weights__c);
		Assert.areEqual(null, orderItemsAfterDelete[0].Total_KG_from_Weights__c);
	 }

}