force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/ScheduleSuspension__c.object-meta.xml
<CustomObject>
    <label>Schedule Suspension</label>
    <nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Suspensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleSuspension__c/fields/Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Aggregator__c</fullName>
    <label>Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Suspensions</relationshipLabel>
    <relationshipName>Suspensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsEveryYear__c.field-meta.xml
<CustomField>
    <fullName>IsEveryYear__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Every Year?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/ReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationDate__c</fullName>
    <label>Reactivation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/SuspensionDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionDate__c</fullName>
    <label>Suspension Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>OR(End_Date__c &gt;= TODAY(), ISBLANK(End_Date__c))</formula>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectionSuspendExtendBatchTest.cls
@isTest
private class CollectionSuspendExtendBatchTest {

	@testSetup
	static void setup() {
		TestDataHelper.suppressSuspensionDateValidation();
		Product2 product = TestDataHelper.insertProduct('Product 1', 'P0001', 'Collection');
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Round__c round = TestDataHelper.insertRound();
		TestDataHelper.insertSchedule(location, round, supplier, supplierProduct, '08:00');
	}

	@isTest
	static void extendToNextYear() {
		Schedule__c schedule = [SELECT Id, CollectionAggregator__c FROM Schedule__c LIMIT 1];
		ScheduleSuspension__c pastReactivationEveryYear = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = System.today().addDays(-10), ReactivationDate__c = System.today().addDays(-1), IsEveryYear__c = true);
		ScheduleSuspension__c pastReactivationNotEveryYear = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = System.today().addDays(-10), ReactivationDate__c = System.today().addDays(-1));
		ScheduleSuspension__c futureReactivationEveryYear = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = System.today().addDays(-5), ReactivationDate__c = System.today().addDays(10), IsEveryYear__c = true);
		ScheduleSuspension__c futureSuspensionEveryYear = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = System.today().addDays(15), ReactivationDate__c = System.today().addDays(25), IsEveryYear__c = true);
		ScheduleSuspension__c inactivePastReactivationEveryYear = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = System.today().addDays(-30), ReactivationDate__c = System.today().addDays(-1), IsEveryYear__c = true, IsActive__c = false);
		INSERT new List<ScheduleSuspension__c>{pastReactivationEveryYear, pastReactivationNotEveryYear, futureReactivationEveryYear, futureSuspensionEveryYear, inactivePastReactivationEveryYear};

		Test.startTest();
		Database.executeBatch(new CollectionSuspendExtendBatch(), 1);
		Test.stopTest();

		Map<Id, ScheduleSuspension__c> suspensions = new Map<Id, ScheduleSuspension__c>([SELECT SuspensionDate__c, ReactivationDate__c FROM ScheduleSuspension__c]);
		pastReactivationEveryYear = suspensions.get(pastReactivationEveryYear.Id);
		Assert.areEqual(System.today().addDays(-10).addYears(1), pastReactivationEveryYear.SuspensionDate__c);
		Assert.areEqual(System.today().addDays(-1).addYears(1), pastReactivationEveryYear.ReactivationDate__c);

		pastReactivationNotEveryYear = suspensions.get(pastReactivationNotEveryYear.Id);
		Assert.areEqual(System.today().addDays(-10), pastReactivationNotEveryYear.SuspensionDate__c);
		Assert.areEqual(System.today().addDays(-1), pastReactivationNotEveryYear.ReactivationDate__c);

		futureReactivationEveryYear = suspensions.get(futureReactivationEveryYear.Id);
		Assert.areEqual(System.today().addDays(-5), futureReactivationEveryYear.SuspensionDate__c);
		Assert.areEqual(System.today().addDays(10), futureReactivationEveryYear.ReactivationDate__c);

		futureSuspensionEveryYear = suspensions.get(futureSuspensionEveryYear.Id);
		Assert.areEqual(System.today().addDays(15), futureSuspensionEveryYear.SuspensionDate__c);
		Assert.areEqual(System.today().addDays(25), futureSuspensionEveryYear.ReactivationDate__c);

		inactivePastReactivationEveryYear = suspensions.get(inactivePastReactivationEveryYear.Id);
		Assert.areEqual(System.today().addDays(-30), inactivePastReactivationEveryYear.SuspensionDate__c);
		Assert.areEqual(System.today().addDays(-1), inactivePastReactivationEveryYear.ReactivationDate__c);
	}
}