force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Qr_code__c/Qr_code__c.object-meta.xml
<CustomObject>
    <label>QR Code</label>
    <nameField>
        <displayFormat>{MM}-{YYYY}-{0}</displayFormat>
        <label>QR Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QR Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qr_code__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Qr_codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qr_code__c/fields/Driver_app_QR_code__c.field-meta.xml
<CustomField>
    <fullName>Driver_app_QR_code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>QR code scanned by the driver app</description>
    <label>Driver app QR code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QRCodeProcessorTest.cls
@isTest
public class QRCodeProcessorTest {
    
    @isTest
    public static void test(){
		
        Account parent = TestDataHelper.insertAccount();
        Account location = TestDataHelper.insertLocation(parent.Id, null);

        insert new Qr_code__c(Driver_app_QR_code__c = 'RZMa002673769', Account__c = location.Id);

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/findcustomerids/'; 

        String body = '';
        body += '{';
        body += '"qrCodes" : ["RZMa002673769"]';
        body += '}';

        req.requestBody = Blob.valueof(body);
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            QRCodeProcessor.findCustomerIdsByQRCodes(new List<String>{'RZMa002673769'});

            body = '';
            body += '{';
            body += '"qrCodes" : ["bdjhsb"]';
            body += '}';
            req.requestBody = Blob.valueof(body);
            RestContext.request = req; 
            RestContext.response= res;

            QRCodeProcessor.findCustomerIdsByQRCodes(new List<String>{'bdjhsb'});
        Test.stopTest();
    }
}