force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/NextCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>NextCollectionDate__c</fullName>
    <formula>PreviousCollectionDate__c + (VALUE(TEXT(WeekFrequency__c)) * 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/PreviousCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>PreviousCollectionDate__c</fullName>
    <label>Previous Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>&quot;18:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PreviousCollectionDateBatchTest.cls
@isTest
private class PreviousCollectionDateBatchTest {

	@testSetup
	static void setup() {
		TestDataHelper.insertCollectionServiceTimeSetting();

		Round__c round = TestDataHelper.insertRound();
		Product2 product = TestDataHelper.insertProduct('Product 1', 'P0001', 'Collection');
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Schedule__c schedule = TestDataHelper.createSchedule(location, round, supplier, supplierProduct, '08:00');
        schedule.PreviousCollectionDate__c = Date.today().addDays(-15);
		INSERT schedule;
	}

	@isTest
	static void updatePreviousCollectionDate() {
		Test.startTest();
		Database.executeBatch(new PreviousCollectionDateBatch());
		Test.stopTest();

		Assert.isTrue(System.today().addDays(-6) < [SELECT NextCollectionDate__c FROM Schedule__c WHERE Time__c = '08:00' LIMIT 1].NextCollectionDate__c);
	}

    @isTest
	static void computeDateWithWeekFrequencyTwo() {
		Assert.isTrue(System.today().addDays(-3) < new PreviousCollectionDateBatch().computePreviousCollectionDate(System.today().addDays(-15), 2));
	}

    @isTest
	static void computeDateWithWeekFrequencyThree() {
		Assert.isTrue(System.today().addDays(-20) < new PreviousCollectionDateBatch().computePreviousCollectionDate(System.today().addDays(-15), 3));
	}
}