force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <label>Friday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <label>Monday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <label>Saturday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <label>Sunday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/SupplierProductName__c.field-meta.xml
<CustomField>
    <fullName>SupplierProductName__c</fullName>
    <formula>Supplier_Product__r.Product_Name__c</formula>
    <label>Supplier Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <label>Thursday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <label>Tuesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <label>Wednesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendGridEmailTest.cls
@isTest
public class SendGridEmailTest {

	@testSetup
	private static void testSetup() {
		TestDataHelper.insertSendGridSetting();
	}

	private static testmethod void sendGridTest() {

		SendGridEmail.Input input = new SendGridEmail.Input();
		input.templateId = 'templateId123';
		input.toAddress = new List<String>{'toAddress@toAddress.com'};
		input.toName = new List<String>{'toName'};
		input.var01 = '1';
		input.var02 = '2';
		input.var03 = '3';
		input.var04 = '4';
		input.var05 = '5';
		input.var06 = '6';
		input.var07 = '7';
		input.var08 = '8';
		input.var09 = '9';
		input.var10 = '10';
		input.var11 = '11';
		input.var12 = '12';
		input.var13 = '13';
		input.var14 = '14';
		input.var15 = '15';
		input.var16 = '16';
		input.var17 = '17';
		input.var18 = '18';
		input.var19 = '19';
		input.var20 = '20';
		input.collection.add(UnitTest.testAccount());

		Test.setMock(HttpCalloutMock.class, new SendGridResponseMock());

		Test.startTest();
		new SendGridEmail(new List<SendGridEmail.Input>{input}).send();
		Test.stopTest();
	}

	private class SendGridResponseMock implements HttpCalloutMock {

		public HTTPResponse respond(HTTPRequest req) {
			HTTPResponse res = new HTTPResponse();
			res.setHeader('Content-Type', 'text/json');
			res.setStatusCode(200);
			return res;
		}
	}

	@isTest static void testHubSpotEvent() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Round__c round = TestDataHelper.insertRound();
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Product2 product = TestDataHelper.insertProduct('Product1', 'FM001', 'Collection');
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		TestDataHelper.insertSchedule(location, round, supplier, supplierProduct, '10:00');
		TestDataHelper.insertSchedule(location, round, supplier, supplierProduct, '11:00');

		List<sObject> aggregators = [SELECT SupplierProductName__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c FROM CollectionAggregator__c];

		SendGridEmail.Input input = new SendGridEmail.Input();
		input.templateId = 'templateId123';
		input.toAddress = new List<String>{'toAddress@toAddress.com'};
		input.toName = new List<String>{'toName'};
		input.accountId = 'TestAccoundId';
		input.eventType = 'TestEventType';
		input.var01 = '1';
		input.var02 = '2';
		input.var03 = '3';
		input.var04 = '4';
		input.var05 = '5';
		input.collection.addAll(aggregators);

		Test.setMock(HttpCalloutMock.class, new SendGridResponseMock());

		Test.startTest();
		new SendGridEmail(new List<SendGridEmail.Input>{input}).send();
		Test.stopTest();
	}
}