force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Ops_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Ops_Issue_Type__c</fullName>
    <label>Ops Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contamination</fullName>
            </value>
            <value>
                <fullName>Over Weight Limit</fullName>
            </value>
            <value>
                <fullName>Unbranded Bags</fullName>
                <label>Unbranded or Non First Mile Bags</label>
            </value>
            <value>
                <fullName>Loose Waste in Bin</fullName>
            </value>
            <value>
                <fullName>Excess Waste</fullName>
            </value>
            <value>
                <fullName>No Access to Collection Point</fullName>
            </value>
            <value>
                <fullName>Safety Issue</fullName>
            </value>
            <value>
                <fullName>Missed Collection</fullName>
            </value>
            <value>
                <fullName>Cardboard presented incorrectly</fullName>
            </value>
            <value>
                <fullName>Delivery Query</fullName>
            </value>
            <value>
                <fullName>Priority Collection Completed</fullName>
            </value>
            <value>
                <fullName>New Collection Completed</fullName>
            </value>
            <value>
                <fullName>Extra Job</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Operations.recordType-meta.xml
<RecordType>
    <fullName>Operations</fullName>
    <active>true</active>
    <businessProcess>Operational Complaint</businessProcess>
    <label>Operations</label>
</RecordType>

force-app/main/default/objects/Case_Types__c/Case_Types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Assigning record type to Case by its type as defined in this custom setting</description>
    <label>Case Types</label>
</CustomObject>

force-app/main/default/objects/Case_Types__c/fields/Case_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type_Name__c</fullName>
    <label>Case Record Type Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Types__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler_Test.cls
@isTest
public class CaseTriggerHandler_Test{

    public static testmethod void MyUnitTest(){
        
        Account parentAccount = TestDataHelper.createAccount();
        INSERT parentAccount;
        Account locationAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        INSERT locationAccount;
        
        List<RecordType> CaseRecordTypes = new list<RecordType>();
        CaseRecordTypes = [Select Id, Name from recordType where sObjectType = 'Case' and isActive = true];
        
        list<Case_Types__c> Setting = new list<Case_Types__c>();
        
        Case_Types__c cs = new Case_Types__c();
        cs.Name = 'CS1';
        cs.Case_Type__c = 'Operational Complaint';
        cs.Case_Record_Type_Name__c = 'Operations';
        setting.add(cs);
        
        Case_Types__c cs2 = new Case_Types__c();
        cs2.Name = 'CS2';
        cs2.Case_Type__c = 'Health & Safety';
        cs2.Case_Record_Type_Name__c = 'Health & Safety';
        setting.add(cs2);
        
        insert setting;
        
        List <Case> cases = new List<Case>();
        
        Case caseObj = new Case(
        AccountId = locationAccount.Id,
        Ops_Issue_Type__c = 'Excess Waste',
        Status = 'Working',
        Origin = 'Phone',
        Type = 'Operational Complaint');
        
        cases.add(caseObj);
        
        Case caseObj1 = new Case(
        AccountId = locationAccount.Id,
        Ops_Issue_Type__c = 'Contamination',
        Status = 'Working',
        Origin = 'Phone', 
        Type = 'Operational Test');
        
        cases.add(caseObj1);
        
        //insert cases;
        
        CaseTriggerHandler test = new CaseTriggerHandler();
        test.UpdateContaminationField(cases);
        test.UpdateCaseRecordType(cases);   
    }
    
	public static testmethod void MyUnitTest1(){
        
        Account parentAccount = TestDataHelper.createAccount();
        INSERT parentAccount;
        Account locationAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        INSERT locationAccount;
        
        List <Case> cases = new List<Case>();
        
        Case caseObj = new Case(
        AccountId = locationAccount.Id,
        Ops_Issue_Type__c = 'Excess Waste',
        Status = 'Working',
        Origin = 'Phone',
        Type = 'Operational Complaint');
        
        cases.add(caseObj);
        
        Case caseObj1 = new Case(
        AccountId = locationAccount.Id,
        Ops_Issue_Type__c = 'Contamination',
        Status = 'Working',
        Origin = 'Phone', 
        Type = 'Operational Test');
        
        cases.add(caseObj1);
        
        insert cases;
}
}