force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/DeliveryPackageTrackingFile__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking File</label>
    <nameField>
        <displayFormat>DelPkgTrkngFile-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>File Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteDeliveryPackageSchedularTest.cls
@isTest
private class DeleteDeliveryPackageSchedularTest {

	@testSetup
	static void setup() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Order order = TestDataHelper.insertOrder(location.Id);
		Test.setMock(WebServiceMock.class, new ParcelforceSoap.ShipmentSuccessMock());
        Suppliers__c supplier = TestDataHelper.insertSupplier('First Mile Ltd');
		DeliveryPackage__c pkg = TestDataHelper.insertDeliveryPackage(order.Id, DeliveryPackage.STATUS_CANCELLED);
		Test.setCreatedDate(pkg.Id, Datetime.now().addDays(-61));
	}

	@isTest
	static void deletePackages() {
		DeliveryPackage__c pkg = [SELECT Id FROM DeliveryPackage__c LIMIT 1];
		Test.startTest();
		new DeleteDeliveryPackageSchedular().execute(null);
		Test.stopTest();
		Assert.areEqual(0, [SELECT Id FROM DeliveryPackage__c].size());
	}

	@isTest
	static void deleteTrackingFiles() {
		DeliveryPackageTrackingFile__c trackingFile = new DeliveryPackageTrackingFile__c(FileName__c = 'SampleFile.csv');
		INSERT trackingFile;

		Test.setCreatedDate(trackingFile.Id, Datetime.now().addDays(-35));
		Test.startTest();
		new DeleteDeliveryPackageSchedular().execute(null);
		Test.stopTest();
		Assert.areEqual(0, [SELECT Id FROM DeliveryPackageTrackingFile__c].size());
	}
}