force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/DeliveryPackageQrCode__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code</label>
    <nameField>
        <displayFormat>DelPkgQrCde - {0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package QR Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/DeliveryPackage__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPackage__c</fullName>
    <label>Delivery Package</label>
    <referenceTo>DeliveryPackage__c</referenceTo>
    <relationshipLabel>QR Codes</relationshipLabel>
    <relationshipName>QrCodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/detrack_Qrcode__c.field-meta.xml
<CustomField>
    <fullName>detrack_Qrcode__c</fullName>
    <label>DEtrack QR Code</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DeliveryPackageAttachQrCodeTest.cls
@isTest
private class DeliveryPackageAttachQrCodeTest {

	@isTest
	static void attach() {
		TestDataHelper.insertSupplier('First Mile Ltd');
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Order order = TestDataHelper.insertOrder(location.Id);
		Product2 product = TestDataHelper.insertProduct('Test Name', 'Test Code', 'Delivery');
		PricebookEntry pbe = TestDataHelper.insertStandardPricebookEntry(product.Id, 65.00);
		OrderItem orderItem = TestDataHelper.insertOrderItem(order.Id, product.Id, pbe.Id);
		DeliveryPackage__c pkg = TestDataHelper.insertDeliveryPackage(order.Id, DeliveryPackage.STATUS_LABELLED);

		List<String> qrCodes = new String[] {'XYZ', 'ABC', 'PQR'};
		DeliveryPackageQrCode__c qrCode1 = TestDataHelper.createDeliveryPackageQrCode(pkg.Id, orderItem.Id, qrCodes[0]);
		DeliveryPackageQrCode__c qrCode2 = TestDataHelper.createDeliveryPackageQrCode(pkg.Id, orderItem.Id, qrCodes[1]);
		DeliveryPackageQrCode__c qrCode3 = TestDataHelper.createDeliveryPackageQrCode(pkg.Id, orderItem.Id, qrCodes[2]);
		INSERT new DeliveryPackageQrCode__c[]{qrCode1, qrCode2, qrCode3};

		Test.startTest();
		DeliveryPackageAttachQrCode.attach(new Id[]{order.id});
		Test.stopTest();

		qrCodes.sort();
		orderItem = [SELECT detrack_Qrcode__c FROM OrderItem LIMIT 1];
		Assert.areEqual(String.join(qrCodes, ','), orderItem.detrack_Qrcode__c);
	}
}