force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BinWeight__c/BinWeight__c.object-meta.xml
<CustomObject>
    <label>Bin Weight</label>
    <nameField>
        <displayFormat>BW-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinWeight__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Collection_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Collection_Waypoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Waypoint</label>
    <referenceTo>Collection_Waypoints__c</referenceTo>
    <relationshipLabel>Bin Weights</relationshipLabel>
    <relationshipName>Bin_Weights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Collected At?</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Weights</relationshipLabel>
    <relationshipName>BinWeights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Collection_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Collection_Waypoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Waypoint</label>
    <referenceTo>Collection_Waypoints__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Collection_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Collection_Waypoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Waypoint</label>
    <referenceTo>Collection_Waypoints__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CollectionDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionDate__c</fullName>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BinWeightMatchToWaypointBatchTest.cls
@isTest
private class BinWeightMatchToWaypointBatchTest {

	@isTest
	static void test() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		BinWeight__c bin1 = new BinWeight__c(Location__c = location.Id, CategoryCode__c = 'GEN1100', Kilogram__c = 100, Date__c = System.now() - 1);
		BinWeight__c bin2 = new BinWeight__c(Location__c = location.Id, CategoryCode__c = 'GEN1100', Kilogram__c = 100, Date__c = System.now() - 1);
		BinWeight__c bin3 = new BinWeight__c(Location__c = location.Id, CategoryCode__c = 'GEN1100', Kilogram__c = 100, Date__c = System.now() - 3);
		BinWeight__c bin4 = new BinWeight__c(Location__c = location.Id, CategoryCode__c = 'GEN1101', Kilogram__c = 100, Date__c = System.now() - 1);
		INSERT new List<BinWeight__c>{bin1, bin2, bin3, bin4};

		Product2 product = TestDataHelper.insertProduct('General Collection', '123', 'Collection');
		product.BinCategoryCode__c = 'GEN1100';
		UPDATE product;

		Round__c round = TestDataHelper.insertRound(true);
		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		DispatchLocation__c dispatchLocation = TestDataHelper.insertDispatchLocation(dispatch, location);
		Collection_Waypoints__c waypoint1 = TestDataHelper.insertWaypoint(location, dispatch, dispatchLocation);
		Collection_Waypoints__c waypoint2 = TestDataHelper.insertWaypoint(location, dispatch, dispatchLocation);

		PricebookEntry pbe = TestDataHelper.insertStandardPricebookEntry(product.Id, 1020);

		Order order = TestDataHelper.insertOrder(location.Id);
		OrderItem orderItem1 = TestDataHelper.createOrderItem(order.Id, product.Id, pbe.Id);
		orderItem1.CollectionDate__c = System.today() - 1;
		orderItem1.Collection_Waypoint__c = waypoint1.Id;
		INSERT orderItem1;

		OrderItem orderItem2 = TestDataHelper.createOrderItem(order.Id, product.Id, pbe.Id);
		orderItem2.CollectionDate__c = System.today() - 5;
		orderItem2.Collection_Waypoint__c = waypoint2.Id;
		INSERT orderItem2;

		Test.startTest();
		new BinWeightMatchToWaypointScheduler().execute(null);
		Test.stopTest();

		Assert.areEqual(null, [SELECT Collection_Waypoint__c FROM BinWeight__c WHERE Id = :bin4.Id].Collection_Waypoint__c);
		Assert.areEqual(orderItem1.Collection_Waypoint__c, [SELECT Collection_Waypoint__c FROM BinWeight__c WHERE Id = :bin1.Id].Collection_Waypoint__c);
		Assert.areEqual(orderItem1.Collection_Waypoint__c, [SELECT Collection_Waypoint__c FROM BinWeight__c WHERE Id = :bin2.Id].Collection_Waypoint__c);
		Assert.areEqual(orderItem2.Collection_Waypoint__c, [SELECT Collection_Waypoint__c FROM BinWeight__c WHERE Id = :bin3.Id].Collection_Waypoint__c);
	}
}