force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Round_Type__c.field-meta.xml
<CustomField>
    <fullName>Round_Type__c</fullName>
    <label>Round Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM Academy</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
                <label>MIDNIGHT</label>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PM + Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DispatchSequenceTest.cls
@isTest
private class DispatchSequenceTest {

	@testSetup
	static void setup() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		Round__c round = TestDataHelper.insertRound(true);
		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		DispatchLocation__c dispatchLocation = TestDataHelper.insertDispatchLocation(dispatch, location);
	}

	@isTest
	static void sequenceMorningDispatches() {
		Round__c round = [SELECT Id FROM Round__c LIMIT 1];
		round.Round_Type__c = 'AM';
		UPDATE round;

		DispatchLocation__c dispatchLocation = [SELECT SequenceNumber__c FROM DispatchLocation__c LIMIT 1];
		Assert.isNull(dispatchLocation.SequenceNumber__c);

		Test.startTest();
		DispatchSequence.sequenceMorningDispatches();
		Test.stopTest();

		dispatchLocation = [SELECT SequenceNumber__c FROM DispatchLocation__c LIMIT 1];
		Assert.isNotNull(dispatchLocation.SequenceNumber__c);
	}

	@isTest
	static void sequenceEveningDispatches() {
		Round__c round = [SELECT Id FROM Round__c LIMIT 1];
		round.Round_Type__c = 'PM';
		UPDATE round;

		DispatchLocation__c dispatchLocation = [SELECT SequenceNumber__c FROM DispatchLocation__c LIMIT 1];
		Assert.isNull(dispatchLocation.SequenceNumber__c);

		Test.startTest();
		EveningDispatchSequence.sequence();
		Test.stopTest();

		dispatchLocation = [SELECT SequenceNumber__c FROM DispatchLocation__c LIMIT 1];
		Assert.isNotNull(dispatchLocation.SequenceNumber__c);
	}
}