force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tonnage__c/Tonnage__c.object-meta.xml
<CustomObject>
    <label>Tonnage</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Tonnage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tonnages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tonnage__c/fields/DailyDispatch__c.field-meta.xml
<CustomField>
    <fullName>DailyDispatch__c</fullName>
    <label>Daily Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Tonnages</relationshipLabel>
    <relationshipName>Tonnages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TonnageSettings__c/TonnageSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Tonnage Settings</label>
</CustomObject>

force-app/main/default/objects/TonnageSettings__c/fields/DefaultDispatch__c.field-meta.xml
<CustomField>
    <fullName>DefaultDispatch__c</fullName>
    <label>Default Dispatch</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/WeightronEvent__c.object-meta.xml
<CustomObject>
    <label>Weightron Event</label>
    <nameField>
        <label>Ticket No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weightron Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WeightronEvent__c/fields/DateOfTip__c.field-meta.xml
<CustomField>
    <fullName>DateOfTip__c</fullName>
    <label>Date of Tip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/Net__c.field-meta.xml
<CustomField>
    <fullName>Net__c</fullName>
    <label>Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/RoundNumber__c.field-meta.xml
<CustomField>
    <fullName>RoundNumber__c</fullName>
    <label>Round Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeightronEvent__c/fields/TimeOfTip__c.field-meta.xml
<CustomField>
    <fullName>TimeOfTip__c</fullName>
    <label>Time of Tip</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/TonnageCreateTest.cls
@isTest
private class TonnageCreateTest {

	@testSetup
	static void makeData() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		List<Round__c> rounds = new List<Round__c>();
		rounds.add(TestDataHelper.createRound('Test Round 1', 1, 'AM'));	// Both days
		rounds.add(TestDataHelper.createRound('Test Round 2', 2, 'PM'));	// Both days
		rounds.add(TestDataHelper.createRound('Test Round 3', 3, 'PM'));	// Previous day only
		INSERT rounds;

		Date today = Date.today();
		Date yesterday = today.addDays(-1);
		List<DailyDispatch__c> dispatches = new List<DailyDispatch__c>();
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[0].Id, Name = rounds[0].Name, Dispatch_Date__c = today));		// Current day
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[1].Id, Name = rounds[1].Name, Dispatch_Date__c = today));		// Current day
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[0].Id, Name = rounds[0].Name, Dispatch_Date__c = yesterday));	// Previous day
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[1].Id, Name = rounds[1].Name, Dispatch_Date__c = yesterday));	// Previous day
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[2].Id, Name = rounds[2].Name, Dispatch_Date__c = yesterday));	// Previous day
		dispatches.add(new DailyDispatch__c(RoundId__c = rounds[0].Id, Name = rounds[0].Name, Dispatch_Date__c = today.addDays(-10)));	// As 'default' dispatch
		INSERT dispatches;

		INSERT new TonnageSettings__c(DefaultDispatch__c = dispatches[5].Id);

		List<WeightronEvent__c> events = new List<WeightronEvent__c>();
		events.add(new WeightronEvent__c(Name = '1234-01', RoundNumber__c = 1, Net__c = 1000, DateOfTip__c = yesterday, TimeOfTip__c = Time.newInstance(6,0,0,0)));	// R1 - AM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-02', RoundNumber__c = 1, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(6,0,0,0)));		// R1 - AM Current Day
		events.add(new WeightronEvent__c(Name = '1234-03', RoundNumber__c = 2, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(2,0,0,0)));		// R2 - PM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-04', RoundNumber__c = 2, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(6,0,0,0)));		// R2 - PM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-05', RoundNumber__c = 2, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(16,59,59,0)));	// R2 - PM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-06', RoundNumber__c = 2, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(17,0,0,0)));	// R2 - PM Current Day
		events.add(new WeightronEvent__c(Name = '1234-07', RoundNumber__c = 3, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(2,0,0,0)));		// R3 - PM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-08', RoundNumber__c = 3, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(21,0,0,0)));	// R3 - PM Previous Day
		events.add(new WeightronEvent__c(Name = '1234-09', RoundNumber__c = 3, Net__c = 1000, DateOfTip__c = yesterday, TimeOfTip__c = Time.newInstance(2,0,0,0)));	// R3 - PM Default Dispatch
		events.add(new WeightronEvent__c(Name = '1234-10', RoundNumber__c = 9, Net__c = 1000, DateOfTip__c = today, TimeOfTip__c = Time.newInstance(6,0,0,0)));		// Invalid Round 6 - Default Dispatch
		INSERT events;
	}

	@isTest
	static void testTonnageCreate() {
		Test.startTest();
		new TonnageCreateScheduler().execute(null);
		Test.stopTest();

		// Validate the created tonnage records and the dispatch date.
		Date today = Date.today();
		Assert.areEqual(2, [SELECT Id FROM Tonnage__c WHERE DailyDispatch__r.Dispatch_Date__c = :today.addDays(-10)].size());	// Default Dispatch
		Assert.areEqual(6, [SELECT Id FROM Tonnage__c WHERE DailyDispatch__r.Dispatch_Date__c = :today.addDays(-1)].size());	// Previous Day
		Assert.areEqual(2, [SELECT Id FROM Tonnage__c WHERE DailyDispatch__r.Dispatch_Date__c = :today].size());				// Current Day
	}

	@isTest
	static void testDeleteEvents() {
		List<WeightronEvent__c> events = [SELECT Id FROM WeightronEvent__c];
		Assert.areEqual(10, [SELECT Id FROM WeightronEvent__c].size());
		for (WeightronEvent__c event : events) {
			Test.setCreatedDate(event.Id, Datetime.now().addDays(-35));
		}

		Test.startTest();
		new DeleteWeightronEventSchedular().execute(null);
		Test.stopTest();
		Assert.areEqual(0, [SELECT Id FROM WeightronEvent__c].size());
	}
}