force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Daily_Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Daily_Dispatch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Dispatch</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>DailyDispatch__c.Dispatch_Date__c</field>
            <operation>equals</operation>
            <valueField>DailyDispatch__c.TODAY__c</valueField>
        </filterItems>
        <filterItems>
            <field>DailyDispatch__c.Dispatch_Date__c</field>
            <operation>equals</operation>
            <valueField>DailyDispatch__c.YESTERDAY__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minerva Road</fullName>
            </value>
            <value>
                <fullName>Camley Street</fullName>
            </value>
            <value>
                <fullName>Hoxton</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Waterloo Hub</fullName>
            </value>
            <value>
                <fullName>Harriet Walk</fullName>
            </value>
            <value>
                <fullName>Oldbury</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
                <isActive>false</isActive>
                <label>Birmingham</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectionWaypointTriggerHandlerTest.cls
@isTest
private class CollectionWaypointTriggerHandlerTest {

	@TestSetup
	static void setup() {
		Round__c round = TestDataHelper.insertRound();
		Product2 product = TestDataHelper.insertProduct('Product 1', 'P0001', 'Collection');
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
        List<Schedule__c> schedules = new List<Schedule__c>();
		schedules.add(TestDataHelper.createSchedule(location, round, supplier, supplierProduct, '08:00'));
		schedules.add(TestDataHelper.createSchedule(location, round, supplier, supplierProduct, '09:00'));
		INSERT schedules;

		Depot__c depot = [SELECT Id FROM Depot__c];
		Round__c round2 = TestDataHelper.createRound('Test Round 2', 2, depot, depot, false);
		INSERT round2;

        Test.startTest();
		Database.executebatch(new DispatchCreationBatch(), 5);
		Test.stopTest();
	}

	@isTest
	static void moveAllWaypoints() {
		List<DailyDispatch__c> dispatches = [SELECT Id FROM DailyDispatch__c ORDER BY RoundId__r.Name ASC];
        List<Collection_Waypoints__c> waypoints = [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id];
		for(Collection_Waypoints__c waypoint : waypoints) {
			waypoint.Daily_Dispatch__c = dispatches[1].Id;
		}

        Test.startTest();
        UPDATE waypoints;
        Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(0, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(waypoints.size(), [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[1].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());
	}

	@isTest
	static void moveOneWaypoint() {
		List<DailyDispatch__c> dispatches = [SELECT Id FROM DailyDispatch__c ORDER BY RoundId__r.Name ASC];
		Collection_Waypoints__c waypoint = [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id LIMIT 1];
		waypoint.Daily_Dispatch__c = dispatches[1].Id;

        Test.startTest();
        UPDATE waypoint;
        Test.stopTest();

		Assert.areEqual(1, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[1].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());
	}

	@isTest
	static void moveAllWaypointsExisting() {
		List<DailyDispatch__c> dispatches = [SELECT Id FROM DailyDispatch__c ORDER BY RoundId__r.Name ASC];
		TestDataHelper.insertDispatchLocation(dispatches[1], TestDataHelper.getLocation());

        List<Collection_Waypoints__c> waypoints = [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id];
		for(Collection_Waypoints__c waypoint : waypoints) {
			waypoint.Daily_Dispatch__c = dispatches[1].Id;
		}

		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());

        Test.startTest();
        UPDATE waypoints;
        Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(0, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(2, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[1].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());
	}

	@isTest
	static void moveOneWaypointsExisting() {
		List<DailyDispatch__c> dispatches = [SELECT Id FROM DailyDispatch__c ORDER BY RoundId__r.Name ASC];
		TestDataHelper.insertDispatchLocation(dispatches[1], TestDataHelper.getLocation());

		Collection_Waypoints__c waypoint = [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id LIMIT 1];
		waypoint.Daily_Dispatch__c = dispatches[1].Id;

		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());

        Test.startTest();
        UPDATE waypoint;
        Test.stopTest();

		Assert.areEqual(1, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[0].Id].size());
		Assert.areEqual(1, [SELECT Id FROM Collection_Waypoints__c WHERE Daily_Dispatch__c = :dispatches[1].Id].size());
		Assert.areEqual(1, [SELECT Id FROM DispatchLocation__c WHERE Dispatch__c = :dispatches[1].Id].size());
	}
}