force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice_HeaderId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_HeaderId__c</fullName>
    <label>Invoice_HeaderId</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/VATRate__c.field-meta.xml
<CustomField>
    <fullName>VATRate__c</fullName>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PartnerVATRate__c.field-meta.xml
<CustomField>
    <fullName>PartnerVATRate__c</fullName>
    <label>Partner VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/VATRate__c.field-meta.xml
<CustomField>
    <fullName>VATRate__c</fullName>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Vat.cls
public without sharing class Vat {

	public static final Decimal DEFAULT_VAT_RATE = 20;

	public static Decimal calculate(List<OrderController.OrderItemData> orderItems) {
		Map<Decimal, Decimal> vatRateToAmountMap = new Map<Decimal, Decimal>();
		for (OrderController.OrderItemData item : orderItems) {
			if (!vatRateToAmountMap.containsKey(item.vatRate)) {
				vatRateToAmountMap.put(item.vatRate, 0);
			}
			vatRateToAmountMap.put(item.vatRate, vatRateToAmountMap.get(item.vatRate) + item.totalPrice);
		}

		Decimal vat = 0;
		for (Decimal vatRate : vatRateToAmountMap.keySet()) {
			vat += vatRateToAmountMap.get(vatRate) * vatRate / 100;
		}

		return vat.setScale(2, RoundingMode.HALF_UP);
	}

	public static void calculate(Set<Id> orderIds) {
		if (orderIds.isEmpty()) {
			return;
		}

		List<Order> orders = [SELECT Id, Account.RecordTypeId, (SELECT TotalPrice, VATRate__c, PartnerVATRate__c FROM OrderItems) FROM Order WHERE Id IN :orderIds AND Status != 'Invoiced'];
		Map<Id, Map<Decimal, Decimal>> orderMap = new Map<Id, Map<Decimal, Decimal>>();
		for (Order order : orders) {
			Boolean isPartnerOrder = order.Account.RecordTypeId == AccountUtil.RECORDTYPEID_PARTNER;
			Map<Decimal, Decimal> vatRateToAmountMap = new Map<Decimal, Decimal>();
			orderMap.put(order.Id, vatRateToAmountMap);
			for (OrderItem item : order.OrderItems) {
				Decimal vatRate = isPartnerOrder ? item.PartnerVATRate__c : item.VATRate__c;
				if (!vatRateToAmountMap.containsKey(vatRate)) {
					vatRateToAmountMap.put(vatRate, 0);
				}
				vatRateToAmountMap.put(vatRate, vatRateToAmountMap.get(vatRate) + item.TotalPrice);
			}
		}

		List<Order> ordersToUpdate = new List<Order>();
		for (Id orderId : orderMap.keySet()) {
			Map<Decimal, Decimal> vatRateToAmountMap = orderMap.get(orderId);
			Decimal orderVat = 0;
			for (Decimal vatRate : vatRateToAmountMap.keySet()) {
				orderVat += vatRateToAmountMap.get(vatRate) * vatRate / 100;
			}
			orderVat = orderVat.setScale(2, RoundingMode.HALF_UP);

			ordersToUpdate.add(new Order(Id = orderId, VAT__c = orderVat));
		}

		if (!ordersToUpdate.isEmpty()) {
			Database.SaveResult[] results = Database.update(ordersToUpdate, false);
			LogRegister.createLogsUpsert(results, ordersToUpdate, 'Set VAT on Order', 'Update', 'Order', null);
		}
	}

	public static Decimal calculate(Invoice_Header__c invoice) {
		Map<Decimal, Decimal> vatRateToAmountMap = new Map<Decimal, Decimal>();
		for (Invoice_Line__c line : invoice.Invoice_Lines__r) {
			if (!vatRateToAmountMap.containsKey(line.VATRate__c)) {
				vatRateToAmountMap.put(line.VATRate__c, 0);
			}
			vatRateToAmountMap.put(line.VATRate__c, vatRateToAmountMap.get(line.VATRate__c) + line.Amount__c);
		}

		Decimal vat = 0;
		for (Decimal vatRate : vatRateToAmountMap.keySet()) {
			vat += vatRateToAmountMap.get(vatRate) * vatRate / 100;
		}

		return vat.setScale(2, RoundingMode.HALF_UP);
	}
}