force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DeliveryOrder__c/DeliveryOrder__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DlvyOrder-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryOrderGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryOrderGroup__c</fullName>
    <label>Delivery Order Group</label>
    <referenceTo>DeliveryOrderGroup__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <label>Demand</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTime__c</fullName>
    <label>Service Time</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/DeliveryOrderGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Order Group</label>
    <nameField>
        <displayFormat>DlvyOrderGrp-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Order Group</relationshipLabel>
    <relationshipName>DeliveryRouteGroup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <summarizedField>DeliveryOrder__c.RouteDate__c</summarizedField>
    <summaryForeignKey>DeliveryOrder__c.DeliveryOrderGroup__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/EndDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>EndDepotIndex__c</fullName>
    <label>End Depot Index</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/MaxRouteTime__c.field-meta.xml
<CustomField>
    <fullName>MaxRouteTime__c</fullName>
    <label>Max Route Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <label>Preference</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>StartDepotIndex__c</fullName>
    <label>Start Depot Index</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/fields/VehicleCapacity__c.field-meta.xml
<CustomField>
    <fullName>VehicleCapacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryRouteGroup__c/DeliveryRouteGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Route Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Index</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/RoutingPostDeliveryJobTest.cls
@isTest
private class RoutingPostDeliveryJobTest {

	private static final Integer JOB_ID = 1234;
	private static final String ROUTE_NAME = 'Route 001';

	@testSetup
	static void setup() {
		TestDataHelper.insertSupplierFirstMile();

		Depot__c depot = TestDataHelper.insertDepot();
		Integer depotIndex = Convert.toInteger(depot.Index__c);

		DeliveryRouteGroup__c routeGroup = new DeliveryRouteGroup__c();
		INSERT routeGroup;
		DeliveryRoute__c route = new DeliveryRoute__c(DeliveryRouteGroup__c = routeGroup.Id, Name = ROUTE_NAME, StartDepotIndex__c = depotIndex, EndDepotIndex__c = depotIndex,
			StartTime__c = '09:00', MaxRouteTime__c = '11:00', VehicleCapacity__c = 100, Preference__c = 1, SkillSet__c = 'A,V,PM,PMC,WC,SC');
		INSERT route;

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
        Order order = TestDataHelper.insertOrder(location.Id);
		DeliveryOrderGroup__c orderGroup = new DeliveryOrderGroup__c(DeliveryRouteGroup__c = routeGroup.Id);
		INSERT orderGroup;
		DeliveryOrder__c deliveryOrder = new DeliveryOrder__c(DeliveryOrderGroup__c = orderGroup.Id, Demand__c = 10, Order__c = order.Id,
			RouteDate__c = System.today(), ServiceTime__c = 120, ServiceType__c = 'DEL', SkillSet__c = 'SC');
		INSERT deliveryOrder;
	}

	@isTest
	static void postJob() {
		DeliveryOrderGroup__c orderGroup = [SELECT Id FROM DeliveryOrderGroup__c];
		orderGroup.RoutingStatus__c = 'Requested';

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new Mock(true));
		UPDATE orderGroup;
		Test.stopTest();

		orderGroup = [SELECT RoutingJobId__c FROM DeliveryOrderGroup__c];
		Assert.areEqual(JOB_ID, orderGroup.RoutingJobId__c);
	}

	@isTest
	static void postJobError() {
		DeliveryOrderGroup__c orderGroup = [SELECT Id FROM DeliveryOrderGroup__c];

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new Mock(false));
		System.enqueueJob(new RoutingPostDeliveryJobQueueable(orderGroup.Id));
		Test.stopTest();

		orderGroup = [SELECT RoutingJobId__c, RoutingResponse__c FROM DeliveryOrderGroup__c];
		Assert.areEqual(null, orderGroup.RoutingJobId__c);
	}

    private class Mock implements HttpCalloutMock {

		Boolean isSuccess = true;
		private Mock(Boolean isSuccess) {
			this.isSuccess = isSuccess;
		}

		public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse response = new HTTPResponse();
			response.setHeader('Content-Type', 'text/json');

			RoutingResponse routingResponse = new RoutingResponse();
			routingResponse.jobId = JOB_ID;
			response.setStatusCode(isSuccess ? 202 : 501);
			response.setBody(JSON.serialize(routingResponse));
            return response;
        }
    }
}