force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteBinSummarySchedulerTest.cls
@isTest
private class DeleteBinSummarySchedulerTest {

	@isTest
	static void test(){
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		Date createdDate = System.today() - 367;
		String month = String.valueOf('0' + CreatedDate.month()).right(2);
		String year = String.valueOf(CreatedDate.year());
		String key1 = location.Id + '-' + 'GEN1100' + '-' + year + '-' + month;
		String key2 = location.Id + '-' + 'GEN660' + '-' + year + '-' + month;

		BinSummary__c bin1 = new BinSummary__c(Location__c = location.Id, Month__c = month, CategoryCode__c = 'GEN1100', Year__c = year, CreatedDate = createdDate, Key__c = key1);
		BinSummary__c bin2 = new BinSummary__c(Location__c = location.Id, Month__c = month, CategoryCode__c = 'GEN660', Year__c = year, CreatedDate = createdDate, Key__c = key2);
		INSERT new List<BinSummary__c>{bin1, bin2};

		Assert.areEqual(2, [SELECT Id FROM BinSummary__c].size());

		Test.startTest();
		new DeleteBinSummaryScheduler().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM BinSummary__c].size());
	}
}