force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Orders (Monthly Parent Invoice)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendInvoiceEmail__c/SendInvoiceEmail__c.object-meta.xml
<CustomObject>
    <description>Invoices to be generated as PDF and sent as email</description>
    <label>Send Invoice Email</label>
    <nameField>
        <displayFormat>InvoiceEmail-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Send Invoice Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendInvoiceEmail__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Send Invoice Emails</relationshipLabel>
    <relationshipName>InvoiceEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendInvoiceEmailBatchTest.cls
@isTest
public with sharing class SendInvoiceEmailBatchTest {

	@isTest
	static void withoutEmailEnabled() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Order order = TestDataHelper.insertOrder(location.Id);
		Invoice_Header__c invoice = TestDataHelper.insertInvoice(parent.Id, order.Id, Invoicing.FREQUENCY_IMMEDIATE);

		INSERT new SendInvoiceEmail__c(Invoice__c = invoice.Id);
		new SendInvoiceEmailBatch().execute(null);
	}

	@isTest
	static void withoutInvoiceLines() {
		TestDataHelper.insertSendGridSetting();

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Order order = TestDataHelper.insertOrder(location.Id);
		Invoice_Header__c invoice = TestDataHelper.insertInvoice(parent.Id, order.Id, Invoicing.FREQUENCY_IMMEDIATE);

		INSERT new SendInvoiceEmail__c(Invoice__c = invoice.Id);
		new SendInvoiceEmailBatch().execute(null);
	}

	@isTest
	static void withoutFinanceContact() {
		TestDataHelper.insertSendGridSetting();

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Order order = TestDataHelper.insertOrder(location.Id);
		Invoice_Header__c invoice = TestDataHelper.insertInvoice(parent.Id, order.Id, Invoicing.FREQUENCY_IMMEDIATE);
		TestDataHelper.insertInvoiceLine(invoice.Id);

		INSERT new SendInvoiceEmail__c(Invoice__c = invoice.Id);
		new SendInvoiceEmailBatch().execute(null);
	}

	@isTest
	static void withFinanceContactAndLines() {
		TestDataHelper.insertSendGridSetting();

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		TestDataHelper.insertContact(parent.Id, 'FirstMile');
		Order order = TestDataHelper.insertOrder(location.Id);
		Invoice_Header__c invoice1 = TestDataHelper.insertInvoice(parent.Id, order.Id, Invoicing.FREQUENCY_IMMEDIATE);
		Invoice_Header__c invoice2 = TestDataHelper.insertInvoice(parent.Id, order.Id, Invoicing.FREQUENCY_IMMEDIATE);
		TestDataHelper.insertInvoiceLine(invoice1.Id);
		TestDataHelper.insertInvoiceLine(invoice2.Id);

		INSERT new SendInvoiceEmail__c(Invoice__c = invoice1.Id);
		INSERT new SendInvoiceEmail__c(Invoice__c = invoice2.Id);
		new SendInvoiceEmailBatch().execute(null);
	}
}