force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Case/fields/Collection_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Collection_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Schedule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Location__c</field>
            <operation>equals</operation>
            <valueField>Schedule__c.Location__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <filterItems>
            <field>Account.Enqix_Dead_Live__c</field>
            <operation>equals</operation>
            <value>LIVE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <businessProcess>Email</businessProcess>
    <label>Master Case Record Type</label>
</RecordType>

force-app/main/default/objects/Missed_Collection__c/Missed_Collection__c.object-meta.xml
<CustomObject>
    <label>Missed Collection</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Missed_Collection__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/Collection_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Collection_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/IsExternalSupplier__c.field-meta.xml
<CustomField>
    <fullName>IsExternalSupplier__c</fullName>
    <formula>Collection_Schedule__r.IsExternalSupplier__c</formula>
    <label>External Supplier?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>Collection_Schedule__r.Supplier_Product__r.Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/SupplierId__c.field-meta.xml
<CustomField>
    <fullName>SupplierId__c</fullName>
    <formula>CASESAFEID(Collection_Schedule__r.Supplier__c)</formula>
    <label>Supplier Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/IsExternalSupplier__c.field-meta.xml
<CustomField>
    <fullName>IsExternalSupplier__c</fullName>
    <formula>AND(NOT(ISBLANK(Supplier__c)), Supplier__r.IsExternal__c)</formula>
    <label>External Supplier?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/SupplierAccount__c.field-meta.xml
<CustomField>
    <fullName>SupplierAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account selected should be of type Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <filterItems>
            <field>Account.IsOwnerOfSupplierGroup__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SupplierMissedCollectionEmail.cls
public without sharing class SupplierMissedCollectionEmail {

	private static final Id ORG_WIDE_EMAIL_ID = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'supplychain@thefirstmile.co.uk'].Id;

 	@InvocableMethod(label='Send Supplier Missed Collection Emails')
	public static void send(List<Id> caseIds) {
		if (caseIds.isEmpty()) return;

		Map<Id, Map<Id, List<Missed_Collection__c>>> caseToMissedCollections = groupMissedCollectionsBySupplier(caseIds);
		if (caseToMissedCollections.isEmpty()) {
			return;
		}

		EmailTemplate template = [SELECT Id, HtmlValue, Subject FROM EmailTemplate WHERE DeveloperName = 'SupplierMissedCollection' LIMIT 1];

		// Send an email to each supplier
		List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
		for (Map<Id, List<Missed_Collection__c>> supplierToMissedCollections : caseToMissedCollections.values()) {
			for (Id supplierId : supplierToMissedCollections.keySet()) {
				List<Missed_Collection__c> missedCollections = supplierToMissedCollections.get(supplierId);
				Missed_Collection__c firstMissedCollection = missedCollections[0];
				Suppliers__c supplier = firstMissedCollection.Collection_Schedule__r.Supplier__r;

				String street = firstMissedCollection.Case__r.Location__r.BillingStreetLineSingle__c;
				String postcode = firstMissedCollection.Case__r.Location__r.BillingPostalCode;
				String body = generateBody(missedCollections);
				String htmlBody = template.HtmlValue.replace('{{0}}', body)
									.replace('{{1}}', supplier.Name)
									.replace('{{2}}', firstMissedCollection.Case__r.Location__r.Name)
									.replace('{{3}}', String.isNotBlank(street) ? street : '')
									.replace('{{4}}', String.isNotBlank(postcode) ? postcode : '');

				Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
				email.setOrgWideEmailAddressId(ORG_WIDE_EMAIL_ID);
				email.setToAddresses(new List<String>{supplier.Email__c});
				email.setSubject(template.Subject);
				email.setHtmlBody(htmlBody);
				email.setWhatId(firstMissedCollection.Case__c);
				emails.add(email);
			}
		}

		if (!emails.isEmpty()) {
			Messaging.sendEmail(emails);
		}
	}

	private static Map<Id, Map<Id, List<Missed_Collection__c>>> groupMissedCollectionsBySupplier(List<Id> caseIds) {
		List<Missed_Collection__c> missedCollections = [SELECT Case__c, SupplierId__c, Date__c, ProductName__c,
			Case__r.Location__r.Name, Case__r.Location__r.BillingStreetLineSingle__c, Case__r.Location__r.BillingPostalCode,
			Collection_Schedule__r.Supplier__r.Name, Collection_Schedule__r.Supplier__r.Email__c
			FROM Missed_Collection__c WHERE Case__c IN :caseIds AND IsExternalSupplier__c = true AND Collection_Schedule__r.Supplier__r.Email__c != null];

		Map<Id, Map<Id, List<Missed_Collection__c>>> caseToMissedCollections = new Map<Id, Map<Id, List<Missed_Collection__c>>>();
		Map<Id, List<Missed_Collection__c>> supplierToMissedCollections;
		for (Missed_Collection__c missedCollection : missedCollections) {
			if (!caseToMissedCollections.containsKey(missedCollection.Case__c)) {
				caseToMissedCollections.put(missedCollection.Case__c, new Map<Id, List<Missed_Collection__c>>());
			}
			supplierToMissedCollections = caseToMissedCollections.get(missedCollection.Case__c);

			if (!supplierToMissedCollections.containsKey(missedCollection.SupplierId__c)) {
				supplierToMissedCollections.put(missedCollection.SupplierId__c, new List<Missed_Collection__c>());
			}
			supplierToMissedCollections.get(missedCollection.SupplierId__c).add(missedCollection);
		}

		return caseToMissedCollections;
	}

	private static String generateBody(List<Missed_Collection__c> missedCollections) {
		String body = '';
		String template = '<tr><td align="center"><table width="90%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td width="70%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{0}</td>'
			+ '<td width="30%" style="text-align: center; font-size: 12px; padding: 10px 0px; line-height: 14px">{1}</td></tr>'
			+ '</table></td></tr>'
			+ '<tr><td align="center"><table width="90%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td height="1.5" bgcolor="#21D1D2" width="1"></td></tr></table></td></tr>';

		for (Missed_Collection__c missedCollection : missedCollections) {
			body += String.format(template, new List<String>{missedCollection.ProductName__c, missedCollection.Date__c.format()});
		}
		return body;
	}
}