force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SageExtract__c/SageExtract__c.object-meta.xml
<CustomObject>
    <label>SageExtract</label>
    <nameField>
        <label>SageExtract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SageExtracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SageExtract__c/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/Bank_Statement__c.field-meta.xml
<CustomField>
    <fullName>Bank_Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Statement</label>
    <referenceTo>Bank_Statement__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/DatePostedtoSage__c.field-meta.xml
<CustomField>
    <fullName>DatePostedtoSage__c</fullName>
    <label>DatePostedtoSage</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/GoodsAmount__c.field-meta.xml
<CustomField>
    <fullName>GoodsAmount__c</fullName>
    <label>GoodsAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice_Line</label>
    <referenceTo>Invoice_Line__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/Narrative__c.field-meta.xml
<CustomField>
    <fullName>Narrative__c</fullName>
    <label>Narrative</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/PostedtoSage__c.field-meta.xml
<CustomField>
    <fullName>PostedtoSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PostedtoSage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/SageExtractFile__c.field-meta.xml
<CustomField>
    <fullName>SageExtractFile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SageExtractFile</label>
    <referenceTo>SageExtractFile__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>TransactionDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SageExtractFile__c/SageExtractFile__c.object-meta.xml
<CustomObject>
    <label>SageExtractFile</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>SageExtractFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SageExtractFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SageCSVFileBatch.cls
public class SageCSVFileBatch implements Database.Batchable<sObject>, Database.Stateful {

	private SageExtractFile__c sageExtractFile;

	public SageCSVFileBatch(Id sageExtractFileId) {
		sageExtractFile = [SELECT Id, Name FROM SageExtractFile__c WHERE Id = :sageExtractFileId];
	}

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		String query = 'SELECT Id, Name, Narrative__c, DatePostedtoSage__c, AccountNumber__c, GoodsAmount__c, TransactionDate__c, PostedtoSage__c, Bank_Statement__c, Bank_Statement__r.Id, Invoice_Line__c, Invoice_Line__r.Id, CreatedDate FROM SageExtract__c WHERE PostedtoSage__c = false AND TransactionDate__c != null ORDER BY Bank_Statement__c, Invoice_Line__c, CreatedDate';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext batchContext, List<SageExtract__c> sageExtracts) {
		for (SageExtract__c sageExtract : sageExtracts) {
			sageExtract.PostedtoSage__c = true;
			sageExtract.DatePostedtoSage__c = System.today();
			sageExtract.SageExtractFile__c = sageExtractFile.Id;
			sageExtract.Narrative__c = sageExtractFile.Name;
		}
		UPDATE sageExtracts;
	}

	public void finish(Database.BatchableContext batchContext) {}
}