force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/PaymentId__c.field-meta.xml
<CustomField>
    <fullName>PaymentId__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentChangeEventTriggerHandler.cls
public with sharing class PaymentChangeEventTriggerHandler extends BusinessCentralEventHandler {

	private static final List<String> ALLOWED_TRANSACTIONS = new List<String>{'Credit Card'};

	public PaymentChangeEventTriggerHandler() {
		super(Bank_Statement__c.sObjectType);
	}

	protected override Map<Id, sObject> fetchRecords(Set<String> recordIds) {
		return new Map<Id, Bank_Statement__c>([SELECT Id, Transaction_type__c, BusinessCentralId__c FROM Bank_Statement__c WHERE Id IN :recordIds]);
	}

	protected override void loadMonitoredFields(Schema.sObjectType sObjectType) {
		// Empty override as there are no monitored fields and no fieldSet
	}	

	protected override Boolean isSkipEvent(EventBus.ChangeEventHeader eventHeader, sObject sObj) {
		return eventHeader.changetype != 'CREATE';
	}

	protected override Boolean isSkipRecord(sObject sObj) {
		return false;
	}

	protected override Boolean isRecordEligible(sObject sObj) {
		Bank_Statement__c bankstatement = (Bank_Statement__c)sObj;
		return ALLOWED_TRANSACTIONS.contains(bankstatement.Transaction_type__c);
	}

	protected override List<BusinessCentralSendRequest__c> createQueueRequests(Set<String> recordIds, List<String> changedFields) {
		List<BusinessCentralSendRequest__c> requests = new List<BusinessCentralSendRequest__c>();
		for (String recordId : recordIds) {
			Bank_Statement__c bankstatement = (Bank_Statement__c)getRecord(recordId);
			requests.add(new BusinessCentralSendRequest__c(PaymentId__c = recordId));
		}
		return requests;
	}

	protected override String getkey(BusinessCentralSendRequest__c requestToQueue) {
		return requestToQueue.PaymentId__c;
	}
}