force-app/main/default/objects/DeliveryPackageItem__c/DeliveryPackageItem__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Item</label>
    <nameField>
        <displayFormat>DPI-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageItem__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dummy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackageItem__c/fields/IsDraftStatus__c.field-meta.xml
<CustomField>
    <fullName>IsDraftStatus__c</fullName>
    <formula>ISPICKVAL(Status__c, &apos;Labelled&apos;)</formula>
    <label>Draft Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageItem__c/fields/IsFinalStatus__c.field-meta.xml
<CustomField>
    <fullName>IsFinalStatus__c</fullName>
    <formula>CONTAINS(&apos;Delivered, Returned To Sender, Cancelled&apos;, TEXT(Status__c))</formula>
    <label>Final Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageItem__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/DeliveryPackageTrackingEvent__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking Event</label>
    <nameField>
        <label>Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/RoyalMailSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Royal Mail Setting</label>
</CustomObject>

force-app/main/default/objects/RoyalMailSetting__c/fields/StatusCancelled__c.field-meta.xml
<CustomField>
    <fullName>StatusCancelled__c</fullName>
    <label>Status: Cancelled</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/fields/StatusDelivered__c.field-meta.xml
<CustomField>
    <fullName>StatusDelivered__c</fullName>
    <label>Status: Delivered</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/fields/StatusReturnedToSender__c.field-meta.xml
<CustomField>
    <fullName>StatusReturnedToSender__c</fullName>
    <label>Status: Returned to Sender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoyalMailTrackingEvent.cls
public without sharing class RoyalMailTrackingEvent {

	private RoyalMailSetting__c setting = RoyalMailSetting__c.getOrgDefaults();
	private String deliveredStatus = setting.StatusDelivered__c;
	private String finalStatus = deliveredStatus + ',' + setting.StatusReturnedToSender__c + ',' + setting.StatusCancelled__c;

	public void process(List<DeliveryPackageTrackingEvent__c> newList) {
		Map<String, List<TrackingEventWrapper>> trackingEventMap = groupEventsByTrackingId(newList);
		Map<String, DeliveryPackageItem__c> itemsToUpdate = new Map<String, DeliveryPackageItem__c>();
		for (String trackingId : trackingEventMap.keySet()) {
			List<TrackingEventWrapper> wrapperEvents = trackingEventMap.get(trackingId);
			wrapperEvents.sort();
			DeliveryPackageTrackingEvent__c event = wrapperEvents[0].event;
			if (wrapperEvents.size() > 1) {
				for (TrackingEventWrapper wrapper : wrapperEvents) {
					if (finalStatus.contains(wrapper.event.Code__c)) {
						event = wrapper.event;
						break;
					}
				}
			}
			itemsToUpdate.put(trackingId, new DeliveryPackageItem__c(TrackingId__c = trackingId, Event__c = event.Code__c, DeliveredDate__c = deliveredStatus.contains(event.Code__c) ? event.DateTime__c : null));
		}
		UPDATE filterInProgressPackages(itemsToUpdate);
	}

	private Map<String, List<TrackingEventWrapper>> groupEventsByTrackingId(List<DeliveryPackageTrackingEvent__c> newList) {
		Map<String, List<TrackingEventWrapper>> trackingEventMap = new Map<String, List<TrackingEventWrapper>>();
		for (DeliveryPackageTrackingEvent__c trackingEvent : newList) {
			if (!trackingEventMap.containsKey(trackingEvent.Name)) {
				trackingEventMap.put(trackingEvent.Name, new List<TrackingEventWrapper>{new TrackingEventWrapper(trackingEvent)});
				continue;
			}
			trackingEventMap.get(trackingEvent.Name).add(new TrackingEventWrapper(trackingEvent));
		}
		return trackingEventMap;
	}

	private List<DeliveryPackageItem__c> filterInProgressPackages(Map<String, DeliveryPackageItem__c> itemsByTrackingId) {
		List<DeliveryPackageItem__c> itemsInProgress = [SELECT TrackingId__c FROM DeliveryPackageItem__c WHERE TrackingId__c IN :itemsByTrackingId.keySet() AND IsFinalStatus__c = false AND IsDraftStatus__c = false];

		List<DeliveryPackageItem__c> filteredItems = new List<DeliveryPackageItem__c>();
		for (DeliveryPackageItem__c itemInProgress : itemsInProgress) {
			DeliveryPackageItem__c item = itemsByTrackingId.get(itemInProgress.TrackingId__c);
			item.Id = itemInProgress.Id;
			filteredItems.add(item);
		}
		return filteredItems;
	}

	private class TrackingEventWrapper implements Comparable {
		private DeliveryPackageTrackingEvent__c event;

		private TrackingEventWrapper(DeliveryPackageTrackingEvent__c event) {
			this.event = event;
		}

		public Integer compareTo(Object compareTo) {
			TrackingEventWrapper compareToEvent = (TrackingEventWrapper)compareTo;
			if (event.DateTime__c == compareToEvent.event.DateTime__c) return 0;
			if (event.DateTime__c > compareToEvent.event.DateTime__c) return -1;
			return 1;
		}
	}
}