force-app/main/default/objects/OrderItem/fields/AD_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>AD_KG_from_Weights__c</fullName>
    <label>AD KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AD_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.AD_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AD KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Coffee_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_from_Weights__c</fullName>
    <label>Coffee KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Coffee_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Coffee_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coffee KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/KWH_Produced_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>KWH_Produced_from_Weights__c</fullName>
    <label>KWH Produced from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/KWH_Produced_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>KWH_Produced_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.KWH_Produced__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KWH Produced Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LastWeightModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastWeightModifiedDate__c</fullName>
    <label>Last Weight Modified Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Overweight__c.field-meta.xml
<CustomField>
    <fullName>Overweight__c</fullName>
    <label>Overweight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG_from_Weights__c</fullName>
    <label>Recycled KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Recycle_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recycled KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved_from_Weights__c</fullName>
    <label>Tonnes CO2 Saved from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.CO2_Saved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tonnes CO2 Saved Per Unit</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_from_Weights__c</fullName>
    <label>Total KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Trees_Saved_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>Trees_Saved_from_Weights__c</fullName>
    <label>Trees Saved from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Trees_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Trees_Saved_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.Trees_Saved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trees Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG_from_Weights__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG_from_Weights__c</fullName>
    <label>WTE KG from Weights</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG_Per_Unit__c</fullName>
    <formula>PricebookEntry.Product2.WTE_KG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WTE KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/Weight__c.object-meta.xml
<CustomObject>
    <label>Weight</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weight__c/fields/AD_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AD_KG_Per_Unit__c</fullName>
    <label>AD KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Coffee_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Coffee_KG_Per_Unit__c</fullName>
    <label>Coffee KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/KWH_Produced_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>KWH_Produced_Per_Unit__c</fullName>
    <label>KWH Produced Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Weights</relationshipLabel>
    <relationshipName>Weights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Overweight__c.field-meta.xml
<CustomField>
    <fullName>Overweight__c</fullName>
    <formula>MAX(Total_KG_Per_Unit__c - IF(ISBLANK(AllowedWeight__c), Order_Product__r.Total_KG_Per_Unit__c, AllowedWeight__c), 0)</formula>
    <label>Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Recycled_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG_Per_Unit__c</fullName>
    <label>Recycled KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Tonnes_CO2_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved_Per_Unit__c</fullName>
    <label>Tonnes CO2 Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Total_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Total_KG_Per_Unit__c</fullName>
    <label>Total KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/Trees_Saved_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Trees_Saved_Per_Unit__c</fullName>
    <label>Trees Saved Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weight__c/fields/WTE_KG_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG_Per_Unit__c</fullName>
    <label>WTE KG Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeightToOrderProductRollup.cls
public without sharing class WeightToOrderProductRollup {

	public static void processWeights(List<Weight__c> weights) {
		Set<Id> orderItemIds = new Set<Id>();
		for (Weight__c weight : weights) {
			orderItemIds.add(weight.Order_Product__c);
		}
		rollupWeights(orderItemIds);
	}

	private static void rollupWeights(Set<Id> orderItemIds) {
		List<AggregateResult> aggregatedWeights = [SELECT Order_Product__c,
			SUM(Coffee_KG_Per_Unit__c) CoffeeKGPerUnit, SUM(AD_KG_Per_Unit__c) ADKGPerUnit, SUM(Recycled_KG_Per_Unit__c) RecycledKGPerUnit,
			SUM(KWH_Produced_Per_Unit__c) KWHProducedPerUnit, SUM(WTE_KG_Per_Unit__c) WTEKGPerUnit,
			SUM(Tonnes_CO2_Saved_Per_Unit__c) TonnesCO2SavedPerUnit, SUM(Trees_Saved_Per_Unit__c) TreesSavedPerUnit,
			SUM(Total_KG_Per_Unit__c) TotalKGPerUnit, SUM(Overweight__c) Overweight
			FROM Weight__c
			WHERE Order_Product__c IN :orderItemIds
			GROUP BY Order_Product__c];

		Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>();
		for (AggregateResult aggrWeight : aggregatedWeights) {
			OrderItem orderProduct = new OrderItem(Id = String.valueOf(aggrWeight.get('Order_Product__c')));
			orderProduct.Coffee_KG_from_Weights__c = (Decimal)aggrWeight.get('CoffeeKGPerUnit');
			orderProduct.AD_KG_from_Weights__c = (Decimal)aggrWeight.get('ADKGPerUnit');
			orderProduct.Recycled_KG_from_Weights__c = (Decimal)aggrWeight.get('RecycledKGPerUnit');
			orderProduct.KWH_Produced_from_Weights__c = (Decimal)aggrWeight.get('KWHProducedPerUnit');
			orderProduct.WTE_KG_from_Weights__c = (Decimal)aggrWeight.get('WTEKGPerUnit');
			orderProduct.Tonnes_CO2_Saved_from_Weights__c = (Decimal)aggrWeight.get('TonnesCO2SavedPerUnit');
			orderProduct.Trees_Saved_from_Weights__c = (Decimal)aggrWeight.get('TreesSavedPerUnit');
			orderProduct.Total_KG_from_Weights__c = (Decimal)aggrWeight.get('TotalKGPerUnit');
			orderProduct.Overweight__c = (Decimal)aggrWeight.get('Overweight');
			orderProduct.LastWeightModifiedDate__c = System.today();
			orderItemMap.put(orderProduct.Id, orderProduct);
		}

		for (Id orderItemId : orderItemIds) {
			if (!orderItemMap.containsKey(orderItemId)) {
				orderItemMap.put(orderItemId, resetOrderProduct(orderItemId));
			}
		}
		UPDATE orderItemMap.values();
	}

	private static OrderItem resetOrderProduct(Id orderItemId) {
		OrderItem orderItem = new OrderItem(Id = orderItemId,
			Coffee_KG_from_Weights__c = null, AD_KG_from_Weights__c = null, Recycled_KG_from_Weights__c = null,
			KWH_Produced_from_Weights__c = null,  WTE_KG_from_Weights__c = null,
			Tonnes_CO2_Saved_from_Weights__c = null, Trees_Saved_from_Weights__c = null,
			Total_KG_from_Weights__c = null);
		return orderItem;
	}
}