force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupEndDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupEndDate__c</fullName>
    <description>The date after which the discount/supplement is no longer applicable.</description>
    <inlineHelpText>The date after which the discount/supplement is no longer applicable.</inlineHelpText>
    <label>Discount End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/recordTypes/AccountDiscount.recordType-meta.xml
<RecordType>
    <fullName>AccountDiscount</fullName>
    <active>true</active>
    <description>Record type for a discount of type &quot;Account&quot;.</description>
    <label>AccountDiscount</label>
</RecordType>

force-app/main/default/classes/AccountDiscountTriggerHandler.cls
public class AccountDiscountTriggerHandler {
		
		/*
		 * aaaa-mm-dd / JIRA XXXX -> 1st version of duplicate discounts (same account and same Product)
		 * 2019-03-22 / JIRA 1487 -> redefinition of the duplicate validation (same account and same product cannot overlap in time)
		 */
		public static void handleBeforeInsert(List<Account_Discount__c> discs) {
			Set<Id> accountIDs = new Set<ID>();
			Set<Id> productIDs = new Set<ID>();
			for(Account_Discount__c accountDiscount : discs)
			{
				accountIDs.add(accountDiscount.Account__c);
				productIDs.add(accountDiscount.Product__c);
			}

			List<Account_Discount__c> currentADs = [SELECT Id, Product__c, Account__c, DiscountSupStartDate__c, DiscountSupEndDate__c FROM Account_Discount__c WHERE Account__c IN :accountIDs OR Product__c IN :productIDs];

			for (Account_Discount__c newAD : discs) {
				for (Account_Discount__c cad : currentADs) {
					if (newAD.Product__c == cad.Product__c && 
						newAD.Account__c == cad.Account__c && 
							(
									!( cad.DiscountSupEndDate__c != null && (newAD.DiscountSupEndDate__c < cad.DiscountSupStartDate__c || newAD.DiscountSupStartDate__c > cad.DiscountSupEndDate__c ) ) ||
                   cad.DiscountSupStartDate__c <= newAD.DiscountSupEndDate__c && cad.DiscountSupEndDate__c == null
								/*
								( cad.DiscountSupStartDate__c >= newAD.DiscountSupStartDate__c && cad.DiscountSupEndDate__c <= newAD.DiscountSupEndDate__c )|| 
								( cad.DiscountSupStartDate__c <= newAD.DiscountSupEndDate__c && cad.DiscountSupEndDate__c == null )*/
							)
						)
					{
						//newAD.addError('A discount for this product already exists.');
						newAD.addError('An account discount for this product and for  for this period already exist.');
					}
				}
			}
		}
}