force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Waste_transfer_note_due__c.field-meta.xml
<CustomField>
    <fullName>Waste_transfer_note_due__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waste transfer note due</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/Subscribed_Products__c.object-meta.xml
<CustomObject>
    <description>The combination of suppliers and its corresponding products that are being bought by the customers (locations).</description>
    <label>Subscribed Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Subscribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Products__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location to which the subscribed product is being applied.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Period__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Period__c</fullName>
    <label>Location Limit Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Half-year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <formula>Account__r.Partnership__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partnership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated to this subscription.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Quantity_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining__c</fullName>
    <label>Quantity Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
public class AccountTriggerHelper {
    public static void cancelSubscribedProducts(Account oldAcc) {
        List<Subscribed_Products__c> subsProdsToDelete = new List <Subscribed_Products__c>();
        for(Account acc : [Select id, (Select id, Partnership__c from Subscribed_Products__r where Partnership__c =: oldAcc.Partnership__r.Name) from Account where id =: oldAcc.Id]){
            subsProdsToDelete.addAll(acc.Subscribed_Products__r);
        }
        system.debug('subsProdsToDelete -->'+subsProdsToDelete);
        delete subsProdsToDelete;
    }
    
    /*
* 2019-05-08 / JIRA 1487 -> Automatic creation of Subscribed products for partner locations and supplier locations
*/
    public static void createSubscribedProducts(List<Account> accs, List<Account_Discount__c> accDisc) {
        List<Subscribed_Products__c> subsProdsToCreate = new List <Subscribed_Products__c>();
        for(Account acc : accs){
            for(Account_Discount__c accDis : accDisc){
                if(accDis.DiscountSupStartDate__c != null){
                    Integer month = accDis.DiscountSupStartDate__c.day();
                    Integer year = accDis.DiscountSupStartDate__c.month();
                }
                Subscribed_Products__c subProd = new Subscribed_Products__c();
                subProd.Account__c = acc.Id;
                subProd.Product__c = accDis.Product__c;
                subProd.Enqix_BID_Location_Limit_Period__c = 'Annual';
                if(accDis.DiscountSupStartDate__c > system.today()){
                    subProd.StartDate__c = Date.newInstance(System.today().Year()-1, accDis.DiscountSupStartDate__c.month(), accDis.DiscountSupStartDate__c.day());
                }else{
                    subProd.StartDate__c = Date.newInstance(System.today().Year(), accDis.DiscountSupStartDate__c.month(), accDis.DiscountSupStartDate__c.day());   
                }
                subProd.Quantity_Remaining__c = 0;
                
                subsProdsToCreate.add(subProd);
            }
        }
        system.debug('subsProdsToCreate -- > '+subsProdsToCreate);
        if(subsProdsToCreate.size() > 0){
            insert subsProdsToCreate;
        }
    }
    
    //Jira 1659 --> " Waste_transfer_note_due__c should also be ticked automatically when a location with no collection schedules places an order "
    public static void updateAcc(Set<Id> accIds) {
        
        system.debug('entered helper account');
        
        List <Account> acc = [Select Id, Waste_transfer_note_due__c, (Select Id From Collections__r) From Account Where Id IN :accIds];
        List <Compliance_Doc__c> wtns = [Select Id from Compliance_Doc__c Where Account__c IN :accIds AND EndDate__c >= TODAY LIMIT 1];
        
        system.debug('acc.size -->' + acc.size());
        system.debug('wtns.size -->' + wtns.size());
        
        List <Account> accToUpdate = new List <Account>(); 
        for (Account acco: acc) { 
            //JIRA 1657 - only check if orederd products and account do not have collection schedules
            if(acco.collections__r.size() == 0 && wtns.size() == 0){
                acco.Waste_transfer_note_due__c = True;
                accToUpdate.add(acco);
            }
        }
        if(accToUpdate.size() > 0){
            update accToUpdate;
        }
    }
}