force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Classification__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Classification__c</fullName>
    <label>Enqix Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BID</fullName>
            </value>
            <value>
                <fullName>Indirect Large</fullName>
            </value>
            <value>
                <fullName>Indirect Medium</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
                <isActive>false</isActive>
                <label>#N/A</label>
            </value>
            <value>
                <fullName>Broker Large</fullName>
                <isActive>false</isActive>
                <label>Broker Large</label>
            </value>
            <value>
                <fullName>Broker Medium</fullName>
                <isActive>false</isActive>
                <label>Broker Medium</label>
            </value>
            <value>
                <fullName>Cleaner Large</fullName>
                <isActive>false</isActive>
                <label>Cleaner Large</label>
            </value>
            <value>
                <fullName>Cleaner Medium</fullName>
                <isActive>false</isActive>
                <label>Cleaner Medium</label>
            </value>
            <value>
                <fullName>KA Multi</fullName>
                <isActive>false</isActive>
                <label>KA Multi</label>
            </value>
            <value>
                <fullName>KA Single</fullName>
                <isActive>false</isActive>
                <label>KA Single</label>
            </value>
            <value>
                <fullName>Location</fullName>
                <isActive>false</isActive>
                <label>Location</label>
            </value>
            <value>
                <fullName>Multi Central</fullName>
                <isActive>false</isActive>
                <label>Multi Central</label>
            </value>
            <value>
                <fullName>Multi Large</fullName>
                <isActive>false</isActive>
                <label>Multi Large</label>
            </value>
            <value>
                <fullName>Multi Medium</fullName>
                <isActive>false</isActive>
                <label>Multi Medium</label>
            </value>
            <value>
                <fullName>Multi Small</fullName>
                <isActive>false</isActive>
                <label>Multi Small</label>
            </value>
            <value>
                <fullName>Pre booked</fullName>
                <isActive>false</isActive>
                <label>Pre booked</label>
            </value>
            <value>
                <fullName>Single Medium</fullName>
                <isActive>false</isActive>
                <label>Single Medium</label>
            </value>
            <value>
                <fullName>Single Small</fullName>
                <isActive>false</isActive>
                <label>Single Small</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ReasonMarkedDead__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ReasonMarkedDead__c</fullName>
    <label>Enqix ReasonMarkedDead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed down</fullName>
                <label>Site Closed down</label>
            </value>
            <value>
                <fullName>Included in service charge</fullName>
                <label>Moved to a serviced office</label>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Poor Customer Support</fullName>
            </value>
            <value>
                <fullName>Delivery Issues</fullName>
            </value>
            <value>
                <fullName>Collection Reliability Issues</fullName>
            </value>
            <value>
                <fullName>Missing Features</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <label>Reseller Lost Work/Internalised</label>
            </value>
            <value>
                <fullName>FM Terminated</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/BID_allocation_product__c.field-meta.xml
<CustomField>
    <fullName>BID_allocation_product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BID allocation product?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupEndDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupEndDate__c</fullName>
    <description>The date after which the discount/supplement is no longer applicable.</description>
    <inlineHelpText>The date after which the discount/supplement is no longer applicable.</inlineHelpText>
    <label>Discount End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Gross_Price__c.field-meta.xml
<CustomField>
    <fullName>Gross_Price__c</fullName>
    <description>The price of product before any discounts.</description>
    <inlineHelpText>The price of product before any discounts.</inlineHelpText>
    <label>Gross Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/recordTypes/AccountDiscount.recordType-meta.xml
<RecordType>
    <fullName>AccountDiscount</fullName>
    <active>true</active>
    <description>Record type for a discount of type &quot;Account&quot;.</description>
    <label>AccountDiscount</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Enqix_Classification__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Classification__c</fullName>
    <label>Enqix Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small (&lt;£250)</fullName>
            </value>
            <value>
                <fullName>Medium (£250 - £5000)</fullName>
            </value>
            <value>
                <fullName>Large (&lt;£5000 - £10000)</fullName>
            </value>
            <value>
                <fullName>Key Account (£10,000+)</fullName>
            </value>
            <value>
                <fullName>Indirect Medium (&lt;£10000)</fullName>
            </value>
            <value>
                <fullName>Indirect Large (&gt;£10000)</fullName>
            </value>
            <value>
                <fullName>BID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OK_or_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>OK_or_Cancelled__c</fullName>
    <label>OK or Cancelled?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Recycle_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycle_KG__c</fullName>
    <inlineHelpText>KG&apos;s of the sack&apos;s contents which are recycled, with assumption sack is at full capacity.</inlineHelpText>
    <label>Recycle KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Report_Groupings__c.field-meta.xml
<CustomField>
    <fullName>Report_Groupings__c</fullName>
    <label>Report Groupings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEEE and Toner</fullName>
            </value>
            <value>
                <fullName>Cardboard</fullName>
            </value>
            <value>
                <fullName>Junk Removal</fullName>
            </value>
            <value>
                <fullName>Food Recycling</fullName>
            </value>
            <value>
                <fullName>Paper Shredding</fullName>
            </value>
            <value>
                <fullName>General Waste</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Mixed Recycling</fullName>
            </value>
            <value>
                <fullName>Stationery and Textiles</fullName>
            </value>
            <value>
                <fullName>Coffee Grounds</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
                <isActive>false</isActive>
                <label>Paper</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled Waste and Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Other Waste/Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Secure Shredding</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance/Junk Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Business Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting and Data</fullName>
    </customValue>
    <customValue>
        <fullName>Product Partnership</fullName>
    </customValue>
    <masterLabel>Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTrigger_Test.cls
@isTest
class AccountTrigger_Test{
    
    @isTest
    public static void UnitTestMethod1(){
        
        test.startTest();
        List<Product2> lstProds = new List<Product2>();

        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i + 1), 5, (i+1)));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();

        for (Integer i=0; i<5; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 102,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Id RecordTypeIdPartner = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
        Id RecordTypeIdLocation = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();

        Id RecordTypeIdAccountDisc = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
        
        Account acc1 = new Account();
        acc1.Name = 'Parent Account';
        acc1.RecordTypeId = RecordTypeIdAccount;
        insert acc1;
  
        Account partnerAcc = new Account();
        partnerAcc.Name = 'Partner Account';
        partnerAcc.RecordTypeId = RecordTypeIdPartner;
        partnerAcc.Price_Book__c = pricebookId;
        partnerAcc.Enqix_Classification__c = 'BID';
        insert partnerAcc;
        
        Test.stopTest();
        
        List <Account> accList = new List <Account>();
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = RecordTypeIdLocation;
        acc.ParentId = acc1.Id;
        acc.Enqix_Location_ID__c  = 'ABC123';
        acc.Price_Book__c = Test.getStandardPricebookId();
        acc.Enqix_Dead_Live__c = 'Live';
        acc.Partnership__c = partnerAcc.Id;
        acc.Enqix_Classification__c = 'BID';        
        accList.add(acc);
        
        Account acc2 = new Account();
        acc2.Name = 'Test Account2';
        acc2.RecordTypeId = RecordTypeIdLocation;
        acc2.ParentId = acc1.Id;
        acc2.Enqix_Location_ID__c  = 'ABC123';
        acc2.Price_Book__c = Test.getStandardPricebookId();
        acc2.Enqix_Dead_Live__c = 'Live';
        acc2.Partnership__c = partnerAcc.Id;
        acc2.Enqix_Classification__c = 'BID';        
        accList.add(acc2);
        
        insert accList;
        
        acc.Partnership__c = null;
        
        update acc;
        
        List<Account_Discount__c> accDisc = new List <Account_Discount__c>();
        
        Account_Discount__c disc = new Account_Discount__c();
        disc.Account__c = partnerAcc.id;
        disc.Product__c = lstProds.get(0).Id;
        disc.DiscountSupStartDate__c = system.today();
        disc.BID_allocation_product__c = True;
        disc.RecordTypeId = RecordTypeIdAccountDisc;
        disc.DiscountSupEndDate__c = system.today()+100;
        disc.Gross_Price__c = 50;        
        accDisc.add(disc);
        
        insert accDisc;
        
        AccountTriggerHelper.createSubscribedProducts(accList, accDisc);
        
        Account acc5 =[SELECT Id, RecordTypeId, Price_Book__c FROM  Account LIMIT 1];
         
        opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.CloseDate = date.today().AddDays(-60);
        opp.StageName = '5 Collections Started';
        opp.AccountId = acc1.Id;
        opp.Services__c = 'Secure Shredding';
        insert opp;
        
        Order ord = new Order();
        ord.AccountId = acc.Id;
        ord.Status = 'Invoiced';
        ord.OK_or_Cancelled__c = 'Cancelled';
        ord.EffectiveDate = system.today();
        ord.Delivery_Date__c = Date.newInstance(2018, 06, 29);
        insert ord;
        
        acc.Enqix_Dead_Live__c ='Dead';
        acc.Enqix_ReasonMarkedDead__c = 'Giveaway Never Ordered';
        update acc;
    }
    
    private static Product2 createTestProduct(String prodName, Integer recycleKG, Integer idx) {
        String rpGroup = (Math.mod(idx, 2) == 0) ? 'Cardboard' : 'Food Recycling';
        
        Product2 prod = TestDataHelper.createProduct(prodName, '123', 'Collection');
        prod.Report_Groupings__c = rpGroup;
		prod.Recycle_KG__c = recycleKG;
       
        return prod;
    }
}