force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralContactId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralContactId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Classification__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Classification__c</fullName>
    <label>Enqix Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BID</fullName>
            </value>
            <value>
                <fullName>Indirect Large</fullName>
            </value>
            <value>
                <fullName>Indirect Medium</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
                <isActive>false</isActive>
                <label>#N/A</label>
            </value>
            <value>
                <fullName>Broker Large</fullName>
                <isActive>false</isActive>
                <label>Broker Large</label>
            </value>
            <value>
                <fullName>Broker Medium</fullName>
                <isActive>false</isActive>
                <label>Broker Medium</label>
            </value>
            <value>
                <fullName>Cleaner Large</fullName>
                <isActive>false</isActive>
                <label>Cleaner Large</label>
            </value>
            <value>
                <fullName>Cleaner Medium</fullName>
                <isActive>false</isActive>
                <label>Cleaner Medium</label>
            </value>
            <value>
                <fullName>KA Multi</fullName>
                <isActive>false</isActive>
                <label>KA Multi</label>
            </value>
            <value>
                <fullName>KA Single</fullName>
                <isActive>false</isActive>
                <label>KA Single</label>
            </value>
            <value>
                <fullName>Location</fullName>
                <isActive>false</isActive>
                <label>Location</label>
            </value>
            <value>
                <fullName>Multi Central</fullName>
                <isActive>false</isActive>
                <label>Multi Central</label>
            </value>
            <value>
                <fullName>Multi Large</fullName>
                <isActive>false</isActive>
                <label>Multi Large</label>
            </value>
            <value>
                <fullName>Multi Medium</fullName>
                <isActive>false</isActive>
                <label>Multi Medium</label>
            </value>
            <value>
                <fullName>Multi Small</fullName>
                <isActive>false</isActive>
                <label>Multi Small</label>
            </value>
            <value>
                <fullName>Pre booked</fullName>
                <isActive>false</isActive>
                <label>Pre booked</label>
            </value>
            <value>
                <fullName>Single Medium</fullName>
                <isActive>false</isActive>
                <label>Single Medium</label>
            </value>
            <value>
                <fullName>Single Small</fullName>
                <isActive>false</isActive>
                <label>Single Small</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupEndDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupEndDate__c</fullName>
    <description>The date after which the discount/supplement is no longer applicable.</description>
    <inlineHelpText>The date after which the discount/supplement is no longer applicable.</inlineHelpText>
    <label>Discount End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/recordTypes/PartnerDiscount.recordType-meta.xml
<RecordType>
    <fullName>PartnerDiscount</fullName>
    <active>true</active>
    <description>Record type for a discount of type &quot;Partner&quot;.</description>
    <label>PartnerDiscount</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Account_Discount__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <formula>CASESAFEID(Order.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product_Category_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_Key__c</fullName>
    <externalId>true</externalId>
    <label>Product Category Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/XpandIT_CreditNote_Controller_Test.cls
@isTest
public class XpandIT_CreditNote_Controller_Test {

	@testSetup
	static void makeData() {
		TestDataHelper.insertVat();

		Product_Category__c pc = new Product_Category__c();
		pc.Name = 'test';
		pc.Enqix_Id__c = 1;
		pc.Product_Category_Key__c = 'test';
		insert pc;

		Product2 prod = TestDataHelper.createProduct('Credit', '333', 'Delivery', pc.Id, null, null, '1');
		prod.Family = 'Hardware';
		INSERT prod;
		
		INSERT new CreditSetting__c(ProductId__c = prod.Id);
		
		// 1. Insert a price book entry for the standard price book.
		// Standard price book entry
		PricebookEntry standardPrice = TestDataHelper.insertStandardPricebookEntry(prod.Id, 1000);

		Test.setMock(HttpCalloutMock.class, new DoogalTest.RestMock('TW1 2RS	51.452903	-0.317551	Postcode terminated prior to Gridlink initiative - last known ONS postcode grid reference	Twickenham	Richmond upon Thames	Twickenham Riverside	Richmond upon Thames 009C	Greater London	London	England		10.66619777679443	Urban major conurbation	Slough and Heathrow	E01003894'));
		Account parentAccount = TestDataHelper.createAccount();
		parentAccount.Enqix_ID__c = '1234566777';
		parentAccount.BusinessCentralId__c = 'Parent-BC-Id-01';
		parentAccount.BusinessCentralContactId__c = 'Parent-FC-BC-Id-01';
		insert parentAccount;

		Account partnerAccount = TestDataHelper.createPartner();
		partnerAccount.Enqix_ID__c = '1234212';
		partnerAccount.Enqix_Classification__c = 'BID';
		partnerAccount.InvoiceFrequency__c = 'Monthly';
		partnerAccount.BusinessCentralId__c = 'Partner-BC-Id-01';
		partnerAccount.BusinessCentralContactId__c = 'Partner-FC-BC-Id-01';
		insert partnerAccount;

		Account childAccount = TestDataHelper.createLocation(parentAccount.Id, null);
		childAccount.BillingPostalCode = 'NW6 1NR';
		childAccount.Enqix_Location_ID__c  = 'ABC123';
		childAccount.Enqix_Classification__c = 'BID';
		childAccount.Enqix_ID__c = '1234';
		childAccount.BusinessCentralId__c = 'Location-BC-Id-01';
		insert childAccount;

		Account childAccountPartner = TestDataHelper.createLocation(parentAccount.Id, partnerAccount.Id);
		childAccountPartner.BillingPostalCode = 'NW6 2NR';
		childAccountPartner.Enqix_Location_ID__c  = 'ABC33123';
		childAccountPartner.Enqix_Classification__c = 'BID';
		childAccountPartner.Enqix_ID__c = '12323234';
		childAccountPartner.BusinessCentralId__c = 'Location-BC-Id-02';
		insert childAccountPartner;

		List <Account> childAccountList = [SELECT Id, Name, ParentId, InvoiceFrequency__c, Partnership__c, Enqix_ID__c, Price_Book__c FROM  Account where RecordType.Name = 'Location' LIMIT 1];

		TestDataHelper.insertSupplier('First Mile Ltd');
		test.startTest();
		system.debug('Number of queries: '  +Limits.getQueries());

		Id partnerD = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('PartnerDiscount').getRecordTypeId();

		Account_Discount__c desconto = new Account_Discount__c(
			Account__c = partnerAccount.Id,
			DiscountSupStartDate__c = system.today(),
			DiscountSupEndDate__c = system.today() + 2,
			Product__c = prod.Id,
			RecordTypeId = partnerD,
			Gross_Price__c = 200,
			BID_Price__c = 10,
			Product_Discount__c = 10
		);
		insert desconto;

		Order order = TestDataHelper.createOrder(childAccount.Id, System.today());
		order.Status = 'Draft';
		order.Pricebook2Id = childAccount.Price_Book__c;
		order.Type = 'Contractor';
		insert order;

		Order order2 = TestDataHelper.createOrder(childAccountPartner.Id, System.today());
		order2.Status = 'Draft';
		order2.Pricebook2Id = childAccountPartner.Price_Book__c;
		order2.Type = 'Contractor';
		insert order2;

		List<OrderItem> ops = new List<OrderItem>();

		OrderItem op3 = TestDataHelper.createOrderItem(order.Id, prod.Id, standardPrice.Id);
		op3.ListPrice__c = 1;
		op3.Description__c = '123';
		op3.Discount_to_Apply__c = 'Account';
		ops.add(op3);

		OrderItem op4 = TestDataHelper.createOrderItem(order2.Id, prod.Id, standardPrice.Id);
		op4.ListPrice__c = 1;
		op4.Description__c = '1234';
		op4.Discount_to_Apply__c = 'Partner';
		ops.add(op4);
		insert ops;

		test.stopTest();
	}

	@isTest
	static void test_method_one() {
		test.startTest();
		List<Invoice_Header__c> invoices = [SELECT Id, Account__c,Account__r.RecordTypeId, Location__c, InvoiceFrequency__c, Location__r.Price_Book__c, Account__r.Price_Book__c FROM Invoice_Header__c];
		System.debug('invoicesLength' + invoices.size());
		System.debug('invoicesasd' + invoices);
		Invoice_Header__c invoice = invoices.get(0);

		Id recordTypePartner = [SELECT RecordTypeId FROM Account WHERE Name = 'Partner'].RecordTypeId;
		System.debug('Account__r.RecordTypeId' + recordTypePartner);
		Invoice_Header__c invoicePartner = [SELECT Id, Account__c, Location__c, InvoiceFrequency__c FROM Invoice_Header__c WHERE Account__r.RecordTypeId = :recordTypePartner LIMIT 1];
		List<Invoice_Line__c> invoicesLines = [SELECT Id, Location_Id__c, Product__c FROM Invoice_Line__c WHERE Invoice_HeaderId__c = :invoice.Id];
		system.debug('invoicesLines -->'+invoicesLines);
		//system.assertEquals(3,invoices.size());

		// BC ID Update
		List<Invoice_Header__c> invoicesToUpdate = new List<Invoice_Header__c>();
		invoicesToUpdate.add(new Invoice_Header__c(Id = invoice.Id, BusinessCentralId__c = 'Invoice-BC-Id-01'));
		invoicesToUpdate.add(new Invoice_Header__c(Id = invoicePartner.Id, BusinessCentralId__c = 'Invoice-BC-Id-02'));
		UPDATE invoicesToUpdate;

		String test1 = XpandIT_CreditNote_Controller.getInvoiceResumeData(invoice.Id);
		//system.assertEquals(invoice.Account__c+'/Per Order', invoice.Account__c+'/'+invoice.InvoiceFrequency__c);

		List<Account> accounts = XpandIT_CreditNote_Controller.getAccountsLocations(invoice.Id, invoice.Account__c);
		//system.assertEquals(1, accounts.size());

		List<Order> orders = XpandIT_CreditNote_Controller.getLocationsOrders(invoice.Id, invoice.Location__c);
		//system.assertEquals(1, orders.size());

		List<OrderItem> orderProducts2 = XpandIT_CreditNote_Controller.generateCreditOrder(invoice.Id, orders.get(0).Id);
		//system.assertEquals(1, orderProducts2.size());

		List<OrderItem> orderProducts2_2 = XpandIT_CreditNote_Controller.generateCreditOrder(invoice.Id);

		List<OrderItem> orderProductsPartner = XpandIT_CreditNote_Controller.generateCreditOrder(invoicePartner.Id);
		//system.assertEquals(1, orderProducts2_2.size());
		Boolean worked = XpandIT_CreditNote_Controller.createCreditOrder(orderProducts2_2, 'notes', invoice.Id, invoice.Location__c, false, true, 'Service');
		//system.assertEquals(true, worked);
		Boolean workedPartner = XpandIT_CreditNote_Controller.createCreditOrder(orderProducts2, 'notes', invoicePartner.Id, invoicePartner.Account__c, true, true, 'Service');
		//system.assertEquals(true, worked);

		Boolean simpleNoteWorked = XpandIT_CreditNote_Controller.createSimpleCreditOrder(10, 'notes', invoice.Id, invoice.Location__c, true, 'Service');
		//system.assertEquals(true, simpleNoteWorked);
		test.stopTest();
	}
}