force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Start_Date__c</fullName>
    <label>Enqix Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transferred_To_Enqix__c.field-meta.xml
<CustomField>
    <fullName>Transferred_To_Enqix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transferred To Enqix?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Overall Account Contact</fullName>
            </value>
            <value>
                <fullName>Finance Contact</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Environmental Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SetLiveControllerTest.cls
@isTest
public with sharing class SetLiveControllerTest {
	
    @isTest
    public static void testDeadLive(){
        Id pricebookId = Test.getStandardPricebookId();
          
		Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        acc.Name = 'parentacc';
        acc.BillingStreet = 'test street';
        acc.BillingCity = 'test city'; 
        acc.Transferred_To_Enqix__c = false;
        acc.Price_Book__c = pricebookId;
        acc.Enqix_Start_Date__c = null;
        insert acc;
        
		Account acc2 = TestDataHelper.createLocation(acc.Id, null);
        acc2.Name = 'child1';
        acc2.BillingStreet = 'test streets';
        acc2.BillingCity = 'test cityy';  
        acc2.Transferred_To_Enqix__c = false;
        insert acc2;
        
		List <Contact> contactList = new List <Contact>();
        Contact c = new Contact();
        c.LastName = 'asdsa';
        c.AccountId = acc.Id;
        c.Contact_Role__c = 'Finance Contact';
        c.Email = 'email2@email.com';
        contactList.add(c);

		Contact c2 = new Contact();
        c2.LastName = 'asdsa';
        c2.AccountId = acc2.Id;
        c2.Contact_Role__c = 'Finance Contact';
        c2.Email = 'email1@email.com';
        contactList.add(c2);
       
        Contact c3 = new Contact();
        c3.LastName = 'test';
        c3.AccountId = acc2.Id;
        c3.Contact_Role__c = 'Finance Contact';
        c3.Email = 'test@firstmile.co.uk';
        contactList.add(c3);
        insert contactList;
        
        AccountContactRelation acr = [select Id, Roles from AccountContactRelation where AccountId = :acc.Id and ContactId = :c.Id limit 1];
        acr.Roles = 'Finance Contact; Service Contact';
        update acr;

		AccountContactRelation acr2 = [select Id, Roles from AccountContactRelation where AccountId = :acc2.Id and ContactId = :c2.Id limit 1];
        acr2.Roles = 'Service Contact';
        update acr2;
        
        Account_Discount__c ad = new Account_Discount__c(
            Account__c = acc.Id,
            DiscountSupStartDate__c = system.today()
        );
		insert ad;
        
        Order Ord1 = new Order(
            AccountId = acc2.id,
            EffectiveDate = System.today(),
            Delivery_Date__c = System.today(),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = PricebookId
        );
        insert ord1;
        
		acc2.Enqix_Start_Date__c = null;
		update acc2;        
		
        //Test account with orders related
        SetLiveController.setLiveCtrl(acc2.Id);
        
        delete Ord1;
        acc2.Enqix_Dead_Live__c = 'Live';
        update acc2;
        
        //Test account with no orders related
        SetLiveController.setLiveCtrl(acc2.Id);
        
        test.startTest();
        acc2.Transferred_To_Enqix__c = true;
        update acc2;
        
        //Test account where the Parent has Transferred_To_Enqix__c = False
        SetLiveController.setLiveCtrl(acc2.Id);
        test.stopTest();
    }

}