force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/BID_Price__c.field-meta.xml
<CustomField>
    <fullName>BID_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The price paid by the partnership in this discount.</description>
    <inlineHelpText>The price paid by the partnership in this discount.</inlineHelpText>
    <label>BID Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupEndDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupEndDate__c</fullName>
    <description>The date after which the discount/supplement is no longer applicable.</description>
    <inlineHelpText>The date after which the discount/supplement is no longer applicable.</inlineHelpText>
    <label>Discount End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product_Discount__c.field-meta.xml
<CustomField>
    <fullName>Product_Discount__c</fullName>
    <label>Product Discount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountUtil.cls
public without sharing class AccountUtil {

	public static final Id RECORDTYPEID_PARENT	= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
	public static final Id RECORDTYPEID_PARTNER = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
	public static final Id RECORDTYPEID_LOCATION = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
	public static final Id RECORDTYPEID_PROSPECT = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();

	public static final String PARTNER_TYPE_BID = 'BID';

	public static final String LIVE = 'Live';

	public static Boolean isLive(Account account) {
		return account.Enqix_Dead_Live__c == LIVE;
	}
	
	public static Boolean isPartner(Account account) {
		return account.RecordTypeId == RECORDTYPEID_PARTNER;
	}

	public static Boolean isFrequencyOverridden(Account location) {
		return String.isNotBlank(location.InvoiceFrequency__c);
	}

	public static Map<String, Account_Discount__c> getDiscounts(Set<Id> accountIds, Set<Id> productIds) {
		accountIds.remove(null);
		productIds.remove(null);
		List<Account_Discount__c> discounts = [SELECT Account__c, Product__c, Product_Discount__c, Bid_Price__c FROM Account_Discount__c 
			WHERE Account__c IN :accountIds AND Product__c IN :productIds 
			AND (DiscountSupStartDate__c <= TODAY OR DiscountSupStartDate__c = null) 
			AND (DiscountSupEndDate__c >= TODAY OR DiscountSupEndDate__c = null)];

		Map<String, Account_Discount__c> discountMap = new Map<String, Account_Discount__c>();
		for (Account_Discount__c discount : discounts) {
			discountMap.put(discount.Account__c + '-' + discount.Product__c, discount);
		}
		return discountMap;
	}
}