force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product_Discount__c.field-meta.xml
<CustomField>
    <fullName>Product_Discount__c</fullName>
    <label>Product Discount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Enqix_PK__c.field-meta.xml
<CustomField>
    <fullName>Enqix_PK__c</fullName>
    <label>Enqix PK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Defines if the product is either only for collection or delivery.</description>
    <inlineHelpText>Defines if the product is either only for collection or delivery.</inlineHelpText>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product_Category_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_Key__c</fullName>
    <externalId>true</externalId>
    <label>Product Category Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Note__c.field-meta.xml
<CustomField>
    <fullName>Collection_Note__c</fullName>
    <label>Collection Note</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Streams__c.field-meta.xml
<CustomField>
    <fullName>Streams__c</fullName>
    <label>Streams</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed Recycling</fullName>
            </value>
            <value>
                <fullName>General Waste</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Cardboard</fullName>
            </value>
            <value>
                <fullName>Coffee Grounds</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Food Recycling</fullName>
                <isActive>false</isActive>
                <label>Food Recycling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>&quot;18:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Enqix_Pk__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Pk__c</fullName>
    <externalId>true</externalId>
    <label>Enqix PK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Enqix_UID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_UID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix  UID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Suppliers__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Test_CollectionScheduleTrigger.cls
@isTest
public class Test_CollectionScheduleTrigger {
    /*
    @testSetup
    private static void setupTestData() {
        
        List <RecordType> accRecordTypes = [SELECT Id,
                                                Name
                                                FROM RecordType
                                                WHERE SObjectType = 'Account'
                                                AND (Name = 'Location' OR Name = 'Partner')
                                           ];
        Id locationRecordTypeId;
        Id partnerRecordTypeId;
        for(RecordType rec : accRecordTypes) {
            if(rec.Name == 'Location') {
                locationRecordTypeId = rec.Id;
            } else if(rec.Name == 'Partner') {
                partnerRecordTypeId = rec.Id;
            }
        }
        
        List<Account> accToInsert = new List<Account>();
        
        Account locationAcc = new Account();
        locationAcc.Name = 'Location Acc';
        locationAcc.RecordTypeId = locationRecordTypeId;
        accToInsert.add(locationAcc);
        
        Account partnerAcc = new Account();
        partnerAcc.Name = 'Partner Acc';
        partnerAcc.RecordTypeId = partnerRecordTypeId;
        accToInsert.add(partnerAcc);
        
        insert accToInsert;
        locationAcc.Partnership__c = partnerAcc.Id;
        update locationAcc;
        
        accToInsert = [SELECT Id FROM Account LIMIT 100];
        System.assertEquals(2, accToInsert.size(), 'Account data not created properly!');
        
        Product_Category__c pc = new Product_Category__c();
        pc.Name = 'test';
        pc.Enqix_Id__c = 1;
        pc.Product_Category_Key__c = 'test';
        insert pc;
        
        product2 productRec = new Product2();
        productRec.Name =  'Product 1';
        productrec.ProductCode = '123';
        productRec.Product_Category__c = pc.id;
        productRec.Product_Type__c = 'Collection';
        productRec.isActive = true;
        insert productRec;
        
        priceBook2 priceBookRec = new priceBook2();
        priceBookRec.Name = 'PriceBook 1';
        priceBookRec.IsActive = true;
        insert priceBookRec;
        
        PricebookEntry priceBookEntryRec = new  PricebookEntry();
        priceBookEntryRec.Product2Id = productRec.Id;
        priceBookEntryRec.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntryRec.UnitPrice = 100;
        priceBookEntryRec.UseStandardPrice = false;
        insert priceBookEntryRec;
        
        PricebookEntry priceBookEntryRec2 = new  PricebookEntry();
        priceBookEntryRec2.Product2Id = productRec.Id;
        priceBookEntryRec2.Pricebook2Id = priceBookRec.Id;
        priceBookEntryRec2.UnitPrice = 500;
        priceBookEntryRec2.UseStandardPrice = false;
        insert priceBookEntryRec2;
        
        Account_Discount__c disc1 = new Account_Discount__c();
        disc1.Account__c = locationAcc.id;
        disc1.Product__c = productRec.Id;
        disc1.Product_Discount__c = 3;
        disc1.DiscountSupStartDate__c = system.today();
        
        Account_Discount__c disc2 = new Account_Discount__c();
        disc2.Account__c = locationAcc.id;
        disc2.Product__c = productRec.Id;
        disc2.Product_Discount__c = 5;
        disc2.DiscountSupStartDate__c = system.today();
        
        Account_Discount__c disc3 = new Account_Discount__c();
        disc3.Account__c = locationAcc.id;
        disc3.Product__c = productRec.Id;
        disc3.Product_Discount__c = 50;
        disc3.DiscountSupStartDate__c = system.today();
        
        Test.startTest();
        insert new List<Account_Discount__c>{disc1, disc2, disc3};
        Test.stopTest();
    }
    */
    
    /*
    private static testMethod void unitTest1() {
        
        
        List <RecordType> accRecordTypes = [SELECT Id,
                                                Name
                                                FROM RecordType
                                                WHERE SObjectType = 'Account'
                                                AND (Name = 'Location' OR Name = 'Partner')
                                           ];
        Id locationRecordTypeId;
        Id partnerRecordTypeId;
        for(RecordType rec : accRecordTypes) {
            if(rec.Name == 'Location') {
                locationRecordTypeId = rec.Id;
            } else if(rec.Name == 'Partner') {
                partnerRecordTypeId = rec.Id;
            }
        }
        
        Account location = [SELECT Id FROM Account WHERE RecordTypeId =: locationRecordTypeId];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'Product 1'];
        priceBook2 pb = [SELECT Id FROM priceBook2 WHERE Name = 'PriceBook 1'];
        

        Suppliers__c s = new Suppliers__c();
        s.Name = 'test';
        s.Enqix_ID__c = 23;
        s.Phone_Number__c = '123423';
        insert s;
        
        Supplier_Product__c sp = new Supplier_Product__c();
        sp.Name = 'test';
        sp.Product__c = prod.id;
        sp.Enqix_UID__c = 'test';
        sp.Enqix_Pk__c = 1;
        sp.Supplier__c = s.id;
        insert sp;
                
        Schedule__c sc = new Schedule__c();
        sc.Collection_Note__c = 'Collection Note';
        sc.Days__c = 'Monday';
        sc.Location__c = location.Id;
        //sc.Price_Book__c = pb.Id;
        sc.Product__c = prod.Id;
        sc.Supplier_Product__c = sp.id;
        sc.Streams__c = 'Cardboard';
        sc.Time__c = '07:45';
        sc.Collection_Quantity__c = 1;
        sc.Supplier__c = s.id;
        
        
            insert sc;
        
        sc = [SELECT Id, 
                List_Price__c, 
                Sale_Price__c 
                FROM Schedule__c 
                WHERE Id =: sc.Id
             ];
        //System.assertEquals(sc.List_Price__c - 50, sc.Sale_Price__c, 'Sale Price calculation is not working properly!');
    }
    */
    
    public TestMethod Static void Test1()
    {
        Test.startTest(); 
        List <RecordType> accRecordTypes = [SELECT Id,
                                                Name
                                                FROM RecordType
                                                WHERE SObjectType = 'Account'
                                                AND (Name = 'Location' OR Name = 'Partner')
                                           ];
        Id locationRecordTypeId;
        Id partnerRecordTypeId;
        for(RecordType rec : accRecordTypes) {
            if(rec.Name == 'Location') {
                locationRecordTypeId = rec.Id;
            } else if(rec.Name == 'Partner') {
                partnerRecordTypeId = rec.Id;
            }
        }
        
        Account parentAcc = TestDataHelper.insertAccount();
        Account partnerAcc = TestDataHelper.insertPartner();
        Account locationAcc = TestDataHelper.insertLocation(parentAcc.Id, partnerAcc.Id);
        
        System.assertEquals(3, [SELECT Id FROM Account].size(), 'Account data not created properly!');
        
        Product_Category__c pc = new Product_Category__c();
        pc.Name = 'test';
        pc.Enqix_Id__c = 1;
        pc.Product_Category_Key__c = 'test';
        insert pc;
        
        product2 productRec = TestDataHelper.insertProduct('Product 1 (P)', '123', 'Collection', pc.Id);
        
        priceBook2 priceBookRec = new priceBook2();
        priceBookRec.Name = 'PriceBook 1';
        priceBookRec.IsActive = true;
        priceBookRec.Effective_Date__c = System.now();
        insert priceBookRec;
        
        PricebookEntry priceBookEntryRec = new  PricebookEntry();
        priceBookEntryRec.Product2Id = productRec.Id;
        priceBookEntryRec.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntryRec.UnitPrice = 100;
        priceBookEntryRec.UseStandardPrice = false;
        insert priceBookEntryRec;
        
        PricebookEntry priceBookEntryRec2 = new  PricebookEntry();
        priceBookEntryRec2.Product2Id = productRec.Id;
        priceBookEntryRec2.Pricebook2Id = priceBookRec.Id;
        priceBookEntryRec2.UnitPrice = 500;
        priceBookEntryRec2.UseStandardPrice = false;
        insert priceBookEntryRec2;
        
        
        Account location = [SELECT Id FROM Account WHERE RecordTypeId =: locationRecordTypeId];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'Product 1 (P)'];
        priceBook2 pb = [SELECT Id FROM priceBook2 WHERE Name = 'PriceBook 1'];
        
        
        Suppliers__c s = new Suppliers__c();
        s.Name = 'test';
        s.Enqix_ID__c = 23;
        s.Phone_Number__c = '123423';
        insert s;
        
        Supplier_Product__c sp = new Supplier_Product__c();
        sp.Name = 'test';
        sp.Product__c = prod.id;
        sp.Enqix_UID__c = 'test';
        sp.Enqix_Pk__c = 1;
        sp.Supplier__c = s.id;
        insert sp;
                
        Schedule__c sc = new Schedule__c();
        sc.Collection_Note__c = 'Collection Note';
        sc.Days__c = 'Monday';
        sc.Location__c = location.Id;
        //sc.Price_Book__c = pb.Id;
        sc.Product__c = prod.Id;
        sc.Supplier_Product__c = sp.id;
        sc.Streams__c = 'Cardboard';
        sc.Time__c = '07:45';
        sc.Collection_Quantity__c = 1;
        sc.Supplier__c = s.id;
        
        insert sc;
        
        Update sc;
        system.debug('sc::'+sc);
        Test.stopTest();
    }
}