force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsBinCollectionAdvanceInvoiced__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollectionAdvanceInvoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection Advance Invoiced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Discount type according to the type of record of the account related to the discount.</description>
    <formula>Account__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Account_Discount__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Fortnightly__c.field-meta.xml
<CustomField>
    <fullName>Fortnightly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fortnightly?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <formula>AND(ISPICKVAL(Supplier_Product__r.Product__r.Product_Type__c, &apos;Collection&apos;), OR(ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bin&apos;), ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bale&apos;)))</formula>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Reactivation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reactivation_Start_Date__c</fullName>
    <label>Reactivation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Suspension_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Suspension_Start_Date__c</fullName>
    <label>Suspension Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/ScheduleAdvanceInvoiceHistory__c.object-meta.xml
<CustomObject>
    <label>Schedule Advance Invoice History</label>
    <nameField>
        <displayFormat>SH-{0}</displayFormat>
        <label>Schedule Advance Invoice History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Advance Invoice History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/IsFortnightly__c.field-meta.xml
<CustomField>
    <fullName>IsFortnightly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fortnightly?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/IsNew__c.field-meta.xml
<CustomField>
    <fullName>IsNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedule Advance Invoice History</relationshipLabel>
    <relationshipName>ScheduleAdvanceInvoiceHistory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/ReactivationStartDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationStartDate__c</fullName>
    <label>Reactivation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Schedule Advance Invoice History</relationshipLabel>
    <relationshipName>ScheduleAdvanceInvoiceHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/SuspensionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionStartDate__c</fullName>
    <label>Suspension Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdvanceBinCollectionToOrderBatch.cls
public without sharing class AdvanceBinCollectionToOrderBatch implements Database.Batchable<sObject> {

	private final Date TODAY = System.today(); // TO DO: what should be start date for quarterly?
	private final Date QUATER_END = DateUtil.getQuarterEndDate(TODAY);

	private final String ORDER_KEY_FORMAT = '{0}-{1}-{2}';
	private final String PRODUCT_KEY_FORMAT = '{0}-{1}-{2}-{3}';

	private Map<String, Account_Discount__c> accountDiscounts = new Map <String, Account_Discount__c>();
	private Map<String, Account_Discount__c> partnerDiscounts = new Map <String, Account_Discount__c>();
	private Map<String, List<ScheduleWrapper>> orderItemKeyMap = new Map<String, List<ScheduleWrapper>>();
	private Map<String, Integer> orderItemCollectionCountMap = new Map<String, Integer>();
	private Map<String, Order> orderMap = new Map<String, Order>();

	private Boolean isDelta;

	public AdvanceBinCollectionToOrderBatch(Boolean isDelta) {
		this.isDelta = isDelta;
	}

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		// TO DO: Delta should not start on 1st of each quarter
		if (isDelta) {
			return Database.getQueryLocator([SELECT Id FROM Account WHERE Id IN
				(SELECT Location__c FROM ScheduleAdvanceInvoiceHistory__c WHERE CreatedDate = YESTERDAY
				AND (Schedule__r.Start_Date__c = null OR Schedule__r.Start_Date__c <= :QUATER_END) AND (Schedule__r.End_Date__c = null OR Schedule__r.End_Date__c >= :TODAY))]);
		} else {
			return Database.getQueryLocator([SELECT Id FROM Account WHERE Id IN
				(SELECT Location__c FROM Schedule__c WHERE Location__r.Parent.IsBinCollectionAdvanceInvoiced__c = true AND Location__r.IsLive__c = true
				AND Is_bin_collection__c = true AND (Start_Date__c = null OR Start_Date__c <= :QUATER_END) AND (End_Date__c = null OR End_Date__c >= :TODAY))]);
		}
	}

	public void execute(Database.BatchableContext batchContext, List<Account> locations) {
		Set<Id> accountIds = new Set<Id>();
		Set<Id> accountProductsIds = new Set<Id>();
		Set<Id> partnerIds = new Set<Id>();
		Set<Id> partnerProductsIds = new Set<Id>();

		loadOrderItemKeyMap(fetchSchedules(locations));
		loadCollectionCountMap();

		for (String key : orderItemKeyMap.keySet()) {
			Schedule__c schedule;
			for (ScheduleWrapper wrapper : orderItemKeyMap.get(key)) {
				schedule = wrapper.schedule;
				if (schedule.Discount_Type__c == 'Partner' && schedule.Location__r.Partnership__c != null) {
					partnerIds.add(schedule.Location__r.Partnership__c);
					partnerProductsIds.add(schedule.Supplier_Product__r.Product__c);
				} else if (schedule.Discount_Type__c == 'Account') {
					accountIds.add(schedule.Location__r.ParentId);
					accountProductsIds.add(schedule.Supplier_Product__r.Product__c);
				}
			}
		}

		partnerDiscounts = AccountUtil.getDiscounts(partnerIds, partnerProductsIds);
		accountDiscounts = AccountUtil.getDiscounts(accountIds, accountProductsIds);

		insertOrders();
		insertOrderItems();
	}

	private List<ScheduleWrapper> fetchSchedules(List<Account> locations) {
		List<ScheduleWrapper> schedules = new List<ScheduleWrapper>();
		if (isDelta) {
			for (ScheduleAdvanceInvoiceHistory__c history : [SELECT Quantity__c, IsNew__c, Schedule__r.Collection_Quantity__c, IsFortnightly__c, Schedule__r.Fortnightly__c,
				StartDate__c, Schedule__r.Start_Date__c, EndDate__c, Schedule__r.End_Date__c,
				SuspensionStartDate__c, Schedule__r.Suspension_Start_Date__c, ReactivationStartDate__c, Schedule__r.Reactivation_Start_Date__c,
				Schedule__r.Location__c, Schedule__r.Location__r.ParentId, Schedule__r.Location__r.Partnership__c, Schedule__r.Location__r.Price_Book__c,
				Schedule__r.Supplier__c, Schedule__r.Supplier__r.Name, Schedule__r.Supplier_Product__r.Product__c,
				Schedule__r.Discount_Type__c, Schedule__r.Enqix_Price__c, Schedule__r.Days__c, Schedule__r.Week_Off__c, Schedule__r.Po_Number__c
				FROM ScheduleAdvanceInvoiceHistory__c WHERE Location__c IN :locations AND CreatedDate = YESTERDAY
				AND (Schedule__r.Start_Date__c = null OR Schedule__r.Start_Date__c <= :QUATER_END) AND (Schedule__r.End_Date__c = null OR Schedule__r.End_Date__c >= :TODAY)
				ORDER BY Location__c]) {
				schedules.add(new ScheduleWrapper(history));
			}
		} else {
			for (Schedule__c schedule : [SELECT Location__c, Location__r.ParentId, Location__r.Partnership__c, Location__r.Price_Book__c,
				Supplier__c, Supplier__r.Name, Supplier_Product__r.Product__c, Collection_Quantity__c,
				Discount_Type__c, Enqix_Price__c, Days__c,
				Start_Date__c, End_Date__c, Suspension_Start_Date__c, Reactivation_Start_Date__c, Fortnightly__c, Week_Off__c, Po_Number__c
				FROM Schedule__c WHERE Location__c IN :locations
				AND Is_bin_collection__c = true AND (Start_Date__c = null OR Start_Date__c <= :QUATER_END) AND (End_Date__c = null OR End_Date__c >= :TODAY)
				ORDER BY Location__c]) {
				schedules.add(new ScheduleWrapper(schedule));
			}
		}
		return schedules;
	}

	private void loadOrderItemKeyMap(List<ScheduleWrapper> scheduleList) {
		String productKey;
		for (ScheduleWrapper wrapper : scheduleList) {
			productKey = getUniqueProductKey(wrapper.schedule);
			if (!orderItemKeyMap.containsKey(productKey)) {
				orderItemKeyMap.put(productKey, new List<ScheduleWrapper>());
			}
			orderItemKeyMap.get(productKey).add(wrapper);
		}
	}

	private String getUniqueOrderKey(Schedule__c schedule) {
		return String.format(ORDER_KEY_FORMAT, new Object[]{schedule.Location__c, schedule.Supplier__c, String.isNotBlank(schedule.Po_Number__c) ? schedule.Po_Number__c : null});
	}

	private String getUniqueProductKey(Schedule__c schedule) {
		return String.format(PRODUCT_KEY_FORMAT, new Object[]{getUniqueOrderKey(schedule), schedule.Supplier_Product__r.Product__c, schedule.Discount_Type__c, schedule.Enqix_Price__c});
	}

	private void loadCollectionCountMap() {
		if (isDelta) {
			Set<String> orderItemKeysToRemove = new Set<String>();
			for (String key : orderItemKeyMap.keySet()) {
				Decimal quantity = 0;
				Schedule__c schedule;
				ScheduleAdvanceInvoiceHistory__c history;
				for (ScheduleWrapper wrapper : orderItemKeyMap.get(key)) {
					schedule = wrapper.schedule;
					history = wrapper.history;
					Integer currentCount = countCollections(schedule.Start_Date__c, schedule.End_Date__c, schedule.Suspension_Start_Date__c, schedule.Reactivation_Start_Date__c, schedule.Days__c, schedule.Fortnightly__c, schedule.Week_Off__c, schedule.Collection_Quantity__c);
					Integer previousCount = history.IsNew__c ? 0 : countCollections(history.StartDate__c, history.EndDate__c, history.SuspensionStartDate__c, history.ReactivationStartDate__c, schedule.Days__c, schedule.Fortnightly__c, schedule.Week_Off__c, history.Quantity__c);
					quantity += currentCount - previousCount;
				}

				if (quantity > 0) {
					orderItemCollectionCountMap.put(key, quantity.intValue());
				} else {
					orderItemKeysToRemove.add(key);
				}
			}

			for (String key : orderItemKeysToRemove) {
				orderItemKeyMap.remove(key);
			}
		} else {
			for (String key : orderItemKeyMap.keySet()) {
				Decimal quantity = 0;
				Schedule__c schedule;
				for (ScheduleWrapper wrapper : orderItemKeyMap.get(key)) {
					schedule = wrapper.schedule;
					quantity += countCollections(schedule.Start_Date__c, schedule.End_Date__c, schedule.Suspension_Start_Date__c, schedule.Reactivation_Start_Date__c, schedule.Days__c, schedule.Fortnightly__c, schedule.Week_Off__c, schedule.Collection_Quantity__c);
				}
				orderItemCollectionCountMap.put(key, quantity.intValue());
			}
		}
	}

	private Integer countCollections(Date startDate, Date endDate, Date suspensionStartDate, Date reactivationStartDate, String weekDay, Boolean isFortnightly, Boolean isWeekOff, Decimal quantity) {
		Integer collectionDayCount = 0;
		Date suspensionEndDate;
		startDate = startDate == null || startDate < TODAY ? TODAY : startDate;
		endDate = endDate == null || endDate > QUATER_END ? QUATER_END : endDate;
		if (suspensionStartDate != null && reactivationStartDate != null && suspensionStartDate <= endDate && reactivationStartDate > startDate) {
			suspensionStartDate = suspensionStartDate < startDate ? startDate : suspensionStartDate;
			suspensionEndDate = reactivationStartDate > endDate ? endDate : reactivationStartDate?.addDays(-1);
		}
		collectionDayCount = DateUtil.countDays(startDate, endDate, weekDay, suspensionStartDate, suspensionEndDate);
		if (isFortnightly) {
			Integer fortnightlyDays = collectionDayCount / 2;
			if (Math.mod(collectionDayCount, 2) != 0) {
				if (DateUtil.Day.valueOf(weekDay).ordinal() < DateUtil.getDayOfWeek(startDate).ordinal()) {
					isWeekOff = !isWeekOff;
				}
				fortnightlyDays = isWeekOff ? ++fortnightlyDays : fortnightlyDays;
			}
			collectionDayCount = fortnightlyDays;
		}
		return collectionDayCount * quantity.intValue();
	}

	private void insertOrders() {
		Schedule__c schedule;
		String orderKey;
		for (String productKey : orderItemKeyMap.keySet()) {
			schedule = orderItemKeyMap.get(productKey)[0].schedule;
			orderKey = getUniqueOrderKey(schedule);
			if (!orderMap.containsKey(orderKey)) {
				Order order = OrderUtil.createOrder(schedule);
				order.PeriodStart__c = DateUtil.getQuarterStartDate(TODAY);
				order.PeriodEnd__c = QUATER_END;
				orderMap.put(orderKey, order);
			}
		}

		Database.SaveResult[] results = Database.insert(orderMap.values(), false);
		LogRegister.createLogsUpsert(results, orderMap.values(), 'Advance Bin Collection Orders', 'Insert', 'Order', 'AccountId');
	}

	private void insertOrderItems() {
		List<OrderItem> orderItems = new List<OrderItem>();
		Schedule__c schedule;
		Order order;
		for (String productKey : orderItemKeyMap.keySet()) {
			schedule = orderItemKeyMap.get(productKey)[0].schedule;
			order = orderMap.get(getUniqueOrderKey(schedule));

			Account_Discount__c discount;
			if (schedule.Discount_Type__c == 'Partner') {
				discount = partnerDiscounts.get(schedule.Location__r.Partnership__c + '-' + schedule.Supplier_Product__r.Product__c);
			} else if (schedule.Discount_Type__c == 'Account') {
				discount = accountDiscounts.get(schedule.Location__r.ParentId + '-' + schedule.Supplier_Product__r.Product__c);
			}

			orderItems.add(OrderUtil.createOrderItem(order, schedule, orderItemCollectionCountMap.get(productKey), discount));
		}

		Database.SaveResult[] results1 = Database.insert(orderItems, false);
		LogRegister.createLogsUpsert(results1, orderItems, 'OrderItems added to Advance Bin Collection Orders', 'Insert', 'OrderItem', 'OrderId');

		OrderUtil.setBinOrderAsConfirmed(orderMap.values());
		Database.SaveResult[] results2 = Database.update(orderMap.values(), false);
		LogRegister.createLogsUpsert(results2, orderMap.values(), 'Set Advance Bin Collection Orders to Confirmed status', 'Update', 'Order', 'AccountId');
	}

	public void finish(Database.BatchableContext batchContext) {}

	private class ScheduleWrapper {
		private Schedule__c schedule {
			get {
				return schedule != null ? schedule : history.Schedule__r;
			}
			set;
		}

		private ScheduleAdvanceInvoiceHistory__c history { get; set;}

		private ScheduleWrapper(Schedule__c schedule) {
			this.schedule = schedule;
		}

		private ScheduleWrapper(ScheduleAdvanceInvoiceHistory__c history) {
			this.history = history;
		}
	}
}