force-app/main/default/objects/Account/fields/Account_Discount__c.field-meta.xml
<CustomField>
    <fullName>Account_Discount__c</fullName>
    <label>Overriding Account Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Discount__c/Account_Discount__c.object-meta.xml
<CustomObject>
    <label>Account Discount</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupEndDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupEndDate__c</fullName>
    <description>The date after which the discount/supplement is no longer applicable.</description>
    <inlineHelpText>The date after which the discount/supplement is no longer applicable.</inlineHelpText>
    <label>Discount End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/DiscountSupStartDate__c.field-meta.xml
<CustomField>
    <fullName>DiscountSupStartDate__c</fullName>
    <label>Discount Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Discount__c/recordTypes/AccountDiscount.recordType-meta.xml
<RecordType>
    <fullName>AccountDiscount</fullName>
    <active>true</active>
    <description>Record type for a discount of type &quot;Account&quot;.</description>
    <label>AccountDiscount</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Enqix_Code__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Code__c</fullName>
    <label>Enqix Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this record is the most recent version of the pricelist</description>
    <label>Most Recent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Skin__c/Product_Skin__c.object-meta.xml
<CustomObject>
    <label>Product Skin</label>
    <nameField>
        <label>Product Skin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Skins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountDiscountTriggerTest.cls
@isTest
private class AccountDiscountTriggerTest {

	@isTest
	static void validateAccountDiscountInsert() {

		/*Product_Category__c productCat = new Product_Category__c();
        productCat.Name = 'Cardboard';
        insert productCat;
        
        Product_Skin__c productSkin = new Product_Skin__c();
        productSkin.Name = 'Collection Skin';
        insert productSkin;*/

		Product2 productRec = TestDataHelper.insertProduct('Product 1','P0001', 'Delivery');
        
        priceBook2 priceBookRec = new priceBook2();
        priceBookRec.Name = 'My Price Book ';
        priceBookRec.IsActive = true;
        pricebookRec.Effective_Date__c=System.Today();
		pricebookRec.Most_Recent__c = true;
        insert priceBookRec;
        priceBookRec = [SELECT Id, Name, IsActive, Effective_Date__c FROM Pricebook2 LIMIT 1];
        
        PricebookEntry priceBookEntryStandardRec = new  PricebookEntry();
        priceBookEntryStandardRec.Product2Id = productRec.Id;
        priceBookEntryStandardRec.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntryStandardRec.UnitPrice = 100;
		priceBookEntryStandardRec.IsActive = True;
        insert priceBookEntryStandardRec;
        
        Pricebook2 pb2 = new Pricebook2();
        pb2.Id = Test.getStandardPricebookId();
        pb2.IsActive = false;
        pb2.Enqix_Code__c = 1123331;
        pb2.Most_Recent__c = True;
        pb2.Effective_Date__c = system.now();
        Update pb2;

		Account account = new Account ();
        account.Name = 'Test Account';
		Id pricebookId = priceBookRec.Id;
		System.debug('Account pricebook Id: ' + priceBookRec.Id);
		System.debug('Account pricebook Id: ' + pricebookId);
        account.Price_Book__c =  pricebookId;
		account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		system.debug('Saving account');
        insert account;
        account = [SELECT id, Name, RecordTypeId, Price_Book__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Price_Book__c =  pricebookId;
        update account;
        account = [SELECT id, Name, RecordTypeId, Price_Book__c FROM Account WHERE Name = 'Test Account' LIMIT 1];

		System.debug('Account: ' + account);
		Account_Discount__c baseAccountDiscount = new Account_Discount__c();
		baseAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		baseAccountDiscount.account__c = account.Id;
		baseAccountDiscount.product__c = productRec.id;
		baseAccountDiscount.DiscountSupStartDate__c= (system.today()-3);
		baseAccountDiscount.DiscountSupEndDate__c = (system.today()+3);
        insert baseAccountDiscount;

		list<Account_Discount__c> lad = new list<Account_Discount__c> ();
		
		Account_Discount__c successfullBeforeAccountDiscount = new Account_Discount__c();
		successfullBeforeAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		successfullBeforeAccountDiscount.account__c = account.Id;
		successfullBeforeAccountDiscount.product__c = productRec.id;
		successfullBeforeAccountDiscount.DiscountSupStartDate__c= (system.today()-7);
		successfullBeforeAccountDiscount.DiscountSupEndDate__c = (system.today()-4);
		lad.add(successfullBeforeAccountDiscount);
        
		Account_Discount__c successfullAfterAccountDiscount = new Account_Discount__c();
		successfullAfterAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		successfullAfterAccountDiscount.account__c = account.Id;
		successfullAfterAccountDiscount.product__c = productRec.id;
		successfullAfterAccountDiscount.DiscountSupStartDate__c= (system.today()+4);
		successfullAfterAccountDiscount.DiscountSupEndDate__c = (system.today()+7);
		lad.add(successfullAfterAccountDiscount);

		Account_Discount__c overlapingStartAccountDiscount = new Account_Discount__c();
		overlapingStartAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		overlapingStartAccountDiscount.account__c = account.Id;
		overlapingStartAccountDiscount.product__c = productRec.id;
		overlapingStartAccountDiscount.DiscountSupStartDate__c= (system.today()-2);
		overlapingStartAccountDiscount.DiscountSupEndDate__c = (system.today()+4);
		lad.add(overlapingStartAccountDiscount);

		Account_Discount__c overlapingEndAccountDiscount = new Account_Discount__c();
		overlapingEndAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		overlapingEndAccountDiscount.account__c = account.Id;
		overlapingEndAccountDiscount.product__c = productRec.id;
		overlapingEndAccountDiscount.DiscountSupStartDate__c= (system.today()-4);
		overlapingEndAccountDiscount.DiscountSupEndDate__c = (system.today()+2);
		lad.add(overlapingEndAccountDiscount);

		Account_Discount__c nullEndAccountDiscount = new Account_Discount__c();
		nullEndAccountDiscount.RecordTypeId = Schema.SObjectType.Account_Discount__c.getRecordTypeInfosByName().get('AccountDiscount').getRecordTypeId();
		nullEndAccountDiscount.account__c = account.Id;
		nullEndAccountDiscount.product__c = productRec.id;
		nullEndAccountDiscount.DiscountSupStartDate__c= (system.today()-4);
		lad.add(nullEndAccountDiscount);

        Database.SaveResult[] AccntDiscResultSet = Database.insert(lad,false);
        system.assertEquals(AccntDiscResultSet[0].isSuccess(), true);
        system.assertEquals(AccntDiscResultSet[1].isSuccess(), true);
        system.assertEquals(AccntDiscResultSet[2].isSuccess(), false);
        system.assertEquals(AccntDiscResultSet[3].isSuccess(), false);
        system.assertEquals(AccntDiscResultSet[4].isSuccess(), false);
	}
	
}