force-app/main/default/objects/Account/fields/BACS_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>BACS_Account_Number__c</fullName>
    <label>BACS Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BACS_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>BACS_Sort_Code__c</fullName>
    <label>BACS Sort Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Document_name__c.field-meta.xml
<CustomField>
    <fullName>Document_name__c</fullName>
    <description>This field will hold the original document name as a text, this will help to distinct information from different days</description>
    <label>Document Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <description>This is the entry date field, stored as a Date, for the Bank Statement</description>
    <label>Entry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Receipt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Amount__c</fullName>
    <description>This field indicates the receipt amount, kept as a number</description>
    <label>Receipt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Details__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Details__c</fullName>
    <description>These are the transaction details, kept as text</description>
    <label>Transaction Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BankStatementsTriggerInactive_Test.cls
/** 
(c) 2018 Nexell GmbH / Rolling-Space
Developed by Nexell GmbH, Zug (Switzerland) / Rolling-Space, Braga (Portugal)
@date Date of creation mm.yyyy 
@author Name of initial developer 

@description Initial PT or Case number + description of what the class does 

@modifications dd.mm.yyyy [XX] PT or Case number followed by short description of change 
Example: 02.04.2018 [PC] PT5703 - Added support of new Account fields 
*/
@isTest
private class BankStatementsTriggerInactive_Test {
	
	@isTest static void test_method_one() {
		Account a = new Account();
		a.Name = 'test account';
		a.BACS_Account_Number__c = 'D 000000';
		a.BACS_Sort_Code__c = 'UK LIMIT';
		a.Enqix_Id__c = '12345y';
		a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		insert a;

		Bank_Statement__c bs = new Bank_Statement__c();
		bs.Transaction_Details__c = 'ZARA UK LIMITED 0000000';
		bs.Unallocated_Amount__c = 20;
		bs.Account__c = a.Id;
		bs.Entry_Date__c = System.today();
		bs.Transaction_Type__c = 'Bank Giro Credit';
		bs.Document_name__c = 'test bss';
		bs.Receipt_Amount__c = 20;
		insert bs;
	}
	
}