force-app/main/default/objects/Account/fields/BACS_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>BACS_Account_Number__c</fullName>
    <label>BACS Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BACS_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>BACS_Sort_Code__c</fullName>
    <label>BACS Sort Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/AllocatedAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocatedAmount__c</fullName>
    <label>AllocatedAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/CP_Transactional_Info__c.field-meta.xml
<CustomField>
    <fullName>CP_Transactional_Info__c</fullName>
    <label>CP_Transactional_Info</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Credit_Note_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Note Invoice</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Document_name__c.field-meta.xml
<CustomField>
    <fullName>Document_name__c</fullName>
    <description>This field will hold the original document name as a text, this will help to distinct information from different days</description>
    <label>Document Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <description>This is the entry date field, stored as a Date, for the Bank Statement</description>
    <label>Entry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/MarkedForSage__c.field-meta.xml
<CustomField>
    <fullName>MarkedForSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marked For Sage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Receipt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Amount__c</fullName>
    <description>This field indicates the receipt amount, kept as a number</description>
    <label>Receipt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Details__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Details__c</fullName>
    <description>These are the transaction details, kept as text</description>
    <label>Transaction Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/recordTypes/Fee.recordType-meta.xml
<RecordType>
    <fullName>Fee</fullName>
    <active>true</active>
    <label>Fee</label>
</RecordType>

force-app/main/default/objects/Enqix_Id_automation__c/Enqix_Id_automation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Enqix Id automation</label>
</CustomObject>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_id__c</fullName>
    <defaultValue>30000</defaultValue>
    <label>Enqix_id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_Id__c</fullName>
    <label>Enqix Location Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Original_Invoice_to_Credit__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_to_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field helps to identify the original invoice for this credit Note order.</description>
    <label>Original Invoice to Credit</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Credit Invoices</relationshipLabel>
    <relationshipName>CreditInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Original_Invoice_to_Credit__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_to_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field helps to identify the original invoice for this credit Note order.</description>
    <label>Original Invoice to Credit</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Credit Orders</relationshipLabel>
    <relationshipName>CreditOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/PaymentAllocation__c.object-meta.xml
<CustomObject>
    <label>PaymentAllocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>PaymentAllocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentAllocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentAllocation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/AllocatedAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocatedAmount__c</fullName>
    <label>AllocatedAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/BankstatementId__c.field-meta.xml
<CustomField>
    <fullName>BankstatementId__c</fullName>
    <label>Bank Statement</label>
    <referenceTo>Bank_Statement__c</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice_Header</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. - PaymentAllocation.InvoiceId__c</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Invoice_Header__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Invoice_Header__c.Query__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Invoice_Header__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Query</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BankStatements_Test.cls
@isTest
private class BankStatements_Test {
    
    @future
    private static void insertCustomSetting(){
        Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Name = 'teste', Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
        system.debug('DEBUG========================='+testRecord);
        insert testRecord;
    } 
      
    @testSetup
    static void setup() {
        TestDataHelper.insertVat();
    }

    @isTest 
    static void test_method_one() {
            
        Account a = new Account();
        a.Name = 'test account';
        a.BACS_Account_Number__c = 'D 000000';
        a.BACS_Sort_Code__c = 'UK LIMIT';
        a.Enqix_Id__c = '12345y';
        a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        insert a;
        
        List<Invoice_Header__c> invoicesToTest = new List<Invoice_Header__c>();

        Invoice_Header__c SpecificHeader1 = new Invoice_Header__c();
        SpecificHeader1.Name = 'test specific invoice header 1';
        SpecificHeader1.Account__c = a.Id;
        SpecificHeader1.AmountOutstanding__c = 150;
        SpecificHeader1.Salesforce__c = true;
        SpecificHeader1.InvoiceFrequency__c = 'Per Order';
        SpecificHeader1.VAT__c = 50;
        Insert SpecificHeader1;

        Invoice_Header__c ih2 = new Invoice_Header__c();
        ih2.Name = 'test invoice header 2';
        ih2.Account__c = a.Id;
        ih2.AmountOutstanding__c = 250;
        ih2.Salesforce__c = true;
        ih2.Original_Invoice_to_Credit__c = SpecificHeader1.Id;
        ih2.VAT__c = 50;
        ih2.InvoiceFrequency__c = 'Per Order';
        invoicesToTest.add(ih2);
        
        Invoice_Header__c ih3 = new Invoice_Header__c(); 
        ih3.Name = 'test invoice header 2';
        ih3.Account__c = a.Id;
        ih3.AmountOutstanding__c = -10;
        ih3.Original_Invoice_to_Credit__c = SpecificHeader1.Id;
        ih3.Salesforce__c = true;
        ih3.VAT__c = 1.2;
        ih3.InvoiceFrequency__c = 'Per Order';
         invoicesToTest.add(ih3);
        
        insert invoicesToTest;
        
        Invoice_Header__c invocieToSpecifiicPayment;
        
        invocieToSpecifiicPayment = [SELECT Id FROM Invoice_Header__c WHERE Name LIKE 'test specific invoice%' LIMIT 1];

        List<Bank_Statement__c> bsToInsert = new List<Bank_Statement__c>();
        
        test.startTest();

        Bank_Statement__c BSForSpecificIncoice = new Bank_Statement__c();
        BSForSpecificIncoice.Transaction_Details__c = 'Pay account specific invoices';
        BSForSpecificIncoice.Cancelled__c = false;
        BSForSpecificIncoice.Unallocated_Amount__c = 75;
        BSForSpecificIncoice.Account__c = a.Id;
        BSForSpecificIncoice.CP_Transactional_Info__c = 'cp_testspecificpayment00001';
        BSForSpecificIncoice.Entry_Date__c = System.today();
        BSForSpecificIncoice.Transaction_Type__c = 'Credit Card';
        BSForSpecificIncoice.Document_name__c = 'Charge for ['+ invocieToSpecifiicPayment.Id + ', ' + invocieToSpecifiicPayment.Id + ']';
        BSForSpecificIncoice.Receipt_Amount__c = 75;
        BSForSpecificIncoice.Credit_Note_Invoice__c = ih3.Id;
        //insert BSForSpecificIncoice; 
        bsToInsert.add(BSForSpecificIncoice);

        SpecificHeader1.Query__c = false;
        SpecificHeader1.Status__c = 'Draft';
		SpecificHeader1.AmountOutstanding__c = 10;
        update SpecificHeader1;
        ih2.Original_Invoice_to_Credit__c = [Select Id From Invoice_Header__c Where Name = :SpecificHeader1.Name LIMIT 1].Id;
        ih2.AmountOutstanding__c = -10;
        update ih2;
        
        Bank_Statement__c bs = new Bank_Statement__c();
        bs.Transaction_Details__c = 'ZARA UK LIMITED 00000002';
        bs.Cancelled__c = false;
        bs.Unallocated_Amount__c = 205;
        bs.Account__c = a.Id;
        bs.Entry_Date__c = System.today();
        bs.Transaction_Type__c = 'Bank Giro Credit';
        bs.Document_name__c = 'test bss';
        bs.Receipt_Amount__c = 20;
        bs.Credit_Note_Invoice__c = ih3.Id;
        bs.MarkedForSage__c  = true;
        bsToInsert.add(bs);
            
        
        Bank_Statement__c bs3 = new Bank_Statement__c();
        bs3.Transaction_Details__c = 'ZARA UK LIMITED 00000002';
        bs3.Cancelled__c = false;
        bs3.Unallocated_Amount__c = 205;
        bs3.Account__c = a.Id;
        bs3.Entry_Date__c = System.today();
        bs3.Transaction_Type__c = 'Credit Note';
        bs3.Document_name__c = 'test bss';
        bs3.Receipt_Amount__c = 205;
        bs3.Credit_Note_Invoice__c = ih3.Id;
        bs3.MarkedForSage__c  = true;
        bsToInsert.add(bs3);
        
        Bank_Statement__c feeBS = new Bank_Statement__c();
        feeBS.Transaction_Details__c = 'ZARA UK LIMITED 00000002';
        feeBS.RecordTypeId = Schema.SObjectType.Bank_Statement__c.getRecordTypeInfosByName().get('Fee').getRecordTypeId();
        feeBS.Cancelled__c = false;
        feeBS.Unallocated_Amount__c = 205;
        feeBS.Account__c = a.Id;
        feeBS.Entry_Date__c = System.today();
        feeBS.Transaction_Type__c = 'Bank Giro Credit';
        feeBS.Document_name__c = 'test bss';
        feeBS.Receipt_Amount__c = 20;
        feeBS.Credit_Note_Invoice__c = ih3.Id;
        feeBS.MarkedForSage__c  = true;
        bsToInsert.add(feeBS);

        insert bsToInsert;
        
        test.stopTest();
        
        PaymentAllocation__c pa = new PaymentAllocation__c();
        pa.InvoiceId__c = ih2.Id;
        pa.BankstatementId__c = bs3.Id;
        pa.AllocatedAmount__c = 10;
        pa.Account__c = a.Id;
        pa.Automatic_Payment__c = false;
        pa.IsCreditNote__c = true;
        pa.IsDirectDebit__c = true;
        pa.IsFromCPCard__c = true;
        insert pa;
  
        //bs.Transaction_Type__c = 'Direct Debit';
        bs.Cancelled__c = true;
        bs3.Transaction_Type__c = 'Direct Debit';
        bs3.Unallocated_Amount__c = 250;

        update bs; 
        delete bs3;
    }  
}