force-app/main/default/objects/Account/fields/BID__c.field-meta.xml
<CustomField>
    <fullName>BID__c</fullName>
    <label>BID or Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bee Midtown</fullName>
            </value>
            <value>
                <fullName>Better Bankside</fullName>
            </value>
            <value>
                <fullName>Bond Street Association</fullName>
            </value>
            <value>
                <fullName>Brixton BID</fullName>
            </value>
            <value>
                <fullName>Cadogan Estate</fullName>
            </value>
            <value>
                <fullName>Camden Town Unlimited</fullName>
            </value>
            <value>
                <fullName>Chancery Lane Association</fullName>
            </value>
            <value>
                <fullName>Clapham BID</fullName>
            </value>
            <value>
                <fullName>Colmore BID</fullName>
            </value>
            <value>
                <fullName>Decent packaging</fullName>
            </value>
            <value>
                <fullName>DICE FM Partner Venues</fullName>
            </value>
            <value>
                <fullName>Ealing</fullName>
            </value>
            <value>
                <fullName>Euston Town BID</fullName>
            </value>
            <value>
                <fullName>Fitzrovia Partnership</fullName>
            </value>
            <value>
                <fullName>Grosvenor Estate</fullName>
            </value>
            <value>
                <fullName>Hammersmith</fullName>
            </value>
            <value>
                <fullName>Harcourts Inns</fullName>
            </value>
            <value>
                <fullName>Hatton Garden</fullName>
            </value>
            <value>
                <fullName>Heart of London</fullName>
            </value>
            <value>
                <fullName>Ilford BID</fullName>
            </value>
            <value>
                <fullName>InStreatham</fullName>
            </value>
            <value>
                <fullName>Kingston First</fullName>
            </value>
            <value>
                <fullName>Lambeth Borough</fullName>
            </value>
            <value>
                <fullName>Love Wimbledon</fullName>
            </value>
            <value>
                <fullName>Marldon Partnership</fullName>
            </value>
            <value>
                <fullName>New West End Company</fullName>
            </value>
            <value>
                <fullName>Old Street District Partnership</fullName>
            </value>
            <value>
                <fullName>Paddington</fullName>
            </value>
            <value>
                <fullName>Positively Putney</fullName>
            </value>
            <value>
                <fullName>Stratford BID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IMAGE__c.field-meta.xml
<CustomField>
    <fullName>IMAGE__c</fullName>
    <formula>IF(AND(RecordType.DeveloperName = &quot;Partner&quot;), IMAGE(&quot;/resource/Account/Type/Partner.jpg&quot;, &quot;Partner&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;), IMAGE(&quot;/resource/Account/Type/Account.jpg&quot;,&quot;Account&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Dead&quot;), IMAGE(&quot;/resource/Account/Type/Dead.jpg&quot;, &quot;Dead&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;&quot;), IMAGE(&quot;/resource/Account/Type/ProspectAccount.jpg&quot;,&quot;PAccount&quot;),
IF(RecordType.DeveloperName = &quot;Supplier&quot;, IMAGE(&quot;/resource/Account/Type/Supplier.jpg&quot;,&quot;Supplier&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;, CONTAINS(Parent_Enqix_Classification__c, &apos;Indirect&apos;)), IMAGE(&quot;/resource/Account/Type/ResellerLocation.jpg&quot;,&quot;Reseller Location&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;), IMAGE(&quot;/resource/Account/Type/Location.jpg&quot;,&quot;Location&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Dead&quot;), IMAGE ( &quot;/resource/Account/Type/Dead.jpg&quot;,&quot;Dead&quot;), IMAGE (&quot;/resource/Account/Type/ProspectLocation.jpg&quot;,&quot;Prospect&quot;)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Linked_Group__c.field-meta.xml
<CustomField>
    <fullName>Linked_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Linked Group)</relationshipLabel>
    <relationshipName>Linked_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/classes/RelatedAccountsController.cls
/**
* Apex controller for lightning component 'RelatedAccounts'
*
* @Date: 01/02/2018
* @Author: Adeel Ahmad
*
* @TestClass : Test_RelatedAccountsController
*/
public class RelatedAccountsController {
 	@AuraEnabled
    public static List<Account> getChildAccounts(String accId) {
        return [SELECT id, Name, IMAGE__c, BID__c, Linked_Group__c, Partnership__r.Id, Partnership__r.Name FROM Account WHERE ParentId=:accId ORDER BY name ASC];
    }
}