force-app/main/default/objects/Account/fields/BillingStreetLineSingle__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetLineSingle__c</fullName>
    <formula>SUBSTITUTE(BillingStreet, MID($Setup.LineBreak__c.Value__c, 2, 2), &apos;, &apos;)</formula>
    <label>Billing Street Line Single</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingJobId__c.field-meta.xml
<CustomField>
    <fullName>RoutingJobId__c</fullName>
    <externalId>true</externalId>
    <label>Routing Job Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingResponse__c.field-meta.xml
<CustomField>
    <fullName>RoutingResponse__c</fullName>
    <label>Routing Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingStatus__c.field-meta.xml
<CustomField>
    <fullName>RoutingStatus__c</fullName>
    <label>Routing Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RoutingStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingSummary__c.field-meta.xml
<CustomField>
    <fullName>RoutingSummary__c</fullName>
    <label>Routing Summary</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Index</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/EarliestArrival__c.field-meta.xml
<CustomField>
    <fullName>EarliestArrival__c</fullName>
    <label>Earliest Arrival</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/LatestArrival__c.field-meta.xml
<CustomField>
    <fullName>LatestArrival__c</fullName>
    <label>Latest Arrival</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/ServiceTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTime__c</fullName>
    <label>Service Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minerva Road</fullName>
            </value>
            <value>
                <fullName>Camley Street</fullName>
            </value>
            <value>
                <fullName>Hoxton</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Waterloo Hub</fullName>
            </value>
            <value>
                <fullName>Harriet Walk</fullName>
            </value>
            <value>
                <fullName>Oldbury</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
                <isActive>false</isActive>
                <label>Birmingham</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/EndDepot__c.field-meta.xml
<CustomField>
    <fullName>EndDepot__c</fullName>
    <label>End Depot</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/EndDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>EndDepotIndex__c</fullName>
    <label>End Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/Round_Type__c.field-meta.xml
<CustomField>
    <fullName>Round_Type__c</fullName>
    <label>Round Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM Academy</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
                <label>MIDNIGHT</label>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PM + Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/StartDepot__c.field-meta.xml
<CustomField>
    <fullName>StartDepot__c</fullName>
    <label>Start Depot</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/StartDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>StartDepotIndex__c</fullName>
    <label>Start Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/RoutingParameterOverride__mdt.object-meta.xml
<CustomObject>
    <label>Routing Parameter Override</label>
    <pluralLabel>Routing Parameter Overrides</pluralLabel>
</CustomObject>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/EndDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>EndDepotIndex__c</fullName>
    <description>Ending location of routes.</description>
    <label>End Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/StartDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>StartDepotIndex__c</fullName>
    <description>Starting location of routes.</description>
    <label>Start Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time of routes.</description>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/RoutingStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Stuck</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <description>Status of job requested to RaaS.</description>
    <masterLabel>Routing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoutingPostCollectionJob.cls
public without sharing class RoutingPostCollectionJob extends RoutingPostJob {

	private Id dispatchId;

	public RoutingPostCollectionJob(Id dispatchId) {
		this.dispatchId = dispatchId;
	}

	protected override RoutingRequest createRequest() {
		DailyDispatch__c dispatch = [SELECT RoundId__r.Round_Type__c, RoundId__r.StartDepot__c, RoundId__r.StartDepot__r.Index__c, RoundId__r.EndDepot__c, RoundId__r.EndDepot__r.Index__c, RoundId__r.StartTime__c
			FROM DailyDispatch__c WHERE Id = :dispatchId];

		RoutingParameterOverride__mdt overrides = RoutingParameterOverride.get('Collection' + dispatch.RoundId__r.Round_Type__c);
		if (String.isNotBlank(dispatch.RoundId__r.StartTime__c)) {
			overrides.StartTime__c = dispatch.RoundId__r.StartTime__c;
		}
		overrides.StartDepotIndex__c = Convert.toInteger(dispatch.RoundId__r.StartDepot__r.Index__c);
		overrides.EndDepotIndex__c = Convert.toInteger(dispatch.RoundId__r.EndDepot__r.Index__c);

		List<Depot__c> depots = [SELECT Index__c, Name, Address__Street__s, Address__City__s, Address__PostalCode__s, Coordinates__Latitude__s, Coordinates__Longitude__s
			FROM Depot__c WHERE Id IN (:dispatch.RoundId__r.StartDepot__c, :dispatch.RoundId__r.EndDepot__c)];

		List<DispatchLocation__c> locations = [SELECT Name, Location__r.Name, Location__r.BillingStreetLineSingle__c, Location__r.BillingPostalCode,
			Location__r.BillingLatitude, Location__r.BillingLongitude, ServiceTime__c, EarliestArrival__c, LatestArrival__c
			FROM DispatchLocation__c WHERE Dispatch__c = :dispatchId  AND Location__r.IsLive__c = true];

		return new RoutingRequestCollection(overrides, depots, locations);
	}

	protected override void updateJobError(String status, String message) {
		updateJob(new DailyDispatch__c(RoutingStatus__c = status, RoutingResponse__c = message));
	}

	protected override void processResult(RoutingResponse routingResponse) {
		updateJob(new DailyDispatch__c(RoutingJobId__c = routingResponse.jobId, RoutingStatus__c = 'In Progress',
			RoutingPollCount__c = 0, RoutingResponse__c = null, RoutingSummary__c = null));

		System.enqueueJob(new RoutingGetCollectionResultQueueable(routingResponse.jobId), 1);
	}

	private void updateJob(DailyDispatch__c dispatch) {
		dispatch.Id = dispatchId;
		UPDATE dispatch;
	}
}