force-app/main/default/objects/Account/fields/BillingStreetLineSingle__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetLineSingle__c</fullName>
    <formula>SUBSTITUTE(BillingStreet, MID($Setup.LineBreak__c.Value__c, 2, 2), &apos;, &apos;)</formula>
    <label>Billing Street Line Single</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/EarliestArrival__c.field-meta.xml
<CustomField>
    <fullName>EarliestArrival__c</fullName>
    <label>Earliest Arrival</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/LatestArrival__c.field-meta.xml
<CustomField>
    <fullName>LatestArrival__c</fullName>
    <label>Latest Arrival</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/ServiceTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTime__c</fullName>
    <label>Service Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/RoutingParameterOverride__mdt.object-meta.xml
<CustomObject>
    <label>Routing Parameter Override</label>
    <pluralLabel>Routing Parameter Overrides</pluralLabel>
</CustomObject>

force-app/main/default/classes/RoutingRequestCollection.cls
public without sharing class RoutingRequestCollection extends RoutingRequest {

	private List<Location> serviceLocations = new List<Location>();

	public RoutingRequestCollection(RoutingParameterOverride__mdt overrides, List<Depot__c> depots, List<DispatchLocation__c> locations) {
		super(overrides, depots);

		for (DispatchLocation__c location : locations) {
			serviceLocations.add(new Location(location));
		}
	}

	private class Location {
		private transient DispatchLocation__c location;

		private Location(DispatchLocation__c location) {
			this.location = location;
		}

		private Integer recordID { get { return Convert.toInteger(location.Name); } }
		private String customerName { get { return location.Location__r.Name; } }
		private String address { get { return location.Location__r.BillingStreetLineSingle__c; } }
		private String zipCode { get { return location.Location__r.BillingPostalCode; } }
		private Decimal clientXCoord { get { return location.Location__r.BillingLongitude; } }
		private Decimal clientYCoord { get { return location.Location__r.BillingLatitude; } }
		private Integer serviceTime { get { return Convert.toInteger(location.ServiceTime__c); } }
		private String earliestArrival { get { return Convert.toHhMm(location.EarliestArrival__c); } }
		private String latestArrival { get { return Convert.toHhMm(location.LatestArrival__c); } }
		private String existingRoute { get { return 'FM-Miley'; } }
	}
}