force-app/main/default/objects/Account/fields/BillingStreetLineSingle__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetLineSingle__c</fullName>
    <formula>SUBSTITUTE(BillingStreet, MID($Setup.LineBreak__c.Value__c, 2, 2), &apos;, &apos;)</formula>
    <label>Billing Street Line Single</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Supplier_Product__r.Supplier__r.Name</formula>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <formula>IF(!ISBLANK(Monday__c), Monday__c,
IF(!ISBLANK(Tuesday__c), Tuesday__c,
IF(!ISBLANK(Wednesday__c), Wednesday__c,
IF(!ISBLANK(Thursday__c), Thursday__c,
IF(!ISBLANK(Friday__c), Friday__c,
IF(!ISBLANK(Saturday__c), Saturday__c,
IF(!ISBLANK(Sunday__c), Sunday__c, &apos;&apos;)))))))</formula>
    <label>Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/DayIndex__c.field-meta.xml
<CustomField>
    <fullName>DayIndex__c</fullName>
    <formula>IF(TextDays__c = &quot;Sunday&quot;, 1,
IF(TextDays__c = &quot;Monday&quot;, 2,
IF(TextDays__c = &quot;Tuesday&quot;, 3,
IF(TextDays__c = &quot;Wednesday&quot;, 4,
IF(TextDays__c = &quot;Thursday&quot;, 5,
IF(TextDays__c = &quot;Friday&quot;, 6,
IF(TextDays__c = &quot;Saturday&quot;, 7, null)))))))</formula>
    <label>Day Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/NextCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>NextCollectionDate__c</fullName>
    <formula>PreviousCollectionDate__c + (VALUE(TEXT(WeekFrequency__c)) * 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Po_Number_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Po_Number_Supplier__c</fullName>
    <label>Po Number Supplier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Name__c</fullName>
    <description>The name of the product .</description>
    <formula>Supplier_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The name of the product .</inlineHelpText>
    <label>Supplier Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TextDays__c.field-meta.xml
<CustomField>
    <fullName>TextDays__c</fullName>
    <formula>IF( INCLUDES(Days__c, &apos;Monday&apos;), &apos;Monday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Tuesday&apos;), &apos;Tuesday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Wednesday&apos;), &apos;Wednesday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Thursday&apos;), &apos;Thursday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Friday&apos;), &apos;Friday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Saturday&apos;), &apos;Saturday&apos;, null)+
IF( INCLUDES(Days__c, &apos;Sunday&apos;), &apos;Sunday&apos;, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TextDays</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>&quot;18:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/WeekFrequency__c.field-meta.xml
<CustomField>
    <fullName>WeekFrequency__c</fullName>
    <label>Week Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/ScheduleSuspension__c.object-meta.xml
<CustomObject>
    <label>Schedule Suspension</label>
    <nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Suspensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleSuspension__c/fields/Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Aggregator__c</fullName>
    <label>Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Suspensions</relationshipLabel>
    <relationshipName>Suspensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsEveryYear__c.field-meta.xml
<CustomField>
    <fullName>IsEveryYear__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Every Year?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/ReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationDate__c</fullName>
    <label>Reactivation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/SuspensionDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionDate__c</fullName>
    <label>Suspension Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <formula>Aggregator__r.Time__c</formula>
    <label>Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/SupplierAccount__c.field-meta.xml
<CustomField>
    <fullName>SupplierAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account selected should be of type Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <filterItems>
            <field>Account.IsOwnerOfSupplierGroup__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SupplierServiceEmail.cls
public without sharing class SupplierServiceEmail {

	private static final Id ORG_WIDE_EMAIL_ID = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'supplychain@thefirstmile.co.uk'].Id;

	@InvocableMethod(label='Send Supplier Service Emails')
	public static void send(List<Input> inputs) {

		EmailTemplate template = [SELECT Id, HtmlValue, Subject FROM EmailTemplate WHERE DeveloperName = 'SupplierService' LIMIT 1];

		List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

		for(Input input : inputs) {
			String title;
			String templateSubString1;
			String templateSubString2;
			String suspensionDetails;

			Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
			if (input.action == 'Add') {
				email.setSubject('First Mile: New Service Added - Please Review');
				title = 'NEW SERVICE ADDED';
				templateSubString1 = 'added a new service to your schedule';
				templateSubString2 = 'updated on your system against this collection schedule';
			} else if (input.action == 'Amend') {
				email.setSubject('First Mile: Service Amended - Please Review');
				title = 'NEW SERVICE AMENDMENT';
				templateSubString1 = 'amended one of your current collection schedules';
				templateSubString2 = 'updated on your system against this collection schedule';
			} else if (input.action == 'Delete') {
				email.setSubject('First Mile: Service Cancellation - Please Review');
				title = 'SERVICE CANCELLATION';
				templateSubString1 = 'cancelled one of your current collection schedules';
				templateSubString2 = 'removed from your system';
			} else if (input.action == 'Suspend') {
				email.setSubject('First Mile: Service Suspension - Please Review');
				title = 'SERVICE SUSPENSION';
				templateSubString1 = 'suspended one or more of your current collection schedules';
				templateSubString2 = 'removed from your system';
			} else {
				return;
			}

			List<Schedule__c> schedules = [SELECT TextDays__c, Supplier_Product_Name__c, Time__c, Po_Number_Supplier__c, Collection_Quantity__c, Supplier__r.Name, CollectionAggregator__c,
			Supplier__r.Email__c, Location__r.Name, Location__r.BillingStreetLineSingle__c, Location__r.BillingPostalCode, Start_Date__c, End_Date__c, WeekFrequency__c, NextCollectionDate__c FROM Schedule__c
			WHERE Location__c = :input.LocationId AND Po_Number_Supplier__c = :input.PoNumber AND (End_Date__c >= TODAY OR End_Date__c = Null) ORDER BY CollectionAggregator__c, DayIndex__c];

			Map<Id, String> aggregatorIdsMap = new Map<Id, String>();
			Integer aggCount = 1;
			for (Schedule__c schedule : schedules) {
				if (!aggregatorIdsMap.containsKey(schedule.CollectionAggregator__c)) {
					aggregatorIdsMap.put(schedule.CollectionAggregator__c, 'Schedule ' + aggCount);
					aggCount++;
				}
			}

			List<ScheduleSuspension__c> scheduleSuspensions = [SELECT Aggregator__c, IsActive__c, IsEveryYear__c, SuspensionDate__c, ReactivationDate__c FROM ScheduleSuspension__c
			WHERE Aggregator__c = :aggregatorIdsMap.keySet() AND ReactivationDate__c > TODAY ORDER BY Aggregator__c, ReactivationDate__c DESC];

			String body = generateBody(schedules, aggregatorIdsMap);
			String suspensionBody = generateSuspensionBody(scheduleSuspensions, aggregatorIdsMap);

			String address = schedules[0].Location__r.BillingStreetLineSingle__c + ', ' + schedules[0].Location__r.BillingPostalCode;
			String htmlBody = template.HtmlValue.replace('{{0}}', body)
									.replace('{{1}}', title)
									.replace('{{2}}', schedules[0].Supplier__r.Name)
									.replace('{{3}}', templateSubString1)
									.replace('{{4}}', 'Customer Name: ' + schedules[0].Location__r.Name + '<br>' + 'Customer Address: ' + address + '<br>' + 'Stream: ' + schedules[0].Supplier_Product_Name__c + '<br>' + 'PO Number: ' + schedules[0].Po_Number_Supplier__c)
									.replace('{{5}}', templateSubString2)
									.replace('{{6}}', suspensionBody);
			email.setOrgWideEmailAddressId(ORG_WIDE_EMAIL_ID);
			email.setToAddresses(new List<String>{schedules[0].Supplier__r.Email__c});
			email.setHtmlBody(htmlBody);
			email.setWhatId(input.caseId);
			emails.add(email);
		}

		if (!emails.isEmpty()) {
			Messaging.sendEmail(emails);
		}
	}

	private static String generateBody(List<Schedule__c> schedules, Map<Id, String> aggregatorIdsMap) {
		String body = '';
		String template = '<tr><td align="center"><table width="95%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td width="12%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{0}</td>'
			+ '<td width="14%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{1}</td>'
			+ '<td width="10%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{2}</td>'
			+ '<td width="7%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{3}</td>'
			+ '<td width="14%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{4}</td>'
			+ '<td width="14%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{5}</td>'
			+ '<td width="15%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{6}</td>'
			+ '<td width="14%" style="text-align: center; font-size: 12px; padding: 10px 0px; line-height: 14px">{7}</td></tr>'
			+ '</table></td></tr>'
			+ '<tr><td align="center"><table width="95%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td height="1.5" bgcolor="#21D1D2" width="1"></td></tr></table></td></tr>';

		for (Schedule__c schedule : schedules) {
			body += String.format(template, new List<String>{aggregatorIdsMap.get(schedule.CollectionAggregator__c), schedule.TextDays__c,
				schedule.Time__c, String.valueOf(schedule.Collection_Quantity__c),
				(String.valueOf(schedule.Start_Date__c) != null) ? String.valueOf(schedule.Start_Date__c) : '-',
				(String.valueOf(schedule.End_Date__c) != null) ? String.valueOf(schedule.End_Date__c) : '-',
				(Integer.valueOf(schedule.WeekFrequency__c) > 1) ? String.valueOf('Once ' + schedule.WeekFrequency__c + ' weeks') : 'Every week',
				(String.valueOf(schedule.NextCollectionDate__c) != null) ? String.valueOf(schedule.NextCollectionDate__c) : '-'});
		}
		return body;
	}

	private static String generateSuspensionBody(List<ScheduleSuspension__c> scheduleSuspensions, Map<Id, String> aggregatorIdsMap) {
		if (scheduleSuspensions.isEmpty()) {
			return '';
		}

		String body = '';
		String template = '<tr><td align="center"><table width="95%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td width="20%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{0}</td>'
			+ '<td width="25%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{1}</td>'
			+ '<td width="25%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{2}</td>'
			+ '<td width="15%" style="font-size: 12px; padding: 10px 0px; line-height: 14px">{3}</td>'
			+ '<td width="15%" style="text-align: center; font-size: 12px; padding: 10px 0px; line-height: 14px">{4}</td></tr>'
			+ '</table></td></tr>'
			+ '<tr><td align="center"><table width="95%" border="0" cellpadding="0" cellspacing="0">'
			+ '<tr><td height="1.5" bgcolor="#21D1D2" width="1"></td></tr></table></td></tr>';

		for (ScheduleSuspension__c scheduleSuspension : scheduleSuspensions) {
			body += String.format(template, new List<String>{aggregatorIdsMap.get(scheduleSuspension.Aggregator__c),
				String.valueOf(scheduleSuspension.SuspensionDate__c), String.valueOf(scheduleSuspension.ReactivationDate__c),
				String.valueOf(scheduleSuspension.IsActive__c), String.valueOf(scheduleSuspension.IsEveryYear__c)});
		}
		return body;
	}

	public class Input {
		@InvocableVariable(required=true)
		public String LocationId;
		@InvocableVariable(required=true)
		public String Action;
		@InvocableVariable(required=true)
		public Id CaseId;
		@InvocableVariable(required=true)
		public String PoNumber;
	}
}