force-app/main/default/objects/Account/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <formula>IF(ParentId &lt;&gt; &quot;&quot;,  Parent.Name &amp; &quot; &quot; &amp; Parent.BillingStreet &amp; &quot; &quot; &amp; Parent.BillingCity &amp; &quot; &quot; &amp; Parent.BillingPostalCode ,  Name &amp; &quot; &quot; &amp; BillingStreet &amp; &quot; &quot; &amp; BillingCity &amp; &quot; &quot; &amp; BillingPostalCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Pulls in billing details from parent account</inlineHelpText>
    <label>Billing Address Loc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Business_Registration_Number__c</fullName>
    <label>Business Registration Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Classification__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Classification__c</fullName>
    <label>Enqix Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BID</fullName>
            </value>
            <value>
                <fullName>Indirect Large</fullName>
            </value>
            <value>
                <fullName>Indirect Medium</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
                <isActive>false</isActive>
                <label>#N/A</label>
            </value>
            <value>
                <fullName>Broker Large</fullName>
                <isActive>false</isActive>
                <label>Broker Large</label>
            </value>
            <value>
                <fullName>Broker Medium</fullName>
                <isActive>false</isActive>
                <label>Broker Medium</label>
            </value>
            <value>
                <fullName>Cleaner Large</fullName>
                <isActive>false</isActive>
                <label>Cleaner Large</label>
            </value>
            <value>
                <fullName>Cleaner Medium</fullName>
                <isActive>false</isActive>
                <label>Cleaner Medium</label>
            </value>
            <value>
                <fullName>KA Multi</fullName>
                <isActive>false</isActive>
                <label>KA Multi</label>
            </value>
            <value>
                <fullName>KA Single</fullName>
                <isActive>false</isActive>
                <label>KA Single</label>
            </value>
            <value>
                <fullName>Location</fullName>
                <isActive>false</isActive>
                <label>Location</label>
            </value>
            <value>
                <fullName>Multi Central</fullName>
                <isActive>false</isActive>
                <label>Multi Central</label>
            </value>
            <value>
                <fullName>Multi Large</fullName>
                <isActive>false</isActive>
                <label>Multi Large</label>
            </value>
            <value>
                <fullName>Multi Medium</fullName>
                <isActive>false</isActive>
                <label>Multi Medium</label>
            </value>
            <value>
                <fullName>Multi Small</fullName>
                <isActive>false</isActive>
                <label>Multi Small</label>
            </value>
            <value>
                <fullName>Pre booked</fullName>
                <isActive>false</isActive>
                <label>Pre booked</label>
            </value>
            <value>
                <fullName>Single Medium</fullName>
                <isActive>false</isActive>
                <label>Single Medium</label>
            </value>
            <value>
                <fullName>Single Small</fullName>
                <isActive>false</isActive>
                <label>Single Small</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/WTN_Date_of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>WTN_Date_of_Transfer__c</fullName>
    <formula>TEXT(DATEVALUE(StartDate__c)) + &apos; - &apos; +  TEXT(DATEVALUE(EndDate__c))</formula>
    <label>Date of Transfer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/CarrierRegNo__c.field-meta.xml
<CustomField>
    <fullName>CarrierRegNo__c</fullName>
    <label>CarrierRegNo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Waste_Category__c/Waste_Category__c.object-meta.xml
<CustomObject>
    <label>Waste Category</label>
    <nameField>
        <label>Waste Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Waste_Category__c/fields/Codes__c.field-meta.xml
<CustomField>
    <fullName>Codes__c</fullName>
    <label>Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Waste_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/WTN_Waste_Category__c.object-meta.xml
<CustomObject>
    <label>WTN Waste Category</label>
    <nameField>
        <displayFormat>WTN{YYYY}{MM}-{0}</displayFormat>
        <label>WTN Waste Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WTN Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTN_Waste_Category__c/fields/Waste_Category__c.field-meta.xml
<CustomField>
    <fullName>Waste_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Waste Category</label>
    <referenceTo>Waste_Category__c</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/fields/WTN__c.field-meta.xml
<CustomField>
    <fullName>WTN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Waste Transfer Note</label>
    <referenceTo>Compliance_Doc__c</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WasteTransferNoteExtension.cls
public class WasteTransferNoteExtension {

	string recordId {get; set;}
	public Compliance_Doc__c cdoc {get; set;}
	public String url {get; set;}
	public string startdate {get; set;}
	public AccountContactRelation serviceContact {get; private set;}
	public Suppliers__c contractor {get; set;}
	public List<WTN_Waste_Category__c> wasteCategories {get; private set;}
	public String firstMileRegNumber {get; set;}

	public WasteTransferNoteExtension(ApexPages.StandardController ctrl) {
		recordId = ctrl.getId();
		cdoc = [select Order__c, Order__r.Enqix_Id__c, StartDate__c, Account__r.Parent.BillingPostalCode, Account__c, Account__r.Parent.Business_Registration_Number__c, Account__r.Parent.Billing_Address__c, Account__r.Parent.Name, Account__r.Parent.Enqix_Classification__c, Contractor__r.CarrierRegNo__c, Contractor__r.Name, WTN_Date_of_Transfer__c from Compliance_Doc__c where Id = :recordId];
		system.debug(cdoc.Contractor__r.Name);
		system.debug(cdoc);
		if (cdoc.Contractor__r.Name != 'First Mile') {
			firstMileRegNumber = [SELECT Business_Registration_Number__c FROM Account WHERE RecordType.Name = 'Account' AND Name = 'First Mile' AND Enqix_Dead_Live__c = 'Live'].Business_Registration_Number__c;
		}
		system.debug(cdoc.Account__r.Parent.Billing_Address__c);
		system.debug(cdoc.Account__r.Parent.Enqix_Classification__c);
		system.debug(cdoc.Account__r.Parent.Billing_Address__c);
		wasteCategories = [select Id, Waste_Category__r.Name, Waste_Category__r.Codes__c from WTN_Waste_Category__c where WTN__c = :recordId];
		getServiceContact();
		getStartDate();
		getSignature();

	}

	public void getServiceContact() {
		List < AccountContactRelation > acrs = [select Contact.Name, Roles from AccountContactRelation where AccountId =: cdoc.Account__c];
		for (AccountContactRelation acr: acrs) {
			List < string > roles = new list < string > ();
			roles.addAll(acr.Roles.split(';'));
			if (roles.size() > 1) {
				for (integer i = 0; i < roles.size(); i++) {
					if (roles[i] == 'Service Contact') {
						serviceContact = acr;
						break;
					}
				}
			} else {
				if (acr.Roles == 'Service Contact') {
					serviceContact = acr;
					break;
				}
			}
		}
		if (serviceContact == null) serviceContact = new AccountContactRelation();
	}

	public void getStartDate() {
		if (cdoc.StartDate__c != null) {
			string day = string.valueOf(cdoc.StartDate__c.day());
			string month = string.valueOf(cdoc.StartDate__c.month());
			string year = string.valueOf(cdoc.StartDate__c.year()).substring(2);
			startdate = day+'/'+month+'/'+year;
		}
		else startdate = '';
	}

	public void getSignature() {
		Map<Id,Order> orderMap = new Map<Id,Order>([select Id, Enqix_Id__c, (select Id, Name from Attachments) from Order where AccountId = :cdoc.Account__c order by CreatedDate desc]);
		//Set<Id> newSet = orderMap.keySet();
		List<Id> newList = new List<Id>(orderMap.keySet());
		system.debug(newList);
		for (Order ord : orderMap.values()) {
			if (ord.Attachments.size() > 0) {
				string title = 'POD_'+ord.Enqix_Id__c+'.jpg';
				for (Attachment a : ord.Attachments) {
					system.debug(a);
					if (a.Name.contains(title)) {
						url = '/servlet/servlet.FileDownload?file='+a.Id;
						break;
					}
				}
			}
		}
		if (String.isBlank(url) && newList.size() > 0) {
			string title = '%POD_image_%';
			List<ContentDocumentLink> cdl = [select Id, ContentDocumentId from ContentDocumentLink where LinkedEntityId IN :newList and ContentDocument.Title LIKE :title limit 1];
			if (cdl.size() > 0) {
				ContentVersion cv = [select Id from ContentVersion where ContentDocumentId = :cdl[0].ContentDocumentId AND IsLatest = true limit 1];
				system.debug(cv);
				url = '/sfc/servlet.shepherd/version/download/' + cv.Id;
				system.debug(url);
			}
		}
	}
}