force-app/main/default/objects/Account/fields/Box_Givewaway_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Box_Givewaway_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick this field. This is used in the auto-conversion process and to send the right email to customer service.</description>
    <inlineHelpText>Do not manually tick this field. This is used in the auto-conversion process and to send the right email to customer service.</inlineHelpText>
    <label>Box Givewaway Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Revolution_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Revolution_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick. This field is from the auto-conversion process and is used to send the appropriate email to customer service.</description>
    <inlineHelpText>Do not manually tick. This field is from the auto-conversion process and is used to send the appropriate email to customer service.</inlineHelpText>
    <label>Revolution Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Me_Sacks_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Send_Me_Sacks_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick. This field is from the auto-conversion process and is used to send the appropriate email to customer service.</description>
    <inlineHelpText>Do not manually tick. This field is from the auto-conversion process and is used to send the appropriate email to customer service.</inlineHelpText>
    <label>Send Me Sacks Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What made them get in touch ?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Got a leaflet</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Saw trucks or sacks on street.</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
            <value>
                <fullName>Office* Exhibition (2012)</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Council website referral</fullName>
            </value>
            <value>
                <fullName>500 offices project</fullName>
            </value>
            <value>
                <fullName>Dead lead</fullName>
            </value>
            <value>
                <fullName>Used us before</fullName>
            </value>
            <value>
                <fullName>Chatter Picture</fullName>
            </value>
            <value>
                <fullName>Giveaway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Auto_Convert__c.field-meta.xml
<CustomField>
    <fullName>Auto_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a hidden field used in the automated-conversion process. Do not tick manually tick. Do not delete.</description>
    <inlineHelpText>This is a hidden field used in the automated-conversion process. Do not manually tick. Do not delete.</inlineHelpText>
    <label>Auto Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Box_Givewaway_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Box_Givewaway_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template to customer service.</description>
    <inlineHelpText>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template.</inlineHelpText>
    <label>Box Givewaway Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Revolution_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Revolution_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template to customer service.</description>
    <inlineHelpText>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template.</inlineHelpText>
    <label>Revolution Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Send_Me_Sacks_Form_Complete__c.field-meta.xml
<CustomField>
    <fullName>Send_Me_Sacks_Form_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template to customer service.</description>
    <inlineHelpText>Do not manually tick this box. It is used in the auto-conversion process. When the form is completed, this field is ticked on the Pardot form handler. This field is mapped to the account record in Salesforce. It&apos;s used to send the correct email template</inlineHelpText>
    <label>Send Me Sacks Form Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Services_wanted__c.field-meta.xml
<CustomField>
    <fullName>Services_wanted__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled Waste and Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Other Waste/Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Secure Shredding</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance/Junk Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Business Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting and Data</fullName>
    </customValue>
    <customValue>
        <fullName>Product Partnership</fullName>
    </customValue>
    <masterLabel>Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeafletLeadConversionTest.cls
@isTest
public class LeafletLeadConversionTest {
    
    @isTest
    static void test_1() {
        Integer emailbefore = Limits.getEmailInvocations();
        
        Lead l = new Lead(
        	FirstName = 'Test',
            LastName = 'Account',
            Company = 'Test Company',
            Email = 'test@mail.com',
            Phone = '00000000000',
            LeadSource = 'Got a leaflet',
            Auto_Convert__c = true,
            Revolution_Form_Complete__c = true,
            Services_wanted__c = 'Reporting and Data'
        );
        
        insert l;
        
        //Find Contact, Account and Opportunity
        Opportunity o = [Select Name, Amount, StageName, AccountId From Opportunity Where Name = :l.Company + ' Giveaway Pack'];
        
        //System.assertEquals(0, o.Amount);
        System.assertEquals('6 Handed Over', o.StageName);
        
        Account a = [Select Name, Source__c From Account Where Id = :o.AccountId];
        
        System.assertEquals(l.Company, a.Name);
        System.assertEquals(l.LeadSource, a.Source__c);
        
        for(Contact c : [Select FirstName, LastName, Email, Phone From Contact Where AccountId = :o.AccountId]){   
            System.assertEquals(l.FirstName, c.FirstName);
            System.assertEquals(l.LastName, c.LastName);
            System.assertEquals(l.Email, c.Email);
            System.assertEquals(l.Phone, c.Phone);
        }
        
        system.assertNotEquals(emailbefore,Limits.getEmailInvocations());
    }
    
    @isTest
    static void test_2() {
        Lead l = new Lead(
        	FirstName = 'Test',
            LastName = 'Account',
            Company = 'Test Company',
            Email = 'test@mail.com',
            Phone = '00000000000',
            LeadSource = 'Got a leaflet',
            Services_wanted__c = 'Reporting and Data'
        );
        
        insert l;
        
        Lead l2 = new Lead(
        	Id = l.Id,
            Auto_Convert__c = true,
            Send_Me_Sacks_Form_Complete__c = true
        );
        
        update l2;
        
        //Find Contact, Account and Opportunity
        Opportunity o = [Select Name, Amount, StageName, AccountId From Opportunity Where Name = :l.Company + ' Giveaway Pack'];
        
        //System.assertEquals(0, o.Amount);
        System.assertEquals('6 Handed Over', o.StageName);
        
        Account a = [Select Name, Source__c From Account Where Id = :o.AccountId];
        
        System.assertEquals(l.Company, a.Name);
        System.assertEquals(l.LeadSource, a.Source__c);
        
        for(Contact c : [Select FirstName, LastName, Email, Phone From Contact Where AccountId = :o.AccountId]){   
            System.assertEquals(l.FirstName, c.FirstName);
            System.assertEquals(l.LastName, c.LastName);
            System.assertEquals(l.Email, c.Email);
            System.assertEquals(l.Phone, c.Phone);
        }
    }
    
    @isTest
    static void test_3() {
        Lead l = new Lead(
        	FirstName = 'Test',
            LastName = 'Account',
            Company = 'Test Company',
            Email = 'test@mail.com',
            Phone = '00000000000',
            LeadSource = 'Got a leaflet',
            Auto_Convert__c = true,
            Box_Givewaway_Form_Complete__c = true,
            Services_wanted__c = 'Reporting and Data'
        );
        
        insert l;
        
        //Find Contact, Account and Opportunity
        Opportunity o = [Select Name, Amount, StageName, AccountId From Opportunity Where Name = :l.Company + ' Giveaway Pack'];
        
        //System.assertEquals(0, o.Amount);
        System.assertEquals('6 Handed Over', o.StageName);
        
        Account a = [Select Name, Source__c From Account Where Id = :o.AccountId];
        
        System.assertEquals(l.Company, a.Name);
        System.assertEquals(l.LeadSource, a.Source__c);
        
        for(Contact c : [Select FirstName, LastName, Email, Phone From Contact Where AccountId = :o.AccountId]){   
            System.assertEquals(l.FirstName, c.FirstName);
            System.assertEquals(l.LastName, c.LastName);
            System.assertEquals(l.Email, c.Email);
            System.assertEquals(l.Phone, c.Phone);
        }
    }

}