force-app/main/default/objects/Account/fields/BusinessCentralContactId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralContactId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinanceContact__c.field-meta.xml
<CustomField>
    <fullName>FinanceContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parter_type__c.field-meta.xml
<CustomField>
    <fullName>Parter_type__c</fullName>
    <label>Partner type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BID</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Supply chain product</fullName>
            </value>
            <value>
                <fullName>Street Association</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>Contact Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountChangeEventTriggerHandler.cls
public without sharing class AccountChangeEventTriggerHandler extends BusinessCentralEventHandler {

	private static final Set<Id> ALLOWED_RECORD_TYPES = new Set<Id>();
	private static final String FIELD_FINANCE_CONTACT = 'FinanceContact__c';
	private static final String FIELD_LAST_MODIFIED = 'LastModifiedDate';

	private static final Set<String> COMPOSITE_FIELDS = new Set<String> {'BillingAddress.Street', 'BillingAddress.City', 'BillingAddress.County', 'BillingAddress.PostalCode', 'BillingAddress.Country'};

	public AccountChangeEventTriggerHandler() {
		super(Account.sObjectType);

		ALLOWED_RECORD_TYPES.add(AccountUtil.RECORDTYPEID_LOCATION);
		ALLOWED_RECORD_TYPES.add(AccountUtil.RECORDTYPEID_PARENT);
		ALLOWED_RECORD_TYPES.add(AccountUtil.RECORDTYPEID_PARTNER);
	}

	protected override void loadMonitoredFields(Schema.sObjectType sObjectType) {
		super.loadMonitoredFields(sObjectType);
		monitoredFields.addAll(COMPOSITE_FIELDS);
	}

	protected override Map<Id, sObject> fetchRecords(Set<String> recordIds) {
		return new Map<Id, Account>([SELECT BusinessCentralId__c, BusinessCentralContactId__c, RecordTypeId, Parter_type__c, FinanceContact__c, Enqix_Dead_Live__c FROM Account WHERE Id IN :recordIds]);
	}

	protected override Boolean isSkipEvent(EventBus.ChangeEventHeader eventHeader, sObject sObj) {
		return eventHeader.changetype != 'UPDATE' || !isChangedFieldsInMonitoredFields(eventHeader);
	}

	protected override Boolean isSkipRecord(sObject sObj) {
		Account account = (Account)sObj;
		return !AccountUtil.isLive(account) && String.isEmpty(account.BusinessCentralId__c);
	}

	protected override Boolean isRecordEligible(sObject sObj) {
		Account account = (Account)sObj;
		return ALLOWED_RECORD_TYPES.contains(account.RecordTypeId) &&
			(account.RecordTypeId == AccountUtil.RECORDTYPEID_LOCATION || account.FinanceContact__c != null);
	}

	protected override List<BusinessCentralSendRequest__c> createQueueRequests(Set<String> recordIds, List<String> changedFields) {
		Boolean isFinanceContactChanged = changedFields.contains(FIELD_FINANCE_CONTACT);
		Boolean isOnlyFinanceContactChanged = isFinanceContactChanged && (changedFields.size() == 1 || (changedFields.size() == 2 && changedFields.contains(FIELD_LAST_MODIFIED)));

		List<BusinessCentralSendRequest__c> requests = new List<BusinessCentralSendRequest__c>();
		for (String recordId : recordIds) {
			Account account = (Account)getRecord(recordId);

			if (String.isBlank(account.BusinessCentralContactId__c) && account.RecordTypeId != AccountUtil.RECORDTYPEID_LOCATION) {
				requests.add(new BusinessCentralSendRequest__c(AccountId__c = recordId, ContactId__c = account.FinanceContact__c));
			}
			if (!isOnlyFinanceContactChanged) {
				requests.add(new BusinessCentralSendRequest__c(AccountId__c = recordId));
			}
		}
		return requests;
	}

	protected override String getkey(BusinessCentralSendRequest__c requestToQueue) {
		return String.isNotBlank(requestToQueue.ContactId__c) ? requestToQueue.AccountId__c + '-' + requestToQueue.ContactId__c : requestToQueue.AccountId__c;
	}
}