force-app/main/default/objects/Account/fields/BusinessCentralContactId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralContactId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Unique_ID__c</fullName>
    <label>External Unique ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/AccountReference__c.field-meta.xml
<CustomField>
    <fullName>AccountReference__c</fullName>
    <label>Account Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>Contact Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/ContactReference__c.field-meta.xml
<CustomField>
    <fullName>ContactReference__c</fullName>
    <label>Contact Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/BusinessCentralSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Business Central Setting</label>
</CustomObject>

force-app/main/default/objects/BusinessCentralSetting__c/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendAccount__c.field-meta.xml
<CustomField>
    <fullName>SendAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendInvoice__c.field-meta.xml
<CustomField>
    <fullName>SendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Invoice?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendPayment__c.field-meta.xml
<CustomField>
    <fullName>SendPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Payment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>AccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountChangeEventTriggerHandlerTest.cls
@isTest
private class AccountChangeEventTriggerHandlerTest {

	@TestSetup
	static void testdata() {
		BusinessCentralSetting__c bcSetting = new BusinessCentralSetting__c(IsLive__c = true, SendAccount__c = true, SendInvoice__c = true, SendPayment__c = true);
		INSERT bcSetting;

		Test.enableChangeDataCapture();
		Account parent = TestDataHelper.createAccount();
		parent.Enqix_Dead_Live__c = null;
		INSERT parent;

		Account partnership = TestDataHelper.createPartner();
		partnership.Enqix_Dead_Live__c = null;
		INSERT partnership;

		Account location = TestDataHelper.createLocation(parent.Id, partnership.Id);
		location.Enqix_Dead_Live__c = null;
		INSERT location;

		Test.startTest();
		Contact parentContact = TestDataHelper.insertContact(parent.Id, 'testContact1');
		Contact partnerContact = TestDataHelper.insertContact(partnership.Id, 'testContact2');
		Test.stopTest();

		List<AccountContactRelation> acrs = [SELECT Id, Roles FROM AccountContactRelation];
		acrs[0].Roles = AcrUtil.SERVICE_ROLE + ';' + AcrUtil.FINANCE_ROLE;
		acrs[1].Roles = AcrUtil.SERVICE_ROLE + ';' + AcrUtil.FINANCE_ROLE;
		UPDATE acrs;

		List<BusinessCentralSendRequest__c> bcRequests = [SELECT Id, AccountId__c, ContactId__c, AccountReference__c, ContactReference__c FROM BusinessCentralSendRequest__c];
		Assert.isFalse(!bcRequests.isEmpty());
	}

	@isTest
	static void testAccountLive() {
		Test.enableChangeDataCapture();
		Test.startTest();
		List<Account> accounts = [SELECT Id FROM Account];
		for (Account account : accounts) {
			account.Enqix_Dead_Live__c = AccountUtil.LIVE;
			account.Price_Book__c = Test.getStandardPricebookId();
		}
		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		UPDATE accounts;
		Test.stopTest();

		List<BusinessCentralSendRequest__c> bcRequests = [SELECT Id, AccountId__c, ContactId__c, AccountReference__c, ContactReference__c FROM BusinessCentralSendRequest__c];
		Assert.areEqual(5, bcRequests.size()); // Succeeds
	}

	@isTest
	static void testAccountUpdate() {
		Test.enableChangeDataCapture();
		Test.startTest();
		List<Account> accounts = [SELECT Id FROM Account];
		for (Account account : accounts) {
			account.External_Unique_ID__c = 'UnqueId_12345';
		}
		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		UPDATE accounts;
		Test.stopTest();

		List<BusinessCentralSendRequest__c> bcRequests = [SELECT Id, AccountId__c, ContactId__c, AccountReference__c, ContactReference__c FROM BusinessCentralSendRequest__c];

		Assert.areEqual(0, bcRequests.size()); // Succeeds
	}

	@isTest
	static void testContactUpdate() {
		Test.startTest();
		List<Account> accounts = [SELECT Id FROM Account];
		Integer counter = 1000;
		for (Account account : accounts) {
			account.BusinessCentralId__c = String.valueOf(counter);
			account.BusinessCentralContactId__c = String.valueOf(counter);
			counter++;
		}
		UPDATE accounts;

		Test.enableChangeDataCapture();
		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Contact contact = [SELECT Id FROM Contact WHERE AccountId = :accounts[0].Id];
		contact.FirstName = 'FirstNameUpdated';
		UPDATE contact;
		Test.stopTest();

		List<BusinessCentralSendRequest__c> bcRequests = [SELECT Id, AccountId__c, ContactId__c, AccountReference__c, ContactReference__c FROM BusinessCentralSendRequest__c];
		Assert.areEqual(1, bcRequests.size()); // Succeeds
	}

	@isTest
	static void testTurnOffIntegration() {
		BusinessCentralSetting__c bcSetting = [SELECT Id FROM BusinessCentralSetting__c LIMIT 1];
		bcSetting.IsLive__c = false;
		UPDATE bcSetting;

		Test.enableChangeDataCapture();
		Test.startTest();
		List<Account> accounts = [SELECT Id FROM Account];
		for (Account account : accounts) {
			account.Enqix_Dead_Live__c = AccountUtil.LIVE;
			account.Price_Book__c = Test.getStandardPricebookId();
		}
		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		UPDATE accounts;

		Contact contact = [SELECT Id FROM Contact LIMIT 1];
		UPDATE contact;

		Test.stopTest();

		List<BusinessCentralSendRequest__c> bcRequests = [SELECT Id, AccountId__c, ContactId__c, AccountReference__c, ContactReference__c FROM BusinessCentralSendRequest__c];
		Assert.areEqual(0, bcRequests.size()); // Succeeds
	}

	public class BusinessCentralMock implements HttpCalloutMock {
		private Integer counter = 0;
		private String responseBody = '{"Number": "{0}"}';

		public HTTPResponse respond(HTTPRequest req) {
			counter++;
			HTTPResponse response = new HTTPResponse();
			response.setBody('{"Number": "' + counter + '"}');
			response.setStatusCode(200);
			return response;
		}
	}
}