force-app/main/default/objects/Account/fields/BusinessCentralContactId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralContactId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralContactLastSentDate__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralContactLastSentDate__c</fullName>
    <label>Business Central Contact Last Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FinanceContact__c.field-meta.xml
<CustomField>
    <fullName>FinanceContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/ContactReference__c.field-meta.xml
<CustomField>
    <fullName>ContactReference__c</fullName>
    <label>Contact Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusinessCentralSendContactBatch.cls
public without sharing class BusinessCentralSendContactBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

	private BusinessCentralRequestChaining requestChaining;
	private Map<String, Id> objectToRequestMap;

	public BusinessCentralSendContactBatch(BusinessCentralRequestChaining requestChaining) {
		this.requestChaining = requestChaining;
		this.objectToRequestMap = requestChaining.getRequests(BusinessCentralRequestChaining.ENTITY_CONTACT);
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		Set<String> accountIds = new Set<String>();
		Set<String> contactIds = new Set<String>();

		for (String key : objectToRequestMap.keySet()) {
			List<String> Ids = key.split('-');
			accountIds.add(Ids[0]);
			contactIds.add(Ids[1]);
		}

		String query = 'SELECT Id, FinanceContact__c, FinanceContact__r.FirstName, FinanceContact__r.LastName, ' +
			'FinanceContact__r.Email, BusinessCentralContactId__c ' +
			'FROM Account WHERE Id IN :accountIds AND FinanceContact__c IN :contactIds AND BusinessCentralId__c != null';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Account> scope) {
		List<Account> accounts = new List<Account>();
		List<BusinessCentralSendRequest__c> bcSendRequests = new List<BusinessCentralSendRequest__c>();
		for (Account account : scope) {
			BusinessCentralContact bcContact = new BusinessCentralContact();
			bcContact.customerNumber = account.Id;
			bcContact.firstName = String.isNotBlank(account.FinanceContact__r.FirstName) ? StringUtil.abbreviate(account.FinanceContact__r.FirstName, 100) : null;
			bcContact.lastName = StringUtil.abbreviate(account.FinanceContact__r.LastName, 30);
			bcContact.email = account.FinanceContact__r.Email;

			String key = account.Id + '-' + account.FinanceContact__c;
			try {
				String bcId = BusinessCentralIntegrationService.sendToBusinessCentral(BusinessCentralRequestChaining.ENTITY_CONTACT, JSON.serialize(bcContact, true), account.BusinessCentralContactId__c);
				accounts.add(new Account(Id = account.Id, BusinessCentralContactId__c = bcId, BusinessCentralContactLastSentDate__c = System.now()));
				bcSendRequests.add(new BusinessCentralSendRequest__c(Id = objectToRequestMap.get(key), ContactReference__c = bcId, Status__c = 'Completed', ErrorMessage__c = null));
			} catch(Exception e) {
				bcSendRequests.add(new BusinessCentralSendRequest__c(Id = objectToRequestMap.get(key), Status__c = 'Error', ErrorMessage__c = e.getMessage()));
			}
		}
		UPDATE accounts;
		UPDATE bcSendRequests;
	}

	public void finish(Database.BatchableContext BC) {
		requestChaining.process();
	}
}