force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Document_name__c.field-meta.xml
<CustomField>
    <fullName>Document_name__c</fullName>
    <description>This field will hold the original document name as a text, this will help to distinct information from different days</description>
    <label>Document Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <description>This is the entry date field, stored as a Date, for the Bank Statement</description>
    <label>Entry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Receipt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Amount__c</fullName>
    <description>This field indicates the receipt amount, kept as a number</description>
    <label>Receipt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Details__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Details__c</fullName>
    <description>These are the transaction details, kept as text</description>
    <label>Transaction Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/PaymentId__c.field-meta.xml
<CustomField>
    <fullName>PaymentId__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/BusinessCentralSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Business Central Setting</label>
</CustomObject>

force-app/main/default/objects/BusinessCentralSetting__c/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendAccount__c.field-meta.xml
<CustomField>
    <fullName>SendAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendInvoice__c.field-meta.xml
<CustomField>
    <fullName>SendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Invoice?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSetting__c/fields/SendPayment__c.field-meta.xml
<CustomField>
    <fullName>SendPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Payment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OrderLookUp__c.field-meta.xml
<CustomField>
    <fullName>OrderLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLookUp</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <label>Payment Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentChangeEventTriggerHandlerTest.cls
@isTest
private without sharing class PaymentChangeEventTriggerHandlerTest {

	@TestSetup
	static void testdata() {
		BusinessCentralSetting__c bcSetting = new BusinessCentralSetting__c(IsLive__c = true, SendAccount__c = true, SendInvoice__c = true, SendPayment__c = true);
		INSERT bcSetting;

		TestDataHelper.insertVat();

		Account parent = TestDataHelper.createAccount();
		parent.BusinessCentralId__c = '1234';
		INSERT parent;

		Account partnership = TestDataHelper.createPartner();
		partnership.BusinessCentralId__c = '456';
		INSERT partnership;

		Account location = TestDataHelper.createLocation(parent.Id, partnership.Id);
		location.BusinessCentralId__c = '789';
		INSERT location;

		Contact parentContact = TestDataHelper.insertContact(parent.Id, 'testContact1');
		Contact partnerContact = TestDataHelper.insertContact(partnership.Id, 'testContact2');

		AccountContactRelation acr = new AccountContactRelation(AccountId = location.Id, ContactId = parentContact.Id, Roles = AcrUtil.SERVICE_ROLE);
		INSERT acr;

		TestDataHelper.insertSupplier('First Mile Ltd');

		Product2 product = TestDataHelper.insertProduct('FirstMile', '1234', 'Collection');
		PricebookEntry priceBookEntry = TestDataHelper.insertStandardPricebookEntry(product.Id, 100);
		order order = TestDataHelper.insertOrder(location.Id, System.today());
		OrderItem orderItems = TestDataHelper.insertOrderItem(order.Id, product.Id, priceBookEntry.Id);

		order.Status = 'Delivered';
		order.Delivery_Date__c = System.today();
		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		UPDATE order;
		Test.getEventBus().deliver();
		Test.stopTest();
	}

	@isTest
	static void testInvoicePayment() {
		Invoice_Header__c invoice = [SELECT Id, Account__c FROM Invoice_Header__c LIMIT 1];
		Bank_Statement__c bs = new Bank_Statement__c(Transaction_Details__c = 'Test Transaction Details');
		bs.Transaction_Type__c = 'Credit Card';
		bs.Account__c = invoice.Account__c;
		bs.Receipt_Amount__c = 100;
		bs.Entry_Date__c = System.today();
		bs.Document_Name__c = 'Charge for [' + invoice.Id + ']';

		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		INSERT bs;
		Test.getEventBus().deliver();
		Test.stopTest();

		Bank_Statement__c bankStatement = [SELECT Id, BusinessCentralId__c FROM Bank_Statement__c WHERE Id = :bs.Id];
		Assert.isNotNull(bankStatement.BusinessCentralId__c, 'BusinessCentral Id must be available.'); // Succeeds

		BusinessCentralSendRequest__c bcReq = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentReference__c != null LIMIT 1];
		Assert.areEqual(bcReq.PaymentId__c, bs.Id); // Succeeds
		Assert.isNotNull(bcReq.PaymentReference__c, 'BusinessCentral Id must be available.'); // Succeeds
	}

	@isTest
	static void testOrderPayment() {
		Invoice_Header__c invoice = [SELECT Id, Account__c, OrderLookUp__c FROM Invoice_Header__c LIMIT 1];
		Bank_Statement__c bs = new Bank_Statement__c(Transaction_Details__c = 'Test Transaction Details', Document_Name__c = 'Test order');
		bs.Transaction_Type__c = 'Credit Card';
		bs.Account__c = invoice.Account__c;
		bs.Receipt_Amount__c = 100;
		bs.Entry_Date__c = System.today();
		bs.Order__c = invoice.OrderLookUp__c;

		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		INSERT bs;
		Test.getEventBus().deliver();
		Test.stopTest();

		Bank_Statement__c bankStatement = [SELECT Id, BusinessCentralId__c FROM Bank_Statement__c WHERE Id = :bs.Id];
		Assert.isNotNull(bankStatement.BusinessCentralId__c, 'BusinessCentral Id must be available.'); // Succeeds

		BusinessCentralSendRequest__c bcReq = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentReference__c != null LIMIT 1];
		Assert.areEqual(bcReq.PaymentId__c, bs.Id); // Succeeds
		Assert.isNotNull(bcReq.PaymentReference__c, 'BusinessCentral Id must be available.'); // Succeeds
	}

	@isTest
	static void testAccountPayment() {
		Invoice_Header__c invoice = [SELECT Id, Account__c FROM Invoice_Header__c LIMIT 1];
		Bank_Statement__c bs = new Bank_Statement__c(Transaction_Details__c = 'Test Transaction Details', Document_Name__c = 'Test order');
		bs.Transaction_Type__c = 'Credit Card';
		bs.Account__c = invoice.Account__c;
		bs.Receipt_Amount__c = 100;
		bs.Entry_Date__c = System.today();

		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		INSERT bs;
		Test.getEventBus().deliver();
		Test.stopTest();

		Bank_Statement__c bankStatement = [SELECT Id, BusinessCentralId__c FROM Bank_Statement__c WHERE Id = :bs.Id];
		Assert.isNotNull(bankStatement.BusinessCentralId__c, 'BusinessCentral Id must be available.'); // Succeeds

		BusinessCentralSendRequest__c bcReq = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentReference__c != null LIMIT 1];
		Assert.areEqual(bcReq.PaymentId__c, bs.Id); // Succeeds
		Assert.isNotNull(bcReq.PaymentReference__c, 'BusinessCentral Id must be available.'); // Succeeds
	}

	@isTest
	static void testPaymentUpdate() {
		Invoice_Header__c invoice = [SELECT Id, Account__c FROM Invoice_Header__c LIMIT 1];
		Bank_Statement__c bs = new Bank_Statement__c(Transaction_Details__c = 'Test Transaction Details', Document_Name__c = 'Test order');
		bs.Transaction_Type__c = 'Credit Card';
		bs.Account__c = invoice.Account__c;
		bs.Receipt_Amount__c = 100;
		bs.Entry_Date__c = System.today();

		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		INSERT bs;
		Test.getEventBus().deliver();

		List<BusinessCentralSendRequest__c> bcReq1 = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentId__c != null];
		Assert.areEqual(1, bcReq1.size()); // Succeeds

		bs.Unallocated_Amount__c = 0;

		Test.startTest();
		UPDATE bs;
		Test.getEventBus().deliver();
		Test.stopTest();

		List<BusinessCentralSendRequest__c> bcReq2 = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentId__c != null AND PaymentId__c != :bs.Id];
		Assert.areEqual(0, bcReq2.size()); // Succeeds
	}

	@isTest
	static void testTurnOffIntegration() {
		BusinessCentralSetting__c bcSetting = [SELECT Id FROM BusinessCentralSetting__c LIMIT 1];
		bcSetting.IsLive__c = false;
		UPDATE bcSetting;

		Invoice_Header__c invoice = [SELECT Id, Account__c FROM Invoice_Header__c LIMIT 1];
		Bank_Statement__c bs = new Bank_Statement__c(Transaction_Details__c = 'Test Transaction Details', Document_Name__c = 'Test order');
		bs.Transaction_Type__c = 'Credit Card';
		bs.Account__c = invoice.Account__c;
		bs.Receipt_Amount__c = 100;
		bs.Entry_Date__c = System.today();

		Test.setMock(HttpCalloutMock.class, new BusinessCentralMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		INSERT bs;
		Test.getEventBus().deliver();
		Test.stopTest();

		Bank_Statement__c bankStatement = [SELECT Id, BusinessCentralId__c FROM Bank_Statement__c WHERE Id = :bs.Id];
		Assert.isNull(bankStatement.BusinessCentralId__c); // Succeeds

		List<BusinessCentralSendRequest__c> bcReq = [SELECT Id, PaymentId__c, PaymentReference__c FROM BusinessCentralSendRequest__c WHERE PaymentId__c != null LIMIT 1];
		Assert.areEqual(0, bcReq.size()); // Succeeds
	}

	public class BusinessCentralMock implements HttpCalloutMock {
		private Integer counter = 0;

		public HTTPResponse respond(HTTPRequest req) {
			counter++;
			HTTPResponse response = new HTTPResponse();
			response.setBody('{"documentNumber": "' + counter + '"}');
			response.setStatusCode(200);
			return response;
		}
	}
}