force-app/main/default/objects/Account/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CP_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>CP_Account_Code__c</fullName>
    <externalId>true</externalId>
    <label>CP Account Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>This field will store location and account PO # (same field but with 2 labels on Account and Location layouts).</description>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountInclVAT_f__c.field-meta.xml
<CustomField>
    <fullName>AmountInclVAT_f__c</fullName>
    <formula>AmountExclVAT__c +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountInclVAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceNo2__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo2__c</fullName>
    <displayFormat>FMI{000000}</displayFormat>
    <label>InvoiceNo2</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoicePaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>InvoicePaymentMethod__c</fullName>
    <formula>text(Account__r.Enqix_Payment_Method__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>InvoicePaymentMethod</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/LineCount__c.field-meta.xml
<CustomField>
    <fullName>LineCount__c</fullName>
    <label>Line Count</label>
    <summaryForeignKey>Invoice_Line__c.Invoice_HeaderId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Original_Invoice_to_Credit__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_to_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field helps to identify the original invoice for this credit Note order.</description>
    <label>Original Invoice to Credit</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Credit Invoices</relationshipLabel>
    <relationshipName>CreditInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/AmountInclVAT_f__c.field-meta.xml
<CustomField>
    <fullName>AmountInclVAT_f__c</fullName>
    <formula>Amount__c +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountInclVAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <formula>Order__r.Delivery_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DeliveryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice_HeaderId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_HeaderId__c</fullName>
    <label>Invoice_HeaderId</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/NominalCode__c.field-meta.xml
<CustomField>
    <fullName>NominalCode__c</fullName>
    <label>Nominal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Statement__c.Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Statement__c</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK(Order__r.PO_Number__c)),
Order__r.PO_Number__c,
IF(
NOT(ISBLANK(Location_Id__r.PO_Number__c)),
Location_Id__r.PO_Number__c,
&quot;&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Original_Invoice_to_Credit__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_to_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field helps to identify the original invoice for this credit Note order.</description>
    <label>Original Invoice to Credit</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Credit Orders</relationshipLabel>
    <relationshipName>CreditOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BusinessCentralSendInvoiceBatch.cls
public without sharing class BusinessCentralSendInvoiceBatch implements Database.Batchable<sObject>, Database.Stateful {

	private final Integer MAX_LINES = Test.isRunningTest() ? 1 : 3000;

	private BusinessCentralRequestChaining requestChaining;
	private Map<String, Id> objectToRequestMap;

	public BusinessCentralSendInvoiceBatch(BusinessCentralRequestChaining requestChaining) {
		this.requestChaining = requestChaining;
		this.objectToRequestMap = requestChaining.getRequests(BusinessCentralRequestChaining.ENTITY_INVOICE);
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		Set<String> invoceIds = objectToRequestMap.keySet();
		String query = 'SELECT Id, BusinessCentralId__c, InvoiceNo2__c, DueDate__c, Account__c, InvoiceFrequency__c, ' +
			'Account__r.PO_Number__c, Account__r.CP_Account_Code__c, Original_Invoice_to_Credit__c, Original_Invoice_to_Credit__r.InvoiceNo2__c, ' +
			'Original_Invoice_to_Credit__r.AmountOutstanding__c, VAT__c, AmountInclVAT_f__c, InvoicePaymentMethod__c, LineCount__c, CurrencyIsoCode, ' +
			'(SELECT Id, NominalCode__c, Description__c, Qty__c, UnitPrice__c, DeliveryDate__c, Order__r.OrderNumber, ' +
				'Order__r.PO_Number__c, Location_Id__r.PO_Number__c, Location_Id__c, Order__c, Payment__r.BusinessCentralId__c FROM Invoice_Lines__r) ' +
			'FROM Invoice_Header__c WHERE Id IN :invoceIds';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Invoice_Header__c> scope) {
		if (scope.size() > 1) {
			throw new IllegalArgumentException('Cannot execute batch with size more than 1.');
		}

		Invoice_Header__c invoice = scope[0];
		if (Invoicing.isCredit(invoice)) {
			System.enqueueJob(new BusinessCentralSendInvoiceQueue(prepareCreditNote(invoice), objectToRequestMap.get(invoice.Id)));
		} else {
			System.enqueueJob(new BusinessCentralSendInvoiceQueue(prepareInvoice(invoice), objectToRequestMap.get(invoice.Id)));
		}
	}

	private List<BusinessCentralInvoice> prepareInvoice(Invoice_Header__c invoice) {
		List<BusinessCentralInvoice> bcInvoices = new List<BusinessCentralInvoice>();
		BusinessCentralInvoice bcInvoice = new BusinessCentralInvoice();
		bcInvoice.documentNumber = StringUtil.abbreviate(invoice.InvoiceNo2__c, 20);
		bcInvoice.salesforceId = invoice.Id;
		bcInvoice.postingDate = invoice.DueDate__c;
		bcInvoice.sellToCustomerNo = invoice.Account__c;
		bcInvoice.cpAccountCode = invoice.Account__r.CP_Account_Code__c;
		bcInvoice.frequency = invoice.InvoiceFrequency__c;
		bcInvoice.externalDocumentNumber = StringUtil.abbreviate(invoice.Account__r.PO_Number__c, 35);
		bcInvoice.dueDate = invoice.DueDate__c;
		bcInvoice.vat = invoice.VAT__c;
		bcInvoice.amountInclVAT = invoice.AmountInclVAT_f__c;
		bcInvoice.paymentMethodCode = PaymentUtil.transformPaymentMethodCode(invoice.InvoicePaymentMethod__c);
		bcInvoice.currencyCode = invoice.CurrencyIsoCode == 'GBP' ? null : invoice.CurrencyIsoCode;
		bcInvoice.lineCount = Integer.valueOf(invoice.LineCount__c);

		List<BusinessCentralInvoice.FMsalesInvoiceLines> bcLines = new List<BusinessCentralInvoice.FMsalesInvoiceLines>();
		Integer lineCount = 0;
		for (Invoice_Line__c line : invoice.Invoice_Lines__r) {
			BusinessCentralInvoice.FMsalesInvoiceLines bcLine = new BusinessCentralInvoice.FMsalesInvoiceLines();
			bcLine.number_X = line.NominalCode__c;
			bcLine.salesforceId = line.Id;
			bcLine.productDescription = line.Description__c;
			bcLine.quantity = line.Qty__c;
			bcLine.unitPrice = line.UnitPrice__c;
			bcLine.shipmentDate = line.DeliveryDate__c;
			bcLine.externalDocumentNumber = (line.Order__r.PO_Number__c ?? line.Location_Id__r.PO_Number__c)?.abbreviate(35);
			bcLine.sellToCustomerNumber = line.Location_Id__c;
			bcLine.orderNumber = line.Order__r.OrderNumber;
			bcLine.paymentId = line.Payment__r?.BusinessCentralId__c;

			bcLines.add(bcLine);
			lineCount++;
			if (lineCount == invoice.LineCount__c || bcLines.size() == MAX_LINES) {
				BusinessCentralInvoice bcInvoiceClone = new BusinessCentralInvoice(bcInvoice);
				bcInvoiceClone.fMsalesInvoiceLines.addAll(bcLines);
				bcInvoices.add(bcInvoiceClone);
				bcLines.clear();
			}
		}
		return bcInvoices;
	}

	private BusinessCentralCreditNote prepareCreditNote(Invoice_Header__c invoice) {
		BusinessCentralCreditNote bcInvoice = new BusinessCentralCreditNote();
		bcInvoice.documentType = 'Credit Memo';
		bcInvoice.documentNumber = StringUtil.abbreviate(invoice.InvoiceNo2__c, 20);
		bcInvoice.salesforceId = invoice.Id;
		bcInvoice.postingDate = invoice.DueDate__c;
		bcInvoice.sellToCustomerNo = invoice.Account__c;
		bcInvoice.billToCustomerNumber = invoice.Account__c;
		bcInvoice.cpAccountCode = invoice.Account__r.CP_Account_Code__c;
		bcInvoice.frequency = invoice.InvoiceFrequency__c;
		bcInvoice.externalDocumentNumber = invoice.Account__r.PO_Number__c?.abbreviate(35);
		if (invoice.Original_Invoice_to_Credit__r.AmountOutstanding__c > 0) {
			bcInvoice.appliesToDocumentType = 'Invoice';
			bcInvoice.appliesToDocumentNumber = invoice.Original_Invoice_to_Credit__r.InvoiceNo2__c;
		}
		bcInvoice.dueDate = invoice.DueDate__c;
		bcInvoice.vat = invoice.VAT__c * -1;
		bcInvoice.amountInclVAT = invoice.AmountInclVAT_f__c * -1;
		bcInvoice.currencyCode = invoice.CurrencyIsoCode == 'GBP' ? null : invoice.CurrencyIsoCode;
		bcInvoice.lineCount = Integer.valueOf(invoice.LineCount__c);

		List<BusinessCentralCreditNote.SalesLines> bcLines = new List<BusinessCentralCreditNote.SalesLines>();
		for (Invoice_Line__c line : invoice.Invoice_Lines__r) {
			BusinessCentralCreditNote.SalesLines bcLine = new BusinessCentralCreditNote.SalesLines();
			bcLine.number_X = line.NominalCode__c;
			bcLine.salesforceId = line.Id;
			bcLine.productDescription = line.Description__c;
			bcLine.quantity = line.Qty__c * -1;
			bcLine.unitPrice = line.UnitPrice__c;
			bcLine.shipmentDate = line.DeliveryDate__c;
			bcLine.externalDocumentNumber = (line.Order__r.PO_Number__c ?? line.Location_Id__r.PO_Number__c)?.abbreviate(35);
			bcLine.sellToCustomerNumber = line.Location_Id__c;
			bcLine.orderNumber = line.Order__r.OrderNumber;
			bcInvoice.SalesLines.add(bcLine);
		}
		return bcInvoice;
	}

	public void finish(Database.BatchableContext BC) {
		requestChaining.process();
	}
}