force-app/main/default/objects/Account/fields/CollectionPriority__c.field-meta.xml
<CustomField>
    <fullName>CollectionPriority__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, &apos;&apos;, IF(OR(VIP_Customer__c, On_Priority__c, Complex_Collection__c), &apos;VIP&apos;, IF(TODAY() &lt;= (Enqix_Start_Date__c + 30), &apos;New&apos;, &apos;Normal&apos;)))</formula>
    <label>Collection Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StreetSegmentID__c.field-meta.xml
<CustomField>
    <fullName>StreetSegmentID__c</fullName>
    <label>StreetSegmentID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsInternalCollection__c.field-meta.xml
<CustomField>
    <fullName>IsInternalCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CollectionType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Extra</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
        <default>true</default>
        <label>Normal</label>
    </customValue>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClusterSequenceBatch.cls
public without sharing class ClusterSequenceBatch implements Database.Batchable<Id> {
	List<Id> dispatchIds = null;

	public ClusterSequenceBatch(List<Id> dispatchIds) {
		this.dispatchIds = dispatchIds;
	}

	public ClusterSequenceBatch(Set<Id> dispatchIds) {
		this(new List<Id>(dispatchIds));
	}

	public Iterable<Id> start(Database.BatchableContext batchContext) {
		return dispatchIds;
	}

	public void execute(Database.BatchableContext batchContext, List<Id> dispatchIds) {
		List<DispatchLocation__c> dispatchLocations = [SELECT Name, SequenceNumber__c, Type__c, IsInternalCollection__c, IsBinCollection__c,
			Location__c, Location__r.StreetSegmentId__c, Location__r.CollectionPriority__c
			FROM DispatchLocation__c WHERE Dispatch__c = :dispatchIds[0] AND Location__r.IsLive__c = true];

		Integer incrementalSequence = 0;
		Integer assignedSequence;
		Map<String, Integer> keyToSequence = new Map<String, Integer>();
		List<DispatchLocation__c> dispatchLocationsToUpdate = new List<DispatchLocation__c>();
		for (DispatchLocation__c dispatchLocation : dispatchLocations) {
			if (!isCluster(dispatchLocation)) {
				assignedSequence = ++incrementalSequence;
			} else {
				assignedSequence = keyToSequence.get(dispatchLocation.Location__r.StreetSegmentId__c);
				if (assignedSequence == null) {
					assignedSequence = ++incrementalSequence;
					keyToSequence.put(dispatchLocation.Location__r.StreetSegmentId__c, assignedSequence);
				}
			}
			dispatchLocation.SequenceNumber__c = assignedSequence;
			dispatchLocationsToUpdate.add(dispatchLocation);
		}

		if (!dispatchLocationsToUpdate.isEmpty()) {
			UPDATE dispatchLocationsToUpdate;
		}
	}

	public void finish(Database.BatchableContext batchContext) {}

	private Boolean isCluster(DispatchLocation__c dispatchLocation) {
		return String.isNotBlank(dispatchLocation.Location__r.StreetSegmentId__c) &&
			dispatchLocation.Location__r.CollectionPriority__c == 'Normal' && dispatchLocation.Type__c == 'Normal' &&
			!dispatchLocation.IsInternalCollection__c && !dispatchLocation.IsBinCollection__c;
	}
}