force-app/main/default/objects/Account/fields/CollectionPriority__c.field-meta.xml
<CustomField>
    <fullName>CollectionPriority__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, &apos;&apos;, IF(OR(VIP_Customer__c, On_Priority__c, Complex_Collection__c), &apos;VIP&apos;, IF(TODAY() &lt;= (Enqix_Start_Date__c + 30), &apos;New&apos;, &apos;Normal&apos;)))</formula>
    <label>Collection Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Comments_c__c.field-meta.xml
<CustomField>
    <fullName>Comments_c__c</fullName>
    <label>Collection notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <label>Collection Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Unachievable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_product_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_product_name__c</fullName>
    <formula>Supplier_Product__r.Product_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier product name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsInternalCollection__c.field-meta.xml
<CustomField>
    <fullName>IsInternalCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SubmittedAt__c.field-meta.xml
<CustomField>
    <fullName>SubmittedAt__c</fullName>
    <label>Submitted At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IF(AND(Delivery_Type__c &gt; 0, Quantity__c &gt; 3), &quot;Large Non-Standard&quot;, 
IF(AND(Delivery_Type__c &gt; 0, Quantity__c &lt; 3), &quot;Small Non-Standard&quot;, &quot;Standard&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minerva Road</fullName>
            </value>
            <value>
                <fullName>Camley Street</fullName>
            </value>
            <value>
                <fullName>Hoxton</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Waterloo Hub</fullName>
            </value>
            <value>
                <fullName>Harriet Walk</fullName>
            </value>
            <value>
                <fullName>Oldbury</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
                <isActive>false</isActive>
                <label>Birmingham</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/EndDepot__c.field-meta.xml
<CustomField>
    <fullName>EndDepot__c</fullName>
    <label>End Depot</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/StartDepot__c.field-meta.xml
<CustomField>
    <fullName>StartDepot__c</fullName>
    <label>Start Depot</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Collection - Support</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery (Bike)</fullName>
            </value>
            <value>
                <fullName>In-Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CollectionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Part Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Missed By Driver</fullName>
    </customValue>
    <masterLabel>Collection Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CollectionType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Extra</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
        <default>true</default>
        <label>Normal</label>
    </customValue>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CollectionLocationRest.cls
@RestResource(urlMapping='/Locations/*')
global without sharing class CollectionLocationRest {

	@HttpGet
	global static void get() {
		String locationIds = RestContext.request.params?.get('id');
		if (String.isBlank(locationIds)) {
			getAll();
		} else {
			getById(locationIds.split(','));
		}
	}

	@HttpPatch
	global static void submit() {
		Request request = (Request)JSON.deserialize(RestContext.request.requestBody.toString(), Request.class);

		DateTime now = System.now();
		List<DispatchLocation__c> dispatchLocations = new List<DispatchLocation__c>();
		for (Id dispatchLocationId : request.locations) {
			dispatchLocations.add(new DispatchLocation__c(Id = dispatchLocationId, Status__c = request.status,
				SubmittedFrom__Longitude__s = request.longitude, SubmittedFrom__Latitude__s = request.latitude, SubmittedAt__c = now));
		}
		UPDATE dispatchLocations;

		getAll();
	}

	private static void getAll() {
		String requestURI = RestContext.request.requestURI;
		String dispatchId = requestURI.substring(requestURI.lastIndexOf('/') + 1);

		List<DispatchLocation__c> dispatchLocations = [SELECT SequenceNumber__c, Status__c, Type__c, IsBinCollection__c, IsInternalCollection__c, Time__c,
			Location__r.Name, Location__r.CollectionPriority__c, Location__r.Comments_c__c,
			Location__r.BillingLatitude, Location__r.BillingLongitude, Location__r.BillingStreet, Location__r.BillingCity, Location__r.BillingPostalCode, Location__r.BillingCountry,
			(SELECT Supplier_Product_Name__c, Is_bin_collection__c, Collection_Quantity__c FROM CollectionWaypoints__r)
			FROM DispatchLocation__c WHERE Dispatch__c = :dispatchId AND Location__r.IsLive__c = true
			ORDER BY SequenceNumber__c, Time__c, Location__c];

		Map<Decimal, List<DispatchLocation__c>> locationBySequenceMap = new Map<Decimal, List<DispatchLocation__c>>();
		for (DispatchLocation__c dispatchLocation : dispatchLocations) {
			if (locationBySequenceMap.containsKey(dispatchLocation.SequenceNumber__c)) {
				locationBySequenceMap.get(dispatchLocation.SequenceNumber__c).add(dispatchLocation);
			} else {
				locationBySequenceMap.put(dispatchLocation.SequenceNumber__c, new List<DispatchLocation__c>{dispatchLocation});
			}
		}

		List<Decimal> sequenceNumbers = new List<Decimal>(locationBySequenceMap.keySet());
		sequenceNumbers.sort();

		Boolean hasNullSequence = !sequenceNumbers.isEmpty() && sequenceNumbers[0] == null;
		if (hasNullSequence) {
			sequenceNumbers.remove(0);
		}

		List<CollectionLocation> locations = new List<CollectionLocation>();
		for (Decimal sequenceNumber : sequenceNumbers) {
			dispatchLocations = locationBySequenceMap.get(sequenceNumber);
			locations.add(new CollectionLocation(dispatchLocations));
		}

		List<CollectionLocation> additionalLocations = new List<CollectionLocation>();
		if (hasNullSequence) {
			for (DispatchLocation__c dispatchLocation : locationBySequenceMap.get(null)) {
				additionalLocations.add(new CollectionLocation(dispatchLocation));
			}
		}

		DailyDispatch__c dispatch = [SELECT RoundId__r.StartDepot__r.Name, RoundId__r.StartDepot__r.Coordinates__Longitude__s, RoundId__r.StartDepot__r.Coordinates__Latitude__s,
			RoundId__r.EndDepot__r.Name, RoundId__r.EndDepot__r.Coordinates__Longitude__s, RoundId__r.EndDepot__r.Coordinates__Latitude__s
			FROM DailyDispatch__c WHERE Id = :dispatchId];
		List<Depot> depots = new List<Depot>{new Depot(dispatch.RoundId__r.StartDepot__r, true), new Depot(dispatch.RoundId__r.EndDepot__r, false)};

		RestResponse response = RestContext.response;
		response.addHeader('Content-Type', 'application/json');
		response.responseBody = Blob.valueOf(JSON.serialize(new Map<String, Object>{'locations' => locations, 'additionalLocations' => additionalLocations, 'depots' => depots}));
	}

	private static void getById(List<String> dispatchLocationIds) {
		List<DispatchLocation__c> dispatchLocations = [SELECT SequenceNumber__c, Status__c, Type__c, IsBinCollection__c, IsInternalCollection__c, Time__c,
			Location__r.Name, Location__r.CollectionPriority__c, Location__r.Comments_c__c,
			Location__r.BillingLatitude, Location__r.BillingLongitude, Location__r.BillingStreet, Location__r.BillingCity, Location__r.BillingPostalCode, Location__r.BillingCountry,
			(SELECT Supplier_Product_Name__c, Is_bin_collection__c, Collection_Quantity__c FROM CollectionWaypoints__r)
			FROM DispatchLocation__c WHERE Id = :dispatchLocationIds
			ORDER BY SequenceNumber__c, Time__c, Location__c];

		List<CollectionLocation> locations = new List<CollectionLocation>();
		for (DispatchLocation__c dispatchLocation : dispatchLocations) {
			locations.add(new CollectionLocation(dispatchLocation));
		}

		RestResponse response = RestContext.response;
		response.addHeader('Content-Type', 'application/json');
		response.responseBody = Blob.valueOf(JSON.serialize(locations));
	}

	@TestVisible
	private class Request {
		@TestVisible private List<String> locations;
		@TestVisible private String status;
		@TestVisible private Decimal longitude;
		@TestVisible private Decimal latitude;
	}

	private class Depot {
		private transient Depot__c depot;
		private transient Boolean isStart;

		private Depot(Depot__c depot, Boolean isStart) {
			this.depot = depot;
			this.isStart = isStart;
		}

		private String name { get { return depot.Name; } }
		private String type { get { return isStart ? 'Start' : 'End'; } }
		private Decimal longitude { get { return depot.Coordinates__Longitude__s; } }
		private Decimal latitude { get { return depot.Coordinates__Latitude__s; } }
	}
}