force-app/main/default/objects/Account/fields/CollectionPriority__c.field-meta.xml
<CustomField>
    <fullName>CollectionPriority__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, &apos;&apos;, IF(OR(VIP_Customer__c, On_Priority__c, Complex_Collection__c), &apos;VIP&apos;, IF(TODAY() &lt;= (Enqix_Start_Date__c + 30), &apos;New&apos;, &apos;Normal&apos;)))</formula>
    <label>Collection Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Comments_c__c.field-meta.xml
<CustomField>
    <fullName>Comments_c__c</fullName>
    <label>Collection notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <label>Collection Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Unachievable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_product_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_product_name__c</fullName>
    <formula>Supplier_Product__r.Product_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier product name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsInternalCollection__c.field-meta.xml
<CustomField>
    <fullName>IsInternalCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CollectionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Part Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Missed By Driver</fullName>
    </customValue>
    <masterLabel>Collection Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CollectionType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Extra</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
        <default>true</default>
        <label>Normal</label>
    </customValue>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CollectionLocation.cls
public without sharing class CollectionLocation {

	private transient DispatchLocation__c dispatchLocation;
	private List<Item> items = new List<Item>();
	private Set<Id> clusteredLocations = new Set<Id>();

	public CollectionLocation(DispatchLocation__c dispatchLocation) {
		this.dispatchLocation = dispatchLocation;

		for (Collection_Waypoints__c waypoint : dispatchLocation.CollectionWaypoints__r) {
			items.add(new Item(waypoint));
		}
	}

	public CollectionLocation(List<DispatchLocation__c> dispatchLocations) {
		this(dispatchLocations[0]);

		if (dispatchLocations.size() < 2) {
			return;
		}

		for (DispatchLocation__c dispatchLocation : dispatchLocations) {
			clusteredLocations.add(dispatchLocation.Id);
		}
	}

	private Id id { get { return dispatchLocation.Id; } }
	private String name { get { return dispatchLocation.Location__r.Name; } }
	private Integer sortOrder { get { return Convert.toInteger(dispatchLocation.SequenceNumber__c); } }
	private Decimal latitude { get { return dispatchLocation.Location__r.BillingLatitude; } }
	private Decimal longitude { get { return dispatchLocation.Location__r.BillingLongitude; } }
	private String street { get { return dispatchLocation.Location__r.BillingStreet; } }
	private String city { get { return dispatchLocation.Location__r.BillingCity; } }
	private String postcode { get { return dispatchLocation.Location__r.BillingPostalCode; } }
	private String country { get { return dispatchLocation.Location__r.BillingCountry; } }
	private String status { get { return dispatchLocation.Status__c; } }
	private String priority { get { return dispatchLocation.Location__r.CollectionPriority__c; } }
	private String type { get { return dispatchLocation.Type__c; } }
	private Boolean isCluster { get { return clusteredLocations.size() > 1; } }
	private Boolean isBinCollection { get { return dispatchLocation.IsBinCollection__c; } }
	private Boolean isInternalCollection { get { return dispatchLocation.IsInternalCollection__c; } }
	private Boolean isSubmissionGeofenced { get { return isBinCollection || type == 'Missed' || type == 'Extra' || priority == 'VIP' || priority == 'New'; } }
	private String scheduleTime { get { return Convert.toHhMm(dispatchLocation.Time__c); } }
	private String notes { get { return dispatchLocation.Location__r.Comments_c__c; } }

	private class Item {
		private transient Collection_Waypoints__c waypoint;

		private Item(Collection_Waypoints__c waypoint) {
			this.waypoint = waypoint;
		}

		private Id id { get { return waypoint.Id; } }
		private String name { get { return waypoint.Supplier_Product_Name__c; } }
		private Boolean isBin { get { return waypoint.Is_bin_collection__c; } }
		private Integer quantity { get { return Convert.toInteger(waypoint.Collection_Quantity__c); } }
	}
}