force-app/main/default/objects/Account/fields/CollectionPriority__c.field-meta.xml
<CustomField>
    <fullName>CollectionPriority__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, &apos;&apos;, IF(OR(VIP_Customer__c, On_Priority__c, Complex_Collection__c), &apos;VIP&apos;, IF(TODAY() &lt;= (Enqix_Start_Date__c + 30), &apos;New&apos;, &apos;Normal&apos;)))</formula>
    <label>Collection Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <filterItems>
            <field>Account.Enqix_Dead_Live__c</field>
            <operation>equals</operation>
            <value>LIVE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/Round_Notes__c.field-meta.xml
<CustomField>
    <fullName>Round_Notes__c</fullName>
    <formula>RoundId__r.Round_Notes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Round Notes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>DailyRounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actual Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Daily Dispatches</relationshipLabel>
    <relationshipName>Daily_Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/WasKeyFolderTaken__c.field-meta.xml
<CustomField>
    <fullName>WasKeyFolderTaken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Folder Taken?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/Missed_Collection__c.object-meta.xml
<CustomObject>
    <label>Missed Collection</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Missed Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missed Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Missed_Collection__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/Daily_Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Daily_Dispatch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Missed_Collection__c/fields/RoundId__c.field-meta.xml
<CustomField>
    <fullName>RoundId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Missed Collections</relationshipLabel>
    <relationshipName>Missed_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Round_Notes__c.field-meta.xml
<CustomField>
    <fullName>Round_Notes__c</fullName>
    <description>Free text notes for the round. Pulls into Daily Dispatch.</description>
    <label>Round Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/Tip_1__c.field-meta.xml
<CustomField>
    <fullName>Tip_1__c</fullName>
    <label>Tip 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tips</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/Tip_2__c.field-meta.xml
<CustomField>
    <fullName>Tip_2__c</fullName>
    <label>Tip 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tips</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <formula>TEXT(Default_Vehicle__r.Body__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/CollectionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Part Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Missed By Driver</fullName>
    </customValue>
    <masterLabel>Collection Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tips.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avon Metals</fullName>
    </customValue>
    <customValue>
        <fullName>Balcan Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Berry BPI</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Barking</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Edmonton</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Oldbury</fullName>
    </customValue>
    <customValue>
        <fullName>Biffa Wembley</fullName>
    </customValue>
    <customValue>
        <fullName>BioBean</fullName>
    </customValue>
    <customValue>
        <fullName>Bio Collectors</fullName>
    </customValue>
    <customValue>
        <fullName>BioGen</fullName>
    </customValue>
    <customValue>
        <fullName>Biomass UK</fullName>
    </customValue>
    <customValue>
        <fullName>Bywaters</fullName>
    </customValue>
    <customValue>
        <fullName>Cater Oils</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Barking</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Belvedere</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Cringle Dock</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Northumberland Warf</fullName>
        <label>Cory Northumberland Wharf</label>
    </customValue>
    <customValue>
        <fullName>Cory Pensbury Place</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Smugglers Way</fullName>
    </customValue>
    <customValue>
        <fullName>Cory Wallbrook Wharf</fullName>
    </customValue>
    <customValue>
        <fullName>CTR Group</fullName>
    </customValue>
    <customValue>
        <fullName>D.S Smith</fullName>
    </customValue>
    <customValue>
        <fullName>Edwards</fullName>
    </customValue>
    <customValue>
        <fullName>Endurmeta</fullName>
    </customValue>
    <customValue>
        <fullName>Enval</fullName>
    </customValue>
    <customValue>
        <fullName>ENVAR</fullName>
    </customValue>
    <customValue>
        <fullName>European Metal Recycling</fullName>
    </customValue>
    <customValue>
        <fullName>G &amp; P Batteries</fullName>
    </customValue>
    <customValue>
        <fullName>Go 4 Greener</fullName>
    </customValue>
    <customValue>
        <fullName>Green recycling</fullName>
    </customValue>
    <masterLabel>Tips</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DispatchFormRest.cls
@RestResource(urlMapping='/DispatchForm/*')
global without sharing class DispatchFormRest {

	@HttpGet
	global static void get() {
		String requestURI = RestContext.request.requestURI;
		String dispatchId = requestURI.substring(requestURI.lastIndexOf('/') + 1);

		DailyDispatch__c dispatch = [SELECT Status__c, RoundId__c, WasKeyFolderTaken__c, CreatedDate,
			RoundId__r.Tip_1__c, RoundId__r.Tip_2__c, RoundId__r.Vehicle_Type__c, RoundId__r.Round_Notes__c
			FROM DailyDispatch__c WHERE Id = :dispatchId];
		List<Vehicle__c> vehicles = [SELECT Name FROM Vehicle__c WHERE Active__c = true ORDER BY Name];

		Response dipatchResponse = new Response(dispatch, vehicles);
		RestResponse response = RestContext.response;
		response.addHeader('Content-Type', 'application/json');
		response.responseBody = Blob.valueOf(JSON.serialize(dipatchResponse));
	}

	private static List<Account> getMissedLocations(DailyDispatch__c dispatch) {
		Id previousDispatchId;
		try {
			previousDispatchId = [SELECT Id FROM DailyDispatch__c WHERE RoundId__c = :dispatch.RoundId__c AND Id != :dispatch.Id AND CreatedDate < :dispatch.CreatedDate ORDER BY CreatedDate DESC LIMIT 1].Id;
		} catch (QueryException e) {
			return new List<Account>();
		}

		List<Missed_Collection__c> missedCollections = [SELECT Case__r.Location__c FROM Missed_Collection__c WHERE Daily_Dispatch__c = :previousDispatchId];
		Set<Id> locationIds = new Set<Id>();
		for (Missed_Collection__c missedCollection : missedCollections) {
			locationIds.add(missedCollection.Case__r.Location__c);
		}
		return [SELECT Name, BillingPostalCode, CollectionPriority__c FROM Account WHERE Id IN :locationIds];
	}

	private static List<Account> getReminderLocations(DailyDispatch__c dispatch) {
		return [SELECT CollectionPriority__c FROM Account WHERE Id IN
			(SELECT Location__c FROM DispatchLocation__c WHERE Dispatch__c = :dispatch.Id AND Location__r.CollectionPriority__c IN ('VIP', 'New'))];
	}

	private class Response {
		private transient DailyDispatch__c dispatch;

		private Boolean isStarted { get { return dispatch.Status__c != 'Created'; } }
		private Boolean isComplete { get { return dispatch.Status__c == 'Complete'; } }
		private Boolean wasKeyFolderTaken { get { return dispatch.WasKeyFolderTaken__c; } }
		private String tip1 { get { return dispatch.RoundId__r.Tip_1__c; } }
		private String tip2 { get { return dispatch.RoundId__r.Tip_2__c; } }
		private String vehicleType { get { return dispatch.RoundId__r.Vehicle_Type__c; } }
		private String notes { get { return dispatch.RoundId__r.Round_Notes__c; } }
		private List<Vehicle> vehicles = new List<Vehicle>();
		private List<Reminder> missedLocations = new List<Reminder>();
		private Integer countLocationsVip = 0;
		private Integer countLocationsNew = 0;

		private Response(DailyDispatch__c dispatch, List<Vehicle__c> vehicles) {
			this.dispatch = dispatch;

			for (Vehicle__c vehicle : vehicles) {
				this.vehicles.add(new Vehicle(vehicle));
			}

			for (Account location : getMissedLocations(dispatch)) {
				missedLocations.add(new Reminder(location));
			}
			for (Account location : getReminderLocations(dispatch)) {
				switch on location.CollectionPriority__c {
					when 'VIP' {
						countLocationsVip++;
					}
					when 'New' {
						countLocationsNew++;
					}
				}
			}
		}
	}

	private class Vehicle {
		private transient Vehicle__c vehicle;

		private Id id { get { return vehicle.Id; } }
		private String name { get { return vehicle.Name; } }

		private Vehicle(Vehicle__c vehicle) {
			this.vehicle = vehicle;
		}
	}

	private class Reminder {
		private transient Account location;

		private String locationName { get { return location.Name; } }
		private String postcode { get { return location.BillingPostalCode; } }
		private String type { get { return location.CollectionPriority__c; } }

		private Reminder(Account location) {
			this.location = location;
		}
	}
}