force-app/main/default/objects/Account/fields/CollectionPriority__c.field-meta.xml
<CustomField>
    <fullName>CollectionPriority__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, &apos;&apos;, IF(OR(VIP_Customer__c, On_Priority__c, Complex_Collection__c), &apos;VIP&apos;, IF(TODAY() &lt;= (Enqix_Start_Date__c + 30), &apos;New&apos;, &apos;Normal&apos;)))</formula>
    <label>Collection Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StreetSegmentID__c.field-meta.xml
<CustomField>
    <fullName>StreetSegmentID__c</fullName>
    <label>StreetSegmentID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingJobId__c.field-meta.xml
<CustomField>
    <fullName>RoutingJobId__c</fullName>
    <externalId>true</externalId>
    <label>Routing Job Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingResponse__c.field-meta.xml
<CustomField>
    <fullName>RoutingResponse__c</fullName>
    <label>Routing Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingStatus__c.field-meta.xml
<CustomField>
    <fullName>RoutingStatus__c</fullName>
    <label>Routing Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RoutingStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/fields/RoutingSummary__c.field-meta.xml
<CustomField>
    <fullName>RoutingSummary__c</fullName>
    <label>Routing Summary</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/IsInternalCollection__c.field-meta.xml
<CustomField>
    <fullName>IsInternalCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumberRaaS__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumberRaaS__c</fullName>
    <label>Sequence Number (RaaS)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CollectionType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Extra</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
        <default>true</default>
        <label>Normal</label>
    </customValue>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RoutingStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Stuck</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <description>Status of job requested to RaaS.</description>
    <masterLabel>Routing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoutingGetCollectionResult.cls
public without sharing class RoutingGetCollectionResult extends RoutingGetResult  {

	public RoutingGetCollectionResult(Integer jobId, Integer pollCount) {
		super(jobId, pollCount);
	}

	protected override void enqueue() {
		updateJob(new DailyDispatch__c());

		if (Test.isRunningTest()) {return;} else {System.enqueueJob(new RoutingGetCollectionResultQueueable(jobId, ++pollCount), 1);}
	}

	protected override void updateJobError(String status, String message) {
		updateJob(new DailyDispatch__c(RoutingStatus__c = status, RoutingResponse__c = message));
	}

	protected override void processResult(RoutingResponse routingResponse) {
		Map<Integer, DispatchLocation__c> dispatchLocationMap = new Map<Integer, DispatchLocation__c>();
		List<DispatchLocation__c> dispatchLocations = [SELECT Name, SequenceNumber__c, Type__c, IsInternalCollection__c, IsBinCollection__c,
			Location__c, Location__r.StreetSegmentId__c, Location__r.CollectionPriority__c
			FROM DispatchLocation__c WHERE Dispatch__r.RoutingJobId__c = :routingResponse.jobId AND Location__r.IsLive__c = true];
		for (DispatchLocation__c dispatchLocation : dispatchLocations) {
			dispatchLocationMap.put(Convert.toInteger(dispatchLocation.Name), dispatchLocation);
		}

		DispatchLocation__c dispatchLocation;
		for (RoutingResponse.ServiceLocation location : routingResponse.serviceLocations) {
			dispatchLocation = dispatchLocationMap.get(location.recordID);
			if (dispatchLocation == null) {continue;}	// Dead location
			dispatchLocation.SequenceNumberRaaS__c = dispatchLocation.SequenceNumber__c = location.sequence;
		}
		resequence(dispatchLocationMap.values());

		UPDATE dispatchLocationMap.values();
		updateJob(new DailyDispatch__c(RoutingStatus__c = 'Completed', RoutingSummary__c = JSON.serializePretty(routingResponse.routeSummary)));
	}

	protected override String key(sObject record) {
		DispatchLocation__c dispatchLocation = (DispatchLocation__c)record;
		return isCluster(dispatchLocation) ? dispatchLocation.Location__r.StreetSegmentId__c : dispatchLocation.Location__c;
	}

	private Boolean isCluster(DispatchLocation__c dispatchLocation) {
		return String.isNotBlank(dispatchLocation.Location__r.StreetSegmentId__c) &&
			dispatchLocation.Location__r.CollectionPriority__c == 'Normal' && dispatchLocation.Type__c == 'Normal' &&
			!dispatchLocation.IsInternalCollection__c && !dispatchLocation.IsBinCollection__c;
	}

	private void updateJob(DailyDispatch__c dispatch) {
		dispatch.RoutingJobId__c = jobId;
		dispatch.RoutingPollCount__c = pollCount;
		UPSERT dispatch RoutingJobId__c;
	}
}