force-app/main/default/objects/Account/fields/Council__c.field-meta.xml
<CustomField>
    <fullName>Council__c</fullName>
    <label>Council</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barking &amp; Dagenham</fullName>
            </value>
            <value>
                <fullName>Barnet</fullName>
            </value>
            <value>
                <fullName>Bexley</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Brent</fullName>
            </value>
            <value>
                <fullName>Bromley</fullName>
            </value>
            <value>
                <fullName>Camden</fullName>
            </value>
            <value>
                <fullName>City of London</fullName>
            </value>
            <value>
                <fullName>Croydon</fullName>
            </value>
            <value>
                <fullName>Ealing</fullName>
            </value>
            <value>
                <fullName>Enfield</fullName>
            </value>
            <value>
                <fullName>Greenwich</fullName>
            </value>
            <value>
                <fullName>Hackney</fullName>
            </value>
            <value>
                <fullName>hammersmith and fulham</fullName>
                <label>Hammersmith and Fulham</label>
            </value>
            <value>
                <fullName>Haringey</fullName>
            </value>
            <value>
                <fullName>Harrow</fullName>
            </value>
            <value>
                <fullName>Havering</fullName>
            </value>
            <value>
                <fullName>Hillingdon</fullName>
            </value>
            <value>
                <fullName>Hounslow</fullName>
            </value>
            <value>
                <fullName>Islington</fullName>
            </value>
            <value>
                <fullName>Kensington and Chelsea</fullName>
            </value>
            <value>
                <fullName>Kingston upon Thames</fullName>
            </value>
            <value>
                <fullName>Lambeth</fullName>
            </value>
            <value>
                <fullName>Lewisham</fullName>
            </value>
            <value>
                <fullName>Merton</fullName>
            </value>
            <value>
                <fullName>More than one</fullName>
            </value>
            <value>
                <fullName>Newham</fullName>
            </value>
            <value>
                <fullName>Redbridge</fullName>
            </value>
            <value>
                <fullName>Richmond upon Thames</fullName>
            </value>
            <value>
                <fullName>Solihull</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Case/fields/Council__c.field-meta.xml
<CustomField>
    <fullName>Council__c</fullName>
    <label>Council</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <businessProcess>Email</businessProcess>
    <label>Master Case Record Type</label>
</RecordType>

force-app/main/default/objects/Contact/fields/FMCP_Token__c.field-meta.xml
<CustomField>
    <fullName>FMCP_Token__c</fullName>
    <label>FMCP Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Unsubscribed__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unsubscribed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/Sendgrid_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sendgrid Setting</label>
</CustomObject>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Account_Contact_Sendgrid_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact_Sendgrid_Id__c</fullName>
    <label>Account Contact Sendgrid Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Email_Activity_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Email_Activity_EndPoint__c</fullName>
    <description>Sendgrid - Email Activity endpoint</description>
    <label>Email Activity EndPoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Integration_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_API_Key__c</fullName>
    <label>Integration API Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Location_Contact_Sendgrid_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Contact_Sendgrid_Id__c</fullName>
    <label>Location Contact Sendgrid Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Sendgrid_From_Email__c.field-meta.xml
<CustomField>
    <fullName>Sendgrid_From_Email__c</fullName>
    <label>Sendgrid From Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Sendgrid_From_Name__c.field-meta.xml
<CustomField>
    <fullName>Sendgrid_From_Name__c</fullName>
    <label>Sendgrid From Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Sendgrid_ReplyTo_Email__c.field-meta.xml
<CustomField>
    <fullName>Sendgrid_ReplyTo_Email__c</fullName>
    <label>Sendgrid ReplyTo Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/Sendgrid_ReplyTo_Name__c.field-meta.xml
<CustomField>
    <fullName>Sendgrid_ReplyTo_Name__c</fullName>
    <label>Sendgrid ReplyTo Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sendgrid_Setting__c/fields/SyncToSendgrid__c.field-meta.xml
<CustomField>
    <fullName>SyncToSendgrid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SyncToSendgrid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnitTest.cls
//Test Class: UnitTest_Test
public class UnitTest
{
    public static Account testAccount()
    {
        Account acc = new Account();
        acc.Name = 'test Account';
        acc.Enqix_Dead_Live__c = 'Live';
        acc.Council__c = 'Birmingham';
        return acc;
    }
    
    public static Account testLocationTypeAccount()
    {
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND IsActive = true and Name= 'Location' LIMIT 1];         
        //Id RecordTypeIdlocation = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'test Account';
        acc.RecordTypeId = rt.Id;
        acc.Council__c = 'Birmingham';
        acc.Enqix_Dead_Live__c = 'Live';
        return acc;
    }
    
    public static Account testAccountTypeAccount()
    {
        //Id RecordTypeIdlocation = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND IsActive = true and Name= 'Account' LIMIT 1];  
        Account acc = new Account();
        acc.Name = 'test Account';
        acc.RecordTypeId = rt.Id;
        acc.Enqix_Dead_Live__c = 'Live';
        acc.Council__c = 'Birmingham';
        return acc;
    }

    public static contact testcontact(Id AccountId)
    {
        Contact con = new Contact();
        con.AccountId = AccountId;
        con.Unsubscribed__c = false;
        con.FirstName = 'test';
        con.LastName = 'test';
        con.Email = 'test@de.com';
        con.FMCP_Token__c = 'test123';
        return con;
    }
    
    public static AccountContactRelation testAccConRelation(Id AccountId, Id ContactId, string Role)
    {
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.AccountId = AccountId;
        acr.ContactId = ContactId; 
        acr.Roles = Role;
        return acr;
    }
    
    public static Case testcase(Id AccountId, Id ContactId)
    {
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND IsActive = true LIMIT 1];  
        Case reccase = new Case();
        reccase.AccountId = AccountId;
        reccase.ContactId = ContactId;
        reccase.RecordTypeId = rt.Id;
        return reccase;
    }
    
    public static Sendgrid_Setting__c testsgsetting()
    {
        TestDataHelper.insertSendGridSetting();
        Sendgrid_Setting__c objsg = new Sendgrid_Setting__c();
        objsg.Name = 'IntegrationId';
        objsg.Email_Activity_EndPoint__c = 'https://api.sendgrid.com/v3/messages?limit=10';
        objsg.Integration_API_Key__c = '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';
        objsg.Location_Contact_Sendgrid_Id__c = 'bff14abf-91c6-44c9-b3d5-d2293566f3a3';
        objsg.Account_Contact_Sendgrid_Id__c = 'bff14abf-91c6-44c9-b3d5-d2293566f3a3';
        objsg.SyncToSendgrid__c = true;
        objsg.Sendgrid_From_Email__c = 'joe.allen@test.com';
        objsg.Sendgrid_From_Name__c = 'joe Allen';
        objsg.Sendgrid_ReplyTo_Email__c = 'joe.allen@test.com';
        objsg.Sendgrid_ReplyTo_Name__c = 'joe Allen';
        return objsg;
    }  
}