force-app/main/default/objects/Account/fields/CP_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>CP_Account_Code__c</fullName>
    <externalId>true</externalId>
    <label>CP Account Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_authorised__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Debit authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Authorised_Date__c</fullName>
    <label>Direct Debit Authorised Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Payment_Method__c</fullName>
    <label>Enqix Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account_Number__c</fullName>
    <label>Payment Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Sort_Code__c</fullName>
    <label>Payment Sort Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Overall Account Contact</fullName>
            </value>
            <value>
                <fullName>Finance Contact</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Environmental Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/DaysOutstanding__c.field-meta.xml
<CustomField>
    <fullName>DaysOutstanding__c</fullName>
    <formula>IF( AmountOutstanding__c &gt; 0, TODAY()- Payment_Due_Date__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysOutstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OrderLookUp__c.field-meta.xml
<CustomField>
    <fullName>OrderLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLookUp</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <formula>Invoiced_Date__c  + VALUE(TEXT(Account__r.CreditDays__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/ToPublish__c.field-meta.xml
<CustomField>
    <fullName>ToPublish__c</fullName>
    <formula>IF(AND(Salesforce__c = False, DATEVALUE(CreatedDate) &lt; DATE(2019,03,01)), True, 
IF(AND(Salesforce__c = True, DATEVALUE(CreatedDate) &gt;= DATE(2019,03,01)), True, False))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ToPublish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DirectDebitControllerTest.cls
@isTest
private class DirectDebitControllerTest {
    
    @testSetup
    static void setup() {
        Id parentRecord = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Account novaConta = new Account(
			Name = 'TESTE Account',
			Enqix_Payment_Method__c = 'Direct Debit',
            Payment_Account_Number__c = '123',
            Payment_Sort_Code__c = '12345678',
            CP_Account_Code__c = '12345678',
            Enqix_Id__c = '12345',
            Direct_Debit_authorised__c = true,
            recordTypeId = parentRecord,
            Direct_Debit_Authorised_Date__c = Date.newInstance(2019, 02, 01)
		);
        insert novaConta;
        Contact newCC = new Contact(
            FirstName = 'Test',
        	LastName = 'Nuno',
            AccountId = novaConta.Id,
            Email = 'test@hotmail.com',
            Contact_Role__c = 'Service Contact'
        );
        insert newCC;
        Account novaConta2 = new Account(
			Name = 'TESTE Account2',
			Enqix_Payment_Method__c = 'Direct Debit',
            Payment_Account_Number__c = '1234',
            Payment_Sort_Code__c = '12345679',
            Direct_Debit_authorised__c = true,
            recordTypeId = parentRecord,
            Direct_Debit_Authorised_Date__c = Date.newInstance(2019, 02, 01)
		);
		//insert novaConta2;
        system.debug('NOVA INVOICE' + novaConta);
        
        Invoice_Header__c header = new Invoice_Header__c(
			Name = 'TESTE header',
			Account__c = novaConta.Id,
			Salesforce__c = true,
            InvoiceFrequency__c = 'Per order',
            CreatedDate__c = Date.newInstance(2019, 02, 01),
            Query__c = False
		);
		INSERT header;
        header.AmountOutstanding__c = 2000;
        UPDATE header;

        Invoice_Header__c header2 = new Invoice_Header__c(
			Name = 'TESTE header2',
			Account__c = novaConta.Id,
            Salesforce__c = true,
			InvoiceFrequency__c = 'Per order',
            CreatedDate__c = Date.newInstance(2019, 02, 01),
            Query__c = False
		);
		INSERT header2;
        header2.AmountOutstanding__c = 2000;
        UPDATE header;

        for (Account a : [SELECT Name, Payment_Account_Number__c, Payment_Sort_Code__c, (SELECT Id, AmountOutstanding__c, ToPublish__c, Query__c, DaysOutstanding__c, Payment_Due_Date__c FROM Invoice_Headers__r) FROM Account WHERE Enqix_Payment_Method__c = 'Direct Debit']) {
            for (Invoice_Header__c h : a.Invoice_Headers__r) {
                system.debug('AmountOutstanding: '+h.AmountOutstanding__c+ ' -- ToPublish: '+h.ToPublish__c+' -- Overdue Days: '+h.DaysOutstanding__c+' -- Payment Due Date: '+h.Payment_Due_Date__c);
            }
        }
        
        Document document = new Document(Name = 'FirstMileLogo', DeveloperName = 'FirstMileLogo', Body = Blob.valueOf('Test'), folderId = UserInfo.getUserId());
        INSERT document;
    }
    
  	@isTest
    static void TestfillTable() {
        DirectDebitController.fillTable();
    }
    
    @isTest
    static void TestcreateBankStatements() {
        DirectDebitController.createBankStatements();
    }
}