force-app/main/default/objects/Account/fields/dd_account_number__c.field-meta.xml
<CustomField>
    <fullName>dd_account_number__c</fullName>
    <label>dd_account_number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dd_sort_code__c.field-meta.xml
<CustomField>
    <fullName>dd_sort_code__c</fullName>
    <label>dd_sort_code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_authorised__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Debit authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Authorised_Date__c</fullName>
    <label>Direct Debit Authorised Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_Details_Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Details_Entry_Date__c</fullName>
    <label>Direct Debit Details Entry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Payment_Method__c</fullName>
    <label>Enqix Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/classes/DirectDebitAuthController.cls
Public with sharing class DirectDebitAuthController {

    Public class authorizedAccount {
        @AuraEnabled
        public string accountName{
            get;
            set;
        }
        @AuraEnabled
        public string company {
            get;
            set;
        }
        @AuraEnabled
        public string sortCode {
            get;
            set;
        }
        @AuraEnabled
        public string accountNumber{
            get;
            set;
        }
        @AuraEnabled
        public string code{
            get;
            set;
        }
        @AuraEnabled
        public dateTime DDEntryDate{
            get;
            set;
        }
        @AuraEnabled
        public boolean DDAuth{
            get;
            set;
        }


    public authorizedAccount(string accountName, string company, String sortCode, string accountNumber, String code, dateTime DDEntryDate, boolean DDAuth) {

            this.accountName = accountName;
			this.company = company;            
			this.sortCode = sortCode;
            this.accountNumber = accountNumber;
            this.code = code;
            this.DDEntryDate = DDEntryDate;
            this.DDAuth = DDAuth;
    }
    }

    @AuraEnabled
	public static List<authorizedAccount> getAuthorizedAccounts() {
        List<authorizedAccount> accounts = new List<authorizedAccount>();
        List < Account > authorizedAccounts = [SELECT Name, dd_account_number__c, Direct_Debit_Details_Entry_Date__c, Direct_Debit_Authorised_Date__c, Direct_Debit_authorised__c, dd_sort_code__c from Account where Enqix_Payment_Method__c = 'Direct Debit' AND Direct_Debit_Details_Entry_Date__c != null AND Direct_Debit_authorised__c = false order by Name];
        Integer numberOfAccounts = Database.countQuery('SELECT COUNT() FROM Account WHERE Enqix_Payment_Method__c = \'Direct Debit\' AND Direct_Debit_Details_Entry_Date__c != null AND Direct_Debit_authorised__c = false');
        system.debug(numberOfAccounts);
        for (Account a : authorizedAccounts) {
            string company = 'FirstMile';
            string code = '0N';

                authorizedAccount aa = new authorizedAccount(a.Name, company, a.dd_sort_code__c, a.dd_account_number__c, code, a.Direct_Debit_Details_Entry_Date__c, a.Direct_Debit_authorised__c);
                accounts.add(aa);
        }
        return accounts;        
   } 

   @AuraEnabled 
   public static String generateCSV(){
       DirectDebitAuthBatch ddbatch = new DirectDebitAuthBatch();
       Database.executeBatch (ddbatch, 50);
       string message = 'Direct debits Authorized will now be processed, an email will be sent when they are finished.';
       return message;
   }
}