force-app/main/default/objects/Account/fields/dd_account_number__c.field-meta.xml
<CustomField>
    <fullName>dd_account_number__c</fullName>
    <label>dd_account_number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dd_sort_code__c.field-meta.xml
<CustomField>
    <fullName>dd_sort_code__c</fullName>
    <label>dd_sort_code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_authorised__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Debit authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Authorised_Date__c</fullName>
    <label>Direct Debit Authorised Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Payment_Method__c</fullName>
    <label>Enqix Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Paid_by_DD_Before__c.field-meta.xml
<CustomField>
    <fullName>Paid_by_DD_Before__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid by DD Before</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/AllocatedAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocatedAmount__c</fullName>
    <label>AllocatedAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reference__c</fullName>
    <description>This field indicates the Customer reference details, kept as text</description>
    <label>Customer Reference</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Document_name__c.field-meta.xml
<CustomField>
    <fullName>Document_name__c</fullName>
    <description>This field will hold the original document name as a text, this will help to distinct information from different days</description>
    <label>Document Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <description>This is the entry date field, stored as a Date, for the Bank Statement</description>
    <label>Entry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/IsDirectDebit__c.field-meta.xml
<CustomField>
    <fullName>IsDirectDebit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDirectDebit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Details__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Details__c</fullName>
    <description>These are the transaction details, kept as text</description>
    <label>Transaction Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Header__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice_Header</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <businessProcess>Email</businessProcess>
    <label>Master Case Record Type</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OrderLookUp__c.field-meta.xml
<CustomField>
    <fullName>OrderLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLookUp</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <formula>Invoiced_Date__c  + VALUE(TEXT(Account__r.CreditDays__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/PaymentAllocation__c.object-meta.xml
<CustomObject>
    <label>PaymentAllocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>PaymentAllocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentAllocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentAllocation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/AllocatedAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocatedAmount__c</fullName>
    <label>AllocatedAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/BankstatementId__c.field-meta.xml
<CustomField>
    <fullName>BankstatementId__c</fullName>
    <label>Bank Statement</label>
    <referenceTo>Bank_Statement__c</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice_Header</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. - PaymentAllocation.InvoiceId__c</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Invoice_Header__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Invoice_Header__c.Query__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Invoice_Header__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Query</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/fields/IsDirectDebit__c.field-meta.xml
<CustomField>
    <fullName>IsDirectDebit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDirectDebit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DirectDebitBatch.cls
/** 
(c) 2018 Xpand IT
Developed by Xpand IT, Braga (Portugal)
@date Date of creation 11.2018 
@author Bruno Mendes 

@description 1034 - Batch job to create Bank Statements for Direct Debit functionality 

@modifications dd.mm.yyyy [XX] PT or Case number followed by short description of change 
Example: 02.04.2018 [PC] PT5703 - Added support of new Account fields 
XX.05.2019 JIRA 1578 -> Improve email to customer functionality
*/
global class DirectDebitBatch implements Database.Batchable < sObject > , Database.Stateful {
    
    global decimal amountAccount;
    global string runSucceeded;
    global String query;
    global List < AccountAmount > accounts;
    global String errors;
    global List<Bank_Statement__c> finalBankStatementList;
    global Map < AccountContactRelation, Id > financeContas;

    public class AccountAmount {
        
        public String company {
            get;
            set;
        }        
        public Id accountId {
            get;
            set;
        }
        public String accountName {
            get;
            set;
        }
        public string sortCode {
            get;
            set;
        }
        public String accountNumber {
            get;
            set;
        }
        public Decimal amount {
            get;
            set;
        }
        public String error { 
            get;
            set;
        }
        public string ddBeforeCode {
            get; 
            set;
        }
        
        public AccountAmount(string company, Id accountId, String accountName, String sortCode, String accountNumber, Decimal amount, string ddBeforeCode) {
            this.company = company;
            this.accountId = accountId;
            this.accountName = accountName;
            this.sortCode = sortCode;
            this.accountNumber = accountNumber;
            this.amount = amount;
            this.ddBeforeCode = ddBeforeCode;
        }
    }
    
    global DirectDebitBatch() {
        accounts = new List < AccountAmount > ();
        errors = '';
        finalBankStatementList = new List<Bank_Statement__c>();
        /* Bruno - JIRA 1431 -> Added Status != Query to the filter. Removed OverdueDays  */
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        query = 'SELECT Name, dd_account_number__c, dd_sort_code__c, Paid_by_DD_Before__c, (SELECT Id, AmountOutstanding__c FROM Invoice_Headers__r WHERE Payment_Due_Date__c <= TODAY AND AmountOutstanding__c != 0 AND AmountOutstanding__c != null AND Query__c = false AND Status__c != \'Query\') FROM Account WHERE Enqix_Payment_Method__c = \'Direct Debit\' AND Direct_Debit_authorised__c = true AND DAY_ONLY(Direct_Debit_Authorised_Date__c) < TODAY AND Id IN (SELECT Account__c FROM Invoice_Header__c WHERE Account__r.Enqix_Payment_Method__c = \'Direct Debit\' AND Account__r.Direct_Debit_authorised__c = true AND DAY_ONLY(Account__r.Direct_Debit_Authorised_Date__c) < TODAY AND Payment_Due_Date__c <= TODAY AND AmountOutstanding__c != 0 AND AmountOutstanding__c != null AND Query__c = false AND Status__c != \'Query\') ORDER BY Name';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> targetAccounts) {
        List < Bank_Statement__c > bankStatementsToCreate = new List < Bank_Statement__c > ();
        List < PaymentAllocation__c > paymentAllocationsToCreate = new List < PaymentAllocation__c > ();
        Map<Id, Invoice_Header__c> invoiceHeadersToUpdateMap = new Map<Id, Invoice_Header__c>();
        Map<Id, Account> accountInvoicesToBePaid = new Map<Id, Account>();
        
        for (Account a : targetAccounts) {
            string ddBeforeCode = '0';
            if(a.Paid_by_DD_Before__c == true){
                ddBeforeCode = '17';
            }else if(a.Paid_by_DD_Before__c == false){
                ddBeforeCode = '01';
            }
            
            string company = 'FirstMile';
            
            Decimal amount = 0;
            for (Invoice_Header__c i: a.Invoice_Headers__r) {
                amount += i.AmountOutstanding__c.setscale(2);
            }
            /* Bruno - Jira 1430 -> Checked if the amount is less than zero and ignored those accounts */ 
            if (amount <= 0) {
                continue;
            }

            Bank_Statement__c bs = new Bank_Statement__c();
            bs.Account__c = a.Id;
            bs.Entry_Date__c = System.today();
            bs.Transaction_Details__c = a.Name + ' Direct Debit Payment';
            bs.Transaction_Type__c = 'Direct Debit';
            bs.Document_name__c = 'Direct Debit Remittance ' + System.today();
            bs.IsDirectDebit__c = True;
            bs.Customer_Reference__c = a.Name + bs.Entry_Date__c + ' DD Remittance';
            bankStatementsToCreate.add(bs);

            AccountAmount aa = new AccountAmount(company, a.Id, a.Name, a.dd_sort_code__c, a.dd_account_number__c, amount, ddBeforeCode);
            accounts.add(aa);
            accountInvoicesToBePaid.put(a.Id, a); 
        }

        Database.SaveResult[] resultsBS = Database.insert(bankStatementsToCreate, false);
        LogRegister.createLogsUpsert(resultsBS, bankStatementsToCreate, 'DirectDebitBatch', 'Insert', 'Bank_Statement__c', 'Account__c');
        for (Integer idx = 0; idx < resultsBS.size(); idx++) {
            if (!resultsBS[idx].isSuccess()) {
                for (Database.Error err: resultsBS[idx].getErrors()) {
                    errors += 'Account where the error occurred: ' + bankStatementsToCreate[idx].Account__c + ' on Bank Statement creation --- The following error has occurred - ' + err.getStatusCode() + ': ' + err.getMessage() + ' Fields that affected this error: ' + err.getFields() + '\n';
                }
                for (Integer i = 0; i < accounts.size(); i++) {
                    if (accounts[i].accountId == bankStatementsToCreate[idx].Account__c) {
                        accounts.remove(i);
                    }
                }
            }
        }
        
        for (Bank_Statement__c bs: bankStatementsToCreate) {
            if (bs.Id == null) continue;

            Account account = accountInvoicesToBePaid.get(bs.Account__c);
            for (Invoice_Header__c i : account.Invoice_Headers__r) {
                PaymentAllocation__c pa = new PaymentAllocation__c();
                pa.InvoiceId__c = i.Id;
                pa.BankstatementId__c = bs.Id;
                pa.Account__c = bs.Account__c;
                pa.AllocatedAmount__c = i.AmountOutstanding__c.setscale(2);
                pa.IsDirectDebit__c = true;
                paymentAllocationsToCreate.add(pa);
                /* Bruno - Jira 1426 -> Process was only updating the amountoutstanding of one invoice header, which was wrong */
                Invoice_Header__c ih = new Invoice_Header__c();
                ih.Id = i.Id;
                ih.AmountOutstanding__c = 0;
                invoiceHeadersToUpdateMap.put(ih.Id, ih);
            }
        }
        
        Database.SaveResult[] resultsPA = Database.insert(paymentAllocationsToCreate, false);   
        LogRegister.createLogsUpsert(resultsPA, paymentAllocationsToCreate, 'DirectDebitBatch', 'Insert', 'PaymentAllocation__c', 'Account__c');
        for (Integer idx = 0; idx < resultsPA.size(); idx++) {
            if (!resultsPA[idx].isSuccess()) {
                for (Database.Error err: resultsPA[idx].getErrors()) {
                    errors += 'Account where the error occurred: ' + paymentAllocationsToCreate[idx].Account__c + ' on Bank Statement creation --- The following error has occurred - ' + err.getStatusCode() + ': ' + err.getMessage() + ' Fields that affected this error: ' + err.getFields() + '\n';
                    PaymentAllocation__c pa = paymentAllocationsToCreate[idx];
                    invoiceHeadersToUpdateMap.remove(pa.InvoiceId__c);
                }
                for (Integer i = 0; i < accounts.size(); i++) {
                    if (accounts[i].accountId == paymentAllocationsToCreate[idx].Account__c) {
                        accounts.remove(i);
                    }
                }
            }
        }     
        
        Database.SaveResult[] resultsIH = Database.update(invoiceHeadersToUpdateMap.values(), false);
        LogRegister.createLogsUpsert(resultsIH, invoiceHeadersToUpdateMap.values(), 'DirectDebitBatch', 'Update', 'Invoice_Header__c', 'Account__c');
        for (Integer idx = 0; idx < resultsIH.size(); idx++) {
            if (!resultsIH[idx].isSuccess()) {
                for (Database.Error err: resultsIH[idx].getErrors()) {
                    errors += 'Account where the error occurred: ' + invoiceHeadersToUpdateMap.values()[idx].Account__c + ' on Bank Statement creation --- The following error has occurred - ' + err.getStatusCode() + ': ' + err.getMessage() + ' Fields that affected this error: ' + err.getFields() + '\n';
                }
                for (Integer i = 0; i < accounts.size(); i++) {
                    if (accounts[i].accountId == invoiceHeadersToUpdateMap.values()[idx].Account__c) {
                        accounts.remove(i);
                    }
                }
            }
        }
        
        //BRUNO - added this code because if an error happens when creating a payment allocation and
        //		  a bank statement is created without any payment allocation, it should be deleted
        Set<Id> bsIds = new Set<Id>();
        for (Bank_Statement__c bs : bankStatementsToCreate) {
            bsIds.add(bs.Id);
        }
        
        List<PaymentAllocation__c> payments = [SELECT Id, BankstatementId__c FROM PaymentAllocation__c WHERE BankstatementId__c IN :bsIds];
        List<Bank_Statement__c> bsToDelete = new List<Bank_Statement__c>();
        Set<Id> existingBS = new Set<Id>();
        for (PaymentAllocation__c pa : payments) {
            existingBS.add(pa.BankstatementId__c);
        }
        List<Bank_Statement__c> bankStatementsToUpdate = new List<Bank_Statement__c>();
        for (Bank_Statement__c bs : bankStatementsToCreate) {
            if (!existingBS.contains(bs.Id) && bs.Id != null) {
                bsToDelete.add(bs);
            }
        }
        if (bsToDelete.size() > 0) {
            Database.DeleteResult[] resultsBsDel = Database.delete(bsToDelete, false);
            LogRegister.createLogs(resultsBsDel, bsToDelete, 'DirectDebitBatch', 'Delete', 'Bank_Statement__c', 'Account__c');
        }  
        
        List <Account> acc = new list <Account>();
        for (AccountAmount aAm: accounts) {           
            Account ac = new Account();            
            ac.id = aAm.accountId;            
            ac.Paid_by_DD_Before__c = true;
            acc.add(ac);
        }
        UPDATE acc;
    }
    
    global void finish(Database.BatchableContext BC) {
        Database.executebatch(new DirectDebitEmailRemittanceBatch(), 50);
        
        DateTime todaysDate = DateTime.now();
        string sTodaysDate = todaysDate.formatGMT('yyyy-MM-dd') + 'T' + todaysDate.formatGMT('HH:mm:ss.SSS') + 'Z';
        String subject = 'Direct Debit';
        String body = 'You will find attached to this email a CSV file containing the results of the Direct Debit Remittance </br>';
        if (String.isNotBlank(errors)) {
            body += errors;
        }
        String finalstr = '\n';
        String attName = 'DirectDebit_'+sTodaysDate+'.csv';
        
        // get accounts
        for (AccountAmount a: accounts) {
            string recordString = '"' + a.accountName + '","' + a.company + '","' + a.sortCode + '","' + a.accountNumber + '","' + a.amount + '","' + a.ddBeforeCode + '"\n';
            finalstr = recordString + finalstr;
        }
        String finalstrTrimmed = finalstr.trim();
        // Define the email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        
        if (accounts.size() > 0) {
            // Create the email attachment    
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setFileName(attName);
            efa.setBody(Blob.valueOf(finalstrTrimmed));

            // Attach file using setFileAttachments function
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {  efa });
        }
        
        // Set the paramaters to the email object
        email.setSubject(subject);
        email.setUseSignature(false);
        
        // Create the email Address
        email.setToAddresses(new String[] {'accounts@thefirstmile.co.uk'});
        email.setHtmlBody(body);
        
        // Sends the email
        if (!Test.isRunningTest()) {
            Messaging.SendEmailResult[] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        }
    }
}