force-app/main/default/objects/Account/fields/dd_account_number__c.field-meta.xml
<CustomField>
    <fullName>dd_account_number__c</fullName>
    <label>dd_account_number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dd_sort_code__c.field-meta.xml
<CustomField>
    <fullName>dd_sort_code__c</fullName>
    <label>dd_sort_code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_authorised__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Debit authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direct_Debit_Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Authorised_Date__c</fullName>
    <label>Direct Debit Authorised Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Payment_Method__c</fullName>
    <label>Enqix Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Paid_by_DD_Before__c.field-meta.xml
<CustomField>
    <fullName>Paid_by_DD_Before__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid by DD Before</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>InvoiceNo</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OrderLookUp__c.field-meta.xml
<CustomField>
    <fullName>OrderLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLookUp</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <formula>Invoiced_Date__c  + VALUE(TEXT(Account__r.CreditDays__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DirectDebitController.cls
global with sharing class DirectDebitController {
    
    public class AccountAmount {
        @AuraEnabled
        public String company {get;set;}
        @AuraEnabled
        public Id accountId {get; set;}
        @AuraEnabled
        public String accountName {get; set;}
        @AuraEnabled
        public string sortCode {get; set;}
        @AuraEnabled
        public String accountNumber {get; set;}
        @AuraEnabled
        public Decimal amount {get; set;} 
        @AuraEnabled
        public String decimalsPlaces {get; set;} 
        @AuraEnabled
        public List<Invoice_Header__c> invoicesToBePaid {get; set;}
        @AuraEnabled
        public decimal ddCode {get; set;}
        
        public AccountAmount(string company, Id accountId, String accountName, String sortCode, String accountNumber, Decimal amount, String decimalsPlaces, List<Invoice_Header__c> invoicesToBePaid, decimal ddCode) {
            
            this.company = company;
            this.accountId = accountId;            
            this.accountName = accountName;
            this.sortCode = sortCode;
            this.accountNumber = accountNumber;
            this.amount = amount;
            this.decimalsPlaces = decimalsPlaces;
            this.invoicesToBePaid = invoicesToBePaid;
            this.ddCode = ddCode;
            
        }
    }
    
    @AuraEnabled
    public static List<AccountAmount> fillTable() {
        List<AccountAmount> accounts = new List<AccountAmount>();
        /* Nuno - Jira 1454 -> Added a filter to the query -- Direct Debit Authorised = TRUE*/
        DateTime dt = DateTime.now() - 10;
        List < Account > accountsAndAmounts = [SELECT Name, dd_account_number__c, dd_sort_code__c, Paid_by_DD_Before__c, (SELECT Id, InvoiceNo__c, AmountOutstanding__c FROM Invoice_Headers__r WHERE AmountOutstanding__c != 0 AND AmountOutstanding__c != null AND Query__c = false AND Status__c != 'Query' AND Payment_Due_Date__c <= TODAY ) FROM Account WHERE Enqix_Payment_Method__c = 'Direct Debit' AND Direct_Debit_authorised__c = true AND Direct_Debit_Authorised_Date__c <= :dt AND Id IN(SELECT Account__c FROM Invoice_Header__c WHERE AmountOutstanding__c != 0 AND AmountOutstanding__c != null AND Query__c = false AND Status__c != 'Query' AND Payment_Due_Date__c <= TODAY) order by Name];
        Integer numberOfAccounts = Database.countQuery('SELECT COUNT() FROM Account WHERE Enqix_Payment_Method__c = \'Direct Debit\' AND Direct_Debit_authorised__c = true AND Id IN(SELECT Account__c FROM Invoice_Header__c WHERE AmountOutstanding__c != 0 AND AmountOutstanding__c != null AND Query__c = false AND Status__c != \'Query\' AND Payment_Due_Date__c <= TODAY)');
        system.debug(numberOfAccounts);
        for (Account a : accountsAndAmounts) {
            List<Invoice_Header__c> invoices = new List<Invoice_Header__c>();
            string company = 'FirstMile';
            decimal ddCode = 0;
            Decimal amount = 0; 
            String decimalsPlaces = '';
            for (Invoice_Header__c i : a.Invoice_Headers__r) {
                system.debug(i.AmountOutstanding__c);
                amount += i.AmountOutstanding__c.setscale(2);                
                invoices.add(i);               
            }
            /* Bruno - Jira 1430 -> Checked if the amount is greater than zero, as the process only wants those accounts */
            if (amount > 0) {
                AccountAmount aa = new AccountAmount(company, a.Id, a.Name, a.dd_sort_code__c, a.dd_account_number__c, amount, decimalsPlaces, invoices, ddCode);
                accounts.add(aa);
            } 
        }
        return accounts;
    }
    
    @AuraEnabled
    public static String createBankStatements() {
        Database.executebatch(new DirectDebitBatch(), 50);
        return 'Direct debits will now be processed, an email will be sent when they are finished.';
    }
}