force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Enqix_Import__c/Enqix_Import__c.object-meta.xml
<CustomObject>
    <description>Serves as a placeholder for Enquix data imports.</description>
    <label>Enqix Import</label>
    <nameField>
        <displayFormat>EI-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enqix Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enqix_Import__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the import job.</description>
    <inlineHelpText>Status of the import job.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enqix_Import__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Import.</description>
    <inlineHelpText>Type of Import.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts/Locations</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/EnquixImportMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings Object that capture the mappings for the Enquix (CSV) files. Name of the individual settings instance represents a row header in the import sheet.</description>
    <label>Enquix Import Mappings</label>
</CustomObject>

force-app/main/default/objects/NoTriggers__c/NoTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to disable triggers for a given profile / user</description>
    <label>No Triggers</label>
</CustomObject>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EnquixOrderImportBatchTest.cls
/**
* @author Zoran Zunko
* @date 10/23/15
*
* @group 
* @group-content ../../ApexDocContent/
*
* @description 
*/

@IsTest
private class EnquixOrderImportBatchTest {
    @TestSetup
    static void dataSetup() {

        List<EnquixImportMappings__c> enquixImportMappings =
                Test.loadData(EnquixImportMappings__c.sObjectType, 'EnqixTestMappings');

        //we need four locations due to the import file template one per accounts
        List<Account> accounts = TestDataFactory.createAccounts('accounts', 4);

        insert accounts;

        //one loca per account
        List<Account> locations = TestDataFactory.createLocations(accounts, 'locations', 1);

        insert locations;

        List<String> locEnqixIds = new List<String>();
        for(Account location : locations) {

            locEnqixIds.add(location.Enqix_ID__c);
        }

        //we need four products
        List<Product2> products = TestDataFactory.createProductsForImport('Product', 4);
        insert products;

        List<String> prodEnqixIds = new List<String>();
        for(Product2 product : products) {

            prodEnqixIds.add(product.Enqix_ID__c);
        }

        List<PricebookEntry> pbEntries = TestDataFactory.createStandardPrice(products, 2.34);
        insert pbEntries;

        Enqix_Import__c enqixImport = new Enqix_Import__c();
        enqixImport.Status__c = EquixImportManager.STATUS_PENDING   ;
        enqixImport.Type__c = EquixImportManager.IMPORT_TYPE_ORDER;

        insert enqixImport;

        Attachment att = new Attachment(
                Name = 'Test',
                Body = Blob.valueOf(TestDataFactory.getOrderOrderLineImportList(locEnqixIds, prodEnqixIds)),
                ParentId = enqixImport.Id
        );

        NoTriggers__c flag = NoTriggers__c.getInstance(UserInfo.getUserId());
        flag.Flag__c = true;

        insert flag;

        insert att;

    }

    static testMethod void testBehavior() {

        Test.startTest();

        System.assert(EnquixOrderImportBatch.batchMe());

        Test.stopTest();

    }
}