force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled Waste and Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Other Waste/Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Secure Shredding</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance/Junk Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Business Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting and Data</fullName>
    </customValue>
    <customValue>
        <fullName>Product Partnership</fullName>
    </customValue>
    <masterLabel>Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTrigger_Test.cls
@isTest
public class OpportunityTrigger_Test{

    public static testmethod void UnitTest(){
        
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.Enqix_Dead_Live__c = 'Pending';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Unqualified';
        opp.CloseDate = date.today().addDays(20);
        opp.AccountId = acc.Id;
        opp.Services__c = 'Secure Shredding	';
        insert opp;
        
        opp.StageName = 'Handed Over';
        update opp;
        
        
    }
}