force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enqix_Id_automation__c/Enqix_Id_automation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Enqix Id automation</label>
</CustomObject>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_id__c</fullName>
    <defaultValue>30000</defaultValue>
    <label>Enqix_id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_Id__c</fullName>
    <label>Enqix Location Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/POD_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>POD_Delivery_Date__c</fullName>
    <label>POD Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <formula>IF(
    /* First condition: Delivery Date is less than 22/09/2024 */
    Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
    /* Use the original logic */
    IF(
        NOT(ISNULL(AD_KG_from_Weights__c)),
        AD_KG_from_Weights__c,
        Quantity * PricebookEntry.Product2.AD_KG__c
    ),

    /* Second condition: Delivery Date is on or after 22/09/2024 */
    IF(
        /* Check if AD_KG_from_Weights__c is greater than 0 */
        AD_KG_from_Weights__c &gt; 0,
        AD_KG_from_Weights__c,

        /* If AD_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
        IF(
            TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
            /* Fall Back Weight Type is &quot;No Weight&quot; */
            0,

            IF(
                /* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
                TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot; 
                &amp;&amp; PricebookEntry.Product2.AD_KG__c &gt; 0,
                /* Apply Company Average Weight if AD_KG__c is greater than 0 */
                Quantity * PricebookEntry.Product2.Estimated_Weight__c,

                /* Default value if none of the conditions match */
                Quantity * PricebookEntry.Product2.AD_KG__c
            )
        )
    )
)</formula>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/detrack_Qrcode__c.field-meta.xml
<CustomField>
    <fullName>detrack_Qrcode__c</fullName>
    <label>DEtrack QR Code</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(Recycled_KG_from_Weights__c)),
Recycled_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.Recycle_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if Recycled_KG_from_Weights__c is greater than 0 */
Recycled_KG_from_Weights__c &gt; 0,
Recycled_KG_from_Weights__c,

/* If Recycled_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.Recycle_KG__c &gt; 0,
/* Apply Company Average Weight if Recycle_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.Recycle_KG__c
)
)
)
)</formula>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <formula>IF(NOT(ISNULL(Tonnes_CO2_Saved_from_Weights__c)), Tonnes_CO2_Saved_from_Weights__c, 
 IF(NOT(ISNULL(Coffee_KG__c)), Coffee_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(AD_KG__c)), AD_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(Recycled_KG__c)), Recycled_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0)
)</formula>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(WTE_KG_from_Weights__c)),
WTE_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.WTE_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if WTE_KG_from_Weights__c is greater than 0 */
WTE_KG_from_Weights__c &gt; 0,
WTE_KG_from_Weights__c,

/* If WTE_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and WTE_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.WTE_KG__c &gt; 0,
/* Apply Company Average Weight if WTE_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.WTE_KG__c
)
)
)
)</formula>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <description>KG&apos;s in the sack which go to AD, assuming sack is full</description>
    <inlineHelpText>KG&apos;s in the sack which go to AD, assuming sack is full</inlineHelpText>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Report_Groupings__c.field-meta.xml
<CustomField>
    <fullName>Report_Groupings__c</fullName>
    <label>Report Groupings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEEE and Toner</fullName>
            </value>
            <value>
                <fullName>Cardboard</fullName>
            </value>
            <value>
                <fullName>Junk Removal</fullName>
            </value>
            <value>
                <fullName>Food Recycling</fullName>
            </value>
            <value>
                <fullName>Paper Shredding</fullName>
            </value>
            <value>
                <fullName>General Waste</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Mixed Recycling</fullName>
            </value>
            <value>
                <fullName>Stationery and Textiles</fullName>
            </value>
            <value>
                <fullName>Coffee Grounds</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
                <isActive>false</isActive>
                <label>Paper</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Skin__c/Product_Skin__c.object-meta.xml
<CustomObject>
    <label>Product Skin</label>
    <nameField>
        <label>Product Skin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Skins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Skin__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SecurePaper_Test.cls
@isTest
public with sharing class SecurePaper_Test {

	@testSetup static void setup() {
        // Create Product Skins
        Product_Skin__c secdestrPS = new Product_Skin__c(); 
        secdestrPS.Name = 'Sec Destr'; 
        insert secdestrPS;

        Product_Skin__c weee = new Product_Skin__c(); 
        weee.Name = 'WEEE'; 
        insert weee;
        
        TestDataHelper.insertSupplier('First Mile Ltd');
    }
    
    @future
    private static void insertCustomSetting(){
      Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Name = 'teste', Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
      system.debug('DEBUG========================='+testRecord);
	  insert testRecord;
	}
	
	@isTest
	public static void createTest(){
        Test.StartTest();
        insertCustomSetting();
        Test.stopTest();
        Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
		system.debug('Começando testes Secure Destructions');
        //Products
        List<Product2> lstProds = new List<Product2>();
  

        system.debug('Criar Produtos SKIN:: ');
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProductSkin('Prod-' + (i+1), 100, (i+1)));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
         
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
          
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 0,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        
        //Insert Parent Accounts
        Account parentAccount = TestDataHelper.insertAccount();
        Account locationAccount = TestDataHelper.insertLocation(parentAccount.Id,null);

        String Enqix_Id = '9999990';

        //Insert Orders for Per Order
        Order ord1 = new Order(
            AccountId = locationAccount.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Enqix_Id__c = Enqix_Id,
            POD_Delivery_Date__c = system.today(),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;

        Attachment orderAttachement = new Attachment(
            Name = 'POD_'+Enqix_Id+'.jpg',
            ParentId = ord1.Id,
            Body = EncodingUtil.base64Decode('Testinho')
        ); 
        insert orderAttachement;

        List <ContentVersion> cvList = new List <ContentVersion>();
        ContentVersion cv = new ContentVersion();
        cv.Title = 'test cdoc';
        cv.VersionData = blob.valueOf('test data.pdf');
        cv.PathOnClient = 'test.pdf';
        cvList.add(cv);
        insert cvList;

        Id cdId = [select ContentDocumentId from ContentVersion where title = 'test cdoc' limit 1].ContentDocumentId;

        //order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = ord1.Id,
            Quantity = 100,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 0,
            Detrack_QRCode__c = 'Test detrackCode',
            Product2Id = lstProds[0].Id
        ));
        insert lstOLI;

        ord1.Status = 'Delivered';
        system.debug('ORDEM DELIVERED COM SKIN SECURE DESTRUCTION NO PRODUCT SKIN');
        upsert ord1;

		Set<Id> orderIds = new Set<Id>();
        orderIds.add(ord1.Id);

        Compliance_Doc__c sd = new Compliance_Doc__c();
        sd.Account__c = locationAccount.Id;
        sd.Order__c = ord1.Id;
        sd.RecordTypeId = Schema.SObjectType.Compliance_Doc__c.getRecordTypeInfosByName().get('Waste Transfer Notes').getRecordTypeId();
        sd.Status__c = 'Draft';
        insert sd;
        
        


        List<Compliance_Doc__c> comps = [SELECT Id, 	Order__c
                                        FROM Compliance_Doc__c 
                                          WHERE Order__c in :orderIds];

		for(Compliance_Doc__c c : comps){
			ApexPages.StandardController sc = new ApexPages.StandardController(c);
            SecurePaperDestRedirectExtension idre = new SecurePaperDestRedirectExtension(sc);
			SecurePaperDestExtension noe = new SecurePaperDestExtension(sc);
			PageReference p = idre.redirect();
            
        }

	}

	private static Product2 createTestProductSkin(String prodName, Integer recycleKG, Integer idx) {
        //system.debug('Entrei no create test product SKIN');
        //List <Product_Skin__c> n =[SELECT Id, Name FROM  Product_Skin__c WHERE Name LIKE 'SECURE DESTRUCTION'];
        //system.debug('TAMANHO DA LISTA DE PRODUCT SKINS COM SECURE DESTRUCTION NO NOME '+n.size());
        //a3A4E0000006ue1UAA (id) Já existe com este nome 
        //Product_Skin__c n = new Product_Skin__c(); 
        //n.Name = 'Sec Destr'; 
        //insert n;
        Product_Category__c proCat= new Product_Category__c(Name = 'Test');
		insert proCat;
		
        Product_Skin__c ps = new Product_Skin__c(
        Name = 'Sec Destr - Tag Prefix: CDD - Weight KG: 25'
        );
        insert ps;
        Product_Skin__c ps1 = new Product_Skin__c(
        Name = 'Sec Destr - Tag Prefix: SD - Weight KG: 25'
        );
        insert ps1;
        Product_Skin__c ps2 = new Product_Skin__c(
        Name = 'Sec Destr - Tag Prefix: Exchange - Weight KG: 25'
        );
        insert ps2;
        //List <Product_Skin__c> product_skins =[SELECT Id, Name FROM  Product_Skin__c WHERE Name LIKE '%Sec Destr%'];
        List <Product_Skin__c> product_skins =[SELECT Id, Name FROM  Product_Skin__c WHERE Name = 'Sec Destr - Tag Prefix: CDD - Weight KG: 25'];
        //system.debug('Existem ' + product_skins.size() + ' Product Skins com Sec Destr no nome'); 
        //Product_Skin__c product_skin = product_skins.get(0);

        //system.debug('SKIN:: '+n.get(0)+'Name::::'+n.get(0).Name);
        String rpGroup = (Math.mod(idx, 2) == 0)?'Cardboard':'Food Recycling';
        
        Product2 prod = TestDataHelper.createProduct(prodName, '123', 'Delivery', procat.Id);
        prod.Report_Groupings__c = rpGroup;
		prod.Recycle_KG__c = recycleKG;
		prod.Product_Skins__c = product_skins[0].Id;
        
		return prod;
       /* Product2 prod = new Product2(
            Name = prodName,  
            Product_Type__c = 'Delivery',
            Report_Groupings__c = rpGroup,
            Recycle_KG__c = recycleKG,
            //Product_Skins__c = 'a3A4E000000BZrpUAG', ERROR - IDs must never be written as hardcoded, always use query and assign!
            Product_Skins__c = product_skins[0].Id,
            IsActive = true,
            Product_Category__c = proCat.Id,
			UnitCost__c = 10,
            ProductCode = '123',
            Nl_accode__c = '4001'
        );        
        //prod.Product_Skins__c = n.Id;
        //system.debug('SAI do create test product SKIN');
        return prod;*/
    }
}