force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinanceContact__c.field-meta.xml
<CustomField>
    <fullName>FinanceContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/classes/ContactDeletion.cls
public without sharing class ContactDeletion {

		public ContactDeletion(List<Contact> contacts) {
			validateFinanceContact(contacts);
		}

		private void validateFinanceContact(List<Contact> contacts) {
			Map<Id, List<Account>> financeContactWithAccountMap = new Map<Id, List<Account>>();
			for (Account account : [SELECT Name, FinanceContact__c FROM Account 
				WHERE FinanceContact__c IN :contacts AND Enqix_Dead_Live__c = :AccountUtil.LIVE 
				AND RecordTypeId IN (:AccountUtil.RECORDTYPEID_PARENT, :AccountUtil.RECORDTYPEID_PARTNER)]) {
				if (!financeContactWithAccountMap.containsKey(account.FinanceContact__c)) {
					financeContactWithAccountMap.put(account.FinanceContact__c, new List<Account>());
				}
				financeContactWithAccountMap.get(account.FinanceContact__c).add(account);
			}

			for (Contact contact : contacts) {
				if (!financeContactWithAccountMap.containsKey(contact.Id)) {
					continue;
				}
				contact.addError('Finance contact is required on live account: ' + prepareErrorMessage(financeContactWithAccountMap.get(contact.Id)));
			}
		}

		private String prepareErrorMessage(List<Account> accounts) {
			List<String> errorMessage = new List<String>();
			for (Account account : accounts) {
				errorMessage.add(account.Name + ' [' + account.Id + ']');
			}
			return String.join(errorMessage, ', ');
		}
	}