force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsBinCollectionAdvanceInvoiced__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollectionAdvanceInvoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection Advance Invoiced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Supplier_Product__r.Supplier__r.Name</formula>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Type__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Waste_Category__c.field-meta.xml
<CustomField>
    <fullName>Waste_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Waste Category</label>
    <referenceTo>Waste_Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product_Category_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_Key__c</fullName>
    <externalId>true</externalId>
    <label>Product Category Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <formula>Supplier_Product__r.Product__r.Container_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Enqix_UID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_UID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix  UID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Waste_Category__c/Waste_Category__c.object-meta.xml
<CustomObject>
    <label>Waste Category</label>
    <nameField>
        <label>Waste Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Waste_Category__c/fields/Codes__c.field-meta.xml
<CustomField>
    <fullName>Codes__c</fullName>
    <label>Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Waste_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CollectionScheduleTriggerTest.cls
@isTest
private class CollectionScheduleTriggerTest {

	private static Id LOCATION_ACCOUNT_RECORDTYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
	private static Id WTN_COMPLIANCE_DOC_RECORDTYPE_ID = Schema.SObjectType.Compliance_Doc__c.getRecordTypeInfosByName().get('Waste Transfer Notes').getRecordTypeId();

	@testSetup
	private static void setup() {
		Product_Category__c productCategory = new Product_Category__c(Name = 'Test Product Category', Enqix_Id__c = 12345, Product_Category_Key__c = 'Test Product Category Key');
		INSERT productCategory;

		Waste_Category__c  wasteCategory = new Waste_Category__c(Name = 'Cardboard Waste', Codes__c = '123456');
		INSERT wasteCategory;

		Container_Type__c containerType = TestDataHelper.insertContainerType('Bin');

		Product2 product = TestDataHelper.createProduct('Test Product', '12355321', 'Collection', productCategory.Id, wasteCategory.Id, containerType.Id, '264');
		INSERT product;

		Suppliers__c supplier = TestDataHelper.insertSupplier('First Mile Ltd');

		Supplier_Product__c supplierProduct = new Supplier_Product__c(Name = 'Test Supplier Product', Supplier__c = supplier.Id, Product__c = product.Id, Enqix_UID__c = '1233');
		INSERT supplierProduct;

		Account parent = TestDataHelper.createAccount();
		parent.IsBinCollectionAdvanceInvoiced__c = true;
		INSERT parent;
		Account location = TestDataHelper.createLocation(parent.Id, null);
		location.Price_Book__c = Test.getStandardPricebookId();
		location.Enqix_Dead_Live__c = 'Live';
		INSERT location;

		List<Schedule__c> collectionSchedules = new List<Schedule__c>();
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '18:00'));
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Tuesday;Wednesday;Thursday', Time__c = '18:00'));
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Saturday;Sunday', Time__c = '20:30'));
		INSERT collectionSchedules;
	}

	@isTest
	private static void testController() {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		CollectionScheduleController.getCollections(location.Id);
	}

	@isTest
	private static void testInsert() {
		List<Schedule__c> collectionSchedules = querySchedules();
		System.assertEquals(6, collectionSchedules.size());
		assertSchedule(collectionSchedules[0], 'Monday', 'Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[1], 'Tuesday', 'Monday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[2], 'Wednesday', 'Monday,Tuesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[3], 'Thursday', 'Monday,Tuesday,Wednesday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[4], 'Saturday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Sunday');
		assertSchedule(collectionSchedules[5], 'Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday');

		List<CollectionAggregator__c> collectionAggregators = queryAggregators();
		System.assertEquals(2, collectionAggregators.size());
		assertAggregator(collectionAggregators[0], 'Monday,Tuesday,Wednesday,Thursday', 'Friday,Saturday,Sunday', '18:00');
		assertAggregator(collectionAggregators[1], 'Saturday,Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday', '20:30');
	}

	@isTest
	private static void testUpdateWithNoChange() {
		List<Schedule__c> collectionSchedules = [SELECT Id FROM Schedule__c WHERE Days__c IN ('Monday', 'Tuesday', 'Wednesday')
												ORDER BY Monday_Collection__c DESC, Tuesday_Collection__c DESC, Wednesday_Collection__c DESC];
		UPDATE collectionSchedules;

		testInsert();
	}

	@isTest
	private static void testUpdate2Of4Days() {
		List<Schedule__c> collectionSchedules = [SELECT Id FROM Schedule__c WHERE Days__c IN ('Monday', 'Tuesday', 'Wednesday')
												ORDER BY Monday_Collection__c DESC, Tuesday_Collection__c DESC, Wednesday_Collection__c DESC];
		collectionSchedules[0].Time__c = '20:30';	// Monday
		collectionSchedules[1].Time__c = '20:30';	// Tuesday
		collectionSchedules[2].Time__c = '18:00';	// Wednesday, no change
		UPDATE collectionSchedules;

		collectionSchedules = querySchedules();
		System.assertEquals(6, collectionSchedules.size());
		assertSchedule(collectionSchedules[0], 'Monday', 'Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[1], 'Tuesday', 'Monday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[2], 'Wednesday', 'Monday,Tuesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[3], 'Thursday', 'Monday,Tuesday,Wednesday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[4], 'Saturday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Sunday');
		assertSchedule(collectionSchedules[5], 'Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday');

		List<CollectionAggregator__c> collectionAggregators = queryAggregators();
		System.assertEquals(2, collectionAggregators.size());
		assertAggregator(collectionAggregators[0], 'Monday,Tuesday,Saturday,Sunday', 'Wednesday,Thursday,Friday', '20:30');
		assertAggregator(collectionAggregators[1], 'Wednesday,Thursday', 'Monday,Tuesday,Friday,Saturday,Sunday', '18:00');
	}

	@isTest
	private static void testUpdate4Of4Days() {
		List<Schedule__c> collectionSchedules = [SELECT Id FROM Schedule__c WHERE Days__c IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday')];
		collectionSchedules[0].Time__c = '20:30';
		collectionSchedules[1].Time__c = '20:30';
		collectionSchedules[2].Time__c = '20:30';
		collectionSchedules[3].Time__c = '20:30';
		UPDATE collectionSchedules;

		collectionSchedules = querySchedules();
		System.assertEquals(6, collectionSchedules.size());
		assertSchedule(collectionSchedules[0], 'Monday', 'Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[1], 'Tuesday', 'Monday,Wednesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[2], 'Wednesday', 'Monday,Tuesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[3], 'Thursday', 'Monday,Tuesday,Wednesday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[4], 'Saturday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Sunday');
		assertSchedule(collectionSchedules[5], 'Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday');

		List<CollectionAggregator__c> collectionAggregators = queryAggregators();
		System.assertEquals(1, collectionAggregators.size());
		assertAggregator(collectionAggregators[0], 'Monday,Tuesday,Wednesday,Thursday,Saturday,Sunday', 'Friday', '20:30');
	}

	@isTest
	private static void testDelete2() {
		List<Schedule__c> collectionSchedules = [SELECT Id FROM Schedule__c WHERE Days__c IN ('Monday', 'Tuesday')];
		DELETE collectionSchedules;

		collectionSchedules = querySchedules();
		System.assertEquals(4, collectionSchedules.size());
		assertSchedule(collectionSchedules[0], 'Wednesday', 'Monday,Tuesday,Thursday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[1], 'Thursday', 'Monday,Tuesday,Wednesday,Friday,Saturday,Sunday');
		assertSchedule(collectionSchedules[2], 'Saturday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Sunday');
		assertSchedule(collectionSchedules[3], 'Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday');

		List<CollectionAggregator__c> collectionAggregators = queryAggregators();
		System.assertEquals(2, collectionAggregators.size());
		assertAggregator(collectionAggregators[0], 'Wednesday,Thursday', 'Monday,Tuesday,Friday,Saturday,Sunday', '18:00');
		assertAggregator(collectionAggregators[1], 'Saturday,Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday', '20:30');
	}

	@isTest
	private static void testDelete4() {
		List<Schedule__c> collectionSchedules = [SELECT Id FROM Schedule__c WHERE Days__c IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday')];
		DELETE collectionSchedules;

		collectionSchedules = querySchedules();
		System.assertEquals(2, collectionSchedules.size());
		assertSchedule(collectionSchedules[0], 'Saturday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Sunday');
		assertSchedule(collectionSchedules[1], 'Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday');

		List<CollectionAggregator__c> collectionAggregators = queryAggregators();
		System.assertEquals(1, collectionAggregators.size());
		assertAggregator(collectionAggregators[0], 'Saturday,Sunday', 'Monday,Tuesday,Wednesday,Thursday,Friday', '20:30');
	}

	@isTest
	private static void testInvalidInsertFailure() {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		Suppliers__c supplier = [SELECT Id FROM Suppliers__c];
		Supplier_Product__c supplierProduct = [SELECT Id FROM Supplier_Product__c];

		List<Schedule__c> collectionSchedules = new List<Schedule__c>();
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday;Tuesday;Wednesday', Time__c = '2A:00'));	// Invalid time format
		try {
			INSERT collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals('Time must be in HH:MM format. E.g. 07:45', e.getDmlMessage(0));
		}
	}

	@isTest
	private static void testDuplicateInsertFailure() {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		Suppliers__c supplier = [SELECT Id FROM Suppliers__c];
		Supplier_Product__c supplierProduct = [SELECT Id FROM Supplier_Product__c];

		List<Schedule__c> collectionSchedules = new List<Schedule__c>();

		// Duplicates within newly inserted records
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '21:00'));
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday;Tuesday;Wednesday;Thursday', Time__c = '21:00')); // Duplicate Monday
		try {
			INSERT collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals(Label.MsgDuplicateCollectionSchedule, e.getDmlMessage(0));
		}

		// Duplicates between newly inserted records and existing records
		collectionSchedules.clear();
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '21:00'));    // Unique
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '18:00'));    // Duplicate
		try {
			INSERT collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals(Label.MsgDuplicateCollectionSchedule, e.getDmlMessage(0));
		}

		// Invalid time format
		collectionSchedules.clear();
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '2A:00'));	// Invalid time format
		try {
			INSERT collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals('Time must be in HH:MM format. E.g. 07:45', e.getDmlMessage(0));
		}
	}

	@isTest
	private static void testDuplicateUpdateFailure() {
		Account location = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Location' LIMIT 1];
		Suppliers__c supplier = [SELECT Id FROM Suppliers__c];
		Supplier_Product__c supplierProduct = [SELECT Id FROM Supplier_Product__c];

		List<Schedule__c> collectionSchedules = new List<Schedule__c>();
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '21:00'));
		collectionSchedules.add(new Schedule__c(Location__c = location.id, Supplier__c = supplier.id, Supplier_Product__c = supplierProduct.id, Collection_Quantity__c = 10,
												Days__c = 'Monday', Time__c = '21:30'));

		Database.SaveResult[] results = Database.insert(collectionSchedules);
		System.assert(results[0].isSuccess());
		System.assert(results[1].isSuccess());

		// Duplicates within updated records
		collectionSchedules[0].Time__c = '23:00'; // Duplicate
		collectionSchedules[1].Time__c = '23:00'; // Duplicate
		try {
			UPDATE collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals(Label.MsgDuplicateCollectionSchedule, e.getDmlMessage(0));
		}

		// Duplicates between updated records and existing records
		collectionSchedules[0].Time__c = '21:00'; // No change
		collectionSchedules[1].Time__c = '18:00'; // Duplicate
		try {
			UPDATE collectionSchedules;
			System.assert(false);
		} catch (DmlException e) {
			System.assertEquals(Label.MsgDuplicateCollectionSchedule, e.getDmlMessage(0));
		}
	}

	private static List<Schedule__c> querySchedules() {
		return [SELECT Monday_Collection__c, Tuesday_Collection__c, Wednesday_Collection__c, Thursday_Collection__c, Friday_Collection__c, Saturday_Collection__c, Sunday_Collection__c
				FROM Schedule__c
				ORDER BY Monday_Collection__c DESC NULLS LAST, Tuesday_Collection__c DESC NULLS LAST, Wednesday_Collection__c DESC NULLS LAST, Thursday_Collection__c DESC NULLS LAST,
					Friday_Collection__c DESC NULLS LAST, Saturday_Collection__c DESC NULLS LAST, Sunday_Collection__c DESC NULLS LAST];
	}

	private static List<CollectionAggregator__c> queryAggregators() {
		return [SELECT Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c
				FROM CollectionAggregator__c
				ORDER BY Monday__c NULLS LAST, Wednesday__c NULLS LAST, Saturday__c NULLS LAST];
	}

	private static void assertSchedule(Schedule__c schedule, String csvDaysEnabled, String csvDaysDisabled) {
		assertSchedule(schedule, csvDaysEnabled, true);
		assertSchedule(schedule, csvDaysDisabled, false);
	}
	private static void assertSchedule(Schedule__c schedule, String csvDays, Boolean isEnabled) {
		for (String dayOfWeek : csvDays.split(',')) {
			System.assertEquals(isEnabled, (Boolean)schedule.get(dayOfWeek + '_Collection__c'));
		}
	}

	private static void assertAggregator(CollectionAggregator__c aggregator, String csvDaysEnabled, String csvDaysDisabled, String collectionTime) {
		assertAggregator(aggregator, csvDaysEnabled, collectionTime);
		assertAggregator(aggregator, csvDaysDisabled, null);
	}
	private static void assertAggregator(CollectionAggregator__c aggregator, String csvDays, String collectionTime) {
		for (String dayOfWeek : csvDays.split(',')) {
			System.assertEquals(collectionTime, (String)aggregator.get(dayOfWeek + '__c'));
		}
	}
}