force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsInvoiceFrequencyOverride__c.field-meta.xml
<CustomField>
    <fullName>IsInvoiceFrequencyOverride__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Frequency Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/is_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>is_Salesforce__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <formula>IF(
    /* First condition: Delivery Date is less than 22/09/2024 */
    Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
    /* Use the original logic */
    IF(
        NOT(ISNULL(AD_KG_from_Weights__c)),
        AD_KG_from_Weights__c,
        Quantity * PricebookEntry.Product2.AD_KG__c
    ),

    /* Second condition: Delivery Date is on or after 22/09/2024 */
    IF(
        /* Check if AD_KG_from_Weights__c is greater than 0 */
        AD_KG_from_Weights__c &gt; 0,
        AD_KG_from_Weights__c,

        /* If AD_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
        IF(
            TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
            /* Fall Back Weight Type is &quot;No Weight&quot; */
            0,

            IF(
                /* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
                TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot; 
                &amp;&amp; PricebookEntry.Product2.AD_KG__c &gt; 0,
                /* Apply Company Average Weight if AD_KG__c is greater than 0 */
                Quantity * PricebookEntry.Product2.Estimated_Weight__c,

                /* Default value if none of the conditions match */
                Quantity * PricebookEntry.Product2.AD_KG__c
            )
        )
    )
)</formula>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/is_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>is_Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(Recycled_KG_from_Weights__c)),
Recycled_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.Recycle_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if Recycled_KG_from_Weights__c is greater than 0 */
Recycled_KG_from_Weights__c &gt; 0,
Recycled_KG_from_Weights__c,

/* If Recycled_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.Recycle_KG__c &gt; 0,
/* Apply Company Average Weight if Recycle_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.Recycle_KG__c
)
)
)
)</formula>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <formula>IF(NOT(ISNULL(Tonnes_CO2_Saved_from_Weights__c)), Tonnes_CO2_Saved_from_Weights__c, 
 IF(NOT(ISNULL(Coffee_KG__c)), Coffee_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(AD_KG__c)), AD_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(Recycled_KG__c)), Recycled_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0)
)</formula>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(WTE_KG_from_Weights__c)),
WTE_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.WTE_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if WTE_KG_from_Weights__c is greater than 0 */
WTE_KG_from_Weights__c &gt; 0,
WTE_KG_from_Weights__c,

/* If WTE_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and WTE_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.WTE_KG__c &gt; 0,
/* Apply Company Average Weight if WTE_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.WTE_KG__c
)
)
)
)</formula>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <description>KG&apos;s in the sack which go to AD, assuming sack is full</description>
    <inlineHelpText>KG&apos;s in the sack which go to AD, assuming sack is full</inlineHelpText>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category__c</fullName>
    <label>Delivery Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Internal Bin</fullName>
            </value>
            <value>
                <fullName>External Bin</fullName>
            </value>
            <value>
                <fullName>Schedule Collection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Skins__c.field-meta.xml
<CustomField>
    <fullName>Product_Skins__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Skin</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Product_Skin__c.Name</field>
            <operation>equals</operation>
            <value>Collection Skin</value>
        </filterItems>
        <filterItems>
            <field>$Source.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>$Source.Product_Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <filterItems>
            <field>Product_Skin__c.Name</field>
            <operation>notEqual</operation>
            <value>Collection Skin</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Skin__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Recycle_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycle_KG__c</fullName>
    <inlineHelpText>KG&apos;s of the sack&apos;s contents which are recycled, with assumption sack is at full capacity.</inlineHelpText>
    <label>Recycle KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Report_Groupings__c.field-meta.xml
<CustomField>
    <fullName>Report_Groupings__c</fullName>
    <label>Report Groupings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEEE and Toner</fullName>
            </value>
            <value>
                <fullName>Cardboard</fullName>
            </value>
            <value>
                <fullName>Junk Removal</fullName>
            </value>
            <value>
                <fullName>Food Recycling</fullName>
            </value>
            <value>
                <fullName>Paper Shredding</fullName>
            </value>
            <value>
                <fullName>General Waste</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Mixed Recycling</fullName>
            </value>
            <value>
                <fullName>Stationery and Textiles</fullName>
            </value>
            <value>
                <fullName>Coffee Grounds</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
                <isActive>false</isActive>
                <label>Paper</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Skin__c/Product_Skin__c.object-meta.xml
<CustomObject>
    <label>Product Skin</label>
    <nameField>
        <label>Product Skin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Skins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderTriggerHelperTest.cls
@isTest
public class OrderTriggerHelperTest {

	public static Id parentRecordtype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
	public static Id childRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
	public static Id pricebookId = Test.getStandardPricebookId();

	@testSetup static void setup() {
		TestDataHelper.insertVat();

		TestDataHelper.insertSupplier('First Mile Ltd');

		Account parentAccount = new Account(Name='Parent Account', InvoiceFrequency__c='Per order', RecordTypeId=parentRecordtype);
		INSERT parentAccount;

		Account childAccount = new Account(Name='Child Account', InvoiceFrequency__c='Monthly', IsInvoiceFrequencyOverride__c = true, ParentId=parentAccount.Id, RecordTypeId=childRecordType, Enqix_Dead_Live__c = 'Live', Price_Book__c = Test.getStandardPricebookId());
		INSERT childAccount;

		List<Product2> lstProds = new List<Product2>();
		for (Integer i=0; i<3; i++) {
			lstProds.add(createTestProduct('Prod-' + (i+1), 10, (i+1)));
		}
		INSERT lstProds;

		List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
		for (Integer i=0; i<3; i++) {
			lstStandardPrice.add(new PricebookEntry(
				Pricebook2Id = pricebookId,
				Product2Id = lstProds.get(i).Id,
				UnitPrice = 100,
				IsActive = true
			));
		}
		INSERT lstStandardPrice;

		Order Order1 = new Order(
			AccountId = childAccount.id,
			EffectiveDate = System.today().addMonths(-(1)),
			Delivery_Date__c = System.today().addMonths(-(1)),
			Status = 'Confirmed',
			AD_KG__c = 100,
			Recycled_KG__c = 100,
			WTE_KG__c = 100,
			Tonnes_CO2_Saved__c = 100,
			Pricebook2Id = pricebookId,
			Is_Salesforce__c = true
		);
		INSERT Order1;

		INSERT (new OrderItem(
			OrderId = Order1.Id,
			Quantity = 1,
			PriceBookEntryId = lstStandardPrice.get(1).Id,
			UnitPrice = 100
		));

		Order1.Status = 'Delivered';
		Test.startTest();
		UPDATE Order1;
		Test.stopTest();
	}

	private static testMethod void testReparenting() {
		// reparent location
		Account parentAccount2 = TestDataHelper.insertAccount();
		Contact financeContact = TestDataHelper.insertContact(parentAccount2.Id, 'Lastname');
		Account location = [SELECT Id FROM Account WHERE RecordTypeId = :childRecordType LIMIT 1];
		location.ParentId = parentAccount2.Id;
		UPDATE location;

		Order order2 = new Order(
			AccountId = location.id,
			EffectiveDate = System.today().addMonths(-(1)),
			Delivery_Date__c = System.today().addMonths(-(1)),
			Status = 'Confirmed',
			AD_KG__c = 100,
			Recycled_KG__c = 100,
			WTE_KG__c = 100,
			Tonnes_CO2_Saved__c = 100,
			Pricebook2Id = pricebookId,
			Is_Salesforce__c = true
		);
		INSERT order2;
		PricebookEntry pe = [SELECT Id FROM PricebookEntry LIMIT 1];
        Test.startTest();
		INSERT (new OrderItem(
			OrderId = order2.Id,
			Quantity = 1,
			PriceBookEntryId = pe.Id,
			UnitPrice = 100
		));

		order2.status = 'Delivered';
		
		UPDATE order2;
		Test.stopTest();
		System.assertEquals(2, [SELECT Id FROM Invoice_Header__c].size(), 'Expecting 2 invoices');
	}

	private static testMethod void testContinueInvoicing() {
		Account location = [SELECT Id FROM Account WHERE RecordTypeId = :childRecordType LIMIT 1];
		Order order2 = new Order(
			AccountId = location.id,
			EffectiveDate = System.today().addMonths(-(1)),
			Delivery_Date__c = System.today().addMonths(-(1)),
			Status = 'Confirmed',
			AD_KG__c = 100,
			Recycled_KG__c = 100,
			WTE_KG__c = 100,
			Tonnes_CO2_Saved__c = 100,
			Pricebook2Id = pricebookId,
			Is_Salesforce__c = true
		);
		INSERT order2;
		PricebookEntry pe = [SELECT Id FROM PricebookEntry LIMIT 1];
		INSERT (new OrderItem(
			OrderId = order2.Id,
			Quantity = 1,
			PriceBookEntryId = pe.Id,
			UnitPrice = 100
		));

		order2.status = 'Delivered';
		Test.startTest();
		UPDATE order2;
		Test.stopTest();
		System.assertEquals(1, [SELECT Id FROM Invoice_Header__c].size(), 'Expecting 1 invoices');
	}

	private static Product2 createTestProduct(String prodName, Integer recycleKG, Integer idx) {
		String rpGroup = (Math.mod(idx, 2) == 0)?'Cardboard':'Food Recycling';
		Product_Category__c proCat= new Product_Category__c(Name = 'Test');
		INSERT proCat;

		Product_Skin__c skin = new Product_Skin__c(Name = 'WEEE test');
		INSERT skin;

		Product2 prod = TestDataHelper.createProduct(prodName, '123', 'Delivery', proCat.Id);
		prod.Report_Groupings__c = rpGroup;
		prod.Recycle_KG__c = recycleKG;
		prod.Product_Skins__c = skin.Id;
		prod.Delivery_Category__c = 'Delivery';

		return prod;
	}
}