force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Enqix_Id_automation__c/Enqix_Id_automation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Enqix Id automation</label>
</CustomObject>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_id__c</fullName>
    <defaultValue>30000</defaultValue>
    <label>Enqix_id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enqix_Id_automation__c/fields/Enqix_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_Id__c</fullName>
    <label>Enqix Location Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <formula>DeliveryDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/is_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>is_Salesforce__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <formula>IF(
    /* First condition: Delivery Date is less than 22/09/2024 */
    Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
    /* Use the original logic */
    IF(
        NOT(ISNULL(AD_KG_from_Weights__c)),
        AD_KG_from_Weights__c,
        Quantity * PricebookEntry.Product2.AD_KG__c
    ),

    /* Second condition: Delivery Date is on or after 22/09/2024 */
    IF(
        /* Check if AD_KG_from_Weights__c is greater than 0 */
        AD_KG_from_Weights__c &gt; 0,
        AD_KG_from_Weights__c,

        /* If AD_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
        IF(
            TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
            /* Fall Back Weight Type is &quot;No Weight&quot; */
            0,

            IF(
                /* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
                TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot; 
                &amp;&amp; PricebookEntry.Product2.AD_KG__c &gt; 0,
                /* Apply Company Average Weight if AD_KG__c is greater than 0 */
                Quantity * PricebookEntry.Product2.Estimated_Weight__c,

                /* Default value if none of the conditions match */
                Quantity * PricebookEntry.Product2.AD_KG__c
            )
        )
    )
)</formula>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/is_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>is_Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <formula>CASESAFEID(Order.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(Recycled_KG_from_Weights__c)),
Recycled_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.Recycle_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if Recycled_KG_from_Weights__c is greater than 0 */
Recycled_KG_from_Weights__c &gt; 0,
Recycled_KG_from_Weights__c,

/* If Recycled_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.Recycle_KG__c &gt; 0,
/* Apply Company Average Weight if Recycle_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.Recycle_KG__c
)
)
)
)</formula>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <formula>IF(NOT(ISNULL(Tonnes_CO2_Saved_from_Weights__c)), Tonnes_CO2_Saved_from_Weights__c, 
 IF(NOT(ISNULL(Coffee_KG__c)), Coffee_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(AD_KG__c)), AD_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(Recycled_KG__c)), Recycled_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0)
)</formula>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(WTE_KG_from_Weights__c)),
WTE_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.WTE_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if WTE_KG_from_Weights__c is greater than 0 */
WTE_KG_from_Weights__c &gt; 0,
WTE_KG_from_Weights__c,

/* If WTE_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and WTE_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.WTE_KG__c &gt; 0,
/* Apply Company Average Weight if WTE_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.WTE_KG__c
)
)
)
)</formula>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <description>KG&apos;s in the sack which go to AD, assuming sack is full</description>
    <inlineHelpText>KG&apos;s in the sack which go to AD, assuming sack is full</inlineHelpText>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceExt_Test.cls
@isTest
public with sharing class InvoiceExt_Test {

	@testSetup
	static void setup() {
        TestDataHelper.insertDefaultLegalEntity('Test Entity');
    }

    @future
    private static void insertCustomSetting(){
      Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Name = 'teste', Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
      system.debug('DEBUG========================='+testRecord);
	  insert testRecord;
	}

	@isTest
	public static void InvoiceExtensionTest() {
        Test.StartTest();
        insertCustomSetting();
        Test.stopTest();
        Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
        TestDataHelper.insertSupplier('First Mile Ltd');
		system.debug('Começando testes monthly');
        Account am1, am2;
        Account parentMonthly;
        
        //Products
        List<Product2> lstProds = new List<Product2>();
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1)));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parentMonthly = new Account(
                                    Name='Sample Monthly Parent Account',
                                    InvoiceFrequency__c='Per order',
        							recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parentMonthly;

        //Insert Child Accounts
        am1 = new Account(Name='Sample Monthly Child Account 1',
                          ParentId=parentMonthly.id,
                          Enqix_Location_ID__c='123456789',
                          recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId(),
                          Enqix_Dead_Live__c = 'Live',
                          Price_Book__c = pricebookId);
        insert am1; 
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = am1.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            is_Salesforce__c = true
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = am1.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            is_Salesforce__c = true
        );
        insert ord2;

        
        Ord2.EffectiveDate = System.today().addMonths(-(20));
        update ord2;
        
        //order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100
        ));
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            UnitPrice = 100
        ));
        insert lstOLI;
        
        //This should insert 2 invoice headers, for each Order
        Ord1.Status = 'Delivered';
        Ord2.Status = 'Delivered';
        update Ord1; 
        update Ord2;
        ord1 = [select Id, Name, Status, AccountId, Account.ParentId, Created_Later__c, Invoice_Created__c, is_Salesforce__c from Order where Id = :Ord1.Id limit 1];
        ord2 = [select Id, Name, Status, AccountId, Account.ParentId, Created_Later__c, Invoice_Created__c, is_Salesforce__c from Order where Id = :Ord2.Id limit 1];
        system.debug('Order 1:'+ord1);
        system.debug('Order 2:'+ord2);
        
        List<OrderItem> lstOLIO1 = [Select Id from OrderItem where OrderId = :Ord1.Id];
        List<OrderItem> lstOLIO2 =  [Select Id from OrderItem where OrderId = :Ord2.Id];
        system.debug('Order Items on Ord1: ' + lstOLIO1.size() + '    |    Order Items on Ord2: ' + lstOLIO2.size());

        Set<Id> orderIds = new Set<Id>();
        orderIds.add(Ord1.Id);
        orderIds.add(Ord2.Id);
        List<Invoice_Header__c> headers = [SELECT Id, OrderLookUp__c, DueDate__c, Status__c, AmountInclVAT__c, InvoiceFrequency__c
                                            FROM Invoice_Header__c 
                                            WHERE Account__c = :parentMonthly.Id];

        List<Invoice_Line__c> lines = [Select Id FROM Invoice_Line__c WHERE Invoice_HeaderId__c in :headers];
        system.debug('Quantos headers? #'+headers.size());
        system.debug('Quantos invoice lines? #' + lines.size());

        Date today = system.today();
        //Change due date para testar apenas se o sch funciona
        /*for(Invoice_Header__c header : headers){
            header.DueDate__c = today;
        }*/
        //upsert(headers);
		List<Invoice_Header__c> invoicesList = new List<Invoice_Header__c>();
        Invoice_Header__c invoice1 = new Invoice_Header__c(Name='JRPG Inv1 Test Cov',
                                                         	InvoiceFrequency__c = 'Monthly',
                                                         	Account__c = parentMonthly.Id,
                                                         	Location__c = am1.Id,
                                                            Status__c = 'Draft',
                                                            Salesforce__c = true,
                                                          	DueDate__c = system.today());
        Invoice_Header__c invoice2 = new Invoice_Header__c(Name='JRPG Inv2 Test Cov',
                                                         	InvoiceFrequency__c = 'Monthly',
                                                         	Account__c = parentMonthly.Id,
                                                         	Location__c = am1.Id,
                                                            Salesforce__c = true,
                                                          	DueDate__c = system.today());
        invoicesList.add(invoice1);
        invoicesList.add(invoice2);
        insert invoicesList;
        Invoice_Line__c invoiceLine1 = new Invoice_Line__c(Name='JRPG Inv1 Line Test Cov',
                                                         	Invoice_HeaderId__c = invoice1.Id,
                                                         	Salesforce__c = true,
                                                         	Order__c = Ord1.Id,
                                                          	Location_Id__c=am1.Id,
                                                          	Amount__c=1);
        Invoice_Line__c invoiceLine2 = new Invoice_Line__c(Name='JRPG Inv2 Line Test Cov',
                                                         	Invoice_HeaderId__c = invoice2.Id,
                                                         	Salesforce__c = true,
                                                         	Order__c = Ord2.Id,
                                                          	Location_Id__c=am1.Id,
                                                          	Amount__c=1);
        insert invoiceLine1;
        insert invoiceLine2;
        for(Invoice_Header__c ih : invoicesList){
            system.debug('IH ID'+ih.Id+'      |      Inv Method: '+ ih.InvoiceFrequency__c);
            ApexPages.StandardController sc = new ApexPages.StandardController(ih);
            InvoiceExtension idre = new InvoiceExtension(sc);
			//PageReference p = idre.redirect();
            
        }

	}
	
    @isTest
	public static void InvoiceExtensionPerOrderTest() {
        TestDataHelper.insertSupplier('First Mile Ltd');
        Enqix_Id_automation__c testRecord = new Enqix_Id_automation__c(Enqix_id__c = 20000, Enqix_Location_Id__c = 30000);
		system.debug('Começando testes Per Order');
        
        //Products
        List<Product2> lstProds = new List<Product2>();
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1)));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        Account parentAccount = TestDataHelper.createAccount();
        INSERT  parentAccount;
        //Inserir accounts
        Account acc = new Account (
                                    Name='Sample Per Order Parent Account1',
                                    RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId(),
                                    parentId = parentAccount.Id,
                                    Enqix_Dead_Live__c = 'Live',
                                    Price_Book__c = pricebookId);
        insert acc;
                
        //Insert Orders for Per Order
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            is_Salesforce__c = true
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            is_Salesforce__c = true
        );
        insert ord2;
        system.debug('Ver invoice method das novas orders:  que vem do parent Id = '+acc.Id);
        system.debug('Ver invoice method das novas orders:  que vem do parent Id = '+acc.Id);
        
        Ord2.EffectiveDate = System.today().addMonths(-(20));
        update ord2;
        
        //order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100
        ));
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            UnitPrice = 100
        ));
        insert lstOLI;
        
        //This should insert 2 invoice headers, for each Order
        Ord1.Status = 'Delivered';
        Ord2.Status = 'Delivered';
        update Ord1; 
        update Ord2;
        ord1 = [select Id, Name, Status, AccountId, Account.ParentId, Created_Later__c, Invoice_Created__c, is_Salesforce__c from Order where Id = :Ord1.Id limit 1];
        ord2 = [select Id, Name, Status, AccountId, Account.ParentId, Created_Later__c, Invoice_Created__c, is_Salesforce__c from Order where Id = :Ord2.Id limit 1];
        system.debug('Order 1:'+ord1);
        system.debug('Order 2:'+ord2);
        
        List<OrderItem> lstOLIO1 = [Select Id from OrderItem where OrderId = :Ord1.Id];
        List<OrderItem> lstOLIO2 =  [Select Id from OrderItem where OrderId = :Ord2.Id];
        system.debug('Order Items on Ord1: ' + lstOLIO1.size() + '    |    Order Items on Ord2: ' + lstOLIO2.size());

        Set<Id> orderIds = new Set<Id>();
        orderIds.add(Ord1.Id);
        orderIds.add(Ord2.Id);
        List<Invoice_Header__c> headers = [SELECT Id, OrderLookUp__c, DueDate__c, Status__c, AmountInclVAT__c, InvoiceFrequency__c
                                            FROM Invoice_Header__c 
                                            WHERE Account__c = :acc.Id];

        List<Invoice_Line__c> lines = [Select Id FROM Invoice_Line__c WHERE Invoice_HeaderId__c in :headers];

        Date today = system.today();

		List<Invoice_Header__c> invoicesList = new List<Invoice_Header__c>();
        Invoice_Header__c invoice1 = new Invoice_Header__c(Name='JRPG Inv1 Test Cov',
                                                         	InvoiceFrequency__c = 'Per Order',
                                                         	Account__c = parentAccount.Id,
                                                         	Location__c = acc.Id,
                                                          	DueDate__c = today);
        Invoice_Header__c invoice2 = new Invoice_Header__c(Name='JRPG Inv2 Test Cov',
                                                         	InvoiceFrequency__c = 'Per Order',
                                                         	Account__c = parentAccount.Id,
                                                         	Location__c = acc.Id,
                                                          	DueDate__c = today);
        invoicesList.add(invoice1);
        invoicesList.add(invoice2);
        insert invoicesList;
        Invoice_Line__c invoiceLine1 = new Invoice_Line__c(Name='JRPG Inv1 Line Test Cov',
                                                         	Invoice_HeaderId__c = invoice1.Id,
                                                         	Salesforce__c = true,
                                                         	Order__c = Ord1.Id,
                                                          	Location_Id__c=acc.Id,
                                                          	Amount__c=1);
        Invoice_Line__c invoiceLine2 = new Invoice_Line__c(Name='JRPG Inv2 Line Test Cov',
                                                         	Invoice_HeaderId__c = invoice2.Id,
                                                         	Salesforce__c = true,
                                                         	Order__c = Ord2.Id,
                                                          	Location_Id__c=acc.Id,
                                                          	Amount__c=1);
        insert invoiceLine1;
        insert invoiceLine2;
        for(Invoice_Header__c ih : invoicesList){

            ApexPages.StandardController sc = new ApexPages.StandardController(ih);
            InvoiceExtensionPerOrder idre = new InvoiceExtensionPerOrder(sc);
			//PageReference p = idre.redirect();
            
        }

	}
	private static Product2 createTestProduct(String prodName, Integer recycleKG, Integer idx) {
        
        String rpGroup = (Math.mod(idx, 2) == 0)?'Cardboard':'Food Recycling';
        Product_Category__c proCat= new Product_Category__c(Name = 'Test');
		insert proCat;
        
        Product2 prod = TestDataHelper.createProduct(prodName, '123', 'Delivery', proCat.Id);
        prod.Report_Groupings__c = rpGroup;
		prod.Recycle_KG__c = recycleKG;

        return prod;
    }
}