force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/EnquixImportMappings__c/EnquixImportMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings Object that capture the mappings for the Enquix (CSV) files. Name of the individual settings instance represents a row header in the import sheet.</description>
    <label>Enquix Import Mappings</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderManager.cls
/**
* @author Zoran Zunko
* @date 10/22/15
*
* @group Order
* @group-content ../../ApexDocContent/Order
*
* @description
* Holds all constants, business logic and data retrieval methods for Order sObject
*/

public with sharing class OrderManager {

    public static Order createOrderRecordFromCSVLine(List<String> csvLine, Map<String, EnquixImportMappings__c> fieldMappings, Map<String, Integer> headerIndexMap) {

        System.debug(LoggingLevel.DEBUG, 'OrderManager createOrderRecordFromCSVLine - start');
        System.debug(LoggingLevel.FINE, 'csvLine: ' + csvLine);
        System.debug(LoggingLevel.FINE, 'fieldMappings: ' + fieldMappings);

        Order recordSObject =
                (Order)EquixImportManager.copyLineToSObject(
                        new Order()
                        , EnquixImportMappingsManager.ORDER_RECORD_GROUP
                        , csvLine
                        , fieldMappings
                        , headerIndexMap
                );

        // Commented out 2016-01-15 - sometimes these fields may not be mapped but we don't want the upload to fail
        //if(Test.isRunningTest()) {

            if(String.isBlank(recordSObject.Status)) recordSObject.Status = 'Confirmed';
            if(recordSObject.EffectiveDate == null ) recordSObject.EffectiveDate= Date.today();
        //}

        recordSObject.Account = new Account(Enqix_Location_ID__c = csvLine.get(headerIndexMap.get(EnquixImportMappingsManager.ORDER_LOCATION_ID_MAPPING)));
        recordSObject.Pricebook2Id = PricebookEntryManager.getStandardPricebookId();
        System.debug(LoggingLevel.DEBUG, 'recordSObject: ' + recordSObject);
        System.debug(LoggingLevel.DEBUG, 'OrderManager createOrderRecordFromCSVLine - end');
        return recordSObject;
    }
}