force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Waste_transfer_note_due__c.field-meta.xml
<CustomField>
    <fullName>Waste_transfer_note_due__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waste transfer note due</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/MostRecent__c.field-meta.xml
<CustomField>
    <fullName>MostRecent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>MostRecent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/wasteTransferNoteDueBatch.cls
global class wasteTransferNoteDueBatch implements Database.Batchable < sObject > {
    
    String query;
    
    global wasteTransferNoteDueBatch(){
        String Dead = 'Dead';
        query = 'SELECT Id, EndDate__c, MostRecent__c, Account__c , Account__r.Waste_transfer_note_due__c, Account__r.Enqix_Dead_Live__c From Compliance_Doc__c Where MostRecent__c = True And EndDate__c = TODAY And Account__r.Enqix_Dead_Live__c != \''+Dead+'\'';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List < SObject > scope) {
        
        Map <Account, List<Compliance_Doc__c>> accountToComplianceDocs = new Map <Account, List<Compliance_Doc__c>>();
        List <Account> accToUpdate = new List <Account>();
        for(SObject cd : scope){
            
            Compliance_Doc__c a = (Compliance_Doc__c) cd;
            
            if(accountToComplianceDocs.containskey(a.Account__r))
            {
                accountToComplianceDocs.get(a.Account__r).add(a);
            }else
            {
                List<Compliance_Doc__c> listOfcds = new List<Compliance_Doc__c>();
                listOfcds.add(a);
                accountToComplianceDocs.put(a.Account__r, listOfcds);
            }
            
            for (Account op: accountToComplianceDocs.keySet()) {
                op.Waste_transfer_note_due__c = True;
                accToUpdate.add(op);
            }
        }
        
        //Remove duplicate items from accToUpdate List
        Set<sobject> myset = new Set<sobject>();
        List<sobject> result = new List<sobject>();
        for (sobject s : accToUpdate) {
            if (myset.add(s)) {
                result.add(s);
            }
        }
        update result;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}