force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MonthsInvoicedInAdvance__c.field-meta.xml
<CustomField>
    <fullName>MonthsInvoicedInAdvance__c</fullName>
    <label>Months Invoiced in Advance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Daily_Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Daily_Dispatch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Dispatch</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>DailyDispatch__c.Dispatch_Date__c</field>
            <operation>equals</operation>
            <valueField>DailyDispatch__c.TODAY__c</valueField>
        </filterItems>
        <filterItems>
            <field>DailyDispatch__c.Dispatch_Date__c</field>
            <operation>equals</operation>
            <valueField>DailyDispatch__c.YESTERDAY__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DailyDispatch__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Order_Created__c.field-meta.xml
<CustomField>
    <fullName>Order_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BinCollectionToOrderBatch.cls
public without sharing class BinCollectionToOrderBatch implements Database.Batchable<sObject> {

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		return Database.getQueryLocator([SELECT Id FROM Account WHERE Id IN
			(SELECT Location__c FROM Collection_Waypoints__c WHERE Location__r.Parent.MonthsInvoicedInAdvance__c = null
				AND Order_Created__c = false AND Location__r.Enqix_Dead_Live__c = 'Live'
				AND Is_bin_collection__c = true AND Type__c = 'Normal' AND (Daily_Dispatch__r.EndTime__c = TODAY OR Daily_Dispatch__r.EndTime__c = YESTERDAY))]);
	}

	public void execute(Database.BatchableContext batchContext, List<Account> locations) {
		new CreateOrderFromWaypoint(locations).create();
	}

	public void finish(Database.BatchableContext batchContext) {
        Database.executeBatch(new WasteDestinationBatch());
    }
}