force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IMAGE__c.field-meta.xml
<CustomField>
    <fullName>IMAGE__c</fullName>
    <formula>IF(AND(RecordType.DeveloperName = &quot;Partner&quot;), IMAGE(&quot;/resource/Account/Type/Partner.jpg&quot;, &quot;Partner&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;), IMAGE(&quot;/resource/Account/Type/Account.jpg&quot;,&quot;Account&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Dead&quot;), IMAGE(&quot;/resource/Account/Type/Dead.jpg&quot;, &quot;Dead&quot;),
IF(AND(RecordType.DeveloperName = &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;&quot;), IMAGE(&quot;/resource/Account/Type/ProspectAccount.jpg&quot;,&quot;PAccount&quot;),
IF(RecordType.DeveloperName = &quot;Supplier&quot;, IMAGE(&quot;/resource/Account/Type/Supplier.jpg&quot;,&quot;Supplier&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;, CONTAINS(Parent_Enqix_Classification__c, &apos;Indirect&apos;)), IMAGE(&quot;/resource/Account/Type/ResellerLocation.jpg&quot;,&quot;Reseller Location&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Live&quot;), IMAGE(&quot;/resource/Account/Type/Location.jpg&quot;,&quot;Location&quot;),
IF(AND(RecordType.DeveloperName &lt;&gt; &quot;Account&quot;, TEXT(Enqix_Dead_Live__c) = &quot;Dead&quot;), IMAGE ( &quot;/resource/Account/Type/Dead.jpg&quot;,&quot;Dead&quot;), IMAGE (&quot;/resource/Account/Type/ProspectLocation.jpg&quot;,&quot;Prospect&quot;)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Real_Classification__c.field-meta.xml
<CustomField>
    <fullName>Real_Classification__c</fullName>
    <formula>IF(ISBLANK(Parent_Enqix_Classification__c), TEXT(Enqix_Classification__c), Parent_Enqix_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Real Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/classes/AccountSearchController.cls
public class AccountSearchController {

    public string PostCode {get; set;}
    public List<SelectOption> EnqixDeadLive {get; set;}
    public string selectedEnqixDeadLive {get; set;}
    public String selectedRecordTypeid {get;set;}
    public string AccountName {get;set;}
    public List<SelectOption> recordtypeLst {get;set;}
    public list<Account> accs {get; set;}
    public string AccStreet {get; set;}
    
    public AccountSearchController()
    {
        recordtypeLst = new List<SelectOption>();
        EnqixDeadLive = new List<SelectOption>();
        
        accs = new list<Account>();
        
        list<RecordType> rtlist = [Select id,Name from recordtype where sobjecttype = 'Account'];
        
        recordtypeLst.add(new SelectOption('All','All'));
        
        for(RecordType rt : rtlist)
        {
            recordtypeLst.add(new SelectOption(rt.id,rt.Name));
            if(rt.Name == 'Location'){
                selectedRecordTypeid = rt.Id;
            }
        }
        
        
        EnqixDeadLive.add(new SelectOption('none','-None-'));
        EnqixDeadLive.add(new SelectOption('Dead','Dead'));
        EnqixDeadLive.add(new SelectOption('Live','Live'));
        selectedEnqixDeadLive = 'Live';
        
        accs = [Select id,Name,BillingPostalCode,Owner.Name,IMAGE__c,Real_Classification__c,BillingStreet,BillingState,BillingCountry,BillingCity,Enqix_Dead_Live__c from Account order by LastModifiedDate desc limit 20];
    }
    
    public PageReference SearchAccount()
    {
        if((PostCode == null || PostCode == '') && (AccountName == null || AccountName == ''))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please enter either Post Code or Name to search'));
            return null;
        }
        
        String SOQL = 'Select id,Name,BillingPostalCode,Owner.Name,IMAGE__c,Real_Classification__c,BillingStreet,BillingState,BillingCountry,BillingCity,Enqix_Dead_Live__c from Account  where BillingPostalCode like \'%'+PostCode+'%\' '; 
        
        if(selectedRecordTypeid != 'All')
            SOQL += ' and Recordtypeid =:selectedRecordTypeid';
            
        if(selectedEnqixDeadLive != 'none')
            SOQL += ' and Enqix_Dead_Live__c =:selectedEnqixDeadLive';
        
        if(AccountName != null && AccountName != '')
            SOQL += ' and Name like \'%'+AccountName+'%\'';
        
        if(AccStreet != null && AccStreet != '')
            SOQL += ' and BillingStreet like \'%'+AccStreet+'%\'';
            
            
        SOQL += ' limit 1000';
        
        accs = Database.Query(SOQL);
        
        return null;
    }
}