force-app/main/default/objects/Account/fields/Enqix_Date_Made_Dead__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Date_Made_Dead__c</fullName>
    <label>Enqix Date Made Dead</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Date_Made_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Date_Made_Live__c</fullName>
    <label>Enqix Date Made Live</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_ReasonMarkedDead__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ReasonMarkedDead__c</fullName>
    <label>Enqix ReasonMarkedDead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed down</fullName>
                <label>Site Closed down</label>
            </value>
            <value>
                <fullName>Included in service charge</fullName>
                <label>Moved to a serviced office</label>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Poor Customer Support</fullName>
            </value>
            <value>
                <fullName>Delivery Issues</fullName>
            </value>
            <value>
                <fullName>Collection Reliability Issues</fullName>
            </value>
            <value>
                <fullName>Missing Features</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <label>Reseller Lost Work/Internalised</label>
            </value>
            <value>
                <fullName>FM Terminated</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {

	@testSetup static void testsetup() {
		Id locationRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
		Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		Id partnerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
		Id pricebookId = Test.getStandardPricebookId();

		Account parent = new Account();
		parent.Name = 'firstmile - parent';
		parent.Industry = 'Other';
		parent.RecordTypeId = accountRecordTypeId;
		parent.Enqix_Dead_Live__c = 'Live';
		parent.Enqix_Date_Made_Live__c = system.today();
		parent.Price_Book__c = pricebookId;
		INSERT parent;

		Account partner = new Account();
		partner.Name = 'firstmile - partner';
		partner.Industry = 'Other';
		partner.RecordTypeId = partnerRecordTypeId;
		partner.Enqix_Dead_Live__c = 'Live';
		partner.Enqix_Date_Made_Live__c = system.today();
		partner.Price_Book__c = pricebookId;
		INSERT partner;

		Account location = new Account();
		location.Name = 'firstmile - location';
		location.Industry = 'Other';
		location.RecordTypeId = locationRecordTypeId;
		location.Enqix_Dead_Live__c = 'live';
		location.Enqix_Date_Made_Live__c = system.today();
		location.Price_Book__c = pricebookId;
		location.parentId = parent.Id;
		location.Partnership__c = partner.Id;
		INSERT location;
	}

	@isTest static void testMethod1() {
        CodeOperation.setCodeOperation();
		Account parent = [SELECT Id FROM Account WHERE Name = 'firstmile - parent'];
		parent.Enqix_Dead_Live__c = 'Dead';
		parent.Enqix_ReasonMarkedDead__c = 'Other';
		parent.Enqix_Date_Made_Dead__c = system.today();
		parent.Price_Book__c = null;
		try {
			UPDATE parent;
		} catch(Exception e) {
			System.assertEquals(e.getMessage().contains('Cannot be dead as account has live location.'), true);
		}
        CodeOperation.setUserOperation();
		System.assertEquals(false, CodeOperation.isCodeOperation());
	}

	@isTest static void testMethod2() {
        CodeOperation.setCodeOperation();
		System.assertEquals(true, CodeOperation.isCodeOperation());
		Account partner = [SELECT Id FROM Account WHERE Name = 'firstmile - partner'];
		partner.Enqix_Dead_Live__c = 'Dead';
		partner.Enqix_Date_Made_Dead__c = system.today();
		partner.Price_Book__c = null;
		try {
			UPDATE partner;
		} catch(Exception e) {
			System.assertEquals(e.getMessage().contains('Cannot be dead as account has live location.'), true);
		}
        
	}
}