force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>BIDS and Partnerships</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <formula>IF(
    /* First condition: Delivery Date is less than 22/09/2024 */
    Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
    /* Use the original logic */
    IF(
        NOT(ISNULL(AD_KG_from_Weights__c)),
        AD_KG_from_Weights__c,
        Quantity * PricebookEntry.Product2.AD_KG__c
    ),

    /* Second condition: Delivery Date is on or after 22/09/2024 */
    IF(
        /* Check if AD_KG_from_Weights__c is greater than 0 */
        AD_KG_from_Weights__c &gt; 0,
        AD_KG_from_Weights__c,

        /* If AD_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
        IF(
            TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
            /* Fall Back Weight Type is &quot;No Weight&quot; */
            0,

            IF(
                /* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
                TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot; 
                &amp;&amp; PricebookEntry.Product2.AD_KG__c &gt; 0,
                /* Apply Company Average Weight if AD_KG__c is greater than 0 */
                Quantity * PricebookEntry.Product2.Estimated_Weight__c,

                /* Default value if none of the conditions match */
                Quantity * PricebookEntry.Product2.AD_KG__c
            )
        )
    )
)</formula>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(Recycled_KG_from_Weights__c)),
Recycled_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.Recycle_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if Recycled_KG_from_Weights__c is greater than 0 */
Recycled_KG_from_Weights__c &gt; 0,
Recycled_KG_from_Weights__c,

/* If Recycled_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.Recycle_KG__c &gt; 0,
/* Apply Company Average Weight if Recycle_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.Recycle_KG__c
)
)
)
)</formula>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <formula>IF(NOT(ISNULL(Tonnes_CO2_Saved_from_Weights__c)), Tonnes_CO2_Saved_from_Weights__c, 
 IF(NOT(ISNULL(Coffee_KG__c)), Coffee_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(AD_KG__c)), AD_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(Recycled_KG__c)), Recycled_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0)
)</formula>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(WTE_KG_from_Weights__c)),
WTE_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.WTE_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if WTE_KG_from_Weights__c is greater than 0 */
WTE_KG_from_Weights__c &gt; 0,
WTE_KG_from_Weights__c,

/* If WTE_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and WTE_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.WTE_KG__c &gt; 0,
/* Apply Company Average Weight if WTE_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.WTE_KG__c
)
)
)
)</formula>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <description>KG&apos;s in the sack which go to AD, assuming sack is full</description>
    <inlineHelpText>KG&apos;s in the sack which go to AD, assuming sack is full</inlineHelpText>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <externalId>true</externalId>
    <label>Enqix Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product_Category_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_Key__c</fullName>
    <externalId>true</externalId>
    <label>Product Category Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Skin__c/Product_Skin__c.object-meta.xml
<CustomObject>
    <label>Product Skin</label>
    <nameField>
        <label>Product Skin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Skins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Skin__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/Subscribed_Products__c.object-meta.xml
<CustomObject>
    <description>The combination of suppliers and its corresponding products that are being bought by the customers (locations).</description>
    <label>Subscribed Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Subscribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Products__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location to which the subscribed product is being applied.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Period__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Period__c</fullName>
    <label>Location Limit Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Half-year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Quantity__c</fullName>
    <label>Quantity Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Last_Discount_Given__c.field-meta.xml
<CustomField>
    <fullName>Last_Discount_Given__c</fullName>
    <label>Last Discount Given(Used All Quantity)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/NextRefreshDate__c.field-meta.xml
<CustomField>
    <fullName>NextRefreshDate__c</fullName>
    <label>NextRefreshDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated to this subscription.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Quantity_Remaining2__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining2__c</fullName>
    <description>new Quantity Remaining</description>
    <formula>IF(ISBLANK(Enqix_BID_Location_Limit_Quantity__c) ,100000000 - IF(ISBLANK(quantityOrdered__c), 0, quantityOrdered__c), Enqix_BID_Location_Limit_Quantity__c - IF(ISBLANK(quantityOrdered__c), 0, quantityOrdered__c))</formula>
    <inlineHelpText>new Quantity Remaining</inlineHelpText>
    <label>Quantity Remaining_</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Quantity_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining__c</fullName>
    <label>Quantity Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/quantityOrdered__c.field-meta.xml
<CustomField>
    <fullName>quantityOrdered__c</fullName>
    <label>quantityOrdered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubscribedProductTest.cls
@isTest
public class SubscribedProductTest {


    public static testmethod void testNRD(){
        Integer di = 1;
        Integer enqixid = 99992130;
        Id pricebookId = Test.getStandardPricebookId();

        //Inserir accounts
        Account parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        Account acc = TestDataHelper.insertLocation(parent.Id, null);


        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;


        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;

        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

        TestDataHelper.insertSupplier('First Mile Ltd');
        OrderItem o = new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        );
        insert o;

        Subscribed_Products__c spN = new Subscribed_Products__c(
            NextRefreshDate__c = system.today() - 10,
            Product__c = o.Product2Id, 
            Account__c = acc.Id, 
            StartDate__c = Date.newInstance(2016, 11, 01),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Annual',
            quantityOrdered__c = null,
            Enqix_ID__c = string.valueOf(enqixid)
            
            );
        insert spN;

        spN.Enqix_BID_Location_Limit_Period__c = 'Quaterly';
        update spN;

        spN.Enqix_BID_Location_Limit_Period__c = 'Monthly';
        update spN;
    }

	public static testmethod void testAnnual(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Id parentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		Account acc;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        Account parent = TestDataHelper.insertAccount();
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

        TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id,
            NextRefreshDate__c = system.today() - 10,                                                       
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Annual',
            quantityOrdered__c = null,
            Enqix_ID__c = string.valueOf(enqixid));
            o.Quantity += 10;
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
        update lstOLI;

		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());
		for(Subscribed_Products__c p: newSubs){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
            try {
                delete lstOLI.get(0);
            } catch (Exception e) {}
		}
	}

    public static testmethod void testMonthly(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id,
            NextRefreshDate__c = system.today() - 10,                                                       
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Monthly',
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());
		for(Subscribed_Products__c p: newSubs){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}

		Order Ord3 = new Order(
			AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
		);
		insert Ord3;

		lstOLI.add(new OrderItem(
            OrderId = Ord3.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(3).Id,
            UnitPrice = 100
        ));
		//update lstOLI;

        system.debug('CORRE SCH ++++++++++++++++++++++++++++++++++++++++++++');
        SubscribedProductsSch nis = new SubscribedProductsSch();
        nis.execute(null);

        //Run batch TODO - fix , Discount to Apply on Order Item does not exist in production
        Id batchjobId = Database.executeBatch(new updateQuantityOrdered_SubscribedProducts(), 100);



		
	}
    
    public static testmethod void testQuarterly(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);

        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		

		//order Items
		TestDataHelper.insertSupplier('First Mile Ltd');
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id,
            NextRefreshDate__c = system.today() - 10,
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Quarterly',
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());

        Set<Id> spIds = new Set<Id>();
        for(Subscribed_Products__c sp : newSubs){
            spIds.add(sp.Id);
        }

        List<Subscribed_Products__c> sproducts_c = [SELECT Id, quantityOrdered__c, Enqix_BID_Location_Limit_Quantity__c, Quantity_Remaining__c, Quantity_Remaining2__c
        FROM Subscribed_Products__c WHERE Id in :spIds];

		for(Subscribed_Products__c p: sproducts_c){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            Date today = system.today();
            p.NextRefreshDate__c = today;
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}
		
		

        system.debug('CORRE SCH ++++++++++++++++++++++++++++++++++++++++++++');
        SubscribedProductsSch nis = new SubscribedProductsSch();
        nis.execute(null);


		
	}



	private static Product2 createTestProduct(String prodName, Integer recycleKG, Integer idx, Integer enqix) {
        
        String rpGroup = (Math.mod(idx, 2) == 0)?'Cardboard':'Food Recycling';
        Product_Category__c pcc = new Product_Category__c(Enqix_Id__c = 91,
        	Name = 'test_product_category', Product_Category_Key__c = 'a123');
        insert pcc;

        Product_Skin__c pskins = new Product_Skin__c(Enqix_Id__c = 91,
        Name = 'test_product_skin' );
        //insert pskins;
        
		Product2 prod = TestDataHelper.createProduct(prodName, 'test1234', 'Collection', pcc.Id, null, null, string.valueOf(enqix));
        prod.Report_Groupings__c = rpGroup;
		prod.Recycle_KG__c = recycleKG;
		prod.Product_Skins__c = pskins.Id;     
        
        return prod;
    }

    public static testmethod void testAnnualEndDate(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id,
            NextRefreshDate__c = system.today() - 10,
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Annual',
            quantityOrdered__c = null,
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());
		for(Subscribed_Products__c p: newSubs){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}




		
	}

    public static testmethod void testMonthlyEndDate(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id, 
            NextRefreshDate__c = system.today() - 10,
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Monthly',
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());
		for(Subscribed_Products__c p: newSubs){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}

		Order Ord3 = new Order(
			AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
		);
		insert Ord3;

		lstOLI.add(new OrderItem(
            OrderId = Ord3.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(3).Id,
            UnitPrice = 100
        ));
		//update lstOLI;




		
	}
    
    public static testmethod void testQuarterlyEndDate(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		

		//order Items
        TestDataHelper.insertSupplier('First Mile Ltd');
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id, 
            NextRefreshDate__c = system.today() - 10,
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Quarterly',
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ');
		system.debug('How many Subscribed Products? : ' + newSubs.size());
		for(Subscribed_Products__c p: newSubs){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            p.quantityOrdered__c = null;
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}
		
		




		
	}

    public static testmethod void testQuantityOrderedNotNull(){
		system.debug('**************** COMEÇANDO TESTE DAS SUBSCRIBED PRODUCTS NOT NULL ****************');
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, null);
        
        //Insert Orders for Monthly
        Order Ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord1;
        
        Order Ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
        );
        insert ord2;

		TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = Ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = Ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));
        
        
        
        insert lstOLI;

		
		
		/*
		List<OrderItem> allOrderLines = [SELECT Id, Quantity, Product2Id, Order.AccountId 
            FROM OrderItem WHERE Product2Id = :p.Product__c and Order.AccountId = :p.Account__c]; 
		*/

		List<Subscribed_Products__c> newSubs = new List<Subscribed_Products__c>();
        Integer enqixid = 99992130;
        Integer di = 1;
		for(OrderItem o : lstOLI){
            //Em vez de  Account__c = o.Order.AccountId, pus acc.Id
			Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = o.Product2Id,
            NextRefreshDate__c = system.today() - 10,                                                       
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Annual',
            Enqix_ID__c = string.valueOf(enqixid));
           
            enqixid++;di++;
			system.debug('**************** quero inserir uma nova subscribed product ****************');
			newSubs.add(sp);
		} 
		insert newSubs;

        system.debug(' QUANTOS NEW SUBS EXISTEM-> '+newSubs.size());

        Set<Id> subs = new Set<Id>();
        for(Subscribed_Products__c po : newSubs){
            subs.add(po.Id);
        }
        system.debug('Quantos Ids dos Subs existem? -> ' + subs.size());

        List<Subscribed_Products__c> real = [SELECT Id, quantityOrdered__c, Enqix_BID_Location_Limit_Quantity__c, Quantity_Remaining2__c, Quantity_Remaining__c
        FROM Subscribed_Products__c WHERE Id in :subs];
        
        system.debug('Lista da query tem -> '+real.size() +' subs');
 
		for(Subscribed_Products__c p: real){
			system.debug('# Quantity Ordered: ' + p.quantityOrdered__c + ', Quantity Limit : ' + p.Enqix_BID_Location_Limit_Quantity__c + ', Quantity Remaining1 e 2: ' + p.Quantity_Remaining__c + ' ; ' + p.Quantity_Remaining2__c);
			//TODO It's Quantity_Remaining2__c  because can't change default one to Formula Field Type.
            p.NextRefreshDate__c = system.today();
            system.debug('METE A NEXT REFRESH DATE DATA DE HOJE -> '+p.NextRefreshDate__c);
            update p;
		}
	}
	
    public static testmethod void testCoverageMore(){
		Account acc;
        Account parent;

		//Products
        List<Product2> lstProds = new List<Product2>();
        
        for (Integer i=0; i<11; i++) {
            lstProds.add(createTestProduct('Prod-' + (i+1), 100, (i+1), 8765+i));
        }
        insert lstProds;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        List<PricebookEntry> lstStandardPrice = new List<PricebookEntry>();
        
        for (Integer i=0; i<11; i++) {
            lstStandardPrice.add(new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = lstProds.get(i).Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert lstStandardPrice;
        
        //Inserir accounts
        parent = new Account(Name='Sample Monthly Parent Account', InvoiceFrequency__c='Monthly', recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId());
        insert parent;
        
        Account partner = TestDataHelper.insertPartner();

        //Insert Child Accounts
        acc = TestDataHelper.insertLocation(parent.Id, partner.Id);
        
        Integer enqixid = 99992130;
        Integer di = 1;
        
        //Insert subscribedProduct
        Subscribed_Products__c sp = new Subscribed_Products__c( Product__c = lstProds.get(1).Id, 
            NextRefreshDate__c = system.today() - 10,                                                         
            Account__c = acc.Id, 
            StartDate__c = system.today().addDays(di),
            EndDate__c = system.today().addDays(di+993),
            Last_Discount_Given__c = Date.newInstance(2017,01,01),
            Enqix_BID_Location_Limit_Quantity__c = 10,
            Enqix_BID_Location_Limit_Period__c = 'Monthly',
            Enqix_ID__c = string.valueOf(enqixid));

        
        //Insert Orders for Monthly
        Order ord1 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(1)),
            Delivery_Date__c = System.today().addMonths(-(1)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            Enqix_Order_Summary__c = 'aa',
            is_salesforce__c = true
        );
        insert ord1;
        
        Order ord2 = new Order(
            AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId,
            Enqix_Order_Summary__c = null,
            is_salesforce__c = true
        );
        insert ord2;

		TestDataHelper.insertSupplier('First Mile Ltd');
		//order Items
        List<OrderItem> lstOLI = new List<OrderItem>();
        lstOLI.add(new OrderItem(
            OrderId = ord1.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(1).Id,
            UnitPrice = 100,
            Product2Id = lstProds.get(1).Id,
            Discount_to_Apply__c = 'Partner',
            Partner_Unit_Price__c = 1
        ));
        
        lstOLI.add(new OrderItem(
            OrderId = ord2.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(2).Id,
            Product2Id = lstProds.get(2).Id,
            UnitPrice = 100
        ));        
        insert lstOLI;
        
		//system.debug('Ordered Quantity in the new Subscribed Products inserted: ')

		Order Ord3 = new Order(
			AccountId = acc.id,
            EffectiveDate = System.today().addMonths(-(2)),
            Delivery_Date__c = System.today().addMonths(-(2)),
            Status = 'Confirmed',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Pricebook2Id = pricebookId
		);
		insert Ord3;

		lstOLI.add(new OrderItem(
            OrderId = Ord3.Id,
            Quantity = 1,
            PriceBookEntryId = lstStandardPrice.get(3).Id,
            UnitPrice = 100
        ));
		//update lstOLI;
        
        system.debug('CORRE SCH ++++++++++++++++++++++++++++++++++++++++++++');
        SubscribedProductsSch nis = new SubscribedProductsSch();
        nis.execute(null);
        Test.startTest();
        SubscribedProductRefreshBatch c = new SubscribedProductRefreshBatch();
        Database.executeBatch(c);
        Test.stopTest();
	
	}
}