force-app/main/default/objects/Account/fields/Enqix_Dead_Live__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Dead_Live__c</fullName>
    <inlineHelpText>This field is Controlled by Quick Action &quot;Set Live&quot;.</inlineHelpText>
    <label>Enqix Dead Live</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What made them get in touch ?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Got a leaflet</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Saw trucks or sacks on street.</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
            <value>
                <fullName>Office* Exhibition (2012)</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Council website referral</fullName>
            </value>
            <value>
                <fullName>500 offices project</fullName>
            </value>
            <value>
                <fullName>Dead lead</fullName>
            </value>
            <value>
                <fullName>Used us before</fullName>
            </value>
            <value>
                <fullName>Chatter Picture</fullName>
            </value>
            <value>
                <fullName>Giveaway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/ReceivedWaypoint__c/ReceivedWaypoint__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint</label>
    <nameField>
        <label>Route</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Received Waypoints</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Received Waypoints</relationshipLabel>
    <relationshipName>ReceivedWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecivedWaypointStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/ReceivedWaypointGroup__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint Group</label>
    <nameField>
        <displayFormat>GRP-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Received Waypoint Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecivedWaypointSource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/RecivedWaypointSource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RaaS</fullName>
    </customValue>
    <masterLabel>Recived Waypoint Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RecivedWaypointStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Recived Waypoint Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReceivedWaypointTest.cls
@isTest
public class ReceivedWaypointTest {

	private static final Date waypointDate = System.today();
	private static final String source = 'RaaS';

	@TestSetup
	static void testData() {
		String timestamp = '2023-05-26 16:53:00';
		Id locatonRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
		Id parentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();

		Account parentAccount = new Account(Name='Parent', RecordtypeId=parentRecordTypeId);
		INSERT parentAccount;
		Account location = new Account(Name=source, ParentId=parentAccount.Id, RecordtypeId=locatonRecordTypeId, Price_Book__c = Test.getStandardPricebookId(), Enqix_Dead_Live__c = 'Live');
		INSERT location;
		
		List<Order> orderList = new List<Order>();
		for (Integer i=0; i<7; i++) {
			orderList.add(new Order(AccountId=location.Id, EffectiveDate=System.today(), Status='Draft'));
		}
		INSERT orderList;

		// Queried again to get orders in sequence
		orderList = [SELECT Id FROM Order ORDER BY OrderNumber];
		List<ReceivedWaypoint__c> receivedWaypointList = new List<ReceivedWaypoint__c>();
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 0', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=00, Order__c=orderList[0].Id));
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 1', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=01, Order__c=orderList[1].Id));
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 1', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=02, Order__c=orderList[2].Id));
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 2', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=03, Order__c=orderList[3].Id));
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 2', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=04, Order__c=orderList[4].Id));
		INSERT receivedWaypointList;

		Test.startTest();
		ReceivedWaypointGroup__c waypointGroup = new ReceivedWaypointGroup__c(Date__c=waypointDate, Source__c=source, Timestamp__c=timestamp);
		INSERT waypointGroup;
		Test.stopTest();

		for (ReceivedWaypoint__c receivedWaypoint : receivedWaypointList) {
			Test.setCreatedDate(receivedWaypoint.Id, Datetime.now().addDays(-31));
		}
		Test.setCreatedDate(waypointGroup.Id, Datetime.now().addDays(-31));
	}

	@IsTest
	static void variation1() {
		Assert.areEqual(3, [SELECT Id FROM maps__Route__c].size(), '3 Routes are inserted');
		Assert.areEqual(5, [SELECT Id FROM maps__Waypoint__c].size(), '5 wayspoints are inserted');
		Assert.areEqual(1, [SELECT Id FROM ReceivedWaypointGroup__c WHERE Status__c = 'Complete'].size(), 'Group insertion completed');
		Assert.areEqual(5, [SELECT Id FROM ReceivedWaypoint__c WHERE Status__c = 'Complete'].size(), '5 ReceivedWaypoints are completed');
	}

	@IsTest
	static void  variation2To7() {
		String timestamp = '2023-05-26 16:55:00';
		List<Order> orderList = [SELECT Id FROM Order ORDER BY OrderNumber];
		List<ReceivedWaypoint__c> receivedWaypointList = new List<ReceivedWaypoint__c>();
		// New Route added and New Waypoint
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 3', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=05, Order__c=orderList[5].Id));
		// Route change and Delete Route 0
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 3', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=00, Order__c=orderList[0].Id));
		// Sequnece change
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 1', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=10, Order__c=orderList[1].Id));
		// Route & sequence change
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 3', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=20, Order__c=orderList[2].Id));
		// New waypoint on existing Routes 
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 2', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=03, Order__c=orderList[6].Id));
		// Delete exisitng waypoint
		// receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 2', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=03, Order__c=orderList[3].Id));
		// No change
		receivedWaypointList.add(new ReceivedWaypoint__c(Name='Route 2', Date__c=waypointDate, Timestamp__c=timestamp, Source__c=source, SequenceNumber__c=04, Order__c=orderList[4].Id));
		INSERT receivedWaypointList;

		Test.startTest();
		INSERT new ReceivedWaypointGroup__c(Date__c=waypointDate, Source__c=source, Timestamp__c=timestamp);
		Test.stopTest();

		Assert.areEqual(3, [SELECT Id FROM maps__Route__c].size(), '3 Routes are inserted');
		Assert.areEqual(6, [SELECT Id FROM maps__Waypoint__c].size(), '6 wayspoints are inserted');
		Assert.areEqual(2, [SELECT Id FROM ReceivedWaypointGroup__c WHERE Status__c = 'Complete'].size(), '2 Group insertion completed');
		Assert.areEqual(11, [SELECT Id FROM ReceivedWaypoint__c WHERE Status__c = 'Complete'].size(), '11 ReceivedWaypoints are completed');
	}

	@IsTest
	static void deleteOlderWaypointsTest() {
		Assert.isTrue([SELECT Id FROM ReceivedWaypoint__c].size() != 0, 'Received waypoints are expected to be found');
		Assert.isTrue([SELECT Id FROM ReceivedWaypointGroup__c].size() != 0, 'ReceivedWaypointGroup are expected to be found');

		Test.startTest();
		ReceivedWaypointDeleteBatch.deleteOlderReceivedWaypoints();
		Test.stopTest();

		Assert.isTrue([SELECT Id FROM ReceivedWaypoint__c].size() == 0, 'All Received waypoints are expected to delete');
		Assert.isTrue([SELECT Id FROM ReceivedWaypointGroup__c].size() == 0, 'All ReceivedWaypointGroup are expected to delete');
	}
}