force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Suppliers__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/WasteTransferNoteRedirectExtensionTest.cls
@isTest
public class WasteTransferNoteRedirectExtensionTest {

	@isTest
	static void redirect() {
		Account parentAccount = TestDataHelper.createAccount();
		parentAccount.Name = 'First Mile';
		INSERT parentAccount;
		Account childAccount = TestDataHelper.createLocation(parentAccount.Id, null);
		INSERT childAccount;

		Contact contact = TestDataHelper.insertContact(parentAccount.Id, 'FM');
		TestDataHelper.insertAccountContactRelation(childAccount.Id, contact.Id, 'Service Contact;Finance Contact');

		Order order = TestDataHelper.insertOrder(childAccount.Id);
		Attachment attachment = new Attachment(ParentId = order.Id, Name = 'POD_'+order.Enqix_Id__c+'.jpg', Body = Blob.valueOf('Test Data'));
		INSERT attachment;

		ContentVersion contentVersion = new ContentVersion(Title = 'POD_image_', VersionData = Blob.valueOf('test'), PathOnClient = 'POD_image_');
		INSERT contentVersion;
		Id ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id LIMIT 1].ContentDocumentId;
		ContentDocumentLink contentDocumentLink = new ContentDocumentLink(ContentDocumentId = contentDocumentId, LinkedEntityId = order.Id, ShareType = 'I');
		INSERT contentDocumentLink;

		Suppliers__c supp = new Suppliers__c();
		supp.Name = 'First Mile Ltd';
		supp.Phone_Number__c = '123456789';
		INSERT supp;

		Compliance_Doc__c cdoc = new Compliance_Doc__c();
		cdoc.RecordTypeId = Schema.SObjectType.Compliance_Doc__c.getRecordTypeInfosByName().get('Waste Transfer Notes').getRecordTypeId();
		cdoc.Name = 'test cdoc';
		cdoc.Account__c = childAccount.Id;
		cdoc.Contractor__c = supp.Id;
		cdoc.StartDate__c = system.today();
		cdoc.EndDate__c = System.today() + 10;
		INSERT cdoc;

		new WasteTransferNoteRedirectExtension(new ApexPages.StandardController(cdoc)).redirect();
		new WasteTransferNoteExtension(new ApexPages.StandardController(cdoc));
	}
}