force-app/main/default/objects/Account/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The location Id from Enqix system</description>
    <externalId>true</externalId>
    <inlineHelpText>The location Id assigned in Enqix system</inlineHelpText>
    <label>Enqix Location ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Order ID as defined in Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order ID as defined in Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Enqix_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Location_ID__c</fullName>
    <label>Enqix Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enqix_Id__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Id__c</fullName>
    <description>Id from Enqix system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Id from Enqix system.</inlineHelpText>
    <label>Enqix Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/Subscribed_Products__c.object-meta.xml
<CustomObject>
    <description>The combination of suppliers and its corresponding products that are being bought by the customers (locations).</description>
    <label>Subscribed Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Subscribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Products__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location to which the subscribed product is being applied.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Period__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Period__c</fullName>
    <label>Location Limit Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Half-year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_ID__c.field-meta.xml
<CustomField>
    <fullName>Enqix_ID__c</fullName>
    <externalId>true</externalId>
    <label>Enqix ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/NextRefreshDate__c.field-meta.xml
<CustomField>
    <fullName>NextRefreshDate__c</fullName>
    <label>NextRefreshDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product associated to this subscription.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscribed Products</relationshipLabel>
    <relationshipName>Subscribed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/quantityOrdered__c.field-meta.xml
<CustomField>
    <fullName>quantityOrdered__c</fullName>
    <label>quantityOrdered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SubscribedProductsTriggerHelper.cls
public with sharing class SubscribedProductsTriggerHelper {

	
	public void populateQuantityOrdered(List < Subscribed_Products__c > subcribed_products) {
		List < Subscribed_Products__c > updateList = new List < Subscribed_Products__c > ();
		//This list needs to be updated because it is being ran for AFTER insert on the trigger, to update the quantityOrdered.
		Set < Id > subscribedProductsIds = new Set < Id > ();
		//To take the select out of the loop, needs to be created 2 set of id's, product id and account id 
		Set < Id > productIds = new Set < Id > ();
		Set < Id > accountIds = new Set < Id > ();

		for (Subscribed_Products__c p: subcribed_products) {
			subscribedProductsIds.add(p.Id);
			productIds.add(p.Product__c);
			accountIds.add(p.Account__c);
		}
		system.debug('TAMANHO LISTA PRODUCTS ' + productIds.size());
		system.debug('Tamanho Lista Accounts ' + accountIds.size());

		List < Subscribed_Products__c > subscribedProductsData = [SELECT NextRefreshDate__c, StartDate__c, Account__r.Enqix_Location_ID__c,
			Account__r.RecordType.DeveloperName, Product__r.Enqix_Id__c, Product__r.Name, quantityOrdered__c, Product__c
			FROM Subscribed_Products__c WHERE Id IN: subscribedProductsIds];

		List < OrderItem > allOrderLines = [SELECT Id, CreatedDate, Quantity, Product2Id, Order.AccountId
			FROM OrderItem WHERE Product2Id in: productIds and Order.AccountId in: accountIds];
		//Debugs
		system.debug('------> Quantas OrderItems que tem em comum o Product e Account dos Subscribed Products? ->' + allOrderLines.size());
		for (Id pid: productIds) {
			system.debug('Id do produto-> ' + pid);
		}
		for (Id aid: accountIds) {
			system.debug('Id da Conta-> ' + aid);
		}

		for (Subscribed_Products__c p: subscribedProductsData) {
			if (p.quantityOrdered__c == null) p.quantityOrdered__c = 0;
			system.debug('Entrou um novo Subscribed Product! quantity ordered = ' + p.quantityOrdered__c);
			for (OrderItem i: allOrderLines) {
				/* Bruno - 11.02.2019 -> 1365 */
				if(i.CreatedDate > p.StartDate__c /*&& i.Product2Id == p.Product__c*/){ //CHanged Here to do this.
					system.debug('Para cada nova OrderItem incrementa a quantidade.\n Só Para Order Items criados após Start Date do S.B. ');
					p.quantityOrdered__c += i.Quantity;
					system.debug('Quantidade desta OrderItem --> ' + i.Quantity);
				}
				
			}
			updateList.add(p);
			system.debug('Nova quantity Ordered = ' + p.quantityOrdered__c);
		}


		if (updateList.size() > 0) {
			system.debug('updatelist::::' + updateList);
			Map<Id,Subscribed_Products__c> removeD = new Map<Id, Subscribed_Products__c>();
			for(Subscribed_Products__c ppp : updateList){
				removeD.put(ppp.Id, ppp);
			}
			List<Subscribed_Products__c> updateListWithoutDups = new List<Subscribed_Products__c>(removeD.values());
			update updateListWithoutDups;
		}
	}

	public void updateData(List < Subscribed_Products__c > lista) {
		boolean hasChanged = false;
		for (Subscribed_Products__c p: lista) {
			hasChanged = updateQuantityOrdered(p);


			if (hasChanged) {
				updateNextRefreshDate(p);
			}
			if (p.NextRefreshDate__c == null) {
				populateFirstNextRefreshDate(p);
			}
		}
	}


	public void updateNextRefreshDate(Subscribed_Products__c p) {
		switch on p.Enqix_BID_Location_Limit_Period__c {
			when 'Annual' {
				p.NextRefreshDate__c = Date.newInstance(p.NextRefreshDate__c.year() + 1, p.NextRefreshDate__c.month(), p.NextRefreshDate__c.day());
			}
			when 'Quarterly' {
				p.NextRefreshDate__c = Date.newInstance(p.NextRefreshDate__c.year(), p.NextRefreshDate__c.month() + 3, p.NextRefreshDate__c.day());
			}
			when 'Monthly' {
				p.NextRefreshDate__c = Date.newInstance(p.NextRefreshDate__c.year(), p.NextRefreshDate__c.month() + 1, p.NextRefreshDate__c.day());
			}
            //Jira 1947 -- add new option "Half-year" to the picklist Enqix_BID_Location_Limit_Period__c
            when 'Half-year' {
				p.NextRefreshDate__c = Date.newInstance(p.NextRefreshDate__c.year(), p.NextRefreshDate__c.month() + 6, p.NextRefreshDate__c.day());
			}
		}
	}


	public void populateFirstNextRefreshDate(Subscribed_Products__c p) {
		system.debug('Attempting to populate the Next Refresh Date');
		if(p.StartDate__c == null){
			system.debug('Could not populate Next Refresh Date because the Start Date is null. Please fill the Start Date.');
			return;
		}
		
		switch on p.Enqix_BID_Location_Limit_Period__c {
			when 'Annual' {
				system.debug('p.StartDate__c ' + p.StartDate__c );
				p.NextRefreshDate__c = Date.newInstance(p.StartDate__c.year() + 1, p.StartDate__c.month(), p.StartDate__c.day());
				
			}
			when 'Quarterly' {
				p.NextRefreshDate__c = Date.newInstance(p.StartDate__c.year(), p.StartDate__c.month() + 3, p.StartDate__c.day());
			}
			when 'Monthly' {
				p.NextRefreshDate__c = Date.newInstance(p.StartDate__c.year(), p.StartDate__c.month() + 1, p.StartDate__c.day());
			}
		}
		if(p.NextRefreshDate__c != null){
			system.debug('Next Refresh Date populated!');
		} 
	}

	public boolean updateQuantityOrdered(Subscribed_Products__c p) {
		boolean flag = false;
		if (p.NextRefreshDate__c <= system.today()) {
			p.quantityOrdered__c = 0;
			flag = true;
		}
		return flag;
	}


	

}