force-app/main/default/objects/Account/fields/FinanceContact__c.field-meta.xml
<CustomField>
    <fullName>FinanceContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/LineCount__c.field-meta.xml
<CustomField>
    <fullName>LineCount__c</fullName>
    <label>Line Count</label>
    <summaryForeignKey>Invoice_Line__c.Invoice_HeaderId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Orders (Monthly Parent Invoice)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendGridSetting__c/SendGridSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SendGrid Setting</label>
</CustomObject>

force-app/main/default/objects/SendGridSetting__c/fields/IsInvoiceEmailEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsInvoiceEmailEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Invoice Email?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendGridSetting__c/fields/MaxInvoiceLinesForPDFGeneration__c.field-meta.xml
<CustomField>
    <fullName>MaxInvoiceLinesForPDFGeneration__c</fullName>
    <label>Maximum Invoice Lines For PDF Generation</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SendInvoiceEmail__c/SendInvoiceEmail__c.object-meta.xml
<CustomObject>
    <description>Invoices to be generated as PDF and sent as email</description>
    <label>Send Invoice Email</label>
    <nameField>
        <displayFormat>InvoiceEmail-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Send Invoice Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendInvoiceEmail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Send Invoice Emails</relationshipLabel>
    <relationshipName>InvoiceEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendInvoiceEmail__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Send Invoice Emails</relationshipLabel>
    <relationshipName>InvoiceEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendInvoiceEmail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Error - Finance Contact</fullName>
            </value>
            <value>
                <fullName>Error - No Lines</fullName>
            </value>
            <value>
                <fullName>Error - More Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendInvoiceEmailBatch.cls
public class SendInvoiceEmailBatch implements Database.Batchable<sObject>, Schedulable {

	private static final String[] STATUS_TO_PROCESS = new String[]{'New', 'Retry'};
	private static final SendGridSetting__c SEND_GRID = SendGridSetting__c.getOrgDefaults();

	@InvocableMethod(label='Send Invoice Email Batch')
	public static void sendEmails() {
		Database.executeBatch(new SendInvoiceEmailBatch(), 25);
	}

	public void execute(SchedulableContext sc) {
		sendEmails();
	}

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		if (!SEND_GRID.IsInvoiceEmailEnabled__c) {
			// DUMMY, no rows returned
			String query = 'SELECT Id FROM SendInvoiceEmail__c WHERE CreatedDate = NEXT_YEAR';
			return Database.getQueryLocator(query);
		}

		String query = 'SELECT Invoice__c, Invoice__r.LineCount__c, Invoice__r.Account__r.FinanceContact__c FROM SendInvoiceEmail__c WHERE Status__c IN :STATUS_TO_PROCESS ORDER BY Invoice__r.LineCount__c';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext batchContext, List<SendInvoiceEmail__c> invoiceEmails) {
		List<Id> invoiceIds = new List<Id>();
		for (SendInvoiceEmail__c invoiceEmail : invoiceEmails) {
			if (invoiceEmail.Invoice__r.LineCount__c == 0) {
				invoiceEmail.Status__c = 'Error - No Lines';
			} else if (invoiceEmail.Invoice__r.LineCount__c > SEND_GRID.MaxInvoiceLinesForPDFGeneration__c) {
				invoiceEmail.Status__c = 'Error - More Lines';
			} else if (invoiceEmail.Invoice__r.Account__r.FinanceContact__c == null) {
				invoiceEmail.Status__c = 'Error - Finance Contact';
			} else {
				invoiceEmail.Status__c = 'Sent';
				invoiceIds.add(invoiceEmail.Invoice__c);
			}
			invoiceEmail.Account__c = invoiceEmail.Invoice__r.Account__c;
		}

		SendInvoiceEmail.send(invoiceIds);
		UPDATE invoiceEmails;
	}

	private static Map<Id, List<Id>> groupByAccount(List<SendInvoiceEmail__c> invoiceEmails) {
		Map<Id, List<Id>> accountToInvoice = new Map<Id, List<Id>>();
		for (SendInvoiceEmail__c invoiceEmail : invoiceEmails) {
			if (accountToInvoice.containsKey(invoiceEmail.Invoice__r.Account__c)) {
				accountToInvoice.get(invoiceEmail.Invoice__r.Account__c).add(invoiceEmail.Invoice__c);
			} else {
				accountToInvoice.put(invoiceEmail.Invoice__r.Account__c, new List<Id>{invoiceEmail.Invoice__c});
			}
		}

		return accountToInvoice;
	}

	public void finish(Database.BatchableContext batchContext) {}
}