force-app/main/default/objects/Account/fields/FirstPost__c.field-meta.xml
<CustomField>
    <fullName>FirstPost__c</fullName>
    <formula>LEFT( BillingPostalCode , FIND(&quot; &quot;,  BillingPostalCode ) - 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPost</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>Street Name. Used to match to put out times so must match spelling from put out times exactly</description>
    <label>Street Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Put_Out_Time__c/Put_Out_Time__c.object-meta.xml
<CustomObject>
    <label>Put Out Time</label>
    <nameField>
        <label>Put Out Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Put Out Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Put_Out_Time__c/fields/First_Post__c.field-meta.xml
<CustomField>
    <fullName>First_Post__c</fullName>
    <formula>Postcode__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Post</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Put_Out_Time__c/fields/Put_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Put_Out_Time__c</fullName>
    <defaultValue>&quot;00:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Put Out Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Put_Out_Time__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PutOutTimeController.cls
public without sharing class PutOutTimeController {

	// Method to fetch relevant Put Out Times
	@AuraEnabled(cacheable=true)
	public static List<Put_Out_Time__c> getRelevantPutOutTimes(Id accountId) {
		// Query the account to get its postcode and street
		Account account = [SELECT FirstPost__c, Street_Name__c FROM Account WHERE Id = :accountId LIMIT 1];

		// Return the matching Put Out Time records
		List<Put_Out_Time__c> putoutTimes = [SELECT Street_Name__c, Put_Out_Time__c FROM Put_Out_Time__c
			WHERE First_Post__c = :account.FirstPost__c AND Street_Name__c = :account.Street_Name__c
			ORDER BY Put_Out_Time__c];

		return putoutTimes.isEmpty() ? null : putoutTimes;
	}
}