force-app/main/default/objects/Account/fields/gaconnector_First_Click_Campaign__c.field-meta.xml
<CustomField>
    <fullName>gaconnector_First_Click_Campaign__c</fullName>
    <label>First Click Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/gaconnector_First_Click_Landing_Page__c.field-meta.xml
<CustomField>
    <fullName>gaconnector_First_Click_Landing_Page__c</fullName>
    <label>First Click Landing Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Estimated_Annual_Sales__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Annual_Sales__c</fullName>
    <label>Estimated Annual Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/gaconnector_First_Click_Landing_Page__c.field-meta.xml
<CustomField>
    <fullName>gaconnector_First_Click_Landing_Page__c</fullName>
    <label>First Click Landing Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/gaconnector_First_Click_Medium__c.field-meta.xml
<CustomField>
    <fullName>gaconnector_First_Click_Medium__c</fullName>
    <label>First Click Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/gaconnector_First_Click_Term__c.field-meta.xml
<CustomField>
    <fullName>gaconnector_First_Click_Term__c</fullName>
    <label>First Click Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>How did they contact us?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce Sign-up</fullName>
            </value>
            <value>
                <fullName>Inbound Email</fullName>
            </value>
            <value>
                <fullName>Inbound Phone</fullName>
            </value>
            <value>
                <fullName>Inbound Website Enquiry</fullName>
            </value>
            <value>
                <fullName>Outbound Contact</fullName>
            </value>
            <value>
                <fullName>Website Live-chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InfinitySftpEmailServiceTest.cls
@isTest
private class InfinitySftpEmailServiceTest {

	@TestSetup
	static void makeData(){
		Account parentAccount = TestDataHelper.insertAccount();
		Account locationAccount = TestDataHelper.insertLocation(parentAccount.Id, null);

		INSERT new Opportunity(Name = 'Test Opp', CloseDate = date.today().addDays(30), StageName = 'Discovery', Estimated_Annual_Sales__c = 10000, AccountId = locationAccount.Id, Type__c = 'Inbound Phone');
	}

	@isTest
	static void emailWithAttachment() {
		Messaging.InboundEmail email = new Messaging.InboundEmail();
		email.subject = 'Test Email';

		Opportunity opp = [SELECT Id FROM Opportunity];
		Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
		binaryAttachment.fileName = 'FileFromInfinity.csv';
		binaryAttachment.body = Blob.valueOf('Channel, Trigger Title, Campaign, Channel Type, HTTP URL, Keyword\n'
									+ 'Paid Search, ' + opp.Id + ', Generic - Search - Waste, ppc, https://www.thefirstmile.co.uk/, waste collection london');
		email.binaryAttachments = new List<Messaging.InboundEmail.BinaryAttachment>{binaryAttachment};

		Test.startTest();
		new InfinitySftpEmailService().handleInboundEmail(email, new Messaging.InboundEnvelope());
		Test.stopTest();

		opp = [SELECT Id, gaconnector_First_Click_Channel__c, gaconnector_First_Click_Campaign__c, gaconnector_First_Click_Term__c,
						gaconnector_First_Click_Medium__c, gaconnector_First_Click_Landing_Page__c FROM Opportunity WHERE Id = :opp.Id];
		Assert.areEqual('Paid Search', opp.gaconnector_First_Click_Channel__c);
		Assert.areEqual('Generic - Search - Waste', opp.gaconnector_First_Click_Campaign__c);
		Assert.areEqual('waste collection london', opp.gaconnector_First_Click_Term__c);
		Assert.areEqual('cpc', opp.gaconnector_First_Click_Medium__c);
		Assert.areEqual('https://www.thefirstmile.co.uk/', opp.gaconnector_First_Click_Landing_Page__c);
	}
}