force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceHeaderOverdueDaysBatchTest.cls
@isTest
public class InvoiceHeaderOverdueDaysBatchTest {
	static testMethod void testMethod1() {
		Account parentAccount = TestDataHelper.insertAccount();
		Account account = TestDataHelper.insertLocation(parentAccount.Id, null);

		Invoice_Header__c invoiceHeader = new Invoice_Header__c();
		invoiceHeader.Name = 'FM Invoice Header';
		invoiceHeader.Account__c = parentAccount.Id;
		invoiceHeader.InvoiceFrequency__c = 'Per Order';
		INSERT invoiceHeader;

		Test.startTest();
		InvoiceHeaderOverdueDaysBatch.updateOverdueDays();
		Test.stopTest();
	}
}