force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/previous_email__c.field-meta.xml
<CustomField>
    <fullName>previous_email__c</fullName>
    <label>previous_email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerTest.cls
@isTest
public with sharing class ContactTriggerTest {

	public static testmethod void UnitTest(){
		Account acc = TestDataHelper.createAccount();
		acc.InvoiceFrequency__c = 'Monthly';
		INSERT acc;
		Contact novo = new Contact(LastName='teste', AccountId = acc.Id, Email = 'cerm@xpand-it.com');
		INSERT novo;

		system.debug('Inserido novo Contacto.');
		novo.Email = 'novo@xpand-it.com';
		update novo;
		Contact este = [SELECT LastName, previous_email__c, Email FROM Contact WHERE LastName = 'teste'];
		system.debug('Feito o update to contacto... vamos ver o previous email agora:' + este.previous_email__c + '. E o novo é: '+este.Email);

	}
}