force-app/main/default/objects/Account/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsInvoiceFrequencyOverride__c.field-meta.xml
<CustomField>
    <fullName>IsInvoiceFrequencyOverride__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Frequency Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>InvoiceFrequency__c</fullName>
    <label>Invoice Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used when invoice is for a specific location</description>
    <inlineHelpText>Field used when invoice is for a specific location</inlineHelpText>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers (Location)</relationshipLabel>
    <relationshipName>Location_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/InvoiceFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Order</fullName>
        <label>Invoice Every Order</label>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
        <label>Consolidate All Weekly (Monday)</label>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
        <label>Consolidate All Twice Monthly (1st, 16th)</label>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <label>Consolidate All Monthly</label>
    </customValue>
    <customValue>
        <fullName>Quarterly - Advance</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly - Scheduled</fullName>
        <label>Monthly - Consolidate Scheduled Only</label>
    </customValue>
    <customValue>
        <fullName>Monthly - Separated</fullName>
        <label>Monthly - Consolidate Scheduled, Consolidate Ad-Hoc</label>
    </customValue>
    <masterLabel>Invoice Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceClosureSchedularTest.cls
@isTest
public class InvoiceClosureSchedularTest {
	@testSetup static void setupMethod() {
		TestDataHelper.insertVat();
		
		Account parentAccount = new Account();
		parentAccount.Name = 'FM Account';
		parentAccount.InvoiceFrequency__c = Invoicing.FREQUENCY_MONTHLY;
		parentAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		INSERT parentAccount;
		
		Account childLocation = new Account();
		childLocation.Name = 'FM Location';
		childLocation.ParentId = parentAccount.Id;
		childLocation.IsInvoiceFrequencyOverride__c = true;
		childLocation.InvoiceFrequency__c = Invoicing.FREQUENCY_MONTHLY;
		childLocation.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
		INSERT childLocation;

		Date yesterday = System.today() - 1;
		List<Invoice_Header__c> invoiceHeaderList = new List<Invoice_Header__c>();
		invoiceHeaderList.add(new Invoice_Header__c(Name = 'Periodic Invoice', Account__c = parentAccount.Id, Location__c = childLocation.Id, Status__c = Invoicing.STATUS_OPEN,
													Salesforce__c = true, InvoiceFrequency__c = Invoicing.FREQUENCY_MONTHLY, DueDate__c = yesterday));
		invoiceHeaderList.add(new Invoice_Header__c(Name = 'Immediate Invoice', Account__c = parentAccount.Id, Location__c = childLocation.Id, Status__c = Invoicing.STATUS_OPEN,
													Salesforce__c = true, InvoiceFrequency__c = Invoicing.FREQUENCY_IMMEDIATE, DueDate__c = yesterday));

		INSERT invoiceHeaderList;
	}

	static testMethod void closeInvoice1() {
		Invoice_Header__c immediateInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Immediate Invoice'];
		System.assertEquals(immediateInvoice.Status__c, Invoicing.STATUS_CLOSED, 'Invoice must be closed on creation' );

		Invoice_Header__c periodicInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Periodic Invoice'];
		System.assertEquals(periodicInvoice.Status__c, Invoicing.STATUS_OPEN, 'Invoice must be open before batch execution' );

		InvoiceClosureScheduler invoiceClosureSch = new InvoiceClosureScheduler();
		Test.startTest();
		invoiceClosureSch.execute(null);
		Test.stopTest();

		periodicInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Periodic Invoice'];
		System.assertEquals(periodicInvoice.Status__c, Invoicing.STATUS_CLOSED, 'Invoice must be closed after batch execution' );
	}

	static testMethod void closeInvoice2() {
		Invoice_Header__c immediateInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Immediate Invoice'];
		System.assertEquals(immediateInvoice.Status__c, Invoicing.STATUS_CLOSED, 'Invoice must be closed on creation' );

		Invoice_Header__c periodicInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Periodic Invoice'];
		System.assertEquals(periodicInvoice.Status__c, Invoicing.STATUS_OPEN, 'Invoice must be open before batch execution' );

		Test.startTest();
		new InvoiceClosureScheduler().execute(null);
		Test.stopTest();

		periodicInvoice = [SELECT Status__c FROM Invoice_Header__c WHERE Name = 'Periodic Invoice'];
		System.assertEquals(periodicInvoice.Status__c, Invoicing.STATUS_CLOSED, 'Invoice must be closed after batch execution' );
	}
}