force-app/main/default/objects/Account/fields/IsBinCollectionAdvanceInvoiced__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollectionAdvanceInvoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection Advance Invoiced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>LEFT(
  IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;),
  LEN(
    IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;)
  ) - 2
)</formula>
    <label>Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/ExtKey__c.field-meta.xml
<CustomField>
    <fullName>ExtKey__c</fullName>
    <externalId>true</externalId>
    <label>ExtKey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <label>Friday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <label>Monday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <label>Saturday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <label>Sunday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <label>Thursday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <formula>IF(!ISBLANK(Monday__c), Monday__c,
IF(!ISBLANK(Tuesday__c), Tuesday__c,
IF(!ISBLANK(Wednesday__c), Wednesday__c,
IF(!ISBLANK(Thursday__c), Thursday__c,
IF(!ISBLANK(Friday__c), Friday__c,
IF(!ISBLANK(Saturday__c), Saturday__c,
IF(!ISBLANK(Sunday__c), Sunday__c, &apos;&apos;)))))))</formula>
    <label>Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <label>Tuesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <label>Wednesday</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Fortnightly__c.field-meta.xml
<CustomField>
    <fullName>Fortnightly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fortnightly?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <formula>AND(ISPICKVAL(Supplier_Product__r.Product__r.Product_Type__c, &apos;Collection&apos;), OR(ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bin&apos;), ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bale&apos;)))</formula>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Reactivation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reactivation_Start_Date__c</fullName>
    <label>Reactivation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Suspension_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Suspension_Start_Date__c</fullName>
    <label>Suspension Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>&quot;18:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/UniqueCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueCode__c</fullName>
    <label>UniqueCode</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/ScheduleAdvanceInvoiceHistory__c.object-meta.xml
<CustomObject>
    <label>Schedule Advance Invoice History</label>
    <nameField>
        <displayFormat>SH-{0}</displayFormat>
        <label>Schedule Advance Invoice History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Advance Invoice History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/IsFortnightly__c.field-meta.xml
<CustomField>
    <fullName>IsFortnightly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fortnightly?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/IsNew__c.field-meta.xml
<CustomField>
    <fullName>IsNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedule Advance Invoice History</relationshipLabel>
    <relationshipName>ScheduleAdvanceInvoiceHistory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/ReactivationStartDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationStartDate__c</fullName>
    <label>Reactivation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Schedule Advance Invoice History</relationshipLabel>
    <relationshipName>ScheduleAdvanceInvoiceHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleAdvanceInvoiceHistory__c/fields/SuspensionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionStartDate__c</fullName>
    <label>Suspension Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectionScheduleTriggerHandler.cls
public class CollectionScheduleTriggerHandler {

	private static Boolean isCloneInsertion = false; // Prevent recursive processing when clones are INSERTed

	public void handleTrigger(List<Schedule__c> newList, Map<Id, Schedule__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when BEFORE_INSERT {
				if (!isCloneInsertion) {
					processInsert(newList);
				}
			}
			when BEFORE_UPDATE {
				processUpdate(newList, oldMap);
			}
			when BEFORE_DELETE {
				processDelete(oldMap.values());
			}
			when AFTER_INSERT, AFTER_UPDATE {
				insertScheduleHistory(newList, oldMap);
			}
		}
	}

	private void processInsert(List<Schedule__c> newList) {
		Map<String, CollectionAggregator__c> mapAggregator = new Map<String, CollectionAggregator__c>();
		List<Schedule__c> clonedSchedules = new List<Schedule__c>();

		for (Schedule__c schedule : newList) {
			// Initialize Aggregator
			String aggregatorKey = generateAggregatorKey(schedule);
			CollectionAggregator__c aggregator = mapAggregator.get(aggregatorKey);
			if (aggregator == null) {
				aggregator = newCollectionAggregator(schedule, aggregatorKey);
				mapAggregator.put(aggregatorKey, aggregator);
			}

			// Set collection time for all days of week on Aggregator
			List<String> collectionDays = schedule.Days__c.split(';');
			setTimeOnDay(aggregator, collectionDays, schedule.Time__c);

			// Clone schedule for each day of week
			clonedSchedules.addAll(clone(schedule, collectionDays, aggregatorKey));

			// Doing this after clones are created, to avoid the 1st day being enabled in all clones
			setCollectionDay(schedule, collectionDays[0], aggregatorKey);
		}

		UPSERT mapAggregator.values() CollectionAggregator__c.Fields.Extkey__c;  // Changed to allOrNone=true

		// Assign Aggregator to each schedule
		List<Schedule__c> allSchedules = new List<Schedule__c>(newList);
		allSchedules.addAll(clonedSchedules);
		for (Schedule__c schedule : allSchedules) {
			schedule.CollectionAggregator__c = mapAggregator.get(generateAggregatorKey(schedule)).Id;
		}

		if (hasDuplicates(allSchedules)) {
			applyError(newList, Label.MsgDuplicateCollectionSchedule);
			return;
		}

		if (!clonedSchedules.isEmpty()) {
			isCloneInsertion = true;
			try {
				INSERT clonedSchedules;
			} catch (DmlException e) {
				applyError(newList, e.getDmlMessage(0));
			}
		}
	}

	private void insertScheduleHistory(List<Schedule__c> newList, Map<Id, Schedule__c> oldMap) {
		Set<Id> existingScheduleHistory = new Set<Id>();
		for (ScheduleAdvanceInvoiceHistory__c scheduleHistory : [SELECT Schedule__c FROM ScheduleAdvanceInvoiceHistory__c WHERE Schedule__c IN :newList AND CreatedDate = TODAY]) {
			existingScheduleHistory.add(scheduleHistory.Schedule__c);
		}

		List<ScheduleAdvanceInvoiceHistory__c> scheduleHistory = new List<ScheduleAdvanceInvoiceHistory__c>();
        List<Schedule__c> scheduleList = [SELECT Id, Location__c, Collection_Quantity__c, Start_Date__c, End_Date__c, Suspension_Start_Date__c, Reactivation_Start_Date__c, Is_bin_collection__c, Location__r.IsLive__c, Location__r.Parent.IsBinCollectionAdvanceInvoiced__c, Fortnightly__c FROM Schedule__c WHERE Id IN :newList]; 
		for (Schedule__c schedule : scheduleList) {
			if (!schedule.Location__r.Parent.IsBinCollectionAdvanceInvoiced__c || !schedule.Is_bin_collection__c || !schedule.Location__r.IsLive__c || existingScheduleHistory.contains(schedule.Id)) {
				continue;
			}

			Schedule__c oldSchedule = oldMap?.get(schedule.Id);
			if (oldSchedule == null) {
				scheduleHistory.add(new ScheduleAdvanceInvoiceHistory__c(Schedule__c = schedule.Id, Location__c = schedule.Location__c, IsNew__c = true));
			} else if (schedule.Collection_Quantity__c != oldSchedule.Collection_Quantity__c || schedule.Fortnightly__c != oldSchedule.Fortnightly__c
				|| schedule.Start_Date__c != oldSchedule.Start_Date__c || schedule.End_Date__c != oldSchedule.End_Date__c 
				|| schedule.Suspension_Start_Date__c != oldSchedule.Suspension_Start_Date__c || schedule.Reactivation_Start_Date__c != oldSchedule.Reactivation_Start_Date__c) {

				scheduleHistory.add(new ScheduleAdvanceInvoiceHistory__c(Schedule__c = oldSchedule.Id, Location__c = oldSchedule.Location__c, Quantity__c = oldSchedule.Collection_Quantity__c, IsFortnightly__c = oldSchedule.Fortnightly__c, 
					StartDate__c = oldSchedule.Start_Date__c, EndDate__c = oldSchedule.End_Date__c, SuspensionStartDate__c = oldSchedule.Suspension_Start_Date__c, ReactivationStartDate__c = oldSchedule.Reactivation_Start_Date__c));
			}
		}
		INSERT scheduleHistory;
	}

	private void processUpdate(List<Schedule__c> updatedList, Map<Id, Schedule__c> oldMap) {
		Map<Object, CollectionAggregator__c> mapAggregator = getAggregatorsByKey(oldMap.values());
		Map<Object, CollectionAggregator__c> aggregatorsToUpsert = new Map<Object, CollectionAggregator__c>();
		List<Schedule__c> schedulesToUpdateAggregator = new List<Schedule__c>();

		for (Schedule__c schedule : updatedList) {
			Schedule__c oldSchedule = oldMap.get(schedule.Id);
			String aggregatorKey = generateAggregatorKey(schedule);
			String aggregatorKeyOld = generateAggregatorKey(oldSchedule);
			if (aggregatorKey == aggregatorKeyOld) {    // Assumption is 'Day change' on a Schedule is not allowed
				continue;
			}

			// Update unique code due to change in key
			setUniqueCode(schedule, aggregatorKey);

			// Initialize Aggregator
			CollectionAggregator__c aggregator = mapAggregator.get(aggregatorKey);
			if (aggregator == null) {
				aggregator = newCollectionAggregator(schedule, aggregatorKey);
				mapAggregator.put(aggregatorKey, aggregator);
			}
			schedulesToUpdateAggregator.add(schedule);

			// Set collection time for day of week on new Aggregator
			setTimeOnDay(aggregator, schedule.Days__c, schedule.Time__c);
			aggregatorsToUpsert.put(aggregatorKey, aggregator);

			// Clear collection time for day of week on current Aggregator
			CollectionAggregator__c aggregatorOld = mapAggregator.get(aggregatorKeyOld);
			clearTimeOnDay(aggregatorOld, schedule.Days__c);
			aggregatorsToUpsert.put(aggregatorKeyOld, aggregatorOld);
		}

		if (hasDuplicates(schedulesToUpdateAggregator)) {
			applyError(schedulesToUpdateAggregator, Label.MsgDuplicateCollectionSchedule);
			return;
		}		

		if (aggregatorsToUpsert.isEmpty()) {
			return;
		}

		// Identify empty Aggregators that are to be deleted
		List<CollectionAggregator__c> aggregatorsToDelete = identifyAggregatorsToDelete(aggregatorsToUpsert);

		UPSERT aggregatorsToUpsert.values() CollectionAggregator__c.Fields.Extkey__c;    // Changed to allOrNone=true

		if (!aggregatorsToDelete.isEmpty()) {
			DELETE aggregatorsToDelete;
		}

		// Assign Aggregator to each schedule
		for (Schedule__c schedule : schedulesToUpdateAggregator) {
			schedule.CollectionAggregator__c = aggregatorsToUpsert.get(generateAggregatorKey(schedule)).Id;
		}
	}

	private void processDelete(List<Schedule__c> deletedList) {
		Map<Object, CollectionAggregator__c> aggregatorsToUpdate = getAggregatorsById(deletedList);

		// Clear collection time for day of week on Aggregator
		for (Schedule__c schedule : deletedList) {
			clearTimeOnDay(aggregatorsToUpdate.get(schedule.CollectionAggregator__c), schedule.Days__c);
		}

		// Identify empty Aggregators that are to be deleted
		List<CollectionAggregator__c> aggregatorsToDelete = identifyAggregatorsToDelete(aggregatorsToUpdate);

		if (!aggregatorsToUpdate.isEmpty()) {
			UPDATE aggregatorsToUpdate.values();
		}
		if (!aggregatorsToDelete.isEmpty()) {
			DELETE aggregatorsToDelete;
		}
	}

	private String generateAggregatorKey(Schedule__c schedule) {
		return schedule.Location__c + '-' + schedule.Supplier_Product__c + '-' + schedule.Collection_quantity__c.intValue() + '-' + schedule.Time__c;
	}

	private CollectionAggregator__c newCollectionAggregator(Schedule__c schedule, String aggregatorKey) {
		return new CollectionAggregator__c(Location__c=schedule.Location__c, Supplier_Product__c=schedule.Supplier_Product__c,
											Quantity__c=schedule.Collection_quantity__c.intValue(), Extkey__c=aggregatorKey);
	}

	private void setTimeOnDay(CollectionAggregator__c aggregator, List<String> collectionDays, String collectionTime) {
		for (String day : collectionDays) {
			setTimeOnDay(aggregator, day, collectionTime);
		}
	}

	private void setTimeOnDay(CollectionAggregator__c aggregator, String dayOfWeek, String collectionTime) {
		aggregator.put(dayOfWeek + '__c', collectionTime);
	}

	private void clearTimeOnDay(CollectionAggregator__c aggregator, String dayOfWeek) {
		if (aggregator != null && String.isNotBlank(dayOfWeek)) {
			setTimeOnDay(aggregator, dayOfWeek, '');
		}
	}

	private void setCollectionDay(Schedule__c schedule, String dayOfWeek, String aggregatorKey) {
		schedule.Days__c = dayOfWeek;
		schedule.put(dayOfWeek + '_Collection__c', true);   // Jira 1905 - New update to new fields created by Ruth, so the driver app users can validate how many schedules there are per Account
		setUniqueCode(schedule, aggregatorKey);             // Changed to set on cloned schedules also
	}

	private void setUniqueCode(Schedule__c schedule, String aggregatorKey) {
		schedule.UniqueCode__c = aggregatorKey + '-' + schedule.Days__c;
	}

	private List<Schedule__c> clone(Schedule__c schedule, List<String> collectionDays, String aggregatorKey) {
		List<Schedule__c> clonedSchedules = new List<Schedule__c>();
		if (collectionDays.size() < 2) {
			return clonedSchedules;
		}

		for (Integer i=1; i<collectionDays.size(); i++) {
			Schedule__c clonedDay = schedule.clone(false, true, true, false);   // Changed to preserveReadonlyTimestamps=true
			setCollectionDay(clonedDay, collectionDays[i], aggregatorKey);
			clonedSchedules.add(clonedDay);
		}
		return clonedSchedules;
	}

	private Map<Object, CollectionAggregator__c> getAggregatorsById(List<Schedule__c> schedules) {
		Set<Id> aggregatorIds = new Set<Id>();
		for (Schedule__c schedule : schedules) {
			aggregatorIds.add(schedule.CollectionAggregator__c);
		}

		return new Map<Object, CollectionAggregator__c>([SELECT Extkey__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c
													FROM CollectionAggregator__c WHERE Id IN :aggregatorIds]);
	}

	private Map<Object, CollectionAggregator__c> getAggregatorsByKey(List<Schedule__c> schedules) {
		Map<Object, CollectionAggregator__c> mapAggregator = new Map<Object, CollectionAggregator__c>();
		for (CollectionAggregator__c aggregator : getAggregatorsById(schedules).values()) {
			mapAggregator.put(aggregator.Extkey__c, aggregator);
		}
		return mapAggregator;
	}

	private List<CollectionAggregator__c> identifyAggregatorsToDelete(Map<Object, CollectionAggregator__c> aggregators) {
		List<CollectionAggregator__c> aggregatorsToDelete = new List<CollectionAggregator__c>();
		for (Object mapKey : aggregators.keySet()) {
			CollectionAggregator__c aggregator = aggregators.get(mapKey);
			if (!hasCollectionTime(aggregator)) {
				aggregatorsToDelete.add(aggregator);
				aggregators.remove(mapKey);
			}
		}
		return aggregatorsToDelete;
	}

	private Boolean hasCollectionTime(CollectionAggregator__c aggregator) {
		return String.isNotBlank(aggregator.Monday__c) || String.isNotBlank(aggregator.Tuesday__c) || String.isNotBlank(aggregator.Wednesday__c) || String.isNotBlank(aggregator.Thursday__c) ||
			String.isNotBlank(aggregator.Friday__c) || String.isNotBlank(aggregator.Saturday__c) || String.isNotBlank(aggregator.Sunday__c);
	}

	private Boolean hasDuplicates(List<Schedule__c> schedules) {
		Set<String> uniqueCodes = new Set<String>();
		for (Schedule__c schedule : schedules) {
			uniqueCodes.add(schedule.UniqueCode__c);
		}

		if (uniqueCodes.size() != schedules.size()) {
			return true;
		}

		return [SELECT COUNT() FROM Schedule__c WHERE UniqueCode__c IN :uniqueCodes] > 0;
	}

	private void applyError(List<Schedule__c> schedules, String errorMessage) {
		for (Schedule__c schedule : schedules) {
			schedule.addError(errorMessage);
		}
	}
}