force-app/main/default/objects/Account/fields/IsBinRentalExempt__c.field-meta.xml
<CustomField>
    <fullName>IsBinRentalExempt__c</fullName>
    <formula>AND(RecordTypeName__c = &apos;Account&apos;, OR(No_Bin_Rental__c, NOT(ISBLANK(Account_Manager__c))))</formula>
    <label>Bin Rental Exempt?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsLive__c.field-meta.xml
<CustomField>
    <fullName>IsLive__c</fullName>
    <formula>ISPICKVAL(Enqix_Dead_Live__c, &apos;Live&apos;)</formula>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MonthsInvoicedInAdvance__c.field-meta.xml
<CustomField>
    <fullName>MonthsInvoicedInAdvance__c</fullName>
    <label>Months Invoiced in Advance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <label>Collection Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Collection_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Collection_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurrings__c/Recurrings__c.object-meta.xml
<CustomObject>
    <label>Recurring</label>
    <nameField>
        <label>Recurrings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurrings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurrings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurrings</relationshipLabel>
    <relationshipName>Recurrings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurrings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Recurrings</relationshipLabel>
    <relationshipName>Recurrings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurrings__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Recurrings</relationshipLabel>
    <relationshipName>Recurrings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is for the driver&apos;s app, looking at the &quot;Collection Active&quot; as you can&apos;t use a formula in a roll-up summary</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Is_bin_collection__c.field-meta.xml
<CustomField>
    <fullName>Is_bin_collection__c</fullName>
    <formula>AND(ISPICKVAL(Supplier_Product__r.Product__r.Product_Type__c, &apos;Collection&apos;), OR(ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bin&apos;), ISPICKVAL(Supplier_Product__r.Product__r.Container_Type__r.Type__c, &apos;Bale&apos;)))</formula>
    <label>Is bin collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BinRentalChargeBatch.cls
public without sharing class BinRentalChargeBatch implements Database.Batchable<sObject> {

	private final Id STANDARD_PRICEBOOK_ID = PriceBookUtil.STANDARD_PRICEBOOK_ID;
	private final Suppliers__c FIRST_MILE_SUPPLIER = SupplierUtil.FIRST_MILE_SUPPLIER;
	private final Date START_DATE;
	private final Date END_DATE;

	private Map<Id, Account> locationsMap = new Map<Id, Account>();
	private Map<Id, Id> productIdToBinRentalIdMap = new Map<Id, Id>();
	private Map<String, Map<Id, Decimal>> locationToRentalBinQuantityMap = new Map<String, Map<Id, Decimal>>();

	public BinRentalChargeBatch() {
		Date today = Date.today();
		START_DATE = today.day() == 1 ? today.addMonths(-1) : today.toStartOfMonth();
		END_DATE = START_DATE.addMonths(1).addDays(-1);
	}

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		return Database.getQueryLocator([SELECT Id, (SELECT Id FROM Recurrings__r WHERE Active__c = true) FROM Account WHERE Id IN
			(SELECT Location__c FROM Collection_Waypoints__c WHERE Location__r.Parent.MonthsInvoicedInAdvance__c = null AND Location__r.IsLive__c = true
			AND Collection_Schedule__r.Is_bin_collection__c = true AND Location__r.Parent.IsBinRentalExempt__c = false AND Supplier_Product__r.Product__r.BinRentalProduct__c != null
			AND DAY_ONLY(CreatedDate) >= :START_DATE AND DAY_ONLY(CreatedDate) <= :END_DATE)]);
	}

	public void execute(Database.BatchableContext batchContext, List<Account> locations) {
		filterLocations(locations);
		loadBinRentalMaps();

		insertBinRentalOrderItems(insertBinRentalOrders());
	}

	private void filterLocations(List<Account> locations) {
		for (Account location : locations) {
			if (location.Recurrings__r.isEmpty()){
				locationsMap.put(location.Id, location);
			}
		}
	}

	private List<Collection_Waypoints__c> fetchWaypoints() {
		return [SELECT Location__c, Collection_Quantity__c, Supplier_Product__r.Product__c, Supplier_Product__r.Product__r.BinRentalProduct__c
			FROM Collection_Waypoints__c WHERE Location__c IN :locationsMap.keySet()
			AND Collection_Schedule__r.Is_bin_collection__c = true AND Supplier_Product__r.Product__r.BinRentalProduct__c != null
			AND DAY_ONLY(CreatedDate) >= :START_DATE AND DAY_ONLY(CreatedDate) <= :END_DATE
			ORDER BY Location__c, Supplier_Product__r.Product__c];
	}

	private void loadBinRentalMaps() {
		List<Collection_Waypoints__c> waypoints = fetchWaypoints();

		Map<String, Map<Id, Decimal>> locationToProductQuantityMap = new Map<String, Map<Id, Decimal>>();
		Decimal quantity;
		for (Collection_Waypoints__c waypoint : waypoints) {
			if (!locationToProductQuantityMap.containsKey(waypoint.Location__c)) {
				locationToProductQuantityMap.put(waypoint.Location__c, new Map<Id, Decimal>());
			}

			quantity = locationToProductQuantityMap.get(waypoint.Location__c).get(waypoint.Supplier_Product__r.Product__c);
			if (quantity == null || waypoint.Collection_Quantity__c > quantity) {
				locationToProductQuantityMap.get(waypoint.Location__c).put(waypoint.Supplier_Product__r.Product__c, waypoint.Collection_Quantity__c);
			}

			productIdToBinRentalIdMap.put(waypoint.Supplier_Product__r.Product__c, waypoint.Supplier_Product__r.Product__r.BinRentalProduct__c);
		}

		loadRentalProductToQuantityMap(locationToProductQuantityMap);
	}

	private void loadRentalProductToQuantityMap(Map<String, Map<Id, Decimal>> locationToProductQuantityMap) {
		for (Id locationId : locationToProductQuantityMap.keySet()) {
			Map<Id, Decimal> rentalProductToQuantityMap = new Map<Id, Decimal>();
			Map<Id, Decimal> productToQuantityMap = locationToProductQuantityMap.get(locationId);
			Id binRentalProductId;
			for (Id productId : productToQuantityMap.keySet()) {
				binRentalProductId = productIdToBinRentalIdMap.get(productId);
				if (!rentalProductToQuantityMap.containsKey(binRentalProductId)) {
					rentalProductToQuantityMap.put(binRentalProductId, productToQuantityMap.get(productId));
				} else {
					rentalProductToQuantityMap.put(binRentalProductId, rentalProductToQuantityMap.get(binRentalProductId) + productToQuantityMap.get(productId));
				}
			}

			locationToRentalBinQuantityMap.put(locationId, rentalProductToQuantityMap);
		}
	}

	private Map<Id, Order> insertBinRentalOrders() {
		Map<Id, Order> locationToOrderMap = new Map<Id, Order>();
		for (Id locationId : locationToRentalBinQuantityMap.keySet()) {
			Order order  = OrderUtil.createOrder(locationId, FIRST_MILE_SUPPLIER, END_DATE);
			order.PeriodStart__c = START_DATE;
			order.PeriodEnd__c = END_DATE;
			locationToOrderMap.put(locationId, order);
		}

		Database.SaveResult[] results = Database.insert(locationToOrderMap.values(), false);
		LogRegister.createLogsUpsert(results, locationToOrderMap.values(), 'Monthly Bin Rental Orders', 'Insert', 'Order', 'AccountId');

		return locationToOrderMap;
	}

	private void insertBinRentalOrderItems(Map<Id, Order> locationToOrderMap) {
		List<OrderItem> orderItems = new List<OrderItem>();
		for (Id locationId : locationToOrderMap.keySet()) {
			Map<Id, Decimal> rentalProductToQuantityMap = locationToRentalBinQuantityMap.get(locationId);

			for (Id binRentalProductId : rentalProductToQuantityMap.keySet()) {
				orderItems.add(OrderUtil.createOrderItem(locationToOrderMap.get(locationId).Id, binRentalProductId, rentalProductToQuantityMap.get(binRentalProductId), STANDARD_PRICEBOOK_ID, null, null, null, FIRST_MILE_SUPPLIER.Id));
			}
		}

		Database.SaveResult[] results = Database.insert(orderItems, false);
		LogRegister.createLogsUpsert(results, orderItems, 'Monthly Bin Rental OrderItems', 'Insert', 'OrderItem', 'OrderId');

		OrderUtil.setBinOrderAsConfirmed(locationToOrderMap.values());
		Database.SaveResult[] results1 = Database.update(locationToOrderMap.values(), false);
		LogRegister.createLogsUpsert(results1, locationToOrderMap.values(), 'Set Monthly Bin Rental Orders to Confirmed status', 'Update', 'Order', 'AccountId');
	}

	public void finish(Database.BatchableContext batchContext) {}
}