force-app/main/default/objects/Account/fields/IsDeliveryChargeExemptLocation__c.field-meta.xml
<CustomField>
    <fullName>IsDeliveryChargeExemptLocation__c</fullName>
    <formula>AND(RecordType.Name == &apos;Location&apos;, OR(IsDeliveryChargeExempt__c, Parent.IsDeliveryChargeExempt__c))</formula>
    <label>Delivery Charge Exempt Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsFuelSurchargeExemptLocation__c.field-meta.xml
<CustomField>
    <fullName>IsFuelSurchargeExemptLocation__c</fullName>
    <formula>IF(RecordType.Name != &apos;Location&apos;, false, IF(IsFuelSurchargeExempt__c, true, Parent.IsFuelSurchargeExempt__c))</formula>
    <label>Fuel Surcharge Exempt Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsVATExemptLocation__c.field-meta.xml
<CustomField>
    <fullName>IsVATExemptLocation__c</fullName>
    <formula>OR(VAT_Exempt__c, Parent.VAT_Exempt__c)</formula>
    <label>VAT Exempt Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/AdditionalChargeSetting__c/AdditionalChargeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Additional Charge Setting</label>
</CustomObject>

force-app/main/default/objects/AdditionalChargeSetting__c/fields/BagContainerNames__c.field-meta.xml
<CustomField>
    <fullName>BagContainerNames__c</fullName>
    <label>Bag Container Names</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeSetting__c/fields/BagDeliveryChargeProduct__c.field-meta.xml
<CustomField>
    <fullName>BagDeliveryChargeProduct__c</fullName>
    <label>Bag Delivery Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeSetting__c/fields/BinContainerNames__c.field-meta.xml
<CustomField>
    <fullName>BinContainerNames__c</fullName>
    <label>Bin Container Names</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeSetting__c/fields/BinDeliveryChargeProduct__c.field-meta.xml
<CustomField>
    <fullName>BinDeliveryChargeProduct__c</fullName>
    <label>Bin Delivery Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeSetting__c/fields/IsDeliveryChargeActive__c.field-meta.xml
<CustomField>
    <fullName>IsDeliveryChargeActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery Charge Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FuelSurchargeSetting__c/FuelSurchargeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Fuel Surcharge Setting</label>
</CustomObject>

force-app/main/default/objects/FuelSurchargeSetting__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FuelSurchargeSetting__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>Product Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FuelSurchargeSetting__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsVATExemptLocation__c.field-meta.xml
<CustomField>
    <fullName>IsVATExemptLocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Exempt Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IncludeFuelSurcharge__c.field-meta.xml
<CustomField>
    <fullName>IncludeFuelSurcharge__c</fullName>
    <formula>AND($Setup.FuelSurchargeSetting__c.IsActive__c, Product2.IncludeFuelSurcharge__c, NOT(Order.Account.IsFuelSurchargeExemptLocation__c), NOT(BEGINS(CreatedBy.Username, &apos;optimizely.integration@thefirstmile.co.uk&apos;)))</formula>
    <label>Include Fuel Surcharge?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdditionalChargesImpl.cls
public without sharing class AdditionalChargesImpl {

	private static final Boolean DELIVERY_CHARGE_ACTIVE;
	private static final Id BAG_DELIVERY_CHARGE_PRODUCT;
	private static final Id BIN_DELIVERY_CHARGE_PRODUCT;
	private static final String BAG_CONTAINER_NAMES;
	private static final String BIN_CONTAINER_NAMES;
	private static final Boolean FUEL_SURCHARGE_ACTIVE;
	private static final Id FUEL_SURCHARGE_PRODUCT;
	private static final Decimal FUEL_SURCHARGE;
	static {
		AdditionalChargeSetting__c additionalChargeSetting = AdditionalChargeSetting__c.getOrgDefaults();
		DELIVERY_CHARGE_ACTIVE = additionalChargeSetting.IsDeliveryChargeActive__c;
		BAG_DELIVERY_CHARGE_PRODUCT = additionalChargeSetting.BagDeliveryChargeProduct__c;
		BIN_DELIVERY_CHARGE_PRODUCT = additionalChargeSetting.BinDeliveryChargeProduct__c;
		BAG_CONTAINER_NAMES = additionalChargeSetting.BagContainerNames__c;
		BIN_CONTAINER_NAMES = additionalChargeSetting.BinContainerNames__c;
		FuelSurchargeSetting__c fuelSurchargeSetting = FuelSurchargeSetting__c.getOrgDefaults();
		FUEL_SURCHARGE_ACTIVE = fuelSurchargeSetting.IsActive__c;
		FUEL_SURCHARGE_PRODUCT = fuelSurchargeSetting.ProductId__c;
		FUEL_SURCHARGE = fuelSurchargeSetting.Surcharge__c;
	}

	public List<AdditionalCharges.OrderItemData> addWTNCharge(AdditionalCharges.OrderData orderData) {
		//check and add WTN and Delivery Charge Order Items
		return new List<AdditionalCharges.OrderItemData>();
	}

	public List<AdditionalCharges.OrderItemData> addDeliveryCharge(AdditionalCharges.OrderData orderData, List<AdditionalCharges.OrderItemData> additionalCharges) {
		if (!DELIVERY_CHARGE_ACTIVE) {
			return new List<AdditionalCharges.OrderItemData>();
		}

		Set<Id> productIds = new Set<Id>();
		Decimal totalAmount = 0;
		for (AdditionalCharges.OrderItemData orderItem : orderData.orderItems) {
			productIds.add(orderItem.productId);
			totalAmount += (orderItem.unitPrice * orderItem.quantity);
		}
		for (AdditionalCharges.OrderItemData orderItem : additionalCharges) {
			totalAmount += (orderItem.unitPrice * orderItem.quantity);
		}

		List<String> bagContainers = StringUtil.splitTrim(BAG_CONTAINER_NAMES, ',');
		List<String> binContainers = StringUtil.splitTrim(BIN_CONTAINER_NAMES, ',');
		Boolean bagProductExist = false, binProductExist = false;

		String containerType;
		for (AggregateResult aggregateResult : [SELECT Container_Type__r.Name name FROM Product2 WHERE Id IN :productIds AND (Container_Type__r.Name IN :bagContainers OR Container_Type__r.Name IN :binContainers) GROUP BY Container_Type__r.Name]) {
			containerType = (String)aggregateResult.get('name');
			if (binContainers.contains(containerType)) {
				binProductExist = true;
			} else {
				bagProductExist = true;
			}
		}

		if (!bagProductExist && !binProductExist) {
			return new List<AdditionalCharges.OrderItemData>();
		}

		Account location = [SELECT IsDeliveryChargeExemptLocation__c, IsVatExemptLocation__c, Price_Book__c FROM Account WHERE Id = :orderData.locationId];
		Boolean applyDeliveryCharge = !(location.IsDeliveryChargeExemptLocation__c || totalAmount > 10000);
		Map<Id, PricebookEntry> productToPriceMap = new Map<Id, PricebookEntry>();

		for (PricebookEntry pricebookEntry : [SELECT Product2Id, UnitPrice, Product2.Name, Product2.IsVatExempt__c FROM PricebookEntry WHERE PriceBook2Id = :location.Price_Book__c AND (Product2Id = :BAG_DELIVERY_CHARGE_PRODUCT OR Product2Id = :BIN_DELIVERY_CHARGE_PRODUCT)]) {
			productToPriceMap.put(pricebookEntry.Product2Id, pricebookEntry);
		}

		List<AdditionalCharges.OrderItemData> orderItems = new List<AdditionalCharges.OrderItemData>();

		if (binProductExist) {
			PricebookEntry pricebookEntry = productToPriceMap.get(BIN_DELIVERY_CHARGE_PRODUCT);
			AdditionalCharges.OrderItemData orderItem = createOrderItem(pricebookEntry, location.IsVatExemptLocation__c, applyDeliveryCharge ? pricebookEntry.UnitPrice : 0);
			orderItems.add(orderItem);
			totalAmount += (orderItem.unitPrice * orderItem.quantity);
		}

		applyDeliveryCharge = !(location.IsDeliveryChargeExemptLocation__c || totalAmount > 10000);
		if (bagProductExist) {
			PricebookEntry pricebookEntry = productToPriceMap.get(BAG_DELIVERY_CHARGE_PRODUCT);
			orderItems.add(createOrderItem(pricebookEntry, location.IsVatExemptLocation__c, applyDeliveryCharge ? pricebookEntry.UnitPrice : 0));
		}

		return orderItems;
	}

	public List<AdditionalCharges.OrderItemData> addFuelSurcharge(AdditionalCharges.OrderData orderData) {
		if (!FUEL_SURCHARGE_ACTIVE) {
			return new List<AdditionalCharges.OrderItemData>();
		}

		Account location = [SELECT IsFuelSurchargeExemptLocation__c, IsVatExemptLocation__c, Price_Book__c FROM Account WHERE Id = :orderData.locationId];
		if (location.IsFuelSurchargeExemptLocation__c) {
			return new List<AdditionalCharges.OrderItemData>();
		}

		Set<Id> productIds = new Set<Id>();
		for (AdditionalCharges.OrderItemData orderItem : orderData.orderItems) {
			productIds.add(orderItem.productId);
		}

		Map<Id, Product2> productMap = new Map<Id, Product2>([SELECT IncludeFuelSurcharge__c FROM Product2 WHERE Id IN :productIds AND IncludeFuelSurcharge__c = true]);
		if (productMap.isEmpty()) {
			return new List<AdditionalCharges.OrderItemData>();
		}
		Decimal totalPrice = 0;
		for (AdditionalCharges.OrderItemData orderItem : orderData.orderItems) {
			if (productMap.containsKey(orderItem.productId)) {
				totalPrice += orderItem.unitPrice * orderItem.quantity;
			}
		}

		PricebookEntry pricebookEntry = [SELECT Product2Id, Product2.Name, Product2.IsVatExempt__c FROM PricebookEntry WHERE PriceBook2Id = :location.Price_Book__c AND Product2Id = :FUEL_SURCHARGE_PRODUCT];
		return new List<AdditionalCharges.OrderItemData>{createOrderItem(pricebookEntry, location.IsVatExemptLocation__c, Math.max(((totalPrice * FUEL_SURCHARGE) / 100).setScale(2), 0))};
	}

	private AdditionalCharges.OrderItemData createOrderItem(PricebookEntry pricebookEntry, Boolean isVatExemptLocation, Decimal unitPrice) {
		AdditionalCharges.OrderItemData orderItem = new AdditionalCharges.OrderItemData();
		orderItem.productId = pricebookEntry.Product2Id;
		orderItem.pricebookEntryId = pricebookEntry.Id;
		orderItem.productName = pricebookEntry.Product2.Name;
		orderItem.vatRate = (pricebookEntry.Product2.IsVatExempt__c || isVatExemptLocation) ? 0 : Vat.DEFAULT_VAT_RATE;
		orderItem.quantity = 1;
		orderItem.unitPrice = unitPrice;
		return orderItem;
	}
}