force-app/main/default/objects/Account/fields/MonthsInvoicedInAdvance__c.field-meta.xml
<CustomField>
    <fullName>MonthsInvoicedInAdvance__c</fullName>
    <label>Months Invoiced in Advance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NextAdvanceInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>NextAdvanceInvoiceDate__c</fullName>
    <inlineHelpText>1st of next month!</inlineHelpText>
    <label>Next Advance Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/CollectionAggregator__c/CollectionAggregator__c.object-meta.xml
<CustomObject>
    <label>Collection Aggregator</label>
    <nameField>
        <label>Collection Aggregator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Aggregators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionAggregator__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>LEFT(
  IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
  IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;),
  LEN(
    IF(!ISBLANK(Monday__c), &apos;Monday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Tuesday__c), &apos;Tuesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Wednesday__c), &apos;Wednesday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Thursday__c), &apos;Thursday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Friday__c), &apos;Friday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Saturday__c), &apos;Saturday, &apos;, &apos;&apos;) + 
    IF(!ISBLANK(Sunday__c), &apos;Sunday, &apos;, &apos;&apos;)
  ) - 2
)</formula>
    <label>Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionAggregator__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Aggregators</relationshipLabel>
    <relationshipName>Collection_Aggregators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/CollectionAggregator__c.field-meta.xml
<CustomField>
    <fullName>CollectionAggregator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <formula>Supplier_Product__r.Product__r.Container_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/PreviousCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>PreviousCollectionDate__c</fullName>
    <label>Previous Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Week_Off__c.field-meta.xml
<CustomField>
    <fullName>Week_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/WeekFrequency__c.field-meta.xml
<CustomField>
    <fullName>WeekFrequency__c</fullName>
    <label>Week Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/ScheduleSuspension__c.object-meta.xml
<CustomObject>
    <label>Schedule Suspension</label>
    <nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Suspensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleSuspension__c/fields/Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Aggregator__c</fullName>
    <label>Aggregator</label>
    <referenceTo>CollectionAggregator__c</referenceTo>
    <relationshipLabel>Suspensions</relationshipLabel>
    <relationshipName>Suspensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/ReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationDate__c</fullName>
    <label>Reactivation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/SuspensionDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionDate__c</fullName>
    <label>Suspension Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdvanceBinCollectionToOrderBatchTest.cls
@isTest
public class AdvanceBinCollectionToOrderBatchTest {

	@testSetup
	private static void setup() {
		TestDataHelper.suppressSuspensionDateValidation();
		Product2 rentalProduct = TestDataHelper.insertProduct('Rental Product', 'RP001', 'Collection');

		Container_Type__c containerType = TestDataHelper.insertContainerType('Bin');
		Product2 product1 = TestDataHelper.insertProduct('Test Product', '12355321', 'Collection', containerType.Id, rentalProduct.Id);

		TestDataHelper.insertStandardPricebookEntry(rentalProduct.Id, 10);
		TestDataHelper.insertStandardPricebookEntry(product1.Id, 10);

		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct1 = TestDataHelper.insertSupplierProduct(supplier, product1);

		Account parent = TestDataHelper.createAccount();
		parent.MonthsInvoicedInAdvance__c = '3';
		parent.NextAdvanceInvoiceDate__c = Date.today().toStartOfMonth().addMonths(1);
		INSERT parent;
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Round__c round = TestDataHelper.insertRound();

		TestDataHelper.insertSchedule(location, round, supplier, supplierProduct1, '18:00');
	}

	@isTest
	static void validateDatesWithoutSuspension() {
		Schedule__c schedule = [SELECT Id, CollectionAggregator__c, Start_Date__c, End_Date__c, Days__c, Week_Off__c, WeekFrequency__c, PreviousCollectionDate__c FROM Schedule__c WHERE Days__c = 'Monday'];
		schedule.Start_Date__c = schedule.End_Date__c = null;

		Test.startTest();
		AdvanceBinCollectionToOrderBatch batch = new AdvanceBinCollectionToOrderBatch();
		batch.loadAggregatorToSuspensionsMap(new List<Schedule__c>{schedule});
		Set<Date> dates = batch.getCollectionDates(schedule);
		Test.stopTest();
		Assert.areEqual(13, dates.size());
	}

	@isTest
	static void validateDatesWithSuspension() {
		Schedule__c schedule = [SELECT Id, CollectionAggregator__c, Start_Date__c, End_Date__c, Days__c, Week_Off__c, WeekFrequency__c, PreviousCollectionDate__c FROM Schedule__c WHERE Days__c = 'Monday'];

		Date startDate = Date.today().toStartOfMonth().addMonths(1);
		ScheduleSuspension__c suspension1 = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = startDate, ReactivationDate__c = startDate.addDays(7));
		ScheduleSuspension__c suspension2 = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = startDate.AddMonths(1), ReactivationDate__c = startDate.AddMonths(1).addDays(7));
		ScheduleSuspension__c suspension3 = new ScheduleSuspension__c(Aggregator__c = schedule.CollectionAggregator__c, SuspensionDate__c = startDate.AddMonths(2), ReactivationDate__c = startDate.AddMonths(2).addDays(7));
		INSERT new List<ScheduleSuspension__c>{suspension1, suspension2, suspension3};

		schedule.Start_Date__c = schedule.End_Date__c = null;

		Test.startTest();
		AdvanceBinCollectionToOrderBatch batch = new AdvanceBinCollectionToOrderBatch();
		batch.loadAggregatorToSuspensionsMap(new List<Schedule__c>{schedule});
		Set<Date> dates = batch.getCollectionDates(schedule);
		Test.stopTest();
		Assert.areEqual(10, dates.size());
	}

	@isTest
	static void test() {
		Account parent = [SELECT NextAdvanceInvoiceDate__c FROM Account WHERE RecordType.Name = 'Account'];

		Test.startTest();
		new AdvanceBinCollectionToOrderSchedular().execute(null);
		Test.stopTest();

		Assert.areEqual(2, [SELECT Count() FROM Order]);

		Id rentalProductId = [SELECT Id FROM Product2 WHERE Name = 'Rental Product'].Id;
		Assert.areEqual(1, [SELECT Count() FROM OrderItem WHERE Product2Id = :rentalProductId]);
		Assert.areEqual(6, [SELECT Quantity FROM OrderItem WHERE Product2Id = :rentalProductId].Quantity);

		Assert.areEqual(parent.NextAdvanceInvoiceDate__c.addMonths(3), [SELECT NextAdvanceInvoiceDate__c FROM Account WHERE RecordType.Name = 'Account'].NextAdvanceInvoiceDate__c);
	}
}