force-app/main/default/objects/Account/fields/No_Bin_Rental__c.field-meta.xml
<CustomField>
    <fullName>No_Bin_Rental__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Bin Rental?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <formula>Supplier_Product__r.Product__r.Container_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Searched product does not match a collection product.</errorMessage>
        <filterItems>
            <field>Product2.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <infoMessage>Collection Product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BinRentalChargeBatchTest.cls
@IsTest
private class BinRentalChargeBatchTest {

	@TestSetup
	private static void setup() {
		Product2 rentalProduct = TestDataHelper.insertProduct('Rental Product', 'RP001', 'Collection');

		Container_Type__c containerType = TestDataHelper.insertContainerType('Bin');
		Product2 collectionProduct1 = TestDataHelper.insertProduct('Collection Product1', 'CP001', 'Collection', containerType.Id, rentalProduct.Id);
		Product2 collectionProduct2 = TestDataHelper.insertProduct('Collection Product2', 'CP002', 'Collection', containerType.Id, rentalProduct.Id);

		TestDataHelper.insertStandardPricebookEntry(rentalProduct.Id, 10);

		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct1 = TestDataHelper.insertSupplierProduct(supplier, collectionProduct1);
		Supplier_Product__c supplierProduct2 = TestDataHelper.insertSupplierProduct(supplier, collectionProduct2);

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		Round__c round = TestDataHelper.insertRound();

		Schedule__c schedule1 = TestDataHelper.insertSchedule(location, round, supplier, supplierProduct1, '18:00');
		Schedule__c schedule2 = TestDataHelper.insertSchedule(location, round, supplier, supplierProduct2, '10:00');

		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		DispatchLocation__c dispatchLocation = TestDataHelper.insertDispatchLocation(dispatch, location);

		TestDataHelper.insertWaypoint(location, dispatch, dispatchLocation, schedule1.Id, supplierProduct1.Id, 5);
		TestDataHelper.insertWaypoint(location, dispatch, dispatchLocation, schedule2.Id, supplierProduct2.Id, 2);
	}

	@IsTest
	static void createsBinRentalOrderAndOrderItem() {
		Test.startTest();
		new BinRentalChargeSchedular().execute(null);
		Test.stopTest();

		List<Order> orders = [SELECT Id, Status FROM Order];
		Assert.areEqual(1, orders.size());

		List<OrderItem> orderItems = [SELECT Id, Quantity FROM OrderItem];
		Assert.areEqual(1, orderItems.size());
		Assert.areEqual(7, orderItems[0].Quantity);
	}

	@IsTest
	static void skipsLocationWithActiveRecurring() {
		Account location = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
		Supplier_Product__c sp = [SELECT Id, Supplier__c, Product__c FROM Supplier_Product__c LIMIT 1];
		TestDataHelper.insertRecurring(location.Id, sp.Product__c,  sp.Supplier__c);

		Test.startTest();
		new BinRentalChargeSchedular().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Count() FROM Order]);
	}

	@IsTest
	static void skipsBinRentalExemptAccount() {
		Account parent = [SELECT Id FROM Account WHERE RecordType.Name = 'Account'];

		parent.No_Bin_Rental__c = true;
		UPDATE parent;

		Test.startTest();
		new BinRentalChargeSchedular().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Count() FROM Order]);
	}

	@IsTest
	static void skipsAccountWithAccountManagerExemption() {
		Account parent = [SELECT Id FROM Account WHERE RecordType.Name = 'Account'];

		parent.Account_Manager__c = UserInfo.getUserId();
		UPDATE parent;

		Test.startTest();
		new BinRentalChargeSchedular().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Count() FROM Order]);
	}

	@IsTest
	static void skipsProductWithoutBinRentalProduct() {
		List<Product2> products = [SELECT Id FROM Product2 WHERE Name IN ('Collection Product1', 'Collection Product2')];
		for(Product2 p : products) {
			p.BinRentalProduct__c = null;
	 	}
		UPDATE products;

		Test.startTest();
		new BinRentalChargeSchedular().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Count() FROM Order]);
	}
}