force-app/main/default/objects/Account/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>This field will store location and account PO # (same field but with 2 labels on Account and Location layouts).</description>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Created__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttachmentHandler_Test.cls
@isTest
public class AttachmentHandler_Test {
    @isTest
    public static void afterInsertOrDeleteEvent_Test(){
        Test.startTest();
        Account parentAccount = TestDataHelper.createAccount();
        insert parentAccount;
        Account childAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        insert childAccount;
        Suppliers__c supObj =  TestDataHelper.insertSupplier('Test Supp');
        
        Order orderObj = new Order(
            AccountId = childAccount.Id,
            EffectiveDate = System.today().addMonths(-(1)),
            Status = 'draft',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Type = 'Regular',
            PO_Number__c = 'WheelieBinOrder0',
            Invoice_Created__c = false,
            Supplier__c = supObj.Id
        );
        insert orderObj;
        
        Blob bodyTest = Blob.valueOf('Test Data');
        
        Attachment attachment = new Attachment();
        attachment.ParentId = orderObj.Id;
        attachment.Name = 'Test Attachment for Parent';
        attachment.Body = bodyTest;
        insert(attachment);
        Test.stopTest();
        
    }
}