force-app/main/default/objects/Account/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>This field will store location and account PO # (same field but with 2 labels on Account and Location layouts).</description>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Created__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <formula>IF(
    /* First condition: Delivery Date is less than 22/09/2024 */
    Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
    /* Use the original logic */
    IF(
        NOT(ISNULL(AD_KG_from_Weights__c)),
        AD_KG_from_Weights__c,
        Quantity * PricebookEntry.Product2.AD_KG__c
    ),

    /* Second condition: Delivery Date is on or after 22/09/2024 */
    IF(
        /* Check if AD_KG_from_Weights__c is greater than 0 */
        AD_KG_from_Weights__c &gt; 0,
        AD_KG_from_Weights__c,

        /* If AD_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
        IF(
            TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
            /* Fall Back Weight Type is &quot;No Weight&quot; */
            0,

            IF(
                /* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
                TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot; 
                &amp;&amp; PricebookEntry.Product2.AD_KG__c &gt; 0,
                /* Apply Company Average Weight if AD_KG__c is greater than 0 */
                Quantity * PricebookEntry.Product2.Estimated_Weight__c,

                /* Default value if none of the conditions match */
                Quantity * PricebookEntry.Product2.AD_KG__c
            )
        )
    )
)</formula>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Recycled_KG__c.field-meta.xml
<CustomField>
    <fullName>Recycled_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(Recycled_KG_from_Weights__c)),
Recycled_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.Recycle_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if Recycled_KG_from_Weights__c is greater than 0 */
Recycled_KG_from_Weights__c &gt; 0,
Recycled_KG_from_Weights__c,

/* If Recycled_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and AD_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.Recycle_KG__c &gt; 0,
/* Apply Company Average Weight if Recycle_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.Recycle_KG__c
)
)
)
)</formula>
    <label>Recycled KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tonnes_CO2_Saved__c.field-meta.xml
<CustomField>
    <fullName>Tonnes_CO2_Saved__c</fullName>
    <formula>IF(NOT(ISNULL(Tonnes_CO2_Saved_from_Weights__c)), Tonnes_CO2_Saved_from_Weights__c, 
 IF(NOT(ISNULL(Coffee_KG__c)), Coffee_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(AD_KG__c)), AD_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0) + 
 IF(NOT(ISNULL(Recycled_KG__c)), Recycled_KG__c * PricebookEntry.Product2.Tonnes_CO2_Saved_Per_KG__c, 0)
)</formula>
    <label>Tonnes CO2 Saved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <formula>IF(
/* First condition: Delivery Date is less than 22/09/2024 */
Order.Delivery_Date__c &lt; DATE(2024, 9, 22),
/* Use the original logic */
IF(
NOT(ISNULL(WTE_KG_from_Weights__c)),
WTE_KG_from_Weights__c,
Quantity *  PricebookEntry.Product2.WTE_KG__c
),

/* Second condition: Delivery Date is on or after 22/09/2024 */
IF(
/* Check if WTE_KG_from_Weights__c is greater than 0 */
WTE_KG_from_Weights__c &gt; 0,
WTE_KG_from_Weights__c,

/* If WTE_KG_from_Weights__c is blank or zero, apply Fall_Back_Weight_Type__c logic */
IF(
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;No Weight&quot;,
/* Fall Back Weight Type is &quot;No Weight&quot; */
0,

IF(
/* Check if it&apos;s a Company Average Weight and WTE_KG__c &gt; 0 */
TEXT(Order.Account.Fall_Back_Weight_Type__c) = &quot;Company Average Weight&quot;
&amp;&amp; PricebookEntry.Product2.WTE_KG__c &gt; 0,
/* Apply Company Average Weight if WTE_KG__c is greater than 0 */
Quantity * PricebookEntry.Product2.Estimated_Weight__c,

/* Default value if none of the conditions match */
Quantity * PricebookEntry.Product2.WTE_KG__c
)
)
)
)</formula>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AD_KG__c.field-meta.xml
<CustomField>
    <fullName>AD_KG__c</fullName>
    <description>KG&apos;s in the sack which go to AD, assuming sack is full</description>
    <inlineHelpText>KG&apos;s in the sack which go to AD, assuming sack is full</inlineHelpText>
    <label>AD KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/WTE_KG__c.field-meta.xml
<CustomField>
    <fullName>WTE_KG__c</fullName>
    <label>WTE KG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/OrderItemsManagerWebService_Test.cls
@isTest
public class OrderItemsManagerWebService_Test {
    
    @isTest 
    private static void handleOrderItem_Test() {
        Test.startTest();
        Id orderIdObj = createDummyData();
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://' + URL.getSalesforceBaseUrl().getHost() +'/services/apexrest/OrderItem/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{"orderIdObject": "orderIdObj","unitPriceObject":129.00}');
        RestContext.request = request;
        // add an order item under specific product
        String orderItemId = OrderItemsManagerWebService.handleOrderItem(orderIdObj, 167.00);
        System.debug('id is::::'+orderItemId);
        // Verify order item has been added
        System.assert(orderItemId != null);
        Test.stopTest();
    }  
    @isTest 
    private static void handleOrderItem_Test2() {
        Test.startTest();
        Account parentAccount = TestDataHelper.createAccount();
        INSERT parentAccount;
        Account locationAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        INSERT locationAccount;
        
        Suppliers__c supObj = new Suppliers__c();
        supObj.Name = 'Test Supp';
        supObj.Phone_Number__c = '1234567898';
        INSERT supObj;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Order orderObj = new Order(
            AccountId = locationAccount.Id,
            EffectiveDate = System.today().addMonths(-(1)),
            Status = 'draft',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Type = 'Regular',
            PO_Number__c = 'WheelieBinOrder0',
            Invoice_Created__c = false,
            Pricebook2Id = pricebookId,
            Supplier__c = supObj.Id
        );
        insert orderObj;
        
        //Create your product
        Product2 prod = TestDataHelper.insertProduct('Additional Waste', 'Pro-X', 'Delivery');
        
        Id orderIdObj = orderObj.id;
        RestRequest request = new RestRequest();
        request.requestUri =
                'https://' + URL.getSalesforceBaseUrl().getHost() + '/services/apexrest/OrderItem/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{"orderIdObject": "orderIdObj","unitPriceObject":129.00}');
        RestContext.request = request;
        // add an order item under specific product
        String orderItemId = OrderItemsManagerWebService.handleOrderItem(orderIdObj, 167.00);
        System.debug('id is::::'+orderItemId);
        // Verify order item has been added
        System.assert(orderItemId != null);
        Test.stopTest();
    }  
    
    @isTest 
    private static void handleOrderItem_Test4() {
        Test.startTest();
        Account parentAccount = TestDataHelper.createAccount();
        INSERT parentAccount;
        Account locationAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        INSERT locationAccount;
        
        Suppliers__c supObj = new Suppliers__c();
        supObj.Name = 'Test Supp';
        supObj.Phone_Number__c = '1234567898';
        INSERT supObj;
        
        Id pricebookId = Test.getStandardPricebookId();
        System.debug('old standard::::::'+pricebookId);
        
        
        //Create your product
        Product2 prod = TestDataHelper.insertProduct('Additional Waste', 'Pro-X', 'Delivery');
        
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true,Effective_Date__c = System.today());
        insert customPB;
        
        Order orderObj = new Order(
            AccountId = locationAccount.Id,
            EffectiveDate = System.today().addMonths(-(1)),
            Status = 'draft',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Type = 'Regular',
            PO_Number__c = 'WheelieBinOrder0',
            Invoice_Created__c = false,
            Pricebook2Id = customPB.Id,
            Supplier__c = supObj.Id
        );
        insert orderObj;
        
        Pricebook2 customPBnew = new Pricebook2(Name='Custom PB', isActive=true,Effective_Date__c = System.today());
        insert customPBnew;
        
        //Create your pricebook entry
        PricebookEntry pbEntry2 = new PricebookEntry(
            Pricebook2Id = customPBnew.Id,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry2;
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://' + URL.getSalesforceBaseUrl().getHost() + '/services/apexrest/OrderItem/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{"orderIdObject": "orderObj.Id","unitPriceObject":129.00}');
        RestContext.request = request;
        // add an order item under specific product
        String orderItemId = OrderItemsManagerWebService.handleOrderItem(orderObj.Id, 167.00);
        System.debug('id is::::'+orderItemId);
        // Verify order item has been added
        System.assert(orderItemId != null);
        Test.stopTest();
    } 
    //helper method
    static ID createDummyData(){
        Account parentAccount = TestDataHelper.createAccount();
        INSERT parentAccount;
        Account locationAccount = TestDataHelper.createLocation(parentAccount.Id, Null);
        INSERT locationAccount;
        
        Suppliers__c supObj = new Suppliers__c();
        supObj.Name = 'Test Supp';
        supObj.Phone_Number__c = '1234567898';
        INSERT supObj;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Order orderObj = new Order(
            AccountId = locationAccount.Id,
            EffectiveDate = System.today().addMonths(-(1)),
            Status = 'draft',
            AD_KG__c = 100,
            Recycled_KG__c = 100,
            WTE_KG__c = 100,
            Tonnes_CO2_Saved__c = 100,
            Type = 'Regular',
            PO_Number__c = 'WheelieBinOrder0',
            Invoice_Created__c = false,
            Pricebook2Id = pricebookId,
            Supplier__c = supObj.Id
        );
        insert orderObj;
        
        //Create your product
        Product2 prod = TestDataHelper.insertProduct('Additional Waste', 'Pro-X', 'Delivery');
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        return orderObj.Id;
    }
}