force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Excess__c.field-meta.xml
<CustomField>
    <fullName>Excess__c</fullName>
    <formula>MAX(Matched__c + Unmatched__c - Waypoints__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Excess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/UnmatchedOverweight__c.field-meta.xml
<CustomField>
    <fullName>UnmatchedOverweight__c</fullName>
    <label>Unmatched Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/BinWeight__c.object-meta.xml
<CustomObject>
    <label>Bin Weight</label>
    <nameField>
        <displayFormat>BW-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinWeight__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Weights</relationshipLabel>
    <relationshipName>BinWeights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Overweight__c.field-meta.xml
<CustomField>
    <fullName>Overweight__c</fullName>
    <formula>MAX(Kilogram__c - AllowedWeight__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>No match</fullName>
            </value>
            <value>
                <fullName>No unique match</fullName>
            </value>
            <value>
                <fullName>Weight already present</fullName>
            </value>
            <value>
                <fullName>Manually matched</fullName>
            </value>
            <value>
                <fullName>Match removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Unachievable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ConfirmationEmailStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationEmailStatus__c</fullName>
    <label>Confirmation Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Do Not Send</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <defaultValue>IF(
WEEKDAY(TODAY()+1)&gt;1 &amp;&amp; WEEKDAY(TODAY()+1)&lt;7, TODAY()+1, IF(WEEKDAY(TODAY()+1)=1, TODAY()+2, TODAY()+3)
)</defaultValue>
    <inlineHelpText>This field is used in the Supplier App.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Overweight__c.field-meta.xml
<CustomField>
    <fullName>Overweight__c</fullName>
    <label>Overweight</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/OverweightSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Overweight Setting</label>
</CustomObject>

force-app/main/default/objects/OverweightSetting__c/fields/FoodChargeProductId__c.field-meta.xml
<CustomField>
    <fullName>FoodChargeProductId__c</fullName>
    <label>Food Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/FoodProductCategoryId__c.field-meta.xml
<CustomField>
    <fullName>FoodProductCategoryId__c</fullName>
    <label>Food Product Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/GeneralWasteChargeProductId__c.field-meta.xml
<CustomField>
    <fullName>GeneralWasteChargeProductId__c</fullName>
    <label>General Waste Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/GeneralWasteProductCategoryId__c.field-meta.xml
<CustomField>
    <fullName>GeneralWasteProductCategoryId__c</fullName>
    <label>General Waste Product Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/GlassChargeProductId__c.field-meta.xml
<CustomField>
    <fullName>GlassChargeProductId__c</fullName>
    <label>Glass Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/GlassProductCategoryId__c.field-meta.xml
<CustomField>
    <fullName>GlassProductCategoryId__c</fullName>
    <label>Glass Product Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/MixedRecyclingChargeProductId__c.field-meta.xml
<CustomField>
    <fullName>MixedRecyclingChargeProductId__c</fullName>
    <label>Mixed Recycling Charge Product</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OverweightSetting__c/fields/MixedRecyclingProductCategoryId__c.field-meta.xml
<CustomField>
    <fullName>MixedRecyclingProductCategoryId__c</fullName>
    <label>Mixed Recycling Product Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BinChargeBatch.cls
public without sharing class BinChargeBatch implements Database.Batchable<sObject>, Database.Stateful {

	private Map<String, Product2> categoryCodeToProductMap = new Map<String, Product2>();

	private Id FIRSTMILE_SUPPLIER_ID;
	private Id GENERAL_WASTE_CATEGORY;
	private Id MIXED_RECYCLING_CATEGORY;
	private Id FOOD_CATEGORY;
	private Id GLASS_CATEGORY;
	private Id GENERAL_WASTE_CHARGE;
	private Id MIXED_RECYCLING_CHARGE;
	private Id FOOD_CHARGE;
	private Id GLASS_CHARGE;
	private Date YESTERDAY;
	private String MONTH;
	private String YEAR;

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		FIRSTMILE_SUPPLIER_ID = [SELECT Id FROM Suppliers__c WHERE Name = 'First Mile Ltd'].Id;

		OverweightSetting__c overweightSetting = OverweightSetting__c.getOrgDefaults();
		GENERAL_WASTE_CATEGORY = overweightSetting.GeneralWasteProductCategoryId__c;
		MIXED_RECYCLING_CATEGORY = overweightSetting.MixedRecyclingProductCategoryId__c;
		FOOD_CATEGORY = overweightSetting.FoodProductCategoryId__c;
		GLASS_CATEGORY = overweightSetting.GlassProductCategoryId__c;
		GENERAL_WASTE_CHARGE = overweightSetting.GeneralWasteChargeProductId__c;
		MIXED_RECYCLING_CHARGE = overweightSetting.MixedRecyclingChargeProductId__c;
		FOOD_CHARGE = overweightSetting.FoodChargeProductId__c;
		GLASS_CHARGE = overweightSetting.GlassChargeProductId__c;

		YESTERDAY = System.today() - 1;
		MONTH = String.valueOf('0' + YESTERDAY.month()).right(2);
		YEAR = String.valueOf(YESTERDAY.year());

		for (Product2 product : [SELECT BinCategoryCode__c, Product_Category__c FROM Product2 WHERE BinCategoryCode__c != null]) {
			categoryCodeToProductMap.put(product.BinCategoryCode__c, product);
		}

		String query = 'SELECT Id, Price_Book__c FROM Account WHERE Id IN (SELECT Location__c FROM BinSummary__c WHERE Month__c = :MONTH AND Year__c = :YEAR AND (Excess__c > 0 OR UnmatchedOverweight__c > 0))';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Account> locations) {
		Map<Id, Account> locationMap = new Map<Id, Account>(locations);

		Map<Id, Order> orderMap = insertOrders(locations);
		List<OrderItem> orderItems = new List<OrderItem>();
		orderItems.addAll(createExcessBinOrderItems(orderMap, locationMap));
		orderItems.addAll(createUnmatchedOverweightChargeOrderItems(orderMap, locationMap));
		INSERT orderItems;

		for (Order order : orderMap.values()) {
			order.Status = 'Delivered';
		}
		UPDATE orderMap.values();
	}

	public void finish(Database.BatchableContext BC) {}

	private Map<Id, Order> insertOrders(List<Account> locations) {
		Map<Id, Order> orderMap = new Map<Id, Order>();
		for (Account location : locations) {
			orderMap.put(location.Id, new Order(AccountId = location.Id, EffectiveDate = YESTERDAY, Delivery_Date__c = YESTERDAY, Requested_Delivery_Date__c = YESTERDAY,
				Status = 'Draft', IsBinCollection__c = true, ConfirmationEmailStatus__c = 'Do Not Send'));
		}

		INSERT orderMap.values();

		return orderMap;
	}

	private List<OrderItem> createExcessBinOrderItems(Map<Id, Order> orderMap, Map<Id, Account> locationMap) {
		List<AggregateResult> aggregateResults = [SELECT Location__c, CategoryCode__c, SUM(Excess__c) Quantity FROM BinSummary__c
			WHERE Location__c IN :locationMap.keySet() AND Excess__c > 0 AND Month__c = :MONTH AND Year__c = :YEAR
			GROUP BY Location__c, CategoryCode__c];
		if (aggregateResults.isEmpty()) {
			return new List<OrderItem>();
		}

		Map<String, Collection_Waypoints__c> waypointMap = fetchWaypointMap(aggregateResults);

		List<OrderItem> orderItems = new List<OrderItem>();
		Id locationId;
		String categoryCode;
		for (AggregateResult aggregateResult : aggregateResults) {
			locationId = (Id)aggregateResult.get('Location__c');
			categoryCode = (String)aggregateResult.get('CategoryCode__c');
			Collection_Waypoints__c waypoint = waypointMap.get(locationId + '-' + categoryCode);
			if (waypoint != null) {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(locationId).Id, categoryCodeToProductMap.get(categoryCode).Id, (Decimal)aggregateResult.get('Quantity'), locationMap.get(locationId).Price_Book__c, waypoint.Manual_Price__c, waypoint.Discount_Type__c, waypoint.Account_Discount__r, FIRSTMILE_SUPPLIER_ID));
			} else {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(locationId).Id, categoryCodeToProductMap.get(categoryCode).Id, (Decimal)aggregateResult.get('Quantity'), locationMap.get(locationId).Price_Book__c, null, null, null, FIRSTMILE_SUPPLIER_ID));
			}
		}

		return orderItems;
	}

	private List<OrderItem> createUnmatchedOverweightChargeOrderItems(Map<Id, Order> orderMap, Map<Id, Account> locationMap) {
		List<AggregateResult> aggregateResults = [SELECT Location__c, CategoryCode__c, SUM(Overweight__c) Overweight FROM BinWeight__c
			WHERE Location__c IN :locationMap.keySet() AND Status__c = 'No match' AND Overweight__c > 0 AND CreatedDate = LAST_MONTH
			GROUP BY Location__c, CategoryCode__c];
		if (aggregateResults.isEmpty()) {
			return new List<OrderItem>();
		}

		Map<Id, Decimal> locationGeneralWasteMap = new Map<Id, Decimal>();
		Map<Id, Decimal> locationMixedWasteMap = new Map<Id, Decimal>();
		Map<Id, Decimal> locationFoodWasteMap = new Map<Id, Decimal>();
		Map<Id, Decimal> locationGlassWasteMap = new Map<Id, Decimal>();
		Id locationId;
		Decimal overweight;
		for (AggregateResult aggregateResult : aggregateResults) {
			locationId = (Id)aggregateResult.get('Location__c');
			overweight = (Decimal)aggregateResult.get('Overweight');
			Product2 product = categoryCodeToProductMap.get((String)aggregateResult.get('CategoryCode__c'));
			if (product.Product_Category__c == GENERAL_WASTE_CATEGORY) {
				Decimal weight = locationGeneralWasteMap.containsKey(locationId) ? locationGeneralWasteMap.get(locationId) + overweight : overweight;
				locationGeneralWasteMap.put(locationId, weight);
			} else if (product.Product_Category__c == MIXED_RECYCLING_CATEGORY) {
				Decimal weight = locationMixedWasteMap.containsKey(locationId) ? locationMixedWasteMap.get(locationId) + overweight : overweight;
				locationMixedWasteMap.put(locationId, weight);
			} else if (product.Product_Category__c == FOOD_CATEGORY) {
				Decimal weight = locationFoodWasteMap.containsKey(locationId) ? locationFoodWasteMap.get(locationId) + overweight : overweight;
				locationFoodWasteMap.put(locationId, weight);
			} else if (product.Product_Category__c == GLASS_CATEGORY) {
				Decimal weight = locationGlassWasteMap.containsKey(locationId) ? locationGlassWasteMap.get(locationId) + overweight : overweight;
				locationGlassWasteMap.put(locationId, weight);
			}
		}

		List<OrderItem> orderItems = new List<OrderItem>();
		for (Account location : locationMap.values()) {
			if (locationGeneralWasteMap.containsKey(location.Id)) {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(location.Id).Id, GENERAL_WASTE_CHARGE, locationGeneralWasteMap.get(location.Id), location.Price_Book__c));
			}
			if (locationMixedWasteMap.containsKey(location.Id)) {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(location.Id).Id, MIXED_RECYCLING_CHARGE, locationMixedWasteMap.get(location.Id), location.Price_Book__c));
			}
			if (locationFoodWasteMap.containsKey(location.Id)) {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(location.Id).Id, FOOD_CHARGE, locationFoodWasteMap.get(location.Id), location.Price_Book__c));
			}
			if (locationGlassWasteMap.containsKey(location.Id)) {
				orderItems.add(OrderUtil.createOrderItem(orderMap.get(location.Id).Id, GLASS_CHARGE, locationGlassWasteMap.get(location.Id), location.Price_Book__c));
			}
		}

		return orderItems;
	}

	private Map<String, Collection_Waypoints__c> fetchWaypointMap(List<AggregateResult> binSummaryAggregateResults) {
		List<String> binKeys = new List<String>();
		for (AggregateResult aggregateResult : binSummaryAggregateResults) {
			binKeys.add((String)aggregateResult.get('Location__c') + '-' + (String)aggregateResult.get('CategoryCode__c') + '-' + YEAR + '-' + MONTH);
		}

		List<AggregateResult> waypointAggregateResults = [SELECT MAX(Id) WaypointId FROM Collection_Waypoints__c WHERE BinKey__c IN :binKeys GROUP BY BinKey__c];
		List<Id> waypointIds = new List<Id>();
		for (AggregateResult aggregateResult : waypointAggregateResults) {
			waypointIds.add((Id)aggregateResult.get('WaypointId'));
		}

		Map<String, Collection_Waypoints__c> waypointMap = new Map<String, Collection_Waypoints__c>();
		for (Collection_Waypoints__c waypoint : [SELECT Location__c, Discount_Type__c, Account_Discount__r.BID_Price__c, Account_Discount__r.Product_Discount__c, Manual_Price__c, Supplier_Product__r.Product__r.BinCategoryCode__c FROM Collection_Waypoints__c WHERE Id IN: waypointIds]) {
			waypointMap.put(waypoint.Location__c + '-' + waypoint.Supplier_Product__r.Product__r.BinCategoryCode__c, waypoint);
		}

		return waypointMap;
	}
}