force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Estimated_Annual_Sales__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Annual_Sales__c</fullName>
    <label>Estimated Annual Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled Waste and Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Other Waste/Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Secure Shredding</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance/Junk Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Business Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting and Data</fullName>
    </customValue>
    <customValue>
        <fullName>Product Partnership</fullName>
    </customValue>
    <masterLabel>Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewLocationControllerTest.cls
@isTest
private class NewLocationControllerTest {

	@isTest static void test_method_one() {
		Test.setMock(HttpCalloutMock.class, new DoogalTest.RestMock('TW1 2RS	51.452903	-0.317551	Postcode terminated prior to Gridlink initiative - last known ONS postcode grid reference	Twickenham	Richmond upon Thames	Twickenham Riverside	Richmond upon Thames 009C	Greater London	London	England		10.66619777679443	Urban major conurbation	Slough and Heathrow	E01003894'));
		Account a = new Account();
		a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		a.Name = 'test';
		a.BillingCity = 'city';
		a.BillingStreet = 'street';
		a.BillingPostalCode = '12345';
		a.BillingCountry = 'United Kingdom';
		a.BillingState = null;
		a.Price_Book__c = Test.getStandardPricebookId();
		insert a;

		Account b = new Account();
		b.Name = 'test3';
		b.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
		b.BillingCity = 'city';
		b.BillingStreet = 'street';
		b.BillingPostalCode = '12345';
		b.BillingCountry = 'United Kingdom';
		b.Price_Book__c = Test.getStandardPricebookId();
		b.BillingState = null;
		insert b;
		
		Opportunity opp = new Opportunity();
		opp.Name = 'test opp';
		opp.AccountId = a.Id;
		opp.CloseDate = System.today() + 10;
		opp.Estimated_Annual_Sales__c = 100;
		opp.StageName = 'DM confirmed - no response';
        opp.Services__c = 'Scheduled Waste and Recycling Collections';
		insert opp;

		Opportunity opp2 = new Opportunity();
		opp2.Name = 'test opp';
		opp2.AccountId = b.Id;
		opp2.CloseDate = System.today() + 10;
		opp2.Estimated_Annual_Sales__c = 100;
		opp2.StageName = 'DM confirmed - no response';
        opp2.Services__c = 'Scheduled Waste and Recycling Collections';
		insert opp2;

		List<string> fields2 = new List<string>();
		fields2.add('test4');

		List<string> fields = new List<string>();
		fields.add('test2');
		fields.add('street2');
		fields.add('city2');
		fields.add('12344');
		fields.add(null);
		fields.add('United Kingdom');

		NewLocationController.createLocationController(opp.Id, fields2);
		NewLocationController.createLocationWithFields(opp2.Id, fields);
		NewLocationController.getParentLocName(opp.Id);
	}

	
}