force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Container_Type__c/Container_Type__c.object-meta.xml
<CustomObject>
    <label>Container Type</label>
    <nameField>
        <label>Container Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook2/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Enqix_Code__c.field-meta.xml
<CustomField>
    <fullName>Enqix_Code__c</fullName>
    <label>Enqix Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this record is the most recent version of the pricelist</description>
    <label>Most Recent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Type</label>
    <referenceTo>Container_Type__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Pricebook2TriggerTest.cls
@isTest
public class Pricebook2TriggerTest {
	
   @testSetup
    static void setupTest() {
        
        Container_Type__c ct = new Container_Type__c();
        ct.Name = 'External Bin';
        insert ct;
        
        product2 productRec = TestDataHelper.createProduct('TestProduct', 'Prod1', 'Collection', null, null, ct.Id, '673765');
        INSERT productRec;
        
        priceBook2 pb = new priceBook2();
        pb.Name = 'Test PriceBook ';
        pb.IsActive = true;
        pb.Enqix_Code__c = 1123331;
        pb.Effective_Date__c=System.Today();
        pb.Most_Recent__c = false;
        insert pb;
        
        PricebookEntry priceBookEntry = new  PricebookEntry();
        priceBookEntry.Product2Id = productRec.Id;
        priceBookEntry.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntry.UnitPrice = 100;
        priceBookEntry.IsActive = True;
        insert priceBookEntry;
        
        Pricebook2 pb2 = new Pricebook2();
        pb2.Id = Test.getStandardPricebookId();
        pb2.IsActive = false;
        pb2.Enqix_Code__c = 1123331;
        pb2.Most_Recent__c = True;
        pb2.Effective_Date__c = system.now();
        Update pb2;
        
        List<Pricebook2> listActivePricebooks = [SELECT id, Enqix_Code__c, Most_Recent__c FROM Pricebook2 WHERE IsActive = true];
 
        Account account = new Account();
        account.Name = 'Xpand IT Account';
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        account.Price_Book__c =  listActivePricebooks[0].Id;
        insert account;
        account.Price_Book__c =  listActivePricebooks[0].Id;
        update account;

        Account locationAcc = new Account();
        locationAcc.Name = 'Location Acc';
        locationAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        locationAcc.ParentId = account.Id;
        insert locationAcc;
    }
    
    @isTest
    public static void insertAnotherpb() {

        PricebookDateChecker pdc = new PricebookDateChecker();
        pdc.execute(null);

    }
}