force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BinLift__c/BinLift__c.object-meta.xml
<CustomObject>
    <label>Bin Lift</label>
    <nameField>
        <displayFormat>BL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Lifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinLift__c/fields/CollectedAt__c.field-meta.xml
<CustomField>
    <fullName>CollectedAt__c</fullName>
    <label>Collected At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Lifts</relationshipLabel>
    <relationshipName>BinLifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Overweight__c.field-meta.xml
<CustomField>
    <fullName>Overweight__c</fullName>
    <formula>MAX(Kilogram__c - AllowedWeight__c, 0)</formula>
    <label>Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attempt 1</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>No match</fullName>
            </value>
            <value>
                <fullName>Weight Added</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unknown Location</fullName>
            </value>
            <value>
                <fullName>Unknown Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/BinMatched__c.field-meta.xml
<CustomField>
    <fullName>BinMatched__c</fullName>
    <label>Bin Matched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/BinUnmatched__c.field-meta.xml
<CustomField>
    <fullName>BinUnmatched__c</fullName>
    <label>Bin Unmatched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/BinUnmatchedOverweight__c.field-meta.xml
<CustomField>
    <fullName>BinUnmatchedOverweight__c</fullName>
    <label>Bin Unmatched Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BinSummaryOfBinLiftBatch.cls
public without sharing class BinSummaryOfBinLiftBatch implements Database.Batchable<sObject>, Database.Stateful {

	private String MONTH;
	private String YEAR;
	private String DATE_CRITERIA;

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		Date today = System.today();

		if (today.day() == 1) {
			Date yesterday = today - 1;
			DATE_CRITERIA = 'CollectedAt__c = LAST_MONTH';
			MONTH = String.valueOf('0' + yesterday.month()).right(2);
			YEAR = String.valueOf(yesterday.year());
		} else {
			DATE_CRITERIA = 'CollectedAt__c = THIS_MONTH AND CollectedAt__c != TODAY';
			MONTH = String.valueOf('0' + today.month()).right(2);
			YEAR = String.valueOf(today.year());
		}

		String query = 'SELECT Id FROM Account WHERE Id IN (SELECT Location__c FROM BinLift__c WHERE Status__c IN (\'No match\', \'Matched\', \'Weight Added\') AND ' + DATE_CRITERIA + ')';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Account> locations) {
		Map<String, BinSummary__c> binSummaryMap = new Map<String, BinSummary__c>();
		String status;
		String key;
		List<String> splitKey;

		String aggregateQuery = 'SELECT Key__c, Status__c, Count(Id) BinLifts, SUM(Overweight__c) OverWeight FROM BinLift__c WHERE Location__c IN :locations AND Status__c IN (\'No match\', \'Matched\', \'Weight Added\') AND ' + DATE_CRITERIA
			+ ' GROUP BY Key__c, Status__c';
		for (AggregateResult aggregateResult : Database.query(aggregateQuery)) {
			status = (String)aggregateResult.get('Status__c');
			key = (String)aggregateResult.get('Key__c');
			splitKey = StringUtil.splitTrim(key, '-');
			BinSummary__c binSummary;

			if (binSummaryMap.containsKey(key)) {
				binSummary = binSummaryMap.get(key);
			} else {
				binSummary = new BinSummary__c(Key__c = key, Location__c = splitKey[0], CategoryCode__c = splitKey[1], Year__c = YEAR, Month__c = MONTH);
			}
			if (status == 'No match') {
				binSummary.BinUnmatched__c = (Integer)aggregateResult.get('BinLifts');
				binSummary.BinUnmatchedOverweight__c = (Decimal)aggregateResult.get('OverWeight');
			} else if (status == 'Matched' || status == 'Weight Added') {
				binSummary.BinMatched__c = (Integer)aggregateResult.get('BinLifts');
			}
			binSummaryMap.put(key, binSummary);
		}

		if (!binSummaryMap.isEmpty()) {
			UPSERT binSummaryMap.values() Key__c;
		}
	}

	public void finish(Database.BatchableContext BC) {
		// if (System.today().day() == 1) {
		// 	Database.executeBatch(new BinChargeBatch(), 50);
		// }
	}
}