force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Packages</relationshipLabel>
    <relationshipName>DeliveryPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingIds__c.field-meta.xml
<CustomField>
    <fullName>TrackingIds__c</fullName>
    <label>All Tracking Ids</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingStreetLineSingle__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreetLineSingle__c</fullName>
    <description>Street as a single line.</description>
    <formula>SUBSTITUTE(ShippingStreet, MID($Setup.LineBreak__c.Value__c, 2, 2), &apos;, &apos;)</formula>
    <label>Shipping Street Line Single</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/RoyalMailSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Royal Mail Setting</label>
</CustomObject>

force-app/main/default/objects/RoyalMailSetting__c/fields/DeclaredWeight__c.field-meta.xml
<CustomField>
    <fullName>DeclaredWeight__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Declared Weight</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/fields/DescriptionOfGoods__c.field-meta.xml
<CustomField>
    <fullName>DescriptionOfGoods__c</fullName>
    <label>Description Of Goods</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/fields/ShippingAccountId__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccountId__c</fullName>
    <label>Shipping Account Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoyalMailSetting__c/fields/ShippingLocationId__c.field-meta.xml
<CustomField>
    <fullName>ShippingLocationId__c</fullName>
    <label>Shipping Location Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoyalMailDeliveryCreateBatch.cls
public without sharing class RoyalMailDeliveryCreateBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

	private final RoyalMailSetting__c royalMailSetting = RoyalMailSetting__c.getOrgDefaults();
	private final String ACCOUNT_ID = royalMailSetting.ShippingAccountId__c;
	private final String LOCATION_ID = royalMailSetting.ShippingLocationId__c;
	private final String SERVICE_CODE = royalMailSetting.ServiceCode__c;
	private final String DESCRIPTION_OF_GOODS = royalMailSetting.DescriptionOfGoods__c;
	private final Decimal DECLARED_WEIGHT = royalMailSetting.DeclaredWeight__c;
	private final String shipmentDate;

	private Set<Id> packageIds = new Set<Id>();

	public RoyalMailDeliveryCreateBatch(Set<Id> packageIds) {
		this.packageIds = packageIds;

		Time lastCollection;
		try {
			lastCollection = Convert.toTime(royalMailSetting.LastCollection__c);
		} catch (Exception e) {
			lastCollection = Time.newInstance(23, 59, 59, 0);
		}

		DateTime NOW = System.now();
		shipmentDate = Convert.toString(NOW.time() <= lastCollection ? NOW.date() : DateUtil.getNextWeekday(NOW.date()), 'yyyy-MM-dd');
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Order__r.Account.Name, Order__r.OrderNumber, Count__c,
			Order__r.ShippingStreetLineSingle__c, Order__r.ShippingCity, Order__r.ShippingPostalCode, Order__r.ShippingCountryCode
			FROM DeliveryPackage__c
			WHERE Id IN :packageIds AND Status__c IN (:DeliveryPackage.STATUS_NEW, :DeliveryPackage.STATUS_RETRY) AND IsCollection__c = false]);
	}

	public void execute(Database.BatchableContext BC, List<DeliveryPackage__c> scope) {
		List<Attachment> attachments = new List<Attachment>();

		for (DeliveryPackage__c pkg : scope) {
			try {
				attachments.add(process(pkg));
			} catch (Exception e) {
				pkg.Status__c = DeliveryPackage.STATUS_ERROR;
				pkg.Message__c = e.getMessage();
			}
		}

		INSERT attachments;
		UPDATE scope;
	}

	public void finish(Database.BatchableContext BC) {}

	private Attachment process(DeliveryPackage__c pkg) {
		RoyalMailDelivery.CreateResponse response = post(createRequest(pkg));
		pkg.Message__c = '';	// Clear any previous error message
		pkg.Status__c = DeliveryPackage.STATUS_LABELLED;
		pkg.TrackingId__c = response.Packages[0].TrackingNumber;

		List<String> trackingIds = new List<String>();
		for (RoyalMailDelivery.ResponsePackage responsePackage : response.Packages) {
			trackingIds.add(responsePackage.TrackingNumber);
		}
		pkg.TrackingIds__c = String.join(trackingIds, ', ');

		return addAttachment(pkg, response);
	}

	private RoyalMailDelivery.CreateRequest createRequest(DeliveryPackage__c pkg) {
		RoyalMailDelivery.CreateRequest request = new RoyalMailDelivery.CreateRequest();

		request.ShipmentInformation.ServiceCode = SERVICE_CODE;
		request.ShipmentInformation.DescriptionOfGoods = DESCRIPTION_OF_GOODS;
		request.ShipmentInformation.ShipmentDate = shipmentDate;

		request.Shipper.ShippingAccountId = ACCOUNT_ID;
		request.Shipper.ShippingLocationId = LOCATION_ID;
		request.Shipper.Reference1 = pkg.Order__r.OrderNumber;

		request.Destination.Address.CompanyName = pkg.Order__r.Account.Name.left(40);
		List<String> shippingStreet = StringUtil.split(pkg.Order__r.ShippingStreetLineSingle__c, ',', 40, 3);
		request.Destination.Address.Line1 = shippingStreet.size() >= 1 ? shippingStreet[0] : null;
		request.Destination.Address.Line2 = shippingStreet.size() >= 2 ? shippingStreet[1] : null;
		request.Destination.Address.Line3 = shippingStreet.size() >= 3 ? shippingStreet[2] : null;
		request.Destination.Address.Town = pkg.Order__r.ShippingCity;
		request.Destination.Address.Postcode = pkg.Order__r.ShippingPostalCode;
		request.Destination.Address.CountryCode = pkg.Order__r.ShippingCountryCode;

		Integer numberOfParcels = Integer.valueOf(pkg.Count__c);
		Integer counter = 1;
		while (counter <= numberOfParcels) {
			request.Packages.add(new RoyalMailDelivery.RequestPackage(DECLARED_WEIGHT, counter++));
		}

		return request;
	}

	private RoyalMailDelivery.CreateResponse post(RoyalMailDelivery.CreateRequest shipmentRequest) {
		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:RoyalMail/shipments/rm');
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json');
		request.setBody(JSON.serialize(shipmentRequest));

		HttpResponse response = new Http().send(request);
		RoyalMailDelivery.CreateResponse shipmentResponse = (RoyalMailDelivery.CreateResponse)JSON.deserialize(response.getBody(), RoyalMailDelivery.CreateResponse.class);
		if (response.getStatusCode() == 200) {
			return shipmentResponse;
		} else {
			String errorMessage = '';
			for (RoyalMailDelivery.Error error : shipmentResponse.Errors) {
				errorMessage += error.Message + ' ';
			}
			throw new RoyalMailDelivery.RequestException(errorMessage.trim());
		}
	}

	private Attachment addAttachment(DeliveryPackage__c pkg, RoyalMailDelivery.CreateResponse response) {
		Attachment attachment = new Attachment();
		attachment.ParentId = pkg.Id;
		attachment.Name = 'RoyalMail Label - ' + response.Packages[0].TrackingNumber + '.pdf';
		attachment.Body = EncodingUtil.base64Decode(response.Labels);
		return attachment;
	}
}