force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BinLift__c/BinLift__c.object-meta.xml
<CustomObject>
    <label>Bin Lift</label>
    <nameField>
        <displayFormat>BL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Lifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinLift__c/fields/CollectedAt__c.field-meta.xml
<CustomField>
    <fullName>CollectedAt__c</fullName>
    <label>Collected At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Kilogram__c.field-meta.xml
<CustomField>
    <fullName>Kilogram__c</fullName>
    <label>Kilogram</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Lifts</relationshipLabel>
    <relationshipName>BinLifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/LocationCode__c.field-meta.xml
<CustomField>
    <fullName>LocationCode__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <label>Location Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Bin Lifts</relationshipLabel>
    <relationshipName>BinLifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attempt 1</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>No match</fullName>
            </value>
            <value>
                <fullName>Weight Added</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unknown Location</fullName>
            </value>
            <value>
                <fullName>Unknown Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/TransponderCode__c.field-meta.xml
<CustomField>
    <fullName>TransponderCode__c</fullName>
    <label>Transponder Code</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/WasteCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>WasteCategoryCode__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <label>Waste Category Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weight</label>
    <referenceTo>Weight__c</referenceTo>
    <relationshipLabel>Bin Lifts</relationshipLabel>
    <relationshipName>BinLifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery date from Enqix system.</description>
    <inlineHelpText>Delivery date from Enqix system.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsBinCollection__c.field-meta.xml
<CustomField>
    <fullName>IsBinCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bin Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CollectionDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionDate__c</fullName>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/productcategory__c.field-meta.xml
<CustomField>
    <fullName>productcategory__c</fullName>
    <formula>PricebookEntry.Product2.Product_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PRoduct Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>Product Category as defined in the Enqix System.</description>
    <inlineHelpText>Product Category as defined in the Enqix System.</inlineHelpText>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weight__c/Weight__c.object-meta.xml
<CustomObject>
    <label>Weight</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weight__c/fields/BinLift__c.field-meta.xml
<CustomField>
    <fullName>BinLift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bin Lift</label>
    <referenceTo>BinLift__c</referenceTo>
    <relationshipLabel>Weights</relationshipLabel>
    <relationshipName>Weights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BinLiftToWeightBatchTest.cls
@isTest
public class BinLiftToWeightBatchTest {

	@testSetup
	static void setup() {
		TestDataHelper.insertVat();

		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null, 'FM0001');

		List<Product2> products = new List<Product2>();
		Product2 product1 = TestDataHelper.createProduct('Product 1', 'P0001', 'Collection');
		product1.ProductCategory__c = 'General Waste';
		product1.BinCategoryCode__c = 'GEN1100';
		products.add(product1);
		Product2 product2 = TestDataHelper.createProduct('Product 2', 'P0002', 'Collection');
		product2.ProductCategory__c = 'General Waste';
		product2.BinCategoryCode__c = 'GEN660';
		products.add(product2);
		INSERT products;
		List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[0].Id, 65.00));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[1].Id, 95.00));
		INSERT pricebookEntries;

		Order order = TestDataHelper.createOrder(location.Id, null);
		order.IsBinCollection__c = true;
		order.Delivery_Date__c = System.today();
		INSERT order;

		List<OrderItem> orderItems = new List<OrderItem>();
		OrderItem orderItem1 = TestDataHelper.createOrderItem(order.Id, products[0].Id, pricebookEntries[0].Id);
		orderItem1.CollectionDate__c = System.today() - 1;
		orderItems.add(orderItem1);
		OrderItem orderItem2 = TestDataHelper.createOrderItem(order.Id, products[1].Id, pricebookEntries[1].Id);
		orderItem2.CollectionDate__c = System.today() - 1;
		orderItems.add(orderItem2);
		INSERT orderItems;
	}

	@isTest static void createBinWeightsAndProcessOrders() {

		List<OrderItem> orderItem = [SELECT Id, Order.AccountId FROM OrderItem];
		DateTime now = System.now() - 1;
		BinLift__c binLift1 = new BinLift__c(OrderProduct__c = orderItem[0].Id, Location__c = orderItem[0].Order.AccountId, LocationCode__c = 'FM0001', Kilogram__c = 100, WasteCategoryCode__c = 'GEN1100', TransponderCode__c = '43FD4C1400004000', ExternalId__c = '43FD4C1443FD4C100', Status__c = 'Matched', CollectedAt__c = now);
		INSERT binLift1;
		BinLift__c binLift2 = new BinLift__c(OrderProduct__c = orderItem[1].Id, Location__c = orderItem[1].Order.AccountId, LocationCode__c = 'FM0001', Kilogram__c = 90, WasteCategoryCode__c = 'GEN660', TransponderCode__c = '43FD4C1400005000', ExternalId__c = '43FD4C140043FD4C10', Status__c = 'Matched', CollectedAt__c = now);
		INSERT binLift2;

		Test.startTest();
		Database.executeBatch(new BinLiftToWeightBatch());
		Test.stopTest();

        Assert.areEqual(2, [SELECT Id FROM Weight__c].size());
	}
}