force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/GoogleAdsEvent__c/GoogleAdsEvent__c.object-meta.xml
<CustomObject>
    <label>Google Ads Event</label>
    <nameField>
        <displayFormat>AdEvent-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Ads Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GoogleAdsEvent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GoogleAdsEvent__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GoogleAdsSetting__c/GoogleAdsSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Google Ads Setting</label>
</CustomObject>

force-app/main/default/objects/GoogleAdsSetting__c/fields/ExternalInbox__c.field-meta.xml
<CustomField>
    <fullName>ExternalInbox__c</fullName>
    <inlineHelpText>Separate each email address by comma</inlineHelpText>
    <label>External Inbox</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GoogleAdsSetting__c/fields/LeadStatusToSkip__c.field-meta.xml
<CustomField>
    <fullName>LeadStatusToSkip__c</fullName>
    <defaultValue>&quot;Closed. Existing customer, Closed. Not Relevant&quot;</defaultValue>
    <description>Comma separated list of lead status to skip</description>
    <label>Lead Status To Skip</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Services_wanted__c.field-meta.xml
<CustomField>
    <fullName>Services_wanted__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>How did they contact us?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce Sign-up</fullName>
            </value>
            <value>
                <fullName>Inbound Email</fullName>
            </value>
            <value>
                <fullName>Inbound Phone</fullName>
            </value>
            <value>
                <fullName>Inbound Website Enquiry</fullName>
            </value>
            <value>
                <fullName>Outbound Contact</fullName>
            </value>
            <value>
                <fullName>Paid Social In-Platform</fullName>
            </value>
            <value>
                <fullName>Website Live-chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Annual_Sales__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Annual_Sales__c</fullName>
    <label>Estimated Annual Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services wanted;</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>How did they contact us?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce Sign-up</fullName>
            </value>
            <value>
                <fullName>Inbound Email</fullName>
            </value>
            <value>
                <fullName>Inbound Phone</fullName>
            </value>
            <value>
                <fullName>Inbound Website Enquiry</fullName>
            </value>
            <value>
                <fullName>Outbound Contact</fullName>
            </value>
            <value>
                <fullName>Website Live-chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IF(AND(Delivery_Type__c &gt; 0, Quantity__c &gt; 3), &quot;Large Non-Standard&quot;, 
IF(AND(Delivery_Type__c &gt; 0, Quantity__c &lt; 3), &quot;Small Non-Standard&quot;, &quot;Standard&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scheduled Waste and Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Other Waste/Recycling Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Secure Shredding</fullName>
    </customValue>
    <customValue>
        <fullName>Clearance/Junk Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Business Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting and Data</fullName>
    </customValue>
    <customValue>
        <fullName>Product Partnership</fullName>
    </customValue>
    <masterLabel>Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GoogleAdsEventExportTest.cls
@isTest
private class GoogleAdsEventExportTest {

	@TestSetup
	static void makeData() {
		INSERT new GoogleAdsSetting__c(ExternalInbox__c = 'test@test.com', LeadStatusToSkip__c = 'Closed. Existing customer, Closed. Not Relevant');

		INSERT new Lead(FirstName = 'Test', LastName = 'Account', Company = 'Test Company', Email = 'test@mail.com', MobilePhone = '090000000123', LeadSource = 'Got a leaflet', Services_wanted__c = 'Reporting and Data');

		Account parentAccount = TestDataHelper.insertAccount();
		Account locationAccount = TestDataHelper.insertLocation(parentAccount.Id, Null);

		Order order = TestDataHelper.insertOrder(locationAccount.Id);
		order.Status = 'Confirmed';
		UPDATE order;

		Opportunity opportunity = new opportunity(Name = 'Test Opp', CloseDate = date.today().addDays(30), StageName = 'Discovery', Estimated_Annual_Sales__c = 10000, AccountId = locationAccount.Id, Services__c = 'Scheduled Waste and Recycling Collections');
		INSERT opportunity;

		opportunity.StageName = 'Handed Over';
		UPDATE opportunity;
	}

	@isTest
	static void testGoogleAdsEventExport() {
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].size());

		Test.startTest();
		new GoogleAdsEventExportScheduler().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].size());
		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'Processed'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'Processed'].size());
	}

	@isTest
	static void testNewOrderOnAccount() {
		Order order = TestDataHelper.insertOrder([SELECT Id FROM Account WHERE Name ='Location'].Id);
		order.Status = 'Confirmed';
		UPDATE order;

		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].size());

		Test.startTest();
		new GoogleAdsEventExportScheduler().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].size());
		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'Processed'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'Processed'].size());
	}

	@isTest
	static void testScheduledDeletion() {
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].size());
		Assert.areEqual(1, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].size());

		Test.setCreatedDate([SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity' AND Status__c = 'New'].Id, Datetime.now().addDays(-95));
		Test.setCreatedDate([SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order' AND Status__c = 'New'].Id, Datetime.now().addDays(-95));

		new GoogleAdsEventExportScheduler().execute(null);

		Test.startTest();
		new DeleteGoogleAdsEventScheduler().execute(null);
		Test.stopTest();

		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Opportunity'].size());
		Assert.areEqual(0, [SELECT Id FROM GoogleAdsEvent__c WHERE Type__c = 'Order'].size());
	}
}