force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/BinLift__c/BinLift__c.object-meta.xml
<CustomObject>
    <label>Bin Lift</label>
    <nameField>
        <displayFormat>BL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Lifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinLift__c/fields/CollectedAt__c.field-meta.xml
<CustomField>
    <fullName>CollectedAt__c</fullName>
    <label>Collected At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Kilogram__c.field-meta.xml
<CustomField>
    <fullName>Kilogram__c</fullName>
    <label>Kilogram</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Lifts</relationshipLabel>
    <relationshipName>BinLifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/LocationCode__c.field-meta.xml
<CustomField>
    <fullName>LocationCode__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <label>Location Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attempt 1</fullName>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>No match</fullName>
            </value>
            <value>
                <fullName>Weight Added</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unknown Location</fullName>
            </value>
            <value>
                <fullName>Unknown Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/TransponderCode__c.field-meta.xml
<CustomField>
    <fullName>TransponderCode__c</fullName>
    <label>Transponder Code</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinLift__c/fields/WasteCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>WasteCategoryCode__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <label>Waste Category Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/BinMatched__c.field-meta.xml
<CustomField>
    <fullName>BinMatched__c</fullName>
    <label>Bin Matched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/BinUnmatched__c.field-meta.xml
<CustomField>
    <fullName>BinUnmatched__c</fullName>
    <label>Bin Unmatched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/OrderProducts__c.field-meta.xml
<CustomField>
    <fullName>OrderProducts__c</fullName>
    <label>Order Products</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Waypoints__c.field-meta.xml
<CustomField>
    <fullName>Waypoints__c</fullName>
    <label>Waypoints</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/BinKey__c.field-meta.xml
<CustomField>
    <fullName>BinKey__c</fullName>
    <label>Bin Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <label>Collection Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Unachievable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Collection_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Collection_Waypoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Waypoint</label>
    <referenceTo>Collection_Waypoints__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BinKey__c.field-meta.xml
<CustomField>
    <fullName>BinKey__c</fullName>
    <label>Bin Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Collection_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Collection_Waypoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Waypoint</label>
    <referenceTo>Collection_Waypoints__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CollectionDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionDate__c</fullName>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CollectionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Part Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Missed By Driver</fullName>
    </customValue>
    <masterLabel>Collection Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BinSummaryTest.cls
@isTest
private class BinSummaryTest {

	@isTest
	static void test() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null, 'FM0001');

		Round__c round = TestDataHelper.insertRound(true);
		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		DispatchLocation__c dispatchLocation = TestDataHelper.insertDispatchLocation(dispatch, location);

		Date yesterday = System.today() - 1;
		String month = String.valueOf('0' + yesterday.month()).right(2);
		String year = String.valueOf(yesterday.year());
        
		String key = Location.Id + '-' + 'GEN1100' + '-' +  year + '-' + month;

		List<Collection_Waypoints__c> waypoints = new List<Collection_Waypoints__c>();
		Collection_Waypoints__c waypoint1 = TestDataHelper.createWaypoint(location, dispatch, dispatchLocation);
		waypoint1.Collection_Quantity__c = 5;
		waypoint1.CreatedDate = yesterday;
		waypoint1.BinKey__c = key;
		waypoints.add(waypoint1);
		Collection_Waypoints__c waypoint2 = TestDataHelper.createWaypoint(location, dispatch, dispatchLocation);
		waypoint2.Collection_Quantity__c = 7;
		waypoint2.CreatedDate = yesterday;
		waypoint2.BinKey__c = key;
		waypoints.add(waypoint2);
		INSERT waypoints;

		BinLift__c binLift1 = new BinLift__c(Location__c = location.Id, LocationCode__c = 'FM0001', TransponderCode__c = '43FD4C1400004000', CollectedAt__c = yesterday, WasteCategoryCode__c = 'GEN1100', Kilogram__c = 100, Key__c = key, Status__c = 'Matched');
		BinLift__c binLift2 = new BinLift__c(Location__c = location.Id, LocationCode__c = 'FM0001', TransponderCode__c = '43FD4C1400004000', CollectedAt__c = yesterday, WasteCategoryCode__c = 'GEN1100', Kilogram__c = 100, Key__c = key, Status__c = 'Matched');
		BinLift__c binLift3 = new BinLift__c(Location__c = location.Id, LocationCode__c = 'FM0001', TransponderCode__c = '43FD4C1400004000', CollectedAt__c = yesterday, WasteCategoryCode__c = 'GEN1100', Kilogram__c = 100, Key__c = key, Status__c = 'No match');
		BinLift__c binLift4 = new BinLift__c(Location__c = location.Id, LocationCode__c = 'FM0001', TransponderCode__c = '43FD4C1400004000', CollectedAt__c = yesterday, WasteCategoryCode__c = 'GEN1100', Kilogram__c = 100, Key__c = key, Status__c = 'No match');
		BinLift__c binLift5 = new BinLift__c(Location__c = location.Id, LocationCode__c = 'FM0001', TransponderCode__c = '43FD4C1400004000', CollectedAt__c = yesterday, WasteCategoryCode__c = 'GEN1100', Kilogram__c = 100, Key__c = key, Status__c = 'No match');
		INSERT new List<BinLift__c>{binLift1, binLift2, binLift3, binLift4, binLift5};

		Product2 product = TestDataHelper.insertProduct('General Collection', '123', 'Collection');
		product.BinCategoryCode__c = 'GEN1100';
		UPDATE product;

		PricebookEntry pbe = TestDataHelper.insertStandardPricebookEntry(product.Id, 1020);
		Order order = TestDataHelper.insertOrder(location.Id);
		OrderItem orderItem1 = TestDataHelper.createOrderItem(order.Id, product.Id, pbe.Id);
		orderItem1.Quantity = 4;
		orderItem1.Collection_Waypoint__c = waypoint1.Id;
        orderItem1.CollectionDate__c = yesterday;
		orderItem1.BinKey__c = key;
		INSERT orderItem1;
		OrderItem orderItem2 = TestDataHelper.createOrderItem(order.Id, product.Id, pbe.Id);
		orderItem2.Quantity = 2;
		orderItem2.Collection_Waypoint__c = waypoint2.Id;
        orderItem2.CollectionDate__c = yesterday;
		orderItem2.BinKey__c = key;
		INSERT orderItem2;

		Test.startTest();
		Database.executeBatch(new BinSummaryOfWaypointBatch());
		Test.stopTest();

		Assert.areEqual(1, [SELECT Id FROM BinSummary__c WHERE Month__c = :month AND Year__c = :year].size());
		Assert.areEqual(12, [SELECT Waypoints__c FROM BinSummary__c][0].Waypoints__c); //5 + 7 = 12
		Assert.areEqual(6, [SELECT OrderProducts__c FROM BinSummary__c][0].OrderProducts__c); //3 + 3 = 6
		Assert.areEqual(2, [SELECT BinMatched__c FROM BinSummary__c][0].BinMatched__c);
		Assert.areEqual(3, [SELECT BinUnmatched__c FROM BinSummary__c][0].BinUnmatched__c);
	}
}