force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Enqix_Import__c/Enqix_Import__c.object-meta.xml
<CustomObject>
    <description>Serves as a placeholder for Enquix data imports.</description>
    <label>Enqix Import</label>
    <nameField>
        <displayFormat>EI-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enqix Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enqix_Import__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the import job.</description>
    <inlineHelpText>Status of the import job.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enqix_Import__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Import.</description>
    <inlineHelpText>Type of Import.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts/Locations</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/EnquixImportMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings Object that capture the mappings for the Enquix (CSV) files. Name of the individual settings instance represents a row header in the import sheet.</description>
    <label>Enquix Import Mappings</label>
</CustomObject>

force-app/main/default/objects/NoTriggers__c/NoTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to disable triggers for a given profile / user</description>
    <label>No Triggers</label>
</CustomObject>

force-app/main/default/classes/EnquixAccountImportBatchTest.cls
/**
* @author Zoran Zunko
* @date 10/23/15
*
* @group 
* @group-content ../../ApexDocContent/
*
* @description 
*/

@IsTest
private class EnquixAccountImportBatchTest {
    @TestSetup
    static void dataSetup() {

        List<EnquixImportMappings__c> enquixImportMappings =
                Test.loadData(EnquixImportMappings__c.sObjectType, 'EnqixTestMappings');

        Enqix_Import__c enqixImport = new Enqix_Import__c();
        enqixImport.Status__c = 'Pending';
        enqixImport.Type__c = 'Accounts/Locations';

        insert enqixImport;

        Attachment att = new Attachment(
                Name = 'Test',
                Body = Blob.valueOf(String.join(TestDataFactory.accountLocationImportList, Parser.CRLF)),
                ParentId = enqixImport.Id
        );

        NoTriggers__c flag = NoTriggers__c.getInstance(UserInfo.getUserId());
        flag.Flag__c = true;

        insert flag;

        insert att;

    }

    static testMethod void testBehavior() {

        Test.startTest();

        System.assert(EnquixAccountImportBatch.batchMe());

        Test.stopTest();

        System.assert([SELECT Id FROM Account].size() != 0);

    }
}