force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parcelforce</fullName>
                <default>true</default>
                <label>Parcelforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Packages</relationshipLabel>
    <relationshipName>DeliveryPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/RequestedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>RequestedDeliveryDate__c</fullName>
    <label>Requested Delivery Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackageQrCode__c/DeliveryPackageQrCode__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code</label>
    <nameField>
        <displayFormat>DelPkgQrCde - {0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package QR Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/DeliveryPackage__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPackage__c</fullName>
    <label>Delivery Package</label>
    <referenceTo>DeliveryPackage__c</referenceTo>
    <relationshipLabel>QR Codes</relationshipLabel>
    <relationshipName>QrCodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeliveryPackageRest.cls
@RestResource(urlMapping='/DeliveryPackage/*')
global without sharing class DeliveryPackageRest {

    @HttpGet
    global static List<sObject> doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Date requestedDeliveryDate = date.valueOf(req.requestURI.substring(req.requestURI.lastIndexOf('/')+1));
        return [SELECT Id, OrderNumber, Account.Name, (SELECT Id, ProductName__c, Quantity, (SELECT Id FROM QrCodes__r) FROM OrderItems), (SELECT Id, Count__c, Carrier__c, Status__c, (SELECT Id FROM Attachments) FROM DeliveryPackages__r WHERE RequestedDeliveryDate__c = :requestedDeliveryDate ORDER BY CreatedDate DESC LIMIT 1) FROM Order WHERE Id IN (SELECT Order__c FROM DeliveryPackage__c WHERE Status__c IN ('Labelled', 'Packaged', 'Lock') AND RequestedDeliveryDate__c = :requestedDeliveryDate) ORDER BY OrderNumber LIMIT 50000];
    }

	@HttpPatch
	global static Id lock(Date requestedDate) {
		DeliveryPackage__c pkg;
		try {
			pkg = [SELECT Id FROM DeliveryPackage__c WHERE Status__c = :DeliveryPackage.STATUS_LABELLED AND RequestedDeliveryDate__c = :requestedDate LIMIT 1 FOR UPDATE];
		} catch (QueryException e) {
			return null;
		}

		pkg.Status__c = DeliveryPackage.STATUS_LOCK;
		UPDATE pkg;

		return pkg.Id;
	}
}