force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/BinSummary__c/BinSummary__c.object-meta.xml
<CustomObject>
    <label>Bin Summary</label>
    <nameField>
        <displayFormat>SBS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinSummary__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Summaries</relationshipLabel>
    <relationshipName>BinSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Matched__c.field-meta.xml
<CustomField>
    <fullName>Matched__c</fullName>
    <label>Matched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/OrderProducts__c.field-meta.xml
<CustomField>
    <fullName>OrderProducts__c</fullName>
    <label>Order Products</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Unmatched__c.field-meta.xml
<CustomField>
    <fullName>Unmatched__c</fullName>
    <label>Unmatched</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/UnmatchedOverweight__c.field-meta.xml
<CustomField>
    <fullName>UnmatchedOverweight__c</fullName>
    <label>Unmatched Overweight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Waypoints__c.field-meta.xml
<CustomField>
    <fullName>Waypoints__c</fullName>
    <label>Waypoints</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BinSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/BinWeight__c.object-meta.xml
<CustomObject>
    <label>Bin Weight</label>
    <nameField>
        <displayFormat>BW-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BinWeight__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>Category code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Collected At?</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bin Weights</relationshipLabel>
    <relationshipName>BinWeights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BinWeight__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>No match</fullName>
            </value>
            <value>
                <fullName>No unique match</fullName>
            </value>
            <value>
                <fullName>Weight already present</fullName>
            </value>
            <value>
                <fullName>Manually matched</fullName>
            </value>
            <value>
                <fullName>Match removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/Collection_Waypoints__c.object-meta.xml
<CustomObject>
    <label>Collection Waypoint</label>
    <nameField>
        <label>Collection Waypoints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Waypoint</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Waypoints__c/fields/DispatchLocation__c.field-meta.xml
<CustomField>
    <fullName>DispatchLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispatch Location</label>
    <referenceTo>DispatchLocation__c</referenceTo>
    <relationshipLabel>Collection Waypoints</relationshipLabel>
    <relationshipName>CollectionWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location lookup must be of Location record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Unachievable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Waypoints__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Product</label>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collection Waypoint</relationshipLabel>
    <relationshipName>Collection_Waypoint</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyDispatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CollectionStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the round allocated.</description>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/productcategory__c.field-meta.xml
<CustomField>
    <fullName>productcategory__c</fullName>
    <formula>PricebookEntry.Product2.Product_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PRoduct Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BinCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BinCategoryCode__c</fullName>
    <label>Bin Category Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>Product Category as defined in the Enqix System.</description>
    <inlineHelpText>Product Category as defined in the Enqix System.</inlineHelpText>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Product__c/fields/DefaultWeightLimit__c.field-meta.xml
<CustomField>
    <fullName>DefaultWeightLimit__c</fullName>
    <formula>Product__r.DefaultWeightLimit__c</formula>
    <label>Default Weight Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/CollectionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Part Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Missed By Driver</fullName>
    </customValue>
    <masterLabel>Collection Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BinChargeBatchTest.cls
@isTest
private class BinChargeBatchTest {

	@isTest
	static void test() {
        TestDataHelper.insertVat();
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

        Round__c round = TestDataHelper.insertRound(true);
		DailyDispatch__c dispatch = TestDataHelper.insertDispatch(round);
		DispatchLocation__c dispatchLocation = TestDataHelper.insertDispatchLocation(dispatch, location);

        Product_Category__c gwProductCategory = TestDataHelper.insertProductCategory('General Waste GW');
		Product_Category__c dmrProductCategory = TestDataHelper.insertProductCategory('Mixed Recycling DMR');
		Product_Category__c fdProductCategory = TestDataHelper.insertProductCategory('Food');
		Product_Category__c glsProductCategory = TestDataHelper.insertProductCategory('Glass');

		List<Product2> products = new List<Product2>();
		products.add(TestDataHelper.createProduct('Test Product 01', 'TP001', 'Collection', gwProductCategory.Id));
		products[0].ProductCategory__c = 'General Waste';
		products[0].DefaultWeightLimit__c = 75;
        products[0].BinCategoryCode__c = 'GEN1100';

		products.add(TestDataHelper.createProduct('Test Product 02', 'TP002', 'Collection', dmrProductCategory.Id));
		products[1].ProductCategory__c = 'Mixed Recycling';
		products[1].DefaultWeightLimit__c = 75;
        products[1].BinCategoryCode__c = 'MILK240';

		products.add(TestDataHelper.createProduct('General Waste Overweight Charge Product', 'GWOVERWT', 'Collection'));
		products[2].ProductCategory__c = 'General Waste Charge';

		products.add(TestDataHelper.createProduct('Mixed Recycling Overweight Charge Product', 'DMROVERWT', 'Collection'));
		products[3].ProductCategory__c = 'Mixed Recycling Charge';

        products.add(TestDataHelper.createProduct('Test Product 03', 'TP003', 'Collection', dmrProductCategory.Id));
		products[4].ProductCategory__c = 'Mixed Recycling';
		products[4].DefaultWeightLimit__c = 75;
        products[4].BinCategoryCode__c = 'MR1100L';

		products.add(TestDataHelper.createProduct('Test Product 04', 'TP004', 'Collection', fdProductCategory.Id));
		products[5].ProductCategory__c = 'Food';
		products[5].DefaultWeightLimit__c = 100;
		products[5].BinCategoryCode__c = 'FOOD160';

		products.add(TestDataHelper.createProduct('Test Product 05', 'TP005', 'Collection', glsProductCategory.Id));
		products[6].ProductCategory__c = 'Glass';
		products[6].DefaultWeightLimit__c = 50;
		products[6].BinCategoryCode__c = 'GLS240';

		products.add(TestDataHelper.createProduct('Food Overweight Charge Product', 'FOODOVERWT', 'Collection'));
		products[7].ProductCategory__c = 'Food Charge';

		products.add(TestDataHelper.createProduct('Glass Overweight Charge Product', 'GLASSOVER', 'Collection'));
		products[8].ProductCategory__c = 'Glass Charge';
		INSERT products;

		TestDataHelper.insertOverweightSetting(gwProductCategory.Id, dmrProductCategory.Id, products[2].Id, products[3].Id, fdProductCategory.Id, glsProductCategory.Id, products[7].Id, products[8].Id);

		List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[0].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[1].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[2].Id, 1));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[3].Id, 1));
        pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[4].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[5].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[6].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[7].Id, 10));
		pricebookEntries.add(TestDataHelper.createStandardPricebookEntry(products[8].Id, 10));
		INSERT pricebookEntries;

		Date createdDate = System.today() - 1;
		String key1 = Location.Id + '-' + 'GEN1100' + '-' +  String.valueOf(createdDate.year()) + '-' + String.valueOf('0' + createdDate.month()).right(2);
		String key2 = Location.Id + '-' + 'MILK240' + '-' +  String.valueOf(createdDate.year()) + '-' + String.valueOf('0' + createdDate.month()).right(2);
        String key3 = Location.Id + '-' + 'MR1100L' + '-' +  String.valueOf(createdDate.year()) + '-' + String.valueOf('0' + createdDate.month()).right(2);
        String key4 = Location.Id + '-' + 'FOOD160' + '-' +  String.valueOf(createdDate.year()) + '-' + String.valueOf('0' + createdDate.month()).right(2);
        String key5 = Location.Id + '-' + 'GLS240' + '-' +  String.valueOf(createdDate.year()) + '-' + String.valueOf('0' + createdDate.month()).right(2);

		BinWeight__c bin1 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'GEN1100', Kilogram__c = 70, CreatedDate = System.today().addMonths(-1), Key__c = key1, Status__c = 'No match');
		BinWeight__c bin2 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'GEN1100', Kilogram__c = 90, CreatedDate = System.today().addMonths(-1), Key__c = key1, Status__c = 'No match');
		BinWeight__c bin3 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'GEN1100', Kilogram__c = 115, CreatedDate = System.today().addMonths(-1), Key__c = key1, Status__c = 'No match');
		BinWeight__c bin4 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'MILK240', Kilogram__c = 130, CreatedDate = System.today().addMonths(-1), Key__c = key2, Status__c = 'No match');
        BinWeight__c bin5 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'MR1100L', Kilogram__c = 125, CreatedDate = System.today().addMonths(-1), Key__c = key3, Status__c = 'No match');
        BinWeight__c bin6 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'FOOD160', Kilogram__c = 175, CreatedDate = System.today().addMonths(-1), Key__c = key4, Status__c = 'No match');
        BinWeight__c bin7 = new BinWeight__c(Location__c = location.Id, Date__c = createdDate, CategoryCode__c = 'GLS240', Kilogram__c = 95, CreatedDate = System.today().addMonths(-1), Key__c = key5, Status__c = 'No match');
		INSERT new List<BinWeight__c>{bin1, bin2, bin3, bin4, bin5, bin6, bin7};

        List<BinSummary__c> binSummaries = new List<BinSummary__c>();
		binSummaries.add(new BinSummary__c(CreatedDate = createdDate, Key__c = key1, Location__c = location.Id, CategoryCode__c = 'GEN1100', Year__c = String.valueOf(createdDate.year()),
									Month__c = String.valueOf('0' + createdDate.month()).right(2), Waypoints__c = 12, OrderProducts__c = 11, Matched__c = 11, Unmatched__c = 3, UnmatchedOverweight__c = 55));
        binSummaries.add(new BinSummary__c(CreatedDate = createdDate, Key__c = key2, Location__c = location.Id, CategoryCode__c = 'MILK240', Year__c = String.valueOf(createdDate.year()),
									Month__c = String.valueOf('0' + createdDate.month()).right(2), Waypoints__c = 5, OrderProducts__c = 5, Matched__c = 5, Unmatched__c = 1, UnmatchedOverweight__c = 55));
        binSummaries.add(new BinSummary__c(CreatedDate = createdDate, Key__c = key3, Location__c = location.Id, CategoryCode__c = 'MR1100L', Year__c = String.valueOf(createdDate.year()),
									Month__c = String.valueOf('0' + createdDate.month()).right(2), Waypoints__c = 5, OrderProducts__c = 5, Matched__c = 9, Unmatched__c = 1, UnmatchedOverweight__c = 50));
		binSummaries.add(new BinSummary__c(CreatedDate = createdDate, Key__c = key4, Location__c = location.Id, CategoryCode__c = 'FOOD160', Year__c = String.valueOf(createdDate.year()),
									Month__c = String.valueOf('0' + createdDate.month()).right(2), Waypoints__c = 8, OrderProducts__c = 8, Matched__c = 8, Unmatched__c = 1, UnmatchedOverweight__c = 75));
		binSummaries.add(new BinSummary__c(CreatedDate = createdDate, Key__c = key5, Location__c = location.Id, CategoryCode__c = 'GLS240', Year__c = String.valueOf(createdDate.year()),
									Month__c = String.valueOf('0' + createdDate.month()).right(2), Waypoints__c = 3, OrderProducts__c = 3, Matched__c = 3, Unmatched__c = 1, UnmatchedOverweight__c = 45));
        INSERT binSummaries;

        Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, products[4]);
        Collection_Waypoints__c waypoint = TestDataHelper.createWaypoint(location, dispatch, dispatchLocation);
		waypoint.Supplier_Product__c = supplierProduct.Id;
        waypoint.Manual_Price__c = 8;
        INSERT waypoint;

		Test.startTest();
		Database.executeBatch(new BinChargeBatch());
		Test.stopTest();

		Assert.areEqual(1, [SELECT Id FROM Order WHERE AccountId = :location.Id].size());
		Assert.areEqual(9, [SELECT Id FROM OrderItem WHERE Location__c = :location.Id].size());

        List<OrderItem> orderItem01 = [SELECT Quantity FROM OrderItem WHERE Product2.Name = 'Test Product 01'];
        Assert.areEqual(1, orderItem01.size());
        Assert.areEqual(2, orderItem01[0].Quantity); //Excess = 11 + 3 - 12 = 2

        List<OrderItem> orderItem02 = [SELECT Quantity FROM OrderItem WHERE Product2.Name = 'Test Product 02'];
        Assert.areEqual(1, orderItem02.size());
        Assert.areEqual(1, orderItem02[0].Quantity); //Excess = 5 + 1 - 5 = 1

        List<OrderItem> orderItem03 = [SELECT Quantity, ListPrice, UnitPrice, TotalPrice FROM OrderItem WHERE Product2.Name = 'Test Product 03'];
        Assert.areEqual(1, orderItem03.size());
        Assert.areEqual(5, orderItem03[0].Quantity); //Excess = 9 + 1 - 5 = 5
        Assert.areEqual(8, orderItem03[0].UnitPrice);
        Assert.areEqual(40, orderItem03[0].TotalPrice); //8 * 5 = 40

        List<OrderItem> orderItem04 = [SELECT Quantity FROM OrderItem WHERE Location__c = :location.Id AND Product2.Name = 'General Waste Overweight Charge Product'];
        Assert.areEqual(1, orderItem04.size());
        Assert.areEqual(55, orderItem04[0].Quantity); //Overweight = 55

        List<OrderItem>	orderItem05 = [SELECT Quantity FROM OrderItem WHERE Location__c = :location.Id AND Product2.Name = 'Mixed Recycling Overweight Charge Product'];
        Assert.areEqual(1, orderItem05.size());
        Assert.areEqual(105, orderItem05[0].Quantity); //Overweight = 50 + 55 = 105

		List<OrderItem> orderItem06 = [SELECT Quantity FROM OrderItem WHERE Product2.Name = 'Test Product 04'];
        Assert.areEqual(1, orderItem06.size());
        Assert.areEqual(1, orderItem06[0].Quantity); //Excess = 8 + 1 - 8 = 1

		List<OrderItem> orderItem07 = [SELECT Quantity FROM OrderItem WHERE Product2.Name = 'Test Product 05'];
        Assert.areEqual(1, orderItem07.size());
        Assert.areEqual(1, orderItem07[0].Quantity); //Excess = 3 + 1 - 3 = 1

		List<OrderItem>	orderItem08 = [SELECT Quantity FROM OrderItem WHERE Location__c = :location.Id AND Product2.Name = 'Food Overweight Charge Product'];
        Assert.areEqual(1, orderItem08.size());
        //Assert.areEqual(105, orderItem08[0].Quantity); //Overweight = 75
		System.debug('orderItem08[0].Quantity: ' + orderItem08[0].Quantity);

		List<OrderItem>	orderItem09 = [SELECT Quantity FROM OrderItem WHERE Location__c = :location.Id AND Product2.Name = 'Glass Overweight Charge Product'];
        Assert.areEqual(1, orderItem09.size());
        //Assert.areEqual(105, orderItem09[0].Quantity); //Overweight = 45
		System.debug('orderItem09[0].Quantity: ' + orderItem09[0].Quantity);

	}
}