force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parcelforce</fullName>
                <default>true</default>
                <label>Parcelforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Packages</relationshipLabel>
    <relationshipName>DeliveryPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/RequestedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>RequestedDeliveryDate__c</fullName>
    <label>Requested Delivery Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FirstMileDeliveryLabelTest.cls
@isTest
private class FirstMileDeliveryLabelTest {

	@testSetup
	static void setup() {
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);
		TestDataHelper.insertSupplier('First Mile Ltd');
		TestDataHelper.insertOrder(location.Id);
	}

	@isTest
	static void createLabel() {
		Order order = [SELECT Id FROM Order LIMIT 1];
		DeliveryPackage__c pkg = new DeliveryPackage__c(Order__c = order.Id, RequestedDeliveryDate__c = Date.Today(), Carrier__c = DeliveryPackage.CARRIER_FIRST_MILE);

		Test.startTest();
		INSERT pkg;
		Test.stopTest();

		pkg = [SELECT Status__c, TrackingId__c FROM DeliveryPackage__c WHERE Id = :pkg.Id];
		Assert.areEqual(DeliveryPackage.STATUS_LABELLED, pkg.Status__c);
		Assert.isNull(pkg.TrackingId__c);

		Attachment attachment = [SELECT Id FROM Attachment WHERE ParentId = :pkg.Id];
		Assert.isNotNull(attachment);
	}
}