force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Location_Service_Status__c = &apos;Stop&apos;, IMAGE(&quot;/resource/Account/Status/Stop.jpg&quot;, &quot;Stop&quot;),IF(Location_Service_Status__c = &apos;Suspended&apos;, IMAGE(&quot;/resource/Account/Status/Suspended.jpg&quot;, &quot;Suspended&quot;), IMAGE(&quot;/resource/Account/Status/OK.jpg&quot;, &quot;OK&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/ParcelforceEvent__c.field-meta.xml
<CustomField>
    <fullName>ParcelforceEvent__c</fullName>
    <label>Parcelforce Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I101</fullName>
                <label>Parcel tracked in</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>Parcel delivered</label>
            </value>
            <value>
                <fullName>I103</fullName>
                <label>Received but not advised</label>
            </value>
            <value>
                <fullName>I104</fullName>
                <label>Advised but not received</label>
            </value>
            <value>
                <fullName>I105</fullName>
                <label>Parcel matched to advice</label>
            </value>
            <value>
                <fullName>I106</fullName>
                <label>Advice received too late</label>
            </value>
            <value>
                <fullName>I107</fullName>
                <label>Redirection requested</label>
            </value>
            <value>
                <fullName>I108</fullName>
                <label>Addressee refused</label>
            </value>
            <value>
                <fullName>I109</fullName>
                <label>Addressee will collect</label>
            </value>
            <value>
                <fullName>I110</fullName>
                <label>Redelivery arranged</label>
            </value>
            <value>
                <fullName>I111</fullName>
                <label>Delivery arranged</label>
            </value>
            <value>
                <fullName>I112</fullName>
                <label>Depot cannot find parcel</label>
            </value>
            <value>
                <fullName>I113</fullName>
                <label>Local redirection</label>
            </value>
            <value>
                <fullName>I114</fullName>
                <label>Out for redelivery</label>
            </value>
            <value>
                <fullName>I115</fullName>
                <label>Out for first delivery</label>
            </value>
            <value>
                <fullName>I116</fullName>
                <label>Out for arranged delivery</label>
            </value>
            <value>
                <fullName>I117</fullName>
                <label>Found during stocktake</label>
            </value>
            <value>
                <fullName>I118</fullName>
                <label>Held - no time to deliver</label>
            </value>
            <value>
                <fullName>I119</fullName>
                <label>Held - incorrect address</label>
            </value>
            <value>
                <fullName>I120</fullName>
                <label>Held - gone away</label>
            </value>
            <value>
                <fullName>I121</fullName>
                <label>Held - parcel damaged</label>
            </value>
            <value>
                <fullName>I122</fullName>
                <label>Held - addressee refused</label>
            </value>
            <value>
                <fullName>I123</fullName>
                <label>Held - depot discretion</label>
            </value>
            <value>
                <fullName>I124</fullName>
                <label>Held - scheduled delivery</label>
            </value>
            <value>
                <fullName>I125</fullName>
                <label>Held - addressee request</label>
            </value>
            <value>
                <fullName>I126</fullName>
                <label>Held - attempted COD</label>
            </value>
            <value>
                <fullName>I127</fullName>
                <label>Held - for collection</label>
            </value>
            <value>
                <fullName>I128</fullName>
                <label>Held - attempted delivery</label>
            </value>
            <value>
                <fullName>I129</fullName>
                <label>Parcel relabelled</label>
            </value>
            <value>
                <fullName>I130</fullName>
                <label>Delivery not attempted</label>
            </value>
            <value>
                <fullName>IPDF</fullName>
                <label>Delivered - IPDF</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingIds__c.field-meta.xml
<CustomField>
    <fullName>TrackingIds__c</fullName>
    <label>All Tracking Ids</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/DeliveryPackageTrackingEvent__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking Event</label>
    <nameField>
        <label>Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/File__c.field-meta.xml
<CustomField>
    <fullName>File__c</fullName>
    <label>File</label>
    <referenceTo>DeliveryPackageTrackingFile__c</referenceTo>
    <relationshipLabel>Tracking Events</relationshipLabel>
    <relationshipName>TrackingEvents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/DeliveryPackageTrackingFile__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking File</label>
    <nameField>
        <displayFormat>DelPkgTrkngFile-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingFile__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>File Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DeliveryPackageTrackingEventHandlerTest.cls
@isTest
public class DeliveryPackageTrackingEventHandlerTest {

	@testSetup
	static void testSetup() {
		TestDataHelper.insertVat();
		TestDataHelper.insertParcelforceSetting();
		Account parent = TestDataHelper.insertAccount();
		Account location = TestDataHelper.insertLocation(parent.Id, null);

		Product2 product = TestDataHelper.insertProduct('test product', '40001', 'Collection');
		PricebookEntry PricebookEntry = TestDataHelper.insertPricebookEntry(Test.getStandardPricebookId(), product.Id, 100);

        TestDataHelper.insertSupplierFirstMile();
		Order order = TestDataHelper.insertOrder(location.Id, Date.today());
		OrderItem orderItem = TestDataHelper.insertOrderItem(order.Id, product.Id, PricebookEntry.Id);
		DeliveryPackage__c pkg = TestDataHelper.insertDeliveryPackage(order.Id, DeliveryPackage.STATUS_NEW);
		pkg.Status__c = DeliveryPackage.STATUS_LABELLED;	// Trigger creation of Items
		pkg.TrackingIds__c = pkg.TrackingId__c = 'T12345';
		UPDATE pkg;
		pkg.Status__c = DeliveryPackage.STATUS_PACKAGED;	// Move out of Draft status
		UPDATE pkg;
	}

	@isTest
	static void parcelforceEventWithOutFinalStatus() {
		DeliveryPackageTrackingFile__c trackingFile = new DeliveryPackageTrackingFile__c(FileName__c = 'Test');
		INSERT trackingFile;

		List<DeliveryPackageTrackingEvent__c> events = new List<DeliveryPackageTrackingEvent__c>();
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I116', DateTime__c = System.now()));
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I115', DateTime__c = System.now().addMinutes(-1)));
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I114', DateTime__c = System.now().addMinutes(-5)));
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I117', DateTime__c = System.now().addMinutes(1)));
		INSERT events;
		Assert.areEqual('I117', [SELECT ParcelforceEvent__c FROM DeliveryPackage__c LIMIT 1].ParcelforceEvent__c);
	}

	@isTest
	static void parcelforceEventWithFinalStatus() {
		DeliveryPackageTrackingFile__c trackingFile = new DeliveryPackageTrackingFile__c(FileName__c = 'Test');
		INSERT trackingFile;

		List<DeliveryPackageTrackingEvent__c> events = new List<DeliveryPackageTrackingEvent__c>();
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I116', DateTime__c = System.now()));
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'IPDF', DateTime__c = System.now().addMinutes(-1))); // Final Status
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I114', DateTime__c = System.now().addMinutes(-5)));
		events.add(new DeliveryPackageTrackingEvent__c(File__c = trackingFile.Id, Name = 'T12345', Code__c = 'I117', DateTime__c = System.now().addMinutes(1)));
		INSERT events;

		Assert.areEqual('IPDF', [SELECT ParcelforceEvent__c FROM DeliveryPackage__c LIMIT 1].ParcelforceEvent__c);
	}
}