force-app/main/default/objects/Account/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>Street Name. Used to match to put out times so must match spelling from put out times exactly</description>
    <label>Street Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Put_Out_Time__c/Put_Out_Time__c.object-meta.xml
<CustomObject>
    <label>Put Out Time</label>
    <nameField>
        <label>Put Out Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Put Out Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Put_Out_Time__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Postcode</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Put Out Times</relationshipLabel>
    <relationshipName>Put_Out_Times1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Put_Out_Time__c/fields/Put_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Put_Out_Time__c</fullName>
    <defaultValue>&quot;00:00&quot;</defaultValue>
    <inlineHelpText>24 Hour Format e.g. 18:00</inlineHelpText>
    <label>Put Out Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Put_Out_Time__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Postcode</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PutOutTimeControllerTest.cls
@isTest
public class PutOutTimeControllerTest {

    @isTest
    static void testMethod1() {
        Account account = TestDataHelper.createAccount();
        account.Street_Name__c = 'Wells Street';
        account.BillingPostalCode = 'L1 8JQ';
        INSERT account;
        Test.setMock(HttpCalloutMock.class, new DoogalTest.RestMock('L1	51.6154	-0.178479'));

        Region__c region = new Region__c();
        region.Name = 'Test 1';
        INSERT region;

        Put_Out_Time__c popOutTime = new Put_Out_Time__c();
        popOutTime.Street_Name__c = 'Wells Street'; 
        popOutTime.Put_Out_Time__c = '05:30';
        popOutTime.Postcode__c = region.Id;
        INSERT popOutTime;

        PutOutTimeController.getRelevantPutOutTimes(account.Id);
    }
}