force-app/main/default/objects/Account/fields/StreetSegmentID__c.field-meta.xml
<CustomField>
    <fullName>StreetSegmentID__c</fullName>
    <label>StreetSegmentID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/DailyDispatch__c/DailyDispatch__c.object-meta.xml
<CustomObject>
    <label>Daily Dispatch</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/DispatchLocation__c.object-meta.xml
<CustomObject>
    <label>Dispatch Location</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchLocation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatch Locations</relationshipLabel>
    <relationshipName>DispatchLocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Supplier_Product__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Product__c.Supplier__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.Product_Type__c</field>
            <operation>equals</operation>
            <value>Collection</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.Product__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Supplier_Product__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Product__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Product__c/Supplier_Product__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <description>Third Party Contractors</description>
    <label>Supplier</label>
    <nameField>
        <label>Suppliers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClusterSequenceBatchTest.cls
@isTest
private class ClusterSequenceBatchTest {

	@testSetup
	static void setup() {
		TestDataHelper.insertCollectionServiceTimeSetting();

		Round__c round = TestDataHelper.insertRound();
		Product2 product = TestDataHelper.insertProduct('Product 1', 'P0001', 'Collection');
		Suppliers__c supplier = TestDataHelper.insertSupplierFirstMile();
		Supplier_Product__c supplierProduct = TestDataHelper.insertSupplierProduct(supplier, product);
		Account parent = TestDataHelper.insertAccount();
		Account location1 = TestDataHelper.insertLocation(parent.Id, null);
		Account location2 = TestDataHelper.createLocation(parent.Id, null);
		location2.StreetSegmentID__c = '40689764024';
		INSERT location2;
		Account location3 = TestDataHelper.createLocation(parent.Id, null);
		location3.StreetSegmentID__c = '40689764024';
		INSERT location3;
		List<Schedule__c> schedules = new List<Schedule__c>();
		schedules.add(TestDataHelper.createSchedule(location1, round, supplier, supplierProduct, '08:00'));
		schedules.add(TestDataHelper.createSchedule(location2, round, supplier, supplierProduct, '09:00'));
		schedules.add(TestDataHelper.createSchedule(location3, round, supplier, supplierProduct, '09:00'));
		INSERT schedules;

		Test.startTest();
		new DispatchCreationScheduler().execute(null);
		Test.stopTest();
	}

	@isTest
	static void clusterTest() {
		Id dailyDispatch = [SELECT Id FROM DailyDispatch__c LIMIT 1].Id;
		Test.startTest();
		Database.executeBatch(new ClusterSequenceBatch(new Set<Id>{dailyDispatch}), 1);
		Test.stopTest();

		Assert.areEqual(3, [SELECT Id, SequenceNumber__c FROM DispatchLocation__c WHERE SequenceNumber__c != null].size());
		Assert.areEqual(2, [SELECT Id, SequenceNumber__c FROM DispatchLocation__c WHERE Location__r.StreetSegmentId__c = '40689764024'].size());
	}
}