force-app/main/default/objects/Account/fields/TotalUnallocatedAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalUnallocatedAmount__c</fullName>
    <label>Total Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>The group/parent account - i.e. a cleaning company or retail head office</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BankStatementToAccountRollupBatch.cls
public without sharing class BankStatementToAccountRollupBatch implements Database.Batchable<sObject>, Database.Stateful {

	private Map<String, List<String>> categoryToWeightFields = new Map<String, List<String>>();

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Id FROM Account
		WHERE Id IN (SELECT Account__c FROM Bank_Statement__c WHERE Transaction_Type__c != 'Credit Note' AND Unallocated_Amount__c > 0)]);
	}

	public void execute(Database.BatchableContext BC, List<Account> scope) {
		List<Account> accountsToUpdate = new List<Account>();
		for (AggregateResult aggregateResult : [SELECT SUM(Unallocated_Amount__c) UnallocatedAmount, Account__c FROM Bank_Statement__c WHERE Account__c IN :scope AND Transaction_Type__c != 'Credit Note' AND Unallocated_Amount__c > 0 GROUP BY Account__c]) {
			accountsToUpdate.add(new Account(Id = (Id)aggregateResult.get('Account__c'), TotalUnallocatedAmount__c = (Decimal)aggregateResult.get('UnallocatedAmount')));
		}

		if (!accountsToUpdate.isEmpty()) {
			UPDATE accountsToUpdate;
		}
	}

	public void finish(Database.BatchableContext BC) {}
}