force-app/main/default/objects/Account/fields/VAT_Exempt__c.field-meta.xml
<CustomField>
    <fullName>VAT_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <label>Bank Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/AllocAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocAmount__c</fullName>
    <label>AllocAmount</label>
    <summarizedField>PaymentAllocation__c.AllocatedAmount__c</summarizedField>
    <summaryForeignKey>PaymentAllocation__c.BankstatementId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/CP_Transactional_Info__c.field-meta.xml
<CustomField>
    <fullName>CP_Transactional_Info__c</fullName>
    <label>CP_Transactional_Info</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/fromCustomerPortal__c.field-meta.xml
<CustomField>
    <fullName>fromCustomerPortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>fromCustomerPortal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field indicates the transaction type, kept as text</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Giro Credit</fullName>
            </value>
            <value>
                <fullName>Inward Payment via FP</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Statement__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AllocAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocAmount__c</fullName>
    <label>AllocAmount</label>
    <summarizedField>PaymentAllocation__c.AllocatedAmount__c</summarizedField>
    <summaryForeignKey>PaymentAllocation__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountExclVAT__c.field-meta.xml
<CustomField>
    <fullName>AmountExclVAT__c</fullName>
    <label>AmountExclVAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <label>AmountOutstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Generate_Payment__c.field-meta.xml
<CustomField>
    <fullName>Generate_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to generate a payment for an order that was paid by card and came from CP, after being delivered and its invoice was created</description>
    <inlineHelpText>Field used to generate a payment for an order that was paid by card and came from CP, after being delivered and its invoice was created</inlineHelpText>
    <label>Generate Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OrderLookUp__c.field-meta.xml
<CustomField>
    <fullName>OrderLookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLookUp</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Outstanding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outstanding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Headers (Outstanding)</relationshipLabel>
    <relationshipName>Invoice_Headers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Ready_to_Email__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/SageExtractCreated__c.field-meta.xml
<CustomField>
    <fullName>SageExtractCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be check if the invoice had not created sages extract records</description>
    <label>Sage Extract Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice_HeaderId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_HeaderId__c</fullName>
    <label>Invoice_HeaderId</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product_AccCode__c.field-meta.xml
<CustomField>
    <fullName>Product_AccCode__c</fullName>
    <formula>Product__r.Nl_accode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product_AccCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/SageExtractCreated__c.field-meta.xml
<CustomField>
    <fullName>SageExtractCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sage Extract Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/CreditCard_Payment__c.field-meta.xml
<CustomField>
    <fullName>CreditCard_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Card Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <formula>PaymentReference__c</formula>
    <label>Payment Reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <label>Payment Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentAllocation__c/PaymentAllocation__c.object-meta.xml
<CustomObject>
    <label>PaymentAllocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>PaymentAllocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentAllocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentAllocation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PaymentAllocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Nl_accode__c.field-meta.xml
<CustomField>
    <fullName>Nl_accode__c</fullName>
    <description>the field Nl_accode__c on the product object should be *required* on creation of a Product.
Nl_accode__c stands for &apos;nominal ledger code&apos;. Users need to populate it with a code from Finance whenever they create a new product.</description>
    <inlineHelpText>The field Nl_accode__c on the product object should be *required* on creation of a Product.
Nl_accode__c stands for &apos;nominal ledger code&apos;. 
Users need to populate it with a code from Finance whenever they create a new product.</inlineHelpText>
    <label>Nl_accode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/SageExtract__c.object-meta.xml
<CustomObject>
    <label>SageExtract</label>
    <nameField>
        <label>SageExtract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SageExtracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SageExtract__c/fields/Bank_Statement__c.field-meta.xml
<CustomField>
    <fullName>Bank_Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Statement</label>
    <referenceTo>Bank_Statement__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice_Line</label>
    <referenceTo>Invoice_Line__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TheVat__c/TheVat__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>The VAT</label>
</CustomObject>

force-app/main/default/objects/TheVat__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/InvoiceHeaderTriggerHelper.cls
public class InvoiceHeaderTriggerHelper {

    public static void populateAmounts(List < Invoice_Header__c > headers) {
        List < Invoice_Header__c > headersWithLinesList = [SELECT Id, Account__r.VAT_Exempt__c, AmountExclVAT__c, VAT__c, AllocAmount__c, AmountOutstanding__c, Payment_Reference__c, OrderLookUp__r.PaymentReference__c, OrderLookUp__r.CreditCard_Payment__c, Generate_Payment__c, (SELECT Id, Amount__c, Vat__c FROM Invoice_Lines__r) FROM Invoice_Header__c WHERE Id IN: headers];
        for (Invoice_Header__c h: headersWithLinesList) {
            for (Invoice_Header__c original: headers) {
                if (h.Id == original.Id) {
                    original.AmountExclVAT__c = 0;
                    for (Invoice_Line__c l: h.Invoice_Lines__r) {
                        original.AmountExclVAT__c += l.Amount__c;
                    }
                    original.VAT__c = h.Account__r.VAT_Exempt__c ? 0 : (original.AmountExclVAT__c * TheVat__c.getInstance().Value__c).setScale(2, RoundingMode.HALF_UP);
                    original.AmountOutstanding__c = original.AmountExclVAT__c + original.VAT__c - original.AllocAmount__c;
                    original.AmountOutstanding__c.setscale(2);
                    original.Outstanding__c = original.AmountOutstanding__c > 0 ? original.Account__c : null;
                    //Joao [JIRA 1612] - added to set generate payment and payment reference
                    //Fix jira 1677/1673
                    if (h.OrderLookUp__r.CreditCard_Payment__c)
                    {
                        original.Generate_Payment__c = true;
                        original.Payment_Reference__c = h.OrderLookUp__r.PaymentReference__c;
                    }
                }
            }
        }
    }

    public static void createSageExtract(List <Invoice_Header__c> invoicesReadOnly) {
        List <Invoice_Header__c> invoices = [SELECT Id, (SELECT Product__r.Nl_accode__c, Product_AccCode__c, Amount__c, VAT__c, Invoice_HeaderId__c, Invoice_HeaderId__r.DueDate__c FROM Invoice_Lines__r) FROM Invoice_Header__c WHERE Id IN :invoicesReadOnly];

        List <Invoice_Line__c> invoiceLines = new List <Invoice_Line__c>();
        List <SageExtract__c> sageLines = new List <SageExtract__c>();
        for (Invoice_Header__c invoice : invoices) {
            for (Invoice_Line__c invoiceLine : invoice.Invoice_Lines__r) {
                sageLines.addAll(Sage.createLines(invoiceLine));
                invoiceLines.add(invoiceLine);
            }

            invoice.SageExtractCreated__c = true;
            invoice.Ready_to_Email__c = true;
        }

        if (!sageLines.isEmpty()) {
            Database.SaveResult[] results1 = Database.update(invoiceLines, false);
            LogRegister.createLogsUpsert(results1, invoiceLines, 'InvoiceHeaderTriggerHelper update invoiceLines', 'update', 'Invoice_Line__c', 'Invoice_Header__c');

            Database.SaveResult[] results2 = Database.insert(sageLines, false);
            LogRegister.createLogsUpsert(results2, sageLines, 'InvoiceHeaderTriggerHelper insert sageLines', 'insert', 'SageExtract__c', 'Invoice_Line__c');
        }

        Database.SaveResult[] results = Database.update(invoices, false);
        LogRegister.createLogsUpsert(results, invoices, 'InvoiceHeaderTriggerHelper update invoices', 'update', 'Invoice_Header__c', 'Account__c');
    }

    /* Bruno - 14-01-2019 - 1215 - Create Payments for Invoices paid by Card on CP */
    public static void payInvoices(List < Invoice_Header__c > headers) {
        system.debug(headers);
        system.debug('Entrou payInvoices');
        Set<Id> accountIds = new Set<Id>();
        List<PaymentAllocation__c> paymentsToInsert = new List<PaymentAllocation__c>();
        for (Invoice_Header__c h : headers) {
            accountIds.add(h.Account__c);
        }
        for (Bank_Statement__c bs : [SELECT Id, Unallocated_Amount__c, Account__c, CP_Transactional_Info__c FROM Bank_Statement__c WHERE Account__c IN :accountIds AND Transaction_Type__c = 'Credit Card' AND fromCustomerPortal__c = true and Unallocated_Amount__c > 0]) {
            for (Invoice_Header__c h : headers) {
                if (String.isNotBlank(bs.CP_Transactional_Info__c) && bs.CP_Transactional_Info__c.length() >= 27)
                {
                    String paymentReference = bs.CP_Transactional_Info__c.substring(0, 27);
                    system.debug('bs --> '+bs);
                    System.debug('BS Payment Reference: '+paymentReference+'  BS AccountId: '+bs.Account__c);
                    System.debug('Inv Payment Reference: '+h.Payment_Reference__c+'  Inv AccountId: '+h.Account__c);

                    if (bs.Account__c == h.Account__c && paymentReference == h.Payment_Reference__c && h.AmountOutstanding__c > 0) {
                        system.debug('Entrou payInvoices if clause');
                        PaymentAllocation__c p = new PaymentAllocation__c(
                            Account__c = bs.Account__c,
                            BankstatementId__c = bs.Id,
                            InvoiceId__c = h.Id,
                            AllocatedAmount__c = bs.Unallocated_Amount__c,
                            IsFromCPCard__c = true
                        );
                        paymentsToInsert.add(p);
                    }
                }
            }
        }
        try {
            if (paymentsToInsert.size() > 0) {
                system.debug(paymentsToInsert);
                insert paymentsToInsert;
            }
        }
        catch (Exception e) {
            system.debug(e.getMessage());
            throw new GeneralException(e.getMessage());
        }
    }

    /* Bruno - 04.02.2019 -> 978 */
    public static void processCreditNotes(List < Invoice_Header__c > headers) {
        List < Bank_Statement__c > bsToCreate = new List < Bank_Statement__c > ();
        for (Invoice_Header__c h: [SELECT Id, AmountExclVAT__c, VAT__c, InvoiceNo__c, Account__c, Account__r.CP_Account_Code__c FROM Invoice_Header__c WHERE ID IN: headers]) {
            system.debug(h);
            Bank_Statement__c b = new Bank_Statement__c();
            b.Document_Name__c = h.InvoiceNo__c + ' CREDIT NOTE';
            b.Entry_Date__c = System.today();
            b.Transaction_Details__c = h.InvoiceNo__c + ' CREDIT';
            b.Transaction_Type__c = 'Credit Note';
            b.Payment_Amount__c = 0;
            b.Receipt_Amount__c = 0;
            b.Customer_Reference__c = h.Account__r.CP_Account_Code__c;
            b.Account__c = h.Account__c;
            b.Unallocated_Amount__c = (h.AmountExclVAT__c + h.Vat__c) * (-1);
            system.debug('AmountExclVAT__c --> '+h.AmountExclVAT__c);
            system.debug('Unallocated_Amount__c 1 --> '+b.Unallocated_Amount__c);
            b.Credit_Note_Invoice__c = h.Id;
            bsToCreate.add(b);
        }
        system.debug(bsToCreate);
        insert bsToCreate;

    }
}