force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/NextCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>NextCollectionDate__c</fullName>
    <formula>PreviousCollectionDate__c + (VALUE(TEXT(WeekFrequency__c)) * 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/PreviousCollectionDate__c.field-meta.xml
<CustomField>
    <fullName>PreviousCollectionDate__c</fullName>
    <label>Previous Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/WeekFrequency__c.field-meta.xml
<CustomField>
    <fullName>WeekFrequency__c</fullName>
    <label>Week Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PreviousCollectionDateBatch.cls
public without sharing class PreviousCollectionDateBatch implements Database.Batchable<sObject> {

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		return Database.getQueryLocator([SELECT NextCollectionDate__c, WeekFrequency__c FROM Schedule__c WHERE NextCollectionDate__c != null AND NextCollectionDate__c <= TODAY AND (End_Date__c >= TODAY OR End_Date__c = null) ORDER BY Location__c]);
	}

	public void execute(Database.BatchableContext batchContext, List<Schedule__c> schedules) {
		for (Schedule__c schedule : schedules) {
			schedule.PreviousCollectionDate__c = computePreviousCollectionDate(schedule.NextCollectionDate__c, Integer.valueOf(schedule.WeekFrequency__c));
		}

		Database.SaveResult[] results = Database.update(schedules, false);
		LogRegister.createLogsUpsert(results, schedules, 'Set Previous Collection Date', 'Update', 'Schedule__c', null);
	}

	public void finish(Database.BatchableContext batchContext) {}

	@TestVisible
	private Date computePreviousCollectionDate(Date nextCollectionDate, Integer weekFrequency) {
		Date previousCollectionDate;
		do {
			previousCollectionDate = nextCollectionDate;
			nextCollectionDate = previousCollectionDate.addDays(Integer.valueOf(7 * weekFrequency));
		} while (nextCollectionDate <= Date.today());

		return previousCollectionDate;
	}
}