force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Suspended__c.field-meta.xml
<CustomField>
    <fullName>Collection_Suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collection Suspended?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Reactivation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reactivation_Start_Date__c</fullName>
    <label>Reactivation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Suspension_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Suspension_Start_Date__c</fullName>
    <label>Suspension Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CollectionSuspendBatch.cls
public class CollectionSuspendBatch implements Database.Batchable<sObject> {
	@InvocableMethod(label='Collection Suspension/Reactivation Batch')
	public static void updateCollectionSuspendFlag() {
		Database.executeBatch(new CollectionSuspendBatch(), 1000);
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT Collection_Suspended__c FROM Schedule__c WHERE (Collection_Suspended__c = false AND Suspension_Start_Date__c <= TODAY AND Reactivation_Start_Date__c > TODAY) OR (Collection_Suspended__c = true AND Reactivation_Start_Date__c <= TODAY)';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Schedule__c> scope) {
		for (Schedule__c schedule : scope) {
			schedule.Collection_Suspended__c = !schedule.Collection_Suspended__c;
		}
		Database.update(scope, false);
	}

	public void finish(Database.BatchableContext BC) {
	}
}