force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parcelforce</fullName>
                <default>true</default>
                <label>Parcelforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Packages</relationshipLabel>
    <relationshipName>DeliveryPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/RequestedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>RequestedDeliveryDate__c</fullName>
    <label>Requested Delivery Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DeliveryWaypoint.cls
public without sharing class DeliveryWaypoint {

	public void create(List<DeliveryPackage__c> packages) {
		Map<String, maps__Route__c> routes = createRoutes(packages);

		List<maps__Waypoint__c> waypoints = new List<maps__Waypoint__c>();
		for (DeliveryPackage__c pkg : packages) {
			maps__Waypoint__c waypoint = new maps__Waypoint__c();
			waypoint.maps__LinkId__c = waypoint.Order__c = pkg.Order__c;
			waypoint.maps__Route__c = routes.get(formRouteName(pkg)).Id;
			waypoints.add(waypoint);
		}
		INSERT waypoints;
	}

	private Map<String, maps__Route__c> createRoutes(List<DeliveryPackage__c> packages) {
		Set<String> routeNames = new Set<String>();
		for (DeliveryPackage__c pkg : packages) {
			routeNames.add(formRouteName(pkg));
		}

		Map<String, maps__Route__c> routes = new Map<String, maps__Route__c>();
		List<maps__Route__c> existingRoutes = [SELECT Id, Name FROM maps__Route__c WHERE Name IN :routeNames];
		for (maps__Route__c route : existingRoutes) {
			routes.put(route.Name, route);
		}

		routeNames.removeAll(routes.keySet());
		if (routeNames.isEmpty()) {
			return routes;
		}

		Map<String, maps__Route__c> newRoutes = new Map<String, maps__Route__c>();
		for(String newRouteName : routeNames) {
			newRoutes.put(newRouteName, new maps__Route__c(Name = newRouteName));
		}
		INSERT newRoutes.values();
		routes.putAll(newRoutes);
		return routes;
	}

	private String formRouteName(DeliveryPackage__c pkg) {
		return pkg.Carrier__c + ' - ' + pkg.RequestedDeliveryDate__c;
	}
}