force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/IsRequestedDeliveryDateSameAsOrder__c.field-meta.xml
<CustomField>
    <fullName>IsRequestedDeliveryDateSameAsOrder__c</fullName>
    <formula>RequestedDeliveryDate__c = Order__r.Requested_Delivery_Date__c</formula>
    <label>Requested Delivery Date Same As Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Packages</relationshipLabel>
    <relationshipName>DeliveryPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/RequestedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>RequestedDeliveryDate__c</fullName>
    <label>Requested Delivery Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/BagsQuantity__c.field-meta.xml
<CustomField>
    <fullName>BagsQuantity__c</fullName>
    <label>Bags Quantity</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsCentralLondonLocation__c.field-meta.xml
<CustomField>
    <fullName>IsCentralLondonLocation__c</fullName>
    <formula>AND(ShippingLatitude &gt; 51.485, ShippingLatitude &lt; 51.524, ShippingLongitude &gt; -0.150, ShippingLongitude &lt; -0.080)</formula>
    <label>Central London Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsDeliveryByExternalCarrier__c.field-meta.xml
<CustomField>
    <fullName>IsDeliveryByExternalCarrier__c</fullName>
    <formula>AND(Number_of_Order_Products__c &gt; 0, Number_of_Order_Products__c = OrderProductsByExternalCarrier__c, CollectionProducts__c = 0,
NOT(OR(Account.Parent.IsExcludeDeliveryByExternalCarrier__c, Account.IsExcludeDeliveryByExternalCarrier__c)))</formula>
    <label>Delivery By External Carrier?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsLondonLocation__c.field-meta.xml
<CustomField>
    <fullName>IsLondonLocation__c</fullName>
    <formula>AND(ShippingLatitude &gt; 51.25, ShippingLatitude &lt; 51.75, ShippingLongitude &gt; -0.56, ShippingLongitude &lt; 0.33)</formula>
    <label>London Location?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <defaultValue>IF(
WEEKDAY(TODAY()+1)&gt;1 &amp;&amp; WEEKDAY(TODAY()+1)&lt;7, TODAY()+1, IF(WEEKDAY(TODAY()+1)=1, TODAY()+2, TODAY()+3)
)</defaultValue>
    <inlineHelpText>This field is used in the Supplier App.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/ParcelforceSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Parcelforce Setting</label>
</CustomObject>

force-app/main/default/objects/ParcelforceSetting__c/fields/MaximumOrdersPerDayLondon__c.field-meta.xml
<CustomField>
    <fullName>MaximumOrdersPerDayLondon__c</fullName>
    <label>Maximum Orders Per Day London</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/fields/MaximumOrdersPerDayNonLondon__c.field-meta.xml
<CustomField>
    <fullName>MaximumOrdersPerDayNonLondon__c</fullName>
    <label>Maximum Orders Per Day Non London</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/fields/MinimumOrdersPerDayLondon__c.field-meta.xml
<CustomField>
    <fullName>MinimumOrdersPerDayLondon__c</fullName>
    <label>Minimum Orders Per Day London</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeliveryPackageCreationSchedular.cls
public without sharing class DeliveryPackageCreationSchedular implements Schedulable {

	private Date nextWeekDay;

	private Integer minOrdersPerDayLondon;
	private Integer maxOrdersPerDayLondon;
	private Integer maxOrdersPerDayNonLondon;
	private Integer bagsPerParcel;

	Integer packageCount;

	public void execute(SchedulableContext SC) {
		ParcelforceSetting__c parcelforceSetting = ParcelforceSetting__c.getOrgDefaults();
		minOrdersPerDayLondon = Integer.valueOf(parcelforceSetting.MinimumOrdersPerDayLondon__c);
		maxOrdersPerDayLondon = Integer.valueOf(parcelforceSetting.MaximumOrdersPerDayLondon__c);
		maxOrdersPerDayNonLondon = Integer.valueOf(parcelforceSetting.MaximumOrdersPerDayNonLondon__c);
		bagsPerParcel = Integer.valueOf(parcelforceSetting.BagsPerParcel__c);

		nextWeekDay = DateUtil.getNextWeekday(System.today());

		List<DeliveryPackage__c> deliveryPackages = new List<DeliveryPackage__c>();

		packageCount = getDeliveryPackageCount(true);
		if (packageCount < maxOrdersPerDayLondon) {
			deliveryPackages.addAll(createDeliveryPackages(getOrdersToProcess(true, false), maxOrdersPerDayLondon));
			deliveryPackages.addAll(createDeliveryPackages(getOrdersToProcess(true, true), maxOrdersPerDayLondon));
		}

		packageCount = getDeliveryPackageCount(false);
		if (packageCount < maxOrdersPerDayNonLondon) {
			deliveryPackages.addAll(createDeliveryPackages(getOrdersToProcess(false, false), maxOrdersPerDayNonLondon));
		}

		if (!deliveryPackages.isEmpty()) {
			INSERT deliveryPackages;
		}
	}

	private List<DeliveryPackage__c> createDeliveryPackages(List<Order> orders, Integer dayLimit) {
		List<DeliveryPackage__c> deliveryPackages = new List<DeliveryPackage__c>();

		for (Order order : orders) {
			if (packageCount >= dayLimit) {
				break;
			}

			if (!order.DeliveryPackages__r.isEmpty()) {
				continue;
			}

			Long boxCount = (order.BagsQuantity__c / bagsPerParcel).round(System.RoundingMode.CEILING);
			deliveryPackages.add(new DeliveryPackage__c(Order__c = order.Id, RequestedDeliveryDate__c = nextWeekDay, Count__c = boxCount));
			packageCount++;
		}

		return deliveryPackages;
	}

	private List<Order> getOrdersToProcess(Boolean isLondonLocation, Boolean isCentralLondonLocation) {
		List<Order> ordersToProcess = [SELECT Requested_Delivery_Date__c, BagsQuantity__c,
				(SELECT Id FROM DeliveryPackages__r WHERE Status__c = :DeliveryPackage.STATUS_CANCELLED AND IsRequestedDeliveryDateSameAsOrder__c = true)
				FROM Order WHERE IsDeliveryByExternalCarrier__c = true AND IsLondonLocation__c = :isLondonLocation AND IsCentralLondonLocation__c = :isCentralLondonLocation ORDER BY CreatedDate];
		return isCentralLondonLocation ? getNonBikeOrders(ordersToProcess) : ordersToProcess;
	}

	private List<Order> getNonBikeOrders(List<Order> ordersToProcess) {
		if (ordersToProcess.size() <= minOrdersPerDayLondon) {
			return new List<Order>();
		}
		for (Integer i=0; i<minOrdersPerDayLondon; i++) {
			ordersToProcess.remove(0);
		}
		return ordersToProcess;
	}

	private Integer getDeliveryPackageCount(Boolean isLondonLocation) {
		List<AggregateResult> aggregatedPackages = [SELECT COUNT(Id) PackageCount FROM DeliveryPackage__c WHERE RequestedDeliveryDate__c = :nextWeekDay AND Order__r.IsLondonLocation__c = :isLondonLocation];
		return (Integer)aggregatedPackages[0].get('PackageCount');
	}
}