force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DeliveryPackageLabelBatch.cls
public without sharing class DeliveryPackageLabelBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

	private Set<Id> packageIds = new Set<Id>();

	public DeliveryPackageLabelBatch(Set<Id> packageIds) {
		this.packageIds = packageIds;
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT TrackingId__c FROM DeliveryPackage__c WHERE Id IN :packageIds AND Status__c = :DeliveryPackage.STATUS_ADVISED]);
	}

	public void execute(Database.BatchableContext BC, List<DeliveryPackage__c> scope) {
		List<Attachment> attachments = new List<Attachment>();
		for (DeliveryPackage__c pkg : scope) {
			pkg.Message__c = '';
			ParcelforceSoap.PrintLabelReply response = new ParcelforceSoap.ShipServicePort().printLabel(pkg.TrackingId__c);
			if (response.Label != null) {
				Attachment attachment = new Attachment();
				attachment.ParentId = pkg.Id;
				attachment.Name = 'Parcelforce Label - ' + pkg.TrackingId__c + '.pdf';
				attachment.Body = EncodingUtil.base64Decode(response.Label.Data);
				attachments.add(attachment);
				pkg.Status__c = DeliveryPackage.STATUS_LABELLED;
			} else {
				pkg.Status__c = DeliveryPackage.STATUS_ERROR;
				ParcelforceSoap.Alerts alerts = response.Alerts;
				for (ParcelforceSoap.Alert alert : alerts.Alert) {
					pkg.Message__c += alert.Message + ('\n');
				}
			}
		}
		INSERT attachments;
		UPDATE scope;
	}

	public void finish(Database.BatchableContext BC) {}
}