force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FirstMilePackageHandler.cls
public without sharing class FirstMilePackageHandler {

	public void handleTrigger(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_INSERT {
				createShipment(newList);
				new DeliveryWaypoint().create(newList);
			}
			when AFTER_UPDATE {
				createShipment(newList, oldMap);
				extractLabel(newList, oldMap);
			}
		}
	}

	private static void createShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();
		for (DeliveryPackage__c pkg : newList) {
			if (pkg.Status__c == DeliveryPackage.STATUS_RETRY && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_RETRY) {
				packages.add(pkg);
			}
		}
		if (!packages.isEmpty()) {
			createShipment(packages);
		}
	}

	private static void createShipment(List<DeliveryPackage__c> newList) {
		List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();
		for (DeliveryPackage__c pkg : newList) {
			packages.add(new DeliveryPackage__c(Id = pkg.Id, Status__c = DeliveryPackage.STATUS_ADVISED, Message__c = ''));
		}
		UPDATE packages;
	}

	private static void extractLabel(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();
		for (DeliveryPackage__c pkg : newList) {
			if (!pkg.IsCollection__c && pkg.Status__c == DeliveryPackage.STATUS_ADVISED && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_ADVISED) {
				packages.add(pkg);
			}
		}
		if (!packages.isEmpty()) {
			Database.executeBatch(new FirstMileDeliveryLabelBatch(packages), 50);
		}
	}
}