force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parcelforce</fullName>
                <default>true</default>
                <label>Parcelforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FirstMileDeliveryLabelBatch.cls
public without sharing class FirstMileDeliveryLabelBatch implements Database.Batchable<DeliveryPackage__c> {

	private List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();

	public FirstMileDeliveryLabelBatch(List<DeliveryPackage__c> packages) {
		this.packages = packages;
	}

	public Iterable<DeliveryPackage__c> start(Database.BatchableContext batchContext) {
		return packages;
	}

	public void execute(Database.BatchableContext BC, List<DeliveryPackage__c> scope) {
		List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();
		List<Attachment> attachments = new List<Attachment>();
		for (DeliveryPackage__c pkg : scope) {
			Attachment attachment = new Attachment();
			attachment.ParentId = pkg.Id;
			attachment.Name = pkg.Carrier__c + ' Label - ' + pkg.Name + '.pdf';
			attachment.Body = createLabelPdf(pkg);
			attachments.add(attachment);
			packages.add(new DeliveryPackage__c(Id = pkg.Id, Status__c = DeliveryPackage.STATUS_LABELLED, Message__c = ''));
		}
		INSERT attachments;
		UPDATE packages;
	}

	private Blob createLabelPdf(DeliveryPackage__c pkg) {
		PageReference pdf = Page.DeliveryPackageLabel;
		pdf.getParameters().put('Id', pkg.Id);
		return Test.isRunningTest() ? Blob.valueOf('test') : pdf.getContentAsPdf();
	}

	public void finish(Database.BatchableContext BC) {}
}