force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/DeliveredDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveredDate__c</fullName>
    <label>Delivered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/IsDraftStatus__c.field-meta.xml
<CustomField>
    <fullName>IsDraftStatus__c</fullName>
    <formula>CONTAINS(&apos;New, Advised, Labelled, Lock&apos;, TEXT(Status__c))</formula>
    <label>Draft Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/IsFinalStatus__c.field-meta.xml
<CustomField>
    <fullName>IsFinalStatus__c</fullName>
    <formula>CONTAINS(&apos;Delivered, Redeliver, Cancelled&apos;, TEXT(Status__c))</formula>
    <label>Final Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/ParcelforceEvent__c.field-meta.xml
<CustomField>
    <fullName>ParcelforceEvent__c</fullName>
    <label>Parcelforce Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I101</fullName>
                <label>Parcel tracked in</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>Parcel delivered</label>
            </value>
            <value>
                <fullName>I103</fullName>
                <label>Received but not advised</label>
            </value>
            <value>
                <fullName>I104</fullName>
                <label>Advised but not received</label>
            </value>
            <value>
                <fullName>I105</fullName>
                <label>Parcel matched to advice</label>
            </value>
            <value>
                <fullName>I106</fullName>
                <label>Advice received too late</label>
            </value>
            <value>
                <fullName>I107</fullName>
                <label>Redirection requested</label>
            </value>
            <value>
                <fullName>I108</fullName>
                <label>Addressee refused</label>
            </value>
            <value>
                <fullName>I109</fullName>
                <label>Addressee will collect</label>
            </value>
            <value>
                <fullName>I110</fullName>
                <label>Redelivery arranged</label>
            </value>
            <value>
                <fullName>I111</fullName>
                <label>Delivery arranged</label>
            </value>
            <value>
                <fullName>I112</fullName>
                <label>Depot cannot find parcel</label>
            </value>
            <value>
                <fullName>I113</fullName>
                <label>Local redirection</label>
            </value>
            <value>
                <fullName>I114</fullName>
                <label>Out for redelivery</label>
            </value>
            <value>
                <fullName>I115</fullName>
                <label>Out for first delivery</label>
            </value>
            <value>
                <fullName>I116</fullName>
                <label>Out for arranged delivery</label>
            </value>
            <value>
                <fullName>I117</fullName>
                <label>Found during stocktake</label>
            </value>
            <value>
                <fullName>I118</fullName>
                <label>Held - no time to deliver</label>
            </value>
            <value>
                <fullName>I119</fullName>
                <label>Held - incorrect address</label>
            </value>
            <value>
                <fullName>I120</fullName>
                <label>Held - gone away</label>
            </value>
            <value>
                <fullName>I121</fullName>
                <label>Held - parcel damaged</label>
            </value>
            <value>
                <fullName>I122</fullName>
                <label>Held - addressee refused</label>
            </value>
            <value>
                <fullName>I123</fullName>
                <label>Held - depot discretion</label>
            </value>
            <value>
                <fullName>I124</fullName>
                <label>Held - scheduled delivery</label>
            </value>
            <value>
                <fullName>I125</fullName>
                <label>Held - addressee request</label>
            </value>
            <value>
                <fullName>I126</fullName>
                <label>Held - attempted COD</label>
            </value>
            <value>
                <fullName>I127</fullName>
                <label>Held - for collection</label>
            </value>
            <value>
                <fullName>I128</fullName>
                <label>Held - attempted delivery</label>
            </value>
            <value>
                <fullName>I129</fullName>
                <label>Parcel relabelled</label>
            </value>
            <value>
                <fullName>I130</fullName>
                <label>Delivery not attempted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/DeliveryPackageTrackingEvent__c.object-meta.xml
<CustomObject>
    <label>Delivery Package Tracking Event</label>
    <nameField>
        <label>Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Package Tracking Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageTrackingEvent__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/ParcelforceSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Parcelforce Setting</label>
</CustomObject>

force-app/main/default/objects/ParcelforceSetting__c/fields/StatusCancelled__c.field-meta.xml
<CustomField>
    <fullName>StatusCancelled__c</fullName>
    <label>Cancelled Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/fields/StatusDelivered__c.field-meta.xml
<CustomField>
    <fullName>StatusDelivered__c</fullName>
    <label>Delivered Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ParcelforceSetting__c/fields/StatusRedelivery__c.field-meta.xml
<CustomField>
    <fullName>StatusRedelivery__c</fullName>
    <label>Redelivery Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParcelforceTrackingEvent.cls
public without sharing class ParcelforceTrackingEvent {

	private ParcelforceSetting__c setting = ParcelforceSetting__c.getOrgDefaults();
	private String deliveredStatus = setting.StatusDelivered__c;
	private String finalStatus = deliveredStatus + ',' + setting.StatusRedelivery__c + ',' + setting.StatusCancelled__c;

	public void process(List<DeliveryPackageTrackingEvent__c> newList) {
		Map<String, List<TrackingEventWrapper>> trackingEventMap = groupEventsByTrackingId(newList);
		Map<String, DeliveryPackage__c> packagesToUpdate = new Map<String, DeliveryPackage__c>();
		for (String trackingId : trackingEventMap.keySet()) {
			List<TrackingEventWrapper> wrapperEvents = trackingEventMap.get(trackingId);
			wrapperEvents.sort();
			DeliveryPackageTrackingEvent__c event = wrapperEvents[0].event;
			if (wrapperEvents.size() > 1) {
				for (TrackingEventWrapper wrapper : wrapperEvents) {
					if (finalStatus.contains(wrapper.event.Code__c)) {
						event = wrapper.event;
						break;
					}
				}
			}
			packagesToUpdate.put(trackingId, new DeliveryPackage__c(TrackingId__c = trackingId, ParcelforceEvent__c = event.Code__c, DeliveredDate__c = deliveredStatus.contains(event.Code__c) ? event.DateTime__c : null));
		}
		UPDATE filterInProgressPackages(packagesToUpdate);
	}

	private Map<String, List<TrackingEventWrapper>> groupEventsByTrackingId(List<DeliveryPackageTrackingEvent__c> newList) {
		Map<String, List<TrackingEventWrapper>> trackingEventMap = new Map<String, List<TrackingEventWrapper>>();
		for (DeliveryPackageTrackingEvent__c trackingEvent : newList) {
			if (!trackingEventMap.containsKey(trackingEvent.Name)) {
				trackingEventMap.put(trackingEvent.Name, new List<TrackingEventWrapper>{new TrackingEventWrapper(trackingEvent)});
				continue;
			}
			trackingEventMap.get(trackingEvent.Name).add(new TrackingEventWrapper(trackingEvent));
		}
		return trackingEventMap;
	}

	private List<DeliveryPackage__c> filterInProgressPackages(Map<String, DeliveryPackage__c> packagesByTrackingId) {
		List<DeliveryPackage__c> packagesInProgress = [SELECT TrackingId__c FROM DeliveryPackage__c WHERE TrackingId__c IN :packagesByTrackingId.keySet() AND IsFinalStatus__c = false AND IsDraftStatus__c = false];

		List<DeliveryPackage__c> filteredPackages = new List<DeliveryPackage__c>();
		for (DeliveryPackage__c packageInProgress : packagesInProgress) {
			DeliveryPackage__c deliveryPackage = packagesByTrackingId.get(packageInProgress.TrackingId__c);
			deliveryPackage.Id = packageInProgress.Id;
			filteredPackages.add(deliveryPackage);
		}
		return filteredPackages;
	}

	private class TrackingEventWrapper implements Comparable {
		private DeliveryPackageTrackingEvent__c event;

		private TrackingEventWrapper(DeliveryPackageTrackingEvent__c event) {
			this.event = event;
		}

		public Integer compareTo(Object compareTo) {
			TrackingEventWrapper compareToEvent = (TrackingEventWrapper)compareTo;
			if (event.DateTime__c == compareToEvent.event.DateTime__c) return 0;
			if (event.DateTime__c > compareToEvent.event.DateTime__c) return -1;
			return 1;
		}
	}
}