force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/IsFinalStatus__c.field-meta.xml
<CustomField>
    <fullName>IsFinalStatus__c</fullName>
    <formula>CONTAINS(&apos;Delivered, Redeliver, Cancelled&apos;, TEXT(Status__c))</formula>
    <label>Final Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ParcelforcePackageHandler.cls
public without sharing class ParcelforcePackageHandler {

	public void handleTrigger(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_INSERT {
				sendShipment(newList);
				new DeliveryWaypoint().create(newList);
			}
			when AFTER_UPDATE {
				sendShipment(newList, oldMap);
				extractLabel(newList, oldMap);
				cancelShipment(newList, oldMap);
			}
		}
	}

	private static void sendShipment(List<DeliveryPackage__c> newList) {
		sendShipment(IdUtil.extractId(newList));
	}

	private static void sendShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		Set<Id> packageIds = new Set<Id>();
		for (DeliveryPackage__c pkg : newList) {
			if (pkg.Status__c == DeliveryPackage.STATUS_RETRY && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_RETRY) {
				packageIds.add(pkg.Id);
			}
		}
		if (!packageIds.isEmpty()) {
			sendShipment(packageIds);
		}
	}

	private static void sendShipment(Set<Id> packageIds) {
		Database.executeBatch(new DeliveryPackageShipmentBatch(packageIds), 40);
	}

	private static void extractLabel(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		Set<Id> packageIds = new Set<Id>();
		for (DeliveryPackage__c pkg : newList) {
			if (!pkg.IsCollection__c && pkg.Status__c == DeliveryPackage.STATUS_ADVISED && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_ADVISED) {
				packageIds.add(pkg.Id);
			}
		}
		if (!packageIds.isEmpty()) {
			Database.executeBatch(new DeliveryPackageLabelBatch(packageIds), 40);	// Maximum 100 callout allowed in single transaction.
		}
	}

	private static void cancelShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		Set<Id> packageIds = new Set<Id>();
		for (DeliveryPackage__c pkg : newList) {
			if (!pkg.IsFinalStatus__c && pkg.Status__c == DeliveryPackage.STATUS_CANCEL_REQUEST && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_CANCEL_REQUEST) {
				packageIds.add(pkg.Id);
			}
		}
		if (!packageIds.isEmpty()) {
			Database.executeBatch(new DeliveryPackageCancellationBatch(packageIds), 40);	// Providing 3 seconds for each callout. 40*3 = 120 seconds.
		}
	}
}