force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/IsFinalStatus__c.field-meta.xml
<CustomField>
    <fullName>IsFinalStatus__c</fullName>
    <formula>CONTAINS(&apos;Delivered, Redeliver, Cancelled&apos;, TEXT(Status__c))</formula>
    <label>Final Status?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoyalMailPackageHandler.cls
public without sharing class RoyalMailPackageHandler {

	public void handleTrigger(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_INSERT {
				createShipment(newList);
				new DeliveryWaypoint().create(newList);
			}
			when AFTER_UPDATE {
				createShipment(newList, oldMap);
				cancelShipment(newList, oldMap);
				pickedShipment(newList, oldMap);
			}
		}
	}

	private static void createShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		List<DeliveryPackage__c> packages = new List<DeliveryPackage__c>();
		for (DeliveryPackage__c pkg : newList) {
			if (pkg.Status__c == DeliveryPackage.STATUS_RETRY && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_RETRY) {
				packages.add(pkg);
			}
		}
		if (!packages.isEmpty()) {
			createShipment(packages);
		}
	}

	private static void createShipment(List<DeliveryPackage__c> packages) {
		Set<Id> packageIds = IdUtil.extractId(packages);
		Database.executeBatch(new RoyalMailDeliveryCreateBatch(packageIds), 40);
	}

	private static void cancelShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		Set<Id> packageIds = new Set<Id>();
		for (DeliveryPackage__c pkg : newList) {
			if (!pkg.IsFinalStatus__c && pkg.Status__c == DeliveryPackage.STATUS_CANCEL_REQUEST && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_CANCEL_REQUEST) {
				packageIds.add(pkg.Id);
			}
		}
		if (!packageIds.isEmpty()) {
			Database.executeBatch(new RoyalMailDeliveryCancelBatch(packageIds), 40);	// Assuming 3 seconds for each callout. 40*3 = 120 seconds.
		}
	}

	private static void pickedShipment(List<DeliveryPackage__c> newList, Map<Id, DeliveryPackage__c> oldMap) {
		Set<Id> packageIds = new Set<Id>();
		for (DeliveryPackage__c pkg : newList) {
			if (!pkg.IsFinalStatus__c && pkg.Status__c == DeliveryPackage.STATUS_PACKAGED && oldMap.get(pkg.Id).Status__c != DeliveryPackage.STATUS_PACKAGED) {
				packageIds.add(pkg.Id);
			}
		}
		if (!packageIds.isEmpty()) {
			Database.executeBatch(new RoyalMailDeliveryPickedBatch(packageIds), 40);	// Assuming 3 seconds for each callout. 40*3 = 120 seconds.
		}
	}
}