force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Advised</fullName>
            </value>
            <value>
                <fullName>Labelled</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Packaged</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Returned To Sender</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryPackage__c/fields/TrackingIds__c.field-meta.xml
<CustomField>
    <fullName>TrackingIds__c</fullName>
    <label>All Tracking Ids</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RoyalMailDeliveryPickedBatch.cls
public without sharing class RoyalMailDeliveryPickedBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
	private Set<Id> packageIds = new Set<Id>();

	public RoyalMailDeliveryPickedBatch(Set<Id> packageIds) {
		this.packageIds = packageIds;
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT TrackingIds__c FROM DeliveryPackage__c WHERE Id IN :packageIds AND Status__c = :DeliveryPackage.STATUS_PACKAGED]);
	}

	public void execute(Database.BatchableContext BC, List<DeliveryPackage__c> scope) {
		for (DeliveryPackage__c pkg : scope) {
			try {
				process(pkg);
			} catch (Exception e) {
				pkg.Message__c = e.getMessage();
			}
		}

		UPDATE scope;
	}

	public void finish(Database.BatchableContext BC) {}

	private void process(DeliveryPackage__c pkg) {
		put(new RoyalMailDelivery.PickedRequest(StringUtil.splitTrim(pkg.TrackingIds__c, ',')));
		//pkg.Status__c = DeliveryPackage.STATUS_PACKAGED;
		pkg.Message__c = '';	// Clear any previous error message
	}

	private void put(RoyalMailDelivery.PickedRequest pickedRequest) {
		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:RoyalMail/shipments/status');
		request.setMethod('PUT');
		request.setHeader('Content-Type', 'application/json');
		request.setBody(JSON.serialize(pickedRequest));

		HttpResponse response = new Http().send(request);
		if (response.getStatusCode() != 200) {
			RoyalMailDelivery.PickedResponse pickedResponse = (RoyalMailDelivery.PickedResponse)JSON.deserialize(response.getBody(), RoyalMailDelivery.PickedResponse.class);
			String errorMessage = '';
			for (RoyalMailDelivery.Error error : pickedResponse.Errors) {
				errorMessage += error.Message + ' ';
			}
			throw new RoyalMailDelivery.RequestException(errorMessage.trim());
		}
	}
}