force-app/main/default/objects/DeliveryPackage__c/DeliveryPackage__c.object-meta.xml
<CustomObject>
    <label>Delivery Package</label>
    <nameField>
        <displayFormat>DelPkg-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/DeliveryPackageQrCode__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code</label>
    <nameField>
        <displayFormat>DelPkgQrCde - {0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Package QR Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCode__c/fields/DeliveryPackage__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPackage__c</fullName>
    <label>Delivery Package</label>
    <referenceTo>DeliveryPackage__c</referenceTo>
    <relationshipLabel>QR Codes</relationshipLabel>
    <relationshipName>QrCodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryPackageQrCodeItem__c/DeliveryPackageQrCodeItem__c.object-meta.xml
<CustomObject>
    <label>Delivery Package QR Code Item</label>
    <nameField>
        <label>QR Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Package QR Code Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryPackageQrCodeItem__c/fields/DeliveryPackageQrCode__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPackageQrCode__c</fullName>
    <label>Delivery Package QR Code</label>
    <referenceTo>DeliveryPackageQrCode__c</referenceTo>
    <relationshipLabel>Delivery Package QR Code Items</relationshipLabel>
    <relationshipName>DeliveryPackageQrCodeItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Qr_code__c/Qr_code__c.object-meta.xml
<CustomObject>
    <label>QR Code</label>
    <nameField>
        <displayFormat>{MM}-{YYYY}-{0}</displayFormat>
        <label>QR Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QR Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qr_code__c/fields/Driver_app_QR_code__c.field-meta.xml
<CustomField>
    <fullName>Driver_app_QR_code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>QR code scanned by the driver app</description>
    <label>Driver app QR code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DeliveryPackageQrCode.cls
public without sharing class DeliveryPackageQrCode {

	public static List<String> verifyDuplicates(List<String> qrCodes) {
		Set<String> individualQrCodes = toIndividual(qrCodes);
		if (individualQrCodes.isEmpty()) {
			return new List<String>();
		}

		Set<String> duplicates = new Set<String>();

		List<Qr_code__c> duplicateQrCodes = [SELECT Driver_app_QR_code__c FROM Qr_code__c WHERE Driver_app_QR_code__c IN :individualQrCodes];
		for (Qr_code__c duplicateQrCode : duplicateQrCodes) {
			duplicates.add(duplicateQrCode.Driver_app_QR_code__c);
		}
		individualQrCodes.removeAll(duplicates);

		List<DeliveryPackageQrCodeItem__c> duplicateItems = [SELECT Name FROM DeliveryPackageQrCodeItem__c WHERE Name IN :individualQrCodes
			AND DeliveryPackageQrCode__r.DeliveryPackage__r.Status__c IN ('Packaged', 'In Progress')];
		for (DeliveryPackageQrCodeItem__c duplicateItem : duplicateItems) {
			duplicates.add(duplicateItem.Name);
		}

		return new List<String>(duplicates);
	}

	public static Set<String> toIndividual(List<String> qrCodes) {
		Set<String> individualQrCodes = new Set<String>();

		for (String qrCode : qrCodes) {
			if (String.isBlank(qrCode)) {
				continue;
			}
			individualQrCodes.addAll(StringUtil.splitTrim(qrCode.toUpperCase().replace('-', ','), ','));
		}

		return individualQrCodes;
	}
}