force-app/main/default/objects/SageExtract__c/SageExtract__c.object-meta.xml
<CustomObject>
    <label>SageExtract</label>
    <nameField>
        <label>SageExtract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SageExtracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SageExtract__c/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/DatePostedtoSage__c.field-meta.xml
<CustomField>
    <fullName>DatePostedtoSage__c</fullName>
    <label>DatePostedtoSage</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/GoodsAmount__c.field-meta.xml
<CustomField>
    <fullName>GoodsAmount__c</fullName>
    <label>GoodsAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/PostedtoSage__c.field-meta.xml
<CustomField>
    <fullName>PostedtoSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PostedtoSage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/SageExtractFile__c.field-meta.xml
<CustomField>
    <fullName>SageExtractFile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SageExtractFile</label>
    <referenceTo>SageExtractFile__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>TransactionDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SageExtractFile__c/SageExtractFile__c.object-meta.xml
<CustomObject>
    <label>SageExtractFile</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>SageExtractFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SageExtractFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SageCsvFileController.cls
public with sharing class SageCsvFileController {

	public ApexPages.StandardSetController sageFiles {
		get {
			if (sageFiles == null) {
				sageFiles = new ApexPages.StandardSetController(Database.getQueryLocator(
					[Select Id, Name, DatePostedtoSage__c, AccountNumber__c, GoodsAmount__c, TransactionDate__c, PostedtoSage__c FROM SageExtract__c WHERE PostedtoSage__c = false]));
				sageFiles.setPageSize(sageFiles.getResultSize());
			}
			return sageFiles;
		}
		set;
	}

	public SageCsvFileController(ApexPages.StandardSetController ctrl) {}

	public void spin() {
		long now = datetime.now().gettime();
		while(datetime.now().gettime()-now<5000); // Busy loop for 5000 ms
	}

	public void SageCSVFileBatchMethod() {
		SageExtractFile__c sef = new SageExtractFile__c();
		INSERT sef;
		Database.executeBatch(new SageCSVFileBatch(sef.Id), 2000);
	}

	public PageReference newPage() {
		PageReference retURL = new PageReference('/lightning/o/SageExtractFile__c/list?filterName=Recent');
		system.debug(retURL);
		retURL.setRedirect(true);
		return retURL;
	}
}