force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/IsScheduledForDeletion__c.field-meta.xml
<CustomField>
    <fullName>IsScheduledForDeletion__c</fullName>
    <formula>DATEVALUE(CreatedDate) &lt; TODAY() - 14</formula>
    <label>Scheduled For Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LogDeleteBatch.cls
public class LogDeleteBatch implements Database.Batchable<sObject> {

	@InvocableMethod(label='Delete Older Logs')
	public static void deleteOlderLogs() {
		Database.executeBatch(new LogDeleteBatch(), 2000);
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT Id FROM Log__c WHERE IsScheduledForDeletion__c = true';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<SObject> scope) {
		Database.delete(scope, false);
	}

	public void finish(Database.BatchableContext BC) {
	}
}