force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Is_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field allow user to easily identify if this log issue is related to an error or a success. Most usefully on reports and fields.</description>
    <label>Is Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Parent_Info__c.field-meta.xml
<CustomField>
    <fullName>Parent_Info__c</fullName>
    <description>This field allow users to identify the parent record associated with this log, if that parent exists.</description>
    <label>Parent Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogRegister.cls
/**
(c) 2018 Xpand-IT
@date 11.2018
@author Bruno Mendes and Joao Gomes

@description Class created to populate the Log__c object

@modifications 12.2018 - Exceptional Monotoring implementation
*/
public with sharing class LogRegister {
	public String objectType {get; set;}
	public String process {get; set;}
	public String action {get; set;}
	public String recordId {get; set;}
	public String errorMessage {get; set;}

	public LogRegister(String objectType, String process, String action, String  recordId, String errorMessage) {
		this.objectType = objectType;
		this.process = process;
		this.action = action;
		this.recordId = recordId;
		this.errorMessage = errorMessage;
	}

	private static Log__c createLog(Boolean isSuccess, List<Database.Error> errors, Id recordId, sObject record, String process, String action, String sObjectType, String parentField) {
		Log__c log = new Log__c(Process__c = process, Action__c = action, Object_Type__c = sObjectType);

		String errorMessage = '';
		if (!String.isBlank(parentField) && record.get(parentField) != null) {
			ID parentId = (String) record.get(parentField);
			log.Parent_Info__c = 'Object Type "' + parentId.getSObjectType() + '" with ID "' + parentId + '"';
		}
		if (!isSuccess) {
			errorMessage = 'Error on ' + action + ' a record of '+ sObjectType + ' with the following data:\n' + record + '\n\n';
			errorMessage += 'Error List:\n';
			for (Database.Error err : errors) {
				errorMessage += 'The following error has occurred - ' + err.getStatusCode() + ': ' + err.getMessage() + ' Fields that affected this error: ' + err.getFields() + '\n';
			}
			log.Is_Error__c = true;
			log.Record_ID__c = '';
			log.Error_Message__c = errorMessage;
		}
		else {
			log.Record_ID__c = recordId;
		}

		return log;
	}

	public static void createLogs(List<Database.DeleteResult> results, List<sObject> records, String process, String action, String sObjectType, String parentField) {
		List<Log__c> logs = new List<Log__c>();
		try {
			for (Integer idx = 0; idx < results.size(); idx++) {
				logs.add(createLog(results[idx].isSuccess(), results[idx].getErrors(), results[idx].getId(), records[idx], process, action, sObjectType, parentField));
			}

			INSERT logs;
		}
		catch (Exception e) {
			System.debug(e.getMessage());
		}
	}

	public static void createLogsUpsert(List<Database.SaveResult> results, List<sObject> records, String process, String action, String sObjectType, String parentField) {
		List<Log__c> logs = new List<Log__c>();
		try {
            for (Integer idx = 0; idx < results.size(); idx++) {
                if (!results[idx].isSuccess()) {
                    logs.add(createLog(false, results[idx].getErrors(), results[idx].getId(), records[idx], process, action, sObjectType, parentField));
                }
            }

			INSERT logs;
		}
		catch (Exception e) {
			System.debug(e.getMessage());
		}
	}

	public static void createLogsUpsert(List<Database.UpsertResult> results, List<sObject> records, String process, String action, String sObjectType, String parentField) {
		List<Log__c> logs = new List<Log__c>();
		try {
            for (Integer idx = 0; idx < results.size(); idx++) {
                if (!results[idx].isSuccess()) {
                    logs.add(createLog(false, results[idx].getErrors(), results[idx].getId(), records[idx], process, action, sObjectType, parentField));
                }
            }

			INSERT logs;
		}
		catch (Exception e) {
			System.debug(e.getMessage());
		}
	}

	public static void createLogs(List<LogRegister> logs) {
		List<Log__c> logsToInsert = new List<Log__c>();
		for (LogRegister logreg : logs) {
			logsToInsert.add(new Log__c(Object_Type__c = logreg.objectType, Process__c = logreg.process, Action__c = logreg.action, Record_ID__c = logreg.recordId, Error_Message__c = logreg.errorMessage));
		}

		try {
			INSERT logsToInsert;
		}
		catch (Exception e) {
			system.debug('Error! - ' + e.getMessage());
		}
	}
}