force-app/main/default/objects/RoyalMailSetting__c/RoyalMailSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Royal Mail Setting</label>
</CustomObject>

force-app/main/default/objects/RoyalMailSetting__c/fields/ShippingLocationId__c.field-meta.xml
<CustomField>
    <fullName>ShippingLocationId__c</fullName>
    <label>Shipping Location Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RoyalMailDeliveryManifest.cls
public without sharing class RoyalMailDeliveryManifest {

	@InvocableMethod (Label = 'Royal Mail Delivery Manifest API')
	public static void process() {
    	RoyalMailDeliveryManifestProcess();
	}

	@future(callout = true)
	private static void RoyalMailDeliveryManifestProcess() {
		RoyalMailDelivery.ManifestRequest manifestRequest = new RoyalMailDelivery.ManifestRequest();
		manifestRequest.ShippingLocationId = RoyalMailSetting__c.getOrgDefaults().ShippingLocationId__c;

		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:RoyalMail/manifests/RM');
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json');
		request.setBody(JSON.serialize(manifestRequest));

		HttpResponse response = new Http().send(request);
		if (response.getStatusCode() != 200) {
			RoyalMailDelivery.ManifestResponse manifestResponse = (RoyalMailDelivery.ManifestResponse)JSON.deserialize(response.getBody(), RoyalMailDelivery.ManifestResponse.class);
			String errorMessage = '';
			for (RoyalMailDelivery.Error error : manifestResponse.Errors) {
				errorMessage += error.Message + ' ';
			}
            System.debug('Error Occurred: ' + manifestResponse.Message);
			//throw new RoyalMailDelivery.RequestException(errorMessage.trim());
		}
	}
}