force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/DaysOutstanding__c.field-meta.xml
<CustomField>
    <fullName>DaysOutstanding__c</fullName>
    <formula>IF( AmountOutstanding__c &gt; 0, TODAY()- Payment_Due_Date__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysOutstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/IsOverdueDaysSynced__c.field-meta.xml
<CustomField>
    <fullName>IsOverdueDaysSynced__c</fullName>
    <formula>NOT(AND(OverdueDays__c != DaysOutstanding__c,
CASE(DaysOutstanding__c, 7, 1, 14, 1, 30, 1, 60, 1, 90, 1, 0) = 1))</formula>
    <label>Overdue Days Synced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/OverdueDays__c.field-meta.xml
<CustomField>
    <fullName>OverdueDays__c</fullName>
    <label>Overdue Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceHeaderOverdueDaysBatch.cls
public class InvoiceHeaderOverdueDaysBatch implements Database.Batchable<sObject> {
	@InvocableMethod(label='Update Overdue Days')
	public static void updateOverdueDays() {
		Database.executeBatch(new InvoiceHeaderOverdueDaysBatch(), 1000);
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT Id, DaysOutstanding__c FROM Invoice_Header__c WHERE IsOverdueDaysSynced__c = false';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Invoice_Header__c> scope) {
		for (Invoice_Header__c invoiceHeader : scope) {
			invoiceHeader.OverdueDays__c = invoiceHeader.DaysOutstanding__c;
		}
		Database.update(scope, false);
	}

	public void finish(Database.BatchableContext BC) {
	}
}