force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Ready_to_Email__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/SageExtractCreated__c.field-meta.xml
<CustomField>
    <fullName>SageExtractCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be check if the invoice had not created sages extract records</description>
    <label>Sage Extract Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice_Line</label>
    <nameField>
        <label>Invoice_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice_HeaderId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_HeaderId__c</fullName>
    <label>Invoice_HeaderId</label>
    <referenceTo>Invoice_Header__c</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice_Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product_AccCode__c.field-meta.xml
<CustomField>
    <fullName>Product_AccCode__c</fullName>
    <formula>Product__r.Nl_accode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product_AccCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/SageExtractCreated__c.field-meta.xml
<CustomField>
    <fullName>SageExtractCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sage Extract Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status related to the Subcontractor Invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Nl_accode__c.field-meta.xml
<CustomField>
    <fullName>Nl_accode__c</fullName>
    <description>the field Nl_accode__c on the product object should be *required* on creation of a Product.
Nl_accode__c stands for &apos;nominal ledger code&apos;. Users need to populate it with a code from Finance whenever they create a new product.</description>
    <inlineHelpText>The field Nl_accode__c on the product object should be *required* on creation of a Product.
Nl_accode__c stands for &apos;nominal ledger code&apos;. 
Users need to populate it with a code from Finance whenever they create a new product.</inlineHelpText>
    <label>Nl_accode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SageExtract__c/SageExtract__c.object-meta.xml
<CustomObject>
    <label>SageExtract</label>
    <nameField>
        <label>SageExtract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SageExtracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SageExtract__c/fields/Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice_Line</label>
    <referenceTo>Invoice_Line__c</referenceTo>
    <relationshipLabel>SageExtracts</relationshipLabel>
    <relationshipName>SageExtracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SageExtractFromInvoiceBatch.cls
public class SageExtractFromInvoiceBatch implements Database.Batchable<sObject> {

	private final static String statusClosed = Invoicing.STATUS_CLOSED;

	private Date dueDate;

	public SageExtractFromInvoiceBatch() {
		this.dueDate = System.today() - 1;
	}

	public SageExtractFromInvoiceBatch(Date someDate) {
		this.dueDate = someDate;
	}

	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		String query = 'SELECT Product__r.Nl_accode__c, Product_AccCode__c, Amount__c, VAT__c, Invoice_HeaderId__c, Invoice_HeaderId__r.DueDate__c FROM Invoice_Line__c WHERE SageExtractCreated__c = false AND Invoice_HeaderId__r.Status__c = :statusClosed AND Invoice_HeaderId__r.DueDate__c = :dueDate ORDER BY Invoice_HeaderId__c';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext batchContext, List<Invoice_Line__c> invoiceLines) {
		List <SageExtract__c> sageLines = new List <SageExtract__c>();
		for (Invoice_Line__c invoiceLine : invoiceLines) {
			sageLines.addAll(Sage.createLines(invoiceLine));
		}

		Database.insert(sageLines, false);
		Database.update(invoiceLines, false);
	}

	public void finish(Database.BatchableContext batchContext) {
		List<Invoice_Header__c> invoices = [SELECT Id FROM Invoice_Header__c WHERE SageExtractCreated__c = false AND Status__c = :statusClosed AND DueDate__c = YESTERDAY];
		for (Invoice_Header__c invoice : invoices) {
			invoice.SageExtractCreated__c = true;
			invoice.Ready_to_Email__c = true;
		}

		Database.update(invoices, false);
	}
}