force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Index</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/RoutingParameterOverride__mdt.object-meta.xml
<CustomObject>
    <label>Routing Parameter Override</label>
    <pluralLabel>Routing Parameter Overrides</pluralLabel>
</CustomObject>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/EndDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>EndDepotIndex__c</fullName>
    <description>Ending location of routes.</description>
    <label>End Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/GenerateMethod__c.field-meta.xml
<CustomField>
    <fullName>GenerateMethod__c</fullName>
    <description>Solver method for how to create routes, either on time or by a fixed number.</description>
    <label>Generate Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/MaxRouteTime__c.field-meta.xml
<CustomField>
    <fullName>MaxRouteTime__c</fullName>
    <description>Max duration of route.</description>
    <label>Max Route Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/NumberOfRoutes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfRoutes__c</fullName>
    <description>Desired number of routes to create.</description>
    <label>Number of Routes to create</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/SequenceGap__c.field-meta.xml
<CustomField>
    <fullName>SequenceGap__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Value to increment between each Sequence value for Service Locations.</description>
    <label>Sequence Gap</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/SequenceStart__c.field-meta.xml
<CustomField>
    <fullName>SequenceStart__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Starting value for first sequenced record on each route.</description>
    <label>Sequence Start</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/Solver__c.field-meta.xml
<CustomField>
    <fullName>Solver__c</fullName>
    <description>Call one of the RouteSmart optimisation solvers.</description>
    <label>Solver</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generate New Routes</fullName>
            </value>
            <value>
                <fullName>Generate And Sequence New Routes</fullName>
            </value>
            <value>
                <fullName>Sequence Existing Routes</fullName>
            </value>
            <value>
                <fullName>Insert onto Existing Routes</fullName>
            </value>
            <value>
                <fullName>Evaluate Existing Routes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/StartDepotIndex__c.field-meta.xml
<CustomField>
    <fullName>StartDepotIndex__c</fullName>
    <description>Starting location of routes.</description>
    <label>Start Depot Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time of routes.</description>
    <label>Start Time</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/UseExtraDistance__c.field-meta.xml
<CustomField>
    <fullName>UseExtraDistance__c</fullName>
    <description>When enabled we use the values defined in the SL layer for the extraDistance attribute when calculating service time for a route. Ex: Additional distance may be added for records with vertical distance such as an apartment bldg.</description>
    <label>Use Extra Distance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/UseExtraTime__c.field-meta.xml
<CustomField>
    <fullName>UseExtraTime__c</fullName>
    <description>When enabled we use the values defined in the SL layer for the extraTime attribute when calculating service time for a route. Ex: Additional Time may be added for record with long driveways or complicated delivery hindrances.</description>
    <label>Use Extra Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/UsePickupDeliveryCapacity__c.field-meta.xml
<CustomField>
    <fullName>UsePickupDeliveryCapacity__c</fullName>
    <description>Solver would make decisions during the sequence for delivering or picking up based on the active capacity count instead of waiting for capacity to be full before deciding to end the sequence or empty. Used for bin delivery and pickup.</description>
    <label>Use Pickup Delivery Capacity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoutingParameterOverride__mdt/fields/UseSpecialties__c.field-meta.xml
<CustomField>
    <fullName>UseSpecialties__c</fullName>
    <description>Option to consider Specialties during optimization.</description>
    <label>Use Specialties</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoutingRequest.cls
public without sharing abstract class RoutingRequest {

	private ParameterOverride parameterOverrides;
	private List<Depot> facilities = new List<Depot>();

	protected RoutingRequest(RoutingParameterOverride__mdt overrides, List<Depot__c> depots) {
		parameterOverrides = new ParameterOverride(overrides);

		for (Depot__c depot : depots) {
			facilities.add(new Depot(depot));
		}
	}

	private class ParameterOverride {
		private transient RoutingParameterOverride__mdt overrides;

		private ParameterOverride(RoutingParameterOverride__mdt overrides) {
			this.overrides = overrides;
		}

		private String solver { get { return overrides.Solver__c; } }
		private String generateMethod { get { return overrides.GenerateMethod__c; } }
		private Integer numberOfRoutes { get { return Convert.toInteger(overrides.NumberOfRoutes__c); } }
		private String maxRouteTime { get { return overrides.MaxRouteTime__c; } }
		private String startTime { get { return overrides.StartTime__c; } }
		private Integer startLocation { get { return Convert.toInteger(overrides.StartDepotIndex__c); } }
		private Integer endLocation { get { return Convert.toInteger(overrides.EndDepotIndex__c); } }
		private Integer seqStart { get { return Convert.toInteger(overrides.SequenceStart__c); } }
		private Integer seqGap { get { return Convert.toInteger(overrides.SequenceGap__c); } }
		private Boolean useExtraDistance { get { return Convert.toBoolean(overrides.UseExtraDistance__c); } }
		private Boolean useExtraTime { get { return Convert.toBoolean(overrides.UseExtraTime__c); } }
		private Boolean useSpecialties { get { return Convert.toBoolean(overrides.UseSpecialties__c); } }
		private Boolean usePickupDeliveryCapacity { get { return Convert.toBoolean(overrides.UsePickupDeliveryCapacity__c); } }
	}

	private class Depot {
		private transient Depot__c depot;

		private Depot(Depot__c depot) {
			this.depot = depot;
		}

		private Integer id { get { return Convert.toInteger(depot.Index__c); } }
		private String name { get { return depot.Name; } }
		private Decimal clientXCoord { get { return depot.Coordinates__Longitude__s; } }
		private Decimal clientYCoord { get { return depot.Coordinates__Latitude__s; } }
		private String address { get { return depot.Address__Street__s; } }
		private String city { get { return depot.Address__City__s; } }
		private String zipCode { get { return depot.Address__PostalCode__s; } }
	}
}