force-app/main/default/objects/ScheduleSuspension__c/ScheduleSuspension__c.object-meta.xml
<CustomObject>
    <label>Schedule Suspension</label>
    <nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Suspensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/IsEveryYear__c.field-meta.xml
<CustomField>
    <fullName>IsEveryYear__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Every Year?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/ReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>ReactivationDate__c</fullName>
    <label>Reactivation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ScheduleSuspension__c/fields/SuspensionDate__c.field-meta.xml
<CustomField>
    <fullName>SuspensionDate__c</fullName>
    <label>Suspension Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CollectionSuspendExtendBatch.cls
public without sharing class CollectionSuspendExtendBatch implements Database.Batchable<sObject> {

	public Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT SuspensionDate__c, ReactivationDate__c FROM ScheduleSuspension__c WHERE IsActive__c = true AND IsEveryYear__c = true AND ReactivationDate__c < TODAY';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<ScheduleSuspension__c> scope) {
		for (ScheduleSuspension__c suspension : scope) {
			suspension.SuspensionDate__c = suspension.SuspensionDate__c.addYears(1);
			suspension.ReactivationDate__c = suspension.ReactivationDate__c.addYears(1);
		}

		Database.SaveResult[] result = Database.update(scope, false);
		LogRegister.createLogsUpsert(result, scope, 'Update suspension/reactivation dates', 'Update', 'ScheduleSuspension__c', null);
	}

	public void finish(Database.BatchableContext BC) {}
}