force-app/main/default/objects/Enqix_Import__c/Enqix_Import__c.object-meta.xml
<CustomObject>
    <description>Serves as a placeholder for Enquix data imports.</description>
    <label>Enqix Import</label>
    <nameField>
        <displayFormat>EI-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enqix Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enqix_Import__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>Log data for the operation, if number of statements falls out of Length, log attachment is generated and attached to the record.</description>
    <inlineHelpText>Log data for the operation, if number of statements falls out of Length, log attachment is generated and attached to the record.</inlineHelpText>
    <label>Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enqix_Import__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the import job.</description>
    <inlineHelpText>Status of the import job.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enqix_Import__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Import.</description>
    <inlineHelpText>Type of Import.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts/Locations</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/EnquixImportMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings Object that capture the mappings for the Enquix (CSV) files. Name of the individual settings instance represents a row header in the import sheet.</description>
    <label>Enquix Import Mappings</label>
</CustomObject>

force-app/main/default/objects/EnquixImportMappings__c/fields/CopyValueFromSheet__c.field-meta.xml
<CustomField>
    <fullName>CopyValueFromSheet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a value should be copied from the import sheet.</description>
    <inlineHelpText>Indicates whether a value should be copied from the import sheet.</inlineHelpText>
    <label>Copy Value From Sheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/fields/EnquixHeaderValue__c.field-meta.xml
<CustomField>
    <fullName>EnquixHeaderValue__c</fullName>
    <description>Header value as presented in the import CSV</description>
    <inlineHelpText>Header value as presented in the import CSV</inlineHelpText>
    <label>Enquix Header Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/fields/ImportType__c.field-meta.xml
<CustomField>
    <fullName>ImportType__c</fullName>
    <description>Account or Order. Defines a scope for the particular mapping.</description>
    <inlineHelpText>Account or Order. Defines a scope for the particular mapping.</inlineHelpText>
    <label>Import Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/fields/SalesforceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SalesforceFieldAPIName__c</fullName>
    <description>This field captures the value of the Salesforce Field API Name associated with a specific Mapping</description>
    <externalId>true</externalId>
    <inlineHelpText>This field captures the value of the Salesforce Field API Name associated with a specific Mapping</inlineHelpText>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnquixImportMappings__c/fields/SalesforceRecordGroup__c.field-meta.xml
<CustomField>
    <fullName>SalesforceRecordGroup__c</fullName>
    <description>This field captures the value of the Group associated with a particular mapping, e.g. it could be Account or Location for Account imports.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field captures the value of the Group associated with a particular mapping, e.g. it could be Account or Location for Account imports.</inlineHelpText>
    <label>Salesforce Record Group</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IF(AND(Delivery_Type__c &gt; 0, Quantity__c &gt; 3), &quot;Large Non-Standard&quot;, 
IF(AND(Delivery_Type__c &gt; 0, Quantity__c &lt; 3), &quot;Small Non-Standard&quot;, &quot;Standard&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EquixImportManager.cls
/**
* @author Zoran Zunko
* @date 9/30/15
*
* @group 
* @group-content ../../ApexDocContent/
*
* @description 
*/

public with sharing class EquixImportManager {

    @TestVisible private static Integer logFieldLength;

    public static Integer getLogFieldLength() {

        if (logFieldLength == null) {

            logFieldLength = Enqix_Import__c.Log__c.getDescribe().getLength();
        }

        return logFieldLength;
    }

    private static Map<String, Integer> monthsMap = new Map<String, Integer> {
            'Jan' => 1,
            'Feb' => 2,
            'Mar' => 3,
            'Apr' => 4,
            'May' => 5,
            'Jun' => 6,
            'Jul' => 7,
            'Aug' => 8,
            'Sep' => 9,
            'Oct' => 10,
            'Nov' => 11,
            'Dec' => 12

    };

    private static Integer convertMonthTextToNumber(String month) {
        return monthsMap.get(month);
    }

    public static final String IMPORT_TYPE_ACCOUNT = 'Accounts/Locations';
    public static final String IMPORT_TYPE_ORDER = 'Orders';

    public static final String STATUS_NEW = 'New';
    public static final String STATUS_PENDING = 'Pending';
    public static final String STATUS_IN_PROGRESS = 'In Progress';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_ERROR = 'Error';

    @TestVisible private static Map<String, Map<String, Map<String, EnquixImportMappings__c>>> importMappingMap;

    public static Map<String, Map<String, Map<String, EnquixImportMappings__c>>> getImportMappingMap() {

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getImportMappingMap start ');
        System.debug(LoggingLevel.DEBUG, 'importMappingMap: ' + importMappingMap);

        if (importMappingMap == null || importMappingMap.size() == 0) {

            importMappingMap = new Map<String, Map<String, Map<String, EnquixImportMappings__c>>>();
            for (EnquixImportMappings__c mapping: EnquixImportMappingsManager.getEnquixImportMappings().values()) {

                if (importMappingMap.get(mapping.ImportType__c) == null) {

                    importMappingMap.put(mapping.ImportType__c, new Map<String, Map<String, EnquixImportMappings__c>>());
                }
                if (importMappingMap.get(mapping.ImportType__c).get(mapping.SalesforceRecordGroup__c) == null) {

                    importMappingMap.get(mapping.ImportType__c).put(mapping.SalesforceRecordGroup__c, new Map<String, EnquixImportMappings__c>());
                }

                importMappingMap.get(mapping.ImportType__c).get(mapping.SalesforceRecordGroup__c).put(mapping.EnquixHeaderValue__c, mapping);
            }
            System.debug(LoggingLevel.DEBUG, 'importMappingMap: ' + importMappingMap);
        }
        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getImportMappingMap end');
        return importMappingMap;
    }

    public static List<Enqix_Import__c> getPendingEnqixImports(String importType) {

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getPendingEnqixImports start');
        List<Enqix_Import__c> enqixImports = [
                SELECT Log__c, Status__c, Type__c
                FROM Enqix_Import__c
                WHERE Status__c = :STATUS_PENDING
                AND Type__c = :importType
                ORDER BY CreatedDate ASC
        ];
        System.debug(LoggingLevel.DEBUG, 'enqixImports.size(): ' + enqixImports.size());
        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getPendingEnqixImports end');

        return enqixImports;
    }

    public static Attachment getLatestAttachmentForEnqixImport(Id enquixImportId) {

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getLatestAttachmentForEnqixImport start');

        List<Attachment> attachments = [
                SELECT Body
                FROM Attachment
                WHERE ParentId = :enquixImportId
                ORDER BY LastModifiedDate DESC
                LIMIT 1
        ];

        if (attachments.size() == 0) {

            throw new EnquixImportException('No attachments exist for Enqix Import: ' + enquixImportId);
        }
        System.debug(LoggingLevel.DEBUG, 'attachments.size(): ' + attachments.size());
        System.debug(LoggingLevel.DEBUG, 'EquixImportManager getLatestAttachmentForEnqixImport end');

        return attachments[0];
    }

    public static Map<String, Integer> processHeader(List<String> headers) {

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager processHeader start');
        System.debug(LoggingLevel.DEBUG, 'headers: ' + headers);
        Map<String, Integer> headerMap = new Map<String, Integer>();

        for (Integer i = 0; i < headers.size(); i++) {

            headerMap.put(headers[i], i);
        }

        System.debug(LoggingLevel.DEBUG, 'headerMap: ' + headerMap);
        System.debug(LoggingLevel.DEBUG, 'EquixImportManager processHeader end');
        return headerMap;
    }

    public static SObject copyLineToSObject(
            SObject recordSObject
            , String recordGroup
            , List<String> csvLine
            , Map<String, EnquixImportMappings__c> fieldMappings
            , Map<String, Integer> headerIndexMap) {

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager copyLineToSObject - start');
        System.debug(LoggingLevel.FINE, 'recordSObject: ' + recordSObject);
        System.debug(LoggingLevel.FINE, 'csvLine: ' + csvLine);

        for (String header : headerIndexMap.keySet()) {
            System.debug(LoggingLevel.FINE, 'header: ' + header);
            System.debug(LoggingLevel.FINE, 'fieldMappings.get(header): ' + fieldMappings.get(header));
            try {
                String elementValue = csvLine.get(headerIndexMap.get(header));
                if (
                    (
                     header == EnquixImportMappingsManager.START_DATE_MAPPING || 
                     header == EnquixImportMappingsManager.END_DATE_MAPPING || 
                     header == EnquixImportMappingsManager.ORDER_EFFECTIVE_DATE_MAPPING || 
                     header == EnquixImportMappingsManager.ORDER_DELIVERY_DATE_MAPPING || 
                     header == EnquixImportMappingsManager.ORDER_INV_SERV_NOTE_DATE
                     ) && String.isNotBlank(elementValue)
                    ) {
                    Integer dateYear;
                    Integer dateMonth;
                    Integer dateDay;

                    String datePart = elementValue.split(' ')[0];
                    List<String> dateParts = datePart.split('/');

                    dateYear = Integer.valueOf(dateParts[2]);
                    dateMonth = Integer.valueOf(dateParts[1]);
                    dateDay = Integer.valueOf(dateParts[0]);

                    if (dateYear != null && dateMonth != null && dateDay != null) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Date.newInstance(dateYear, dateMonth, dateDay));
                    }
                    /*Integer dateYear = Integer.valueOf(elementValue);
                    Integer dateMonth = convertMonthTextToNumber(
                            csvLine.get(
                                    headerIndexMap.get(
                                            EnquixImportMappingsManager.START_DATE_MONTH_MAPPING)
                            )
                    );

                    if (dateYear != null && dateMonth != null) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Date.newInstance(dateYear, dateMonth, 0));
                    }*/
                }
                /*else if (header == EnquixImportMappingsManager.END_DATE_MAPPING) {
                    Integer dateYear;
                    Integer dateMonth;
                    Integer dateDay;

                    String datePart = elementValue.split(' ')[0];
                    List<String> dateParts = datePart.split('/');

                    dateYear = Integer.valueOf(dateParts[2]);
                    dateMonth = Integer.valueOf(dateParts[1]);
                    dateDay = Integer.valueOf(dateParts[0]);

                    if (dateYear != null && dateMonth != null && dateDay != null) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Date.newInstance(dateYear, dateMonth, dateDay));
                    }
//                    Integer dateYear = Integer.valueOf(elementValue);
//                    Integer dateMonth = convertMonthTextToNumber(
//                            csvLine.get(
//                                    headerIndexMap.get(
//                                            EnquixImportMappingsManager.END_DATE_MONTH_MAPPING)
//                            )
//                    );
//                    if (dateYear != null && dateMonth != null) {
//                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Date.newInstance(dateYear, dateMonth, 0));
//                    }
                }*/
                else if (header == EnquixImportMappingsManager.COLLECTION_STREET_MAPPING1) {

                    String colStreet1 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.COLLECTION_STREET_MAPPING1)
                    );
                    String colStreet2 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.COLLECTION_STREET_MAPPING2)
                    );
                    String colStreet3 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.COLLECTION_STREET_MAPPING3)
                    );
                    String colStreet = '';
                    if (!String.isBlank(colStreet1)) {
                        colStreet += colStreet1;
                    }
                    if (!String.isBlank(colStreet2)) {
                        colStreet += ( String.isBlank(colStreet) ? '' : ', ' ) + colStreet2;
                    }
                    if (!String.isBlank(colStreet3)) {
                        colStreet += ( String.isBlank(colStreet) ? '' : ', ' ) + colStreet3;
                    }
                    recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, colStreet);
                }
                else if (header == EnquixImportMappingsManager.DELIVERY_STREET_MAPPING1) {

                    String delStreet1 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.DELIVERY_STREET_MAPPING1)
                    );
                    String delStreet2 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.DELIVERY_STREET_MAPPING2)
                    );
                    String delStreet3 = csvLine.get(
                            headerIndexMap.get(
                                    EnquixImportMappingsManager.DELIVERY_STREET_MAPPING3)
                    );
                    String delStreet = '';
                    if (!String.isBlank(delStreet1)) {
                        delStreet += delStreet1;
                    }
                    if (!String.isBlank(delStreet2)) {
                        delStreet += ( String.isBlank(delStreet) ? '' : ', ' ) + delStreet2;
                    }
                    if (!String.isBlank(delStreet3)) {
                        delStreet += ( String.isBlank(delStreet) ? '' : ', ' ) + delStreet3;
                    }
                    recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, delStreet);
                }
                else if (fieldMappings.get(header) != null && fieldMappings.get(header).SalesforceFieldAPIName__c != 'null' && fieldMappings.get(header).CopyValueFromSheet__c) {

                    System.debug(LoggingLevel.DEBUG, 'fieldMappings.get(header).SalesforceFieldAPIName__c: ' + fieldMappings.get(header).SalesforceFieldAPIName__c);
                    System.debug(LoggingLevel.DEBUG, 'recordSObject.getSObjectType().getDescribe().fields.getMap().get(fieldMappings.get(header).SalesforceFieldAPIName__c): ' + recordSObject.getSObjectType().getDescribe().fields.getMap().get(fieldMappings.get(header).SalesforceFieldAPIName__c));
                    Schema.DisplayType fieldType = recordSObject.getSObjectType().getDescribe().fields.getMap().get(fieldMappings.get(header).SalesforceFieldAPIName__c).getDescribe().getType();
                    if (fieldType == Schema.DisplayType.Double) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Double.valueOf(elementValue));
                    }
                    else if (fieldType == Schema.DisplayType.Integer) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Integer.valueOf(elementValue));
                    }
                    else if (fieldType == Schema.DisplayType.CURRENCY) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Double.valueOf(elementValue));
                    }
                    else if (fieldType == Schema.DisplayType.Percent) {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, Decimal.valueOf(elementValue));
                    }
                    else if (fieldType == Schema.DisplayType.Date) {
                        List<String> dateParts = elementValue.split(' ')[0].replace(' ', '').split('/');

                        Date formDate = Date.newInstance(Integer.valueOf(dateParts[2]), Integer.valueOf(dateParts[0]), Integer.valueOf(dateParts[1]));
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, formDate);
                    }
                    else {
                        recordSObject.put(fieldMappings.get(header).SalesforceFieldAPIName__c, elementValue);
                    }
                }
                System.debug('elementValue: ' + elementValue);
            }
            catch (Exception ex) {

                System.debug(LoggingLevel.ERROR, 'header: ' + header);
                System.debug(LoggingLevel.ERROR, 'fieldMappings.get(header): ' + fieldMappings.get(header));
                System.debug(LoggingLevel.DEBUG, 'csvLine.get(headerIndexMap.get(header)): ' + csvLine.get(headerIndexMap.get(header)));
                System.debug(LoggingLevel.WARN, ex.getMessage() + ' ' + ex.getStackTraceString());
            }
        }

        System.debug(LoggingLevel.DEBUG, 'EquixImportManager copyLineToSObject - end');
        return recordSObject;
    }
}