force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Active_Driver__c.field-meta.xml
<CustomField>
    <fullName>Active_Driver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Driver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External_Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Id_Ba__c.field-meta.xml
<CustomField>
    <fullName>Id_Ba__c</fullName>
    <description>Id Driver Reference from BambooHR</description>
    <label>Id_Ba</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>CAT C Driver</fullName>
            </value>
            <value>
                <fullName>Cyclist</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Loader</fullName>
            </value>
            <value>
                <fullName>Spare Collections</fullName>
                <label>Spare</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Yard Assistant</fullName>
            </value>
            <value>
                <fullName>Collection PM Driver</fullName>
            </value>
            <value>
                <fullName>Collection AM Driver</fullName>
            </value>
            <value>
                <fullName>Delivery Driver</fullName>
            </value>
            <value>
                <fullName>Spare Driver</fullName>
            </value>
            <value>
                <fullName>Academy Trainer</fullName>
            </value>
            <value>
                <fullName>Academy Driver</fullName>
            </value>
            <value>
                <fullName>Academy Collection AM</fullName>
            </value>
            <value>
                <fullName>Spare (CAT B)</fullName>
            </value>
            <value>
                <fullName>Cyclist AM</fullName>
            </value>
            <value>
                <fullName>Waste and Education Officer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BambooEmployeeDirectoryQueueable.cls
public without sharing class BambooEmployeeDirectoryQueueable implements Queueable, Database.AllowsCallouts {

	private Integer page;

	public BambooEmployeeDirectoryQueueable() {
		this(1);
	}

	public BambooEmployeeDirectoryQueueable(Integer page) {
		this.page = page;
	}

	public void execute(QueueableContext context) {
		Response response = fetchEmployeeDirectory();
		if (response == null) {
			return;
		}

		List<Driver__c> driversToUpsert = new List<Driver__c>();
		for (Employee employee : response.data) {
			if (employee.customField4416 != 'Drivers') {
				continue;
			}

			Driver__c driver = new Driver__c();
			driver.Id_Ba__c  = Integer.valueOf(employee.eeid);
			driver.External_Id__c = employee.employeeNumber;
			driver.Active_Driver__c = employee.status == 'Active';
			driver.First_Name__c = employee.firstName;
			driver.Last_Name__c = employee.lastName;
			driver.Name = employee.firstNameLastName;
			driver.Job_Title__c = employee.jobInformationJobTitle;
			driversToUpsert.add(driver);
		}

		if (!driversToUpsert.isEmpty()) {
			Database.UpsertResult[] results = Database.upsert(driversToUpsert, Driver__c.Id_Ba__c, false);
			LogRegister.createLogsUpsert(results, driversToUpsert, 'Upsert Bamboo Employee Directory', 'Upsert', 'Driver__c', null);
		}

		if (response.pagination.next_page != null) {
			System.enqueueJob(new BambooEmployeeDirectoryQueueable(response.pagination.current_page + 1));
		}
	}

	private Response fetchEmployeeDirectory() {
		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:Bamboo/v1/datasets/employee?page_size=500&page=' + page);
		request.setMethod('POST');
		request.setBody('{"fields": ["eeid","employeeNumber","firstName","lastName","firstNameLastName","jobInformationJobTitle","status","customField4416"]}');

		HttpResponse response = new Http().send(request);
		if (response.getStatusCode() != 200) {
			return null;
		}

		return (Response)JSON.deserialize(response.getBody(), Response.class);
	}

	private class Response {
		private List<Employee> data;
		private Pagination pagination;
	}

	private class Employee {
		private String eeid;
		private string employeeNumber;
		private string status;
		private String firstName;
		private String lastName;
		private String firstNameLastName;
		private String jobInformationJobTitle;
		private String customField4416;
	}

	private class Pagination {
		private String next_page;
		private Integer current_page;
	}
}