force-app/main/default/objects/Subscribed_Products__c/Subscribed_Products__c.object-meta.xml
<CustomObject>
    <description>The combination of suppliers and its corresponding products that are being bought by the customers (locations).</description>
    <label>Subscribed Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Subscribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Period__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Period__c</fullName>
    <label>Location Limit Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Half-year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/NextRefreshDate__c.field-meta.xml
<CustomField>
    <fullName>NextRefreshDate__c</fullName>
    <label>NextRefreshDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/quantityOrdered__c.field-meta.xml
<CustomField>
    <fullName>quantityOrdered__c</fullName>
    <label>quantityOrdered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubscribedProductsSch.cls
global class SubscribedProductsSch implements Schedulable {
	global void execute(SchedulableContext sc) {
		SubscribedProductRefreshBatch subsProdRefresh = new SubscribedProductRefreshBatch();
		database.executebatch(subsProdRefresh, 200);

		//checkRefreshDate();
	}

	/*public void checkRefreshDate(){
		Date today = system.today();

		List<Subscribed_Products__c> lista = [SELECT Id, NextRefreshDate__c, Enqix_BID_Location_Limit_Period__c FROM Subscribed_Products__c 
		WHERE NextRefreshDate__c != null and NextRefreshDate__c <= Today and Enqix_BID_Location_Limit_Period__c != null 
		];

		
		system.debug('ESTOU DENTRO DO SCH DOS SUBSCRIBED PRODUCTS+++++++++++++++++++++++++++++++++++++ TENHO ALGUM => '+lista.size());
		for(Subscribed_Products__c h : lista){
			//if(today.day() == h.NextRefreshDate__c.day() && today.month() == h.NextRefreshDate__c.month() && today.year() == h.NextRefreshDate__c.year()){
				h.quantityOrdered__c = 0;
			//}
		}
		
		update(lista);
		
	}*/

}