force-app/main/default/objects/Subscribed_Products__c/Subscribed_Products__c.object-meta.xml
<CustomObject>
    <description>The combination of suppliers and its corresponding products that are being bought by the customers (locations).</description>
    <label>Subscribed Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Subscribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Products__c/fields/Enqix_BID_Location_Limit_Period__c.field-meta.xml
<CustomField>
    <fullName>Enqix_BID_Location_Limit_Period__c</fullName>
    <label>Location Limit Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Half-year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/NextRefreshDate__c.field-meta.xml
<CustomField>
    <fullName>NextRefreshDate__c</fullName>
    <label>NextRefreshDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscribed_Products__c/fields/quantityOrdered__c.field-meta.xml
<CustomField>
    <fullName>quantityOrdered__c</fullName>
    <label>quantityOrdered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubscribedProductRefreshBatch.cls
global class SubscribedProductRefreshBatch implements Database.Batchable <sObject>, Database.Stateful {
    
    global String query;

    global SubscribedProductRefreshBatch(){
        query = 'SELECT Id, quantityOrdered__c, NextRefreshDate__c, Enqix_BID_Location_Limit_Period__c FROM Subscribed_Products__c WHERE NextRefreshDate__c != null and NextRefreshDate__c = Today and Enqix_BID_Location_Limit_Period__c != null';
    }

     global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Subscribed_Products__c> scope){
        system.debug('scope.size()---> '+ scope.size());
        
        List<Subscribed_Products__c> lista = new List<Subscribed_Products__c>();
        for(Subscribed_Products__c h : scope){
				h.quantityOrdered__c = 0;
                lista.add(h);
		}
        update lista;
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('SubscribedProducts were updated successfully');
    }
}