force-app/main/default/objects/DeliveryOrder__c/DeliveryOrder__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DlvyOrder-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryOrderGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryOrderGroup__c</fullName>
    <label>Delivery Order Group</label>
    <referenceTo>DeliveryOrderGroup__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <label>Demand</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTime__c</fullName>
    <label>Service Time</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/SkillSet__c.field-meta.xml
<CustomField>
    <fullName>SkillSet__c</fullName>
    <label>Skill Set</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/DeliveryOrderGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Order Group</label>
    <nameField>
        <displayFormat>DlvyOrderGrp-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <summarizedField>DeliveryOrder__c.RouteDate__c</summarizedField>
    <summaryForeignKey>DeliveryOrder__c.DeliveryOrderGroup__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DeliveryOrderFileUpload.cls
public with sharing class DeliveryOrderFileUpload extends FileUpload{
    public static final String FILE_REFERENCE = 'DeliveryOrder';
	private static final String LABEL = 'Delivery Order';
	private static final String DELIMITER = ',';
    private static final Map<String, String> FIELDS_TO_PROCESS = new Map<String, String>{'OrderId'=>'Order__c',
																						'Service Time' => 'ServiceTime__c',
																						'Demand' => 'Demand__c',
                                                                                        'serviceType' => 'ServiceType__c',
                                                                                        'RouteDate' => 'RouteDate__c',
																						'SkillSetProperty' => 'SkillSet__c'};

	private static final Schema.SObjectType SOBJECT_TYPE = SObjectType.DeliveryOrder__c.getSobjectType();
	private static final Map<String, Schema.SObjectField> FIELD_MAP = SObjectType.DeliveryOrder__c.fields.getMap();

    protected override String getOptionLabel() {
		return LABEL;
	}

	protected override String getFileReference() {
		return FILE_REFERENCE;
	}

	protected override Schema.SObjectType getObjectType() {
		return SOBJECT_TYPE;
	}

	protected override Map<String, Schema.SObjectField> getFieldMap() {
		return FIELD_MAP;
	}

	public override String getDelimiter() {
		return DELIMITER;
	}

	public override void process(List<Object> rows) {
        DeliveryOrderGroup__c deliveryOrderGroup = new DeliveryOrderGroup__c();
        INSERT deliveryOrderGroup;
		List<SObject> sObjects = createSObject(rows);
        for (SObject sObj : sObjects) {
            sObj.put('DeliveryOrderGroup__c', deliveryOrderGroup.Id); 
			System.debug('Name-->'+ deliveryOrderGroup.Name);
        }
		List<Database.SaveResult> results = Database.insert(sObjects, false);
		LogRegister.createLogsUpsert(results, sObjects, 'Delivery Order - File Upload', 'Insert', 'DeliveryOrder__c', 'DeliveryOrderGroup__c');
	}

	protected override String getFieldName(String columnHeader) {
		return FIELDS_TO_PROCESS.get(columnHeader);
	}

	protected override void addField(SObject sObj, String fieldName, Object value) {
		if (!FIELDS_TO_PROCESS.values().contains(fieldName)) {
			return;
		}

		if (fieldName == 'RouteDate__c') {
			String dateStr = String.valueOf(value);
            List<String> dateParts = dateStr.substringBefore(' ').split('/');
            Date d = date.newInstance(Integer.valueOf(dateParts[2]), Integer.valueOf(dateParts[0]),  Integer.valueOf(dateParts[1]));
            value = d;
    }

    super.addField(sObj, fieldName, value);
 	}
    
}