force-app/main/default/objects/DeliveryOrder__c/DeliveryOrder__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DlvyOrder-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryOrderGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryOrderGroup__c</fullName>
    <label>Delivery Order Group</label>
    <referenceTo>DeliveryOrderGroup__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/DeliveryOrderGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Order Group</label>
    <nameField>
        <displayFormat>DlvyOrderGrp-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Order Group</relationshipLabel>
    <relationshipName>DeliveryRouteGroup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RoutingPollCount__c.field-meta.xml
<CustomField>
    <fullName>RoutingPollCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Routing Poll Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RoutingSummary__c.field-meta.xml
<CustomField>
    <fullName>RoutingSummary__c</fullName>
    <label>Routing Summary</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryRouteGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteGroup__c</fullName>
    <label>Delivery Route Group</label>
    <referenceTo>DeliveryRouteGroup__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryRouteGroup__c/DeliveryRouteGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Route Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RoutingGetDeliveryResult.cls
public without sharing class RoutingGetDeliveryResult extends RoutingGetResult  {

	public RoutingGetDeliveryResult(Integer jobId, Integer pollCount) {
		super(jobId, pollCount);
	}

	protected override void enqueue() {
		updateJob(new DeliveryOrderGroup__c());

		if (Test.isRunningTest()) {return;} else {System.enqueueJob(new RoutingGetDeliveryResultQueueable(jobId, ++pollCount), 1);}
	}

	protected override void updateJobError(String status, String message) {
		updateJob(new DeliveryOrderGroup__c(RoutingStatus__c = status, RoutingResponse__c = message));
	}

	protected override void processResult(RoutingResponse routingResponse) {
		Map<String, DeliveryRoute__c> routeMap = new Map<String, DeliveryRoute__c>();
		List<DeliveryRoute__c> routes = [SELECT Name FROM DeliveryRoute__c WHERE DeliveryRouteGroup__c IN (SELECT DeliveryRouteGroup__c FROM DeliveryOrderGroup__c WHERE RoutingJobId__c = :routingResponse.jobId)];
		for (DeliveryRoute__c route : routes) {
			routeMap.put(route.Name, route);
		}

		Map<Integer, DeliveryOrder__c> deliveryOrderMap = new Map<Integer, DeliveryOrder__c>();
		List<DeliveryOrder__c> deliveryOrders = [SELECT Order__r.OrderNumber, Order__r.AccountId FROM DeliveryOrder__c WHERE DeliveryOrderGroup__r.RoutingJobId__c = :routingResponse.jobId];
		for (DeliveryOrder__c deliveryOrder : deliveryOrders) {
			deliveryOrderMap.put(Convert.toInteger(deliveryOrder.Order__r.OrderNumber), deliveryOrder);
		}

		DeliveryRoute__c route;
		DeliveryOrder__c deliveryOrder;
		Map<Id, List<DeliveryOrder__c>> deliveryOrdersByRoute = new Map<Id, List<DeliveryOrder__c>>();
		for (RoutingResponse.ServiceLocation location : routingResponse.serviceLocations) {
			route = routeMap.get(location.route);
			if (route == null) {
				deliveryOrderMap.remove(location.recordID);
				continue;	// Posibly some data error, due to which RaaS did not assign a route
			}
			deliveryOrder = deliveryOrderMap.get(location.recordID);
			deliveryOrder.DeliveryRoute__c = route.Id;
			deliveryOrder.SequenceNumber__c = location.sequence;

			// Group by each route
			if (deliveryOrdersByRoute.containsKey(route.Id)) {
				deliveryOrdersByRoute.get(route.Id).add(deliveryOrder);
			} else {
				deliveryOrdersByRoute.put(route.Id, new List<DeliveryOrder__c>{deliveryOrder});
			}
		}

		for (List<DeliveryOrder__c> deliveryOrderGroup : deliveryOrdersByRoute.values()) {
			resequence(deliveryOrderGroup);
		}

		UPDATE deliveryOrderMap.values();
		updateJob(new DeliveryOrderGroup__c(RoutingStatus__c = 'Completed', RoutingSummary__c = JSON.serializePretty(routingResponse.routeSummary)));
	}

	protected override String key(sObject record) {
		return ((DeliveryOrder__c)record).Order__r.AccountId;
	}

	private void updateJob(DeliveryOrderGroup__c deliveryOrderGroup) {
		deliveryOrderGroup.RoutingJobId__c = jobId;
		deliveryOrderGroup.RoutingPollCount__c = pollCount;
		UPSERT deliveryOrderGroup RoutingJobId__c;
	}
}