force-app/main/default/objects/DeliveryOrder__c/DeliveryOrder__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DlvyOrder-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryOrderGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryOrderGroup__c</fullName>
    <label>Delivery Order Group</label>
    <referenceTo>DeliveryOrderGroup__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>DeliveryOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryOrder__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryOrderGroup__c/DeliveryOrderGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Order Group</label>
    <nameField>
        <displayFormat>DlvyOrderGrp-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryOrderGroup__c/fields/RouteDate__c.field-meta.xml
<CustomField>
    <fullName>RouteDate__c</fullName>
    <label>Route Date</label>
    <summarizedField>DeliveryOrder__c.RouteDate__c</summarizedField>
    <summaryForeignKey>DeliveryOrder__c.DeliveryOrderGroup__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypoint__c/ReceivedWaypoint__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint</label>
    <nameField>
        <label>Route</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Received Waypoints</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Received Waypoints</relationshipLabel>
    <relationshipName>ReceivedWaypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypoint__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/ReceivedWaypointGroup__c.object-meta.xml
<CustomObject>
    <label>Received Waypoint Group</label>
    <nameField>
        <displayFormat>GRP-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Received Waypoint Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecivedWaypointSource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReceivedWaypointGroup__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/RecivedWaypointSource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RaaS</fullName>
    </customValue>
    <masterLabel>Recived Waypoint Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryOrderGroupTriggerHandler.cls
public without sharing class DeliveryOrderGroupTriggerHandler {

	public void handleTrigger(List<DeliveryOrderGroup__c> newList, Map<Id, DeliveryOrderGroup__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_UPDATE {
				handleUpdate(newList, oldMap);
			}
		}
	}

	private void handleUpdate(List<DeliveryOrderGroup__c> newList, Map<Id, DeliveryOrderGroup__c> oldMap) {
		List<DeliveryOrderGroup__c> requestedGroups = filter(newList, oldMap, 'Requested');
		if (!requestedGroups.isEmpty()) {
			Database.executebatch(new RoutingPostDeliveryJobBatch(IdUtil.extractId(requestedGroups)), 1);
		}

		List<DeliveryOrderGroup__c> completedGroups = filter(newList, oldMap, 'Completed');
		if (!completedGroups.isEmpty()) {
			createReceivedWaypoints(completedGroups);
		}
	}


	private List<DeliveryOrderGroup__c> filter(List<DeliveryOrderGroup__c> newList, Map<Id, DeliveryOrderGroup__c> oldMap, String status) {
		List<DeliveryOrderGroup__c> orderGroups = new List<DeliveryOrderGroup__c>();
		for (DeliveryOrderGroup__c orderGroup : newList) {
			if (orderGroup.RoutingStatus__c == status && oldMap.get(orderGroup.Id).RoutingStatus__c != status) {
				orderGroups.add(orderGroup);
			}
		}
		return orderGroups;
	}

	private void createReceivedWaypoints(List<DeliveryOrderGroup__c> orderGroups) {
		List<DeliveryOrder__c> deliveryOrders = [SELECT RouteDate__c, DeliveryOrderGroup__c , Order__c, DeliveryRoute__r.Name, SequenceNumber__c
			FROM DeliveryOrder__c WHERE DeliveryOrderGroup__c IN :orderGroups AND DeliveryRoute__c != null];
		List<ReceivedWaypoint__c> receivedWaypoints = new List<ReceivedWaypoint__c>();
		for (DeliveryOrder__c deliveryOrder : deliveryOrders) {
			ReceivedWaypoint__c receivedWaypoint = new ReceivedWaypoint__c(Source__c = 'RaaS', Date__c = deliveryOrder.RouteDate__c, Timestamp__c = deliveryOrder.DeliveryOrderGroup__c,
				Order__c = deliveryOrder.Order__c, Name = deliveryOrder.DeliveryRoute__r.Name, SequenceNumber__c = deliveryOrder.SequenceNumber__c);
			receivedWaypoints.add(receivedWaypoint);
		}
		INSERT receivedWaypoints;

		LIst<ReceivedWaypointGroup__c> receivedWaypointGroups = new List<ReceivedWaypointGroup__c>();
		for (DeliveryOrderGroup__c orderGroup : orderGroups) {
			receivedWaypointGroups.add(new ReceivedWaypointGroup__c(Source__c = 'RaaS', Date__c = orderGroup.RouteDate__c, Timestamp__c = orderGroup.Id));
		}
		INSERT receivedWaypointGroups;
	}
}