force-app/main/default/objects/BusinessCentralSendRequest__c/BusinessCentralSendRequest__c.object-meta.xml
<CustomObject>
    <label>Business Central Send Request</label>
    <nameField>
        <displayFormat>Request-{0}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Central Send Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessCentralSendRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice_Header</label>
    <nameField>
        <label>Invoice_Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice_Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/AmountExclVAT__c.field-meta.xml
<CustomField>
    <fullName>AmountExclVAT__c</fullName>
    <label>AmountExclVAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/BusinessCentralId__c.field-meta.xml
<CustomField>
    <fullName>BusinessCentralId__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/LineCount__c.field-meta.xml
<CustomField>
    <fullName>LineCount__c</fullName>
    <label>Line Count</label>
    <summaryForeignKey>Invoice_Line__c.Invoice_HeaderId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceChangeEventTriggerHandler.cls
public class InvoiceChangeEventTriggerHandler extends BusinessCentralEventHandler {

	private static final Date CUT_OFF_DATE = Date.newInstance(2026, 5, 28);

	public InvoiceChangeEventTriggerHandler() {
		super(Invoice_Header__c.sObjectType);
	}

	protected override Map<Id, sObject> fetchRecords(Set<String> recordIds) {
		return new Map<Id, Invoice_Header__c>([SELECT BusinessCentralId__c, Status__c, LineCount__c, DueDate__c, AmountExclVAT__c FROM Invoice_Header__c WHERE Id IN :recordIds]);
	}

	protected override Boolean isSkipEvent(EventBus.ChangeEventHeader eventHeader, sObject sObj) {
		Invoice_Header__c invoice = (Invoice_Header__c)sObj;

		if (eventHeader.changetype == 'CREATE') {
			return invoice.Status__c != Invoicing.STATUS_CLOSED;
		} else if (eventHeader.changetype == 'UPDATE') {
			return !isChangedFieldsInMonitoredFields(eventHeader) || invoice.Status__c != Invoicing.STATUS_CLOSED;
		} else {
			return true;
		}
	}

	protected override Boolean isSkipRecord(sObject sObj) {
        Invoice_Header__c invoice = (Invoice_Header__c)sObj;
		return invoice.AmountExclVAT__c == 0;
	}

	protected override Boolean isRecordEligible(sObject sObj) {
		Invoice_Header__c invoice = (Invoice_Header__c)sObj;
		return String.isEmpty(invoice.BusinessCentralId__c) && invoice.LineCount__c > 0 && invoice.DueDate__c >= CUT_OFF_DATE;
	}

	protected override List<BusinessCentralSendRequest__c> createQueueRequests(Set<String> recordIds, List<String> changedFields) {
		List<BusinessCentralSendRequest__c> requests = new List<BusinessCentralSendRequest__c>();
		for (String recordId : recordIds) {
			requests.add(new BusinessCentralSendRequest__c(InvoiceId__c = recordId));
		}
		return requests;
	}

	protected override String getkey(BusinessCentralSendRequest__c requestToQueue) {
		return requestToQueue.InvoiceId__c;
	}
}