force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>AND(DATEVALUE(StartDate__c) &lt;= TODAY(), DATEVALUE(EndDate__c) &gt;= TODAY())</formula>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/recordTypes/WTN.recordType-meta.xml
<RecordType>
    <fullName>WTN</fullName>
    <active>true</active>
    <label>Waste Transfer Notes</label>
</RecordType>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Collection Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Collection_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Collection quantity - always 1 unless bins are used, in which case the number of bins</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/WtnWasteCategory__c.field-meta.xml
<CustomField>
    <fullName>WtnWasteCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WTN Waste Category</label>
    <referenceTo>WTN_Waste_Category__c</referenceTo>
    <relationshipLabel>Collection Schedules</relationshipLabel>
    <relationshipName>CollectionSchedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/WTN_Waste_Category__c.object-meta.xml
<CustomObject>
    <label>WTN Waste Category</label>
    <nameField>
        <displayFormat>WTN{YYYY}{MM}-{0}</displayFormat>
        <label>WTN Waste Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WTN Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTN_Waste_Category__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/fields/WTN__c.field-meta.xml
<CustomField>
    <fullName>WTN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Waste Transfer Note</label>
    <referenceTo>Compliance_Doc__c</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WtnWasteCategorySummaryBatch.cls
public without sharing class WtnWasteCategorySummaryBatch implements Database.Batchable<sObject>  {

	private final Boolean ALL_RECORDS;
	private List<String> wtnIds;
	private List<Schedule__c> schedules;

	public WtnWasteCategorySummaryBatch() {
		this(false);
	}

	public WtnWasteCategorySummaryBatch(Boolean allRecords) {
		ALL_RECORDS = allRecords;
	}

	public WtnWasteCategorySummaryBatch(List<String> wtnIds) {
		this();
		this.wtnIds = wtnIds;
	}

	public WtnWasteCategorySummaryBatch(List<Schedule__c> schedules) {
		this();
		this.schedules = schedules;
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		if (ALL_RECORDS) {
			return Database.getQueryLocator([SELECT Id FROM WTN_Waste_Category__c WHERE WTN__r.IsActive__c = true AND WTN__r.Name LIKE 'Season Ticket WTN%']);
		}

		if (wtnIds != null) {
			return Database.getQueryLocator([SELECT Id FROM WTN_Waste_Category__c WHERE WTN__c IN :wtnIds]);
		}

		if (schedules == null) {
			schedules = [SELECT WtnWasteCategory__c FROM Schedule__c WHERE WtnWasteCategory__c != null AND (Start_Date__c = TODAY OR End_Date__c = YESTERDAY)];
		}

		Set<Id> wtnWasteCategoryIds = new Set<Id>();
		for (Schedule__c schedule : schedules) {
			wtnWasteCategoryIds.add(schedule.WtnWasteCategory__c);
		}
		return Database.getQueryLocator([SELECT Id FROM WTN_Waste_Category__c WHERE Id IN :wtnWasteCategoryIds]);
	}

	public void execute(Database.BatchableContext bc, List<WTN_Waste_Category__c> scope) {
		List<WTN_Waste_Category__c> wtnWasteCategories = new List<WTN_Waste_Category__c>();
		for (AggregateResult ar : [SELECT WtnWasteCategory__c, SUM(Collection_Quantity__c) TotalQty FROM Schedule__c
				WHERE WtnWasteCategory__c IN :scope
				AND (Start_Date__c = null OR Start_Date__c <= TODAY)
				AND (End_Date__c = null OR End_Date__c >= TODAY)
				GROUP BY WtnWasteCategory__c]) {
			wtnWasteCategories.add(new WTN_Waste_Category__c(Id = (Id)ar.get('WtnWasteCategory__c'), Quantity__c = (Decimal)ar.get('TotalQty')));
		}
		Database.SaveResult[] results = Database.update(wtnWasteCategories, false);
		LogRegister.createLogsUpsert(results, wtnWasteCategories, 'WTN Waste Category Summary', 'Update', 'WTN_Waste_Category__c', null);
	}

	public void finish(Database.BatchableContext bc) {}
}