force-app/main/default/objects/Compliance_Doc__c/Compliance_Doc__c.object-meta.xml
<CustomObject>
    <label>Compliance Document</label>
    <nameField>
        <label>Compliance_Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Doc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Compliance_Docs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Documents</relationshipLabel>
    <relationshipName>Compliance_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Doc__c/recordTypes/WTN.recordType-meta.xml
<RecordType>
    <fullName>WTN</fullName>
    <active>true</active>
    <label>Waste Transfer Notes</label>
</RecordType>

force-app/main/default/objects/WTN_Waste_Category__c/WTN_Waste_Category__c.object-meta.xml
<CustomObject>
    <label>WTN Waste Category</label>
    <nameField>
        <displayFormat>WTN{YYYY}{MM}-{0}</displayFormat>
        <label>WTN Waste Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WTN Waste Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTN_Waste_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTN_Waste_Category__c/fields/WTN__c.field-meta.xml
<CustomField>
    <fullName>WTN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Waste Transfer Note</label>
    <referenceTo>Compliance_Doc__c</referenceTo>
    <relationshipLabel>WTN Waste Categories</relationshipLabel>
    <relationshipName>WTN_Waste_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WtnWasteCategoryTriggerHandler.cls
public without sharing class WtnWasteCategoryTriggerHandler {

	public void handleTrigger(List<WTN_Waste_Category__c> newList, Map<Id, WTN_Waste_Category__c> oldMap, TriggerOperation operation) {
		switch on operation {
			when AFTER_INSERT {
				applyOnSchedules(newList);
			}
		}
	}

	private void applyOnSchedules(List<WTN_Waste_Category__c> wtnWasteCategories) {
		// Filter by Season Ticket WTN records
		List<WTN_Waste_Category__c> seasonTicketWasteCategories = [SELECT WTN__r.Account__c, WTN__r.Contractor__c, Product__c FROM WTN_Waste_Category__c
			WHERE ID IN :wtnWasteCategories AND WTN__r.Name LIKE 'Season Ticket WTN%'];
		if (!seasonTicketWasteCategories.isEmpty()) {
			WtnWasteCategoryOnSchedule.apply(seasonTicketWasteCategories);
		}
	}
}